import { AdapterProject } from '../types'

export default {
  name: 'Ocean',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'OCEAN',
  coingeckoId: 'ocean-protocol',
  id: 'qbhkmt',
  description:
    'Ocean Protocol is a data exchange protocol enabling decentralized data sharing and monetization.',
  investors: [
    'vjpj24',
    'i1x9du',
    'zloyr1',
    'ztpy5d',
    'n01vko',
    'xt0vj3',
    'oi4yuk',
    '798xl8',
    'knw63n',
    'laupoy',
    'fxmvug',
    'n73vnt',
    '948drp',
    'gwix1y',
    'omaddb',
    '9p60sa',
    '1u19m7',
    'oq9fz1',
    'wldl30',
    'k1qvmn',
    '7800nu',
  ],
  duneQueries: null,
  cmcId: 3911,
} satisfies AdapterProject
