import { AdapterProject } from '../types'

export default {
  name: 'Humanode',
  chain: null,
  category: 'OTHER',
  token: 'HMND',
  coingeckoId: 'humanode',
  id: 'ful6z6',
  description:
    'Humanode is the first human-powered crypto-biometric network, where 1 human = 1 node = 1 vote. Humanode is a new-age decentralized crypto-biometric network that integrates pioneering cryptography with private biometrics and blockchain technology. The project aims to create a strong and sustainable decentralized system that is grounded on the existence of unique human beings.',
  discord: 'https://discord.com/invite/8my5gbgptx',
  investors: [
    'xmw0ev',
    'ltitbn',
    'bxcu1r',
    '6hezki',
    '5qx1w8',
    'okjrd0',
    '5dsvsj',
    'mlhi9g',
    'yfrryp',
    'n7ldex',
    'jwrten',
    'unykak',
    '9e1gk4',
    'lhs5s8',
    'b0lq1g',
    '52fjgj',
    'due5zk',
    's812zr',
    'ka28kz',
  ],
  linkedin: 'https://www.linkedin.com/company/human-node/',
  duneQueries: null,
  blog: 'https://blog.humanode.io/',
  github: 'https://github.com/humanode-network',
  telegram: 'https://t.me/humanode',
  twitter: 'https://twitter.com/humanode_io',
  url: 'https://humanode.io/',
} satisfies AdapterProject
