import { AdapterProject } from '../types'

export default {
  name: 'Kaito',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'pgim2q',
  description: 'Kaito AI is an AI-powered search and recommendation engine for digital assets,',
  discord: '1062261368809603165',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/_kaitoai',
  url: 'https://www.kaito.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
