import { AdapterProject } from '../types'

export default {
  name: 'Revert',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'hcinar',
  description: 'Revert makes it incredibly easy to build integrations with any third party API.',
  discord: '1126480907881160714',
  investors: [],
  linkedin: 'https://github.com/revertinc/Revert',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.linkedin.com/company/90436779/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/revertdotdev',
  url: 'https://www.revert.dev/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
