import { AdapterProject } from '../types'

export default {
  name: 'Freatic',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'php632',
  description:
    'Freatic is a project focused on developing a decentralized information markets protocol.',
  discord: null,
  investors: [
    'fahk60',
    '26x5nn',
    'ze1wdg',
    'hhudw8',
    'zbwc1y',
    'z9ht3t',
    'ivtzio',
    'jimmh7',
    'eyy236',
    'uita3x',
    'kpp3he',
  ],
  linkedin: 'https://www.linkedin.com/company/freaticteam/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@freaticteam',
  github: 'https://github.com/freatic',
  telegram: null,
  twitter: 'https://twitter.com/intent/user?screen_name=freaticteam',
  url: 'https://freatic.team/',
  verified: false,
} satisfies AdapterProject
