import { AdapterProject } from '../types'

export default {
  name: 'EpiK',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'AIEPK',
  coinGeckoID: 'epik-protocol',
  id: '0lasch',
  description:
    'EpiK Protocol: Using IPFS, DAO and token economy to build a large-scale knowledge graph.',
  discord: '740760785487265815',
  investors: [
    'z2j0xs',
    'm8rgyb',
    'ta5llm',
    'q8nh5s',
    '2zbjm7',
    'dstkk5',
    'hxmvxz',
    'r2w61y',
    'lfbmt3',
    'k4kgrp',
    'd752i2',
    'pj4b1s',
    '3wlhk2',
    'zrv0uy',
    'ik81jg',
    'z1jqg1',
    'mej3v6',
  ],
  linkedin: 'http://www.linkedin.com/company/epikprotocol',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://epikprotocol.medium.com/',
  github: 'https://github.com/EpiK-Protocol',
  telegram: 'https://t.me/EpikProtocol',
  twitter: 'https://twitter.com/EpikProtocol',
  url: 'https://www.epik-protocol.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
