import { AdapterProject } from '../types'

export default {
  name: 'EpiK',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'AIEPK',
  coingeckoId: 'epik-protocol',
  id: '0lasch',
  description:
    'EpiK Protocol: Using IPFS, DAO and token economy to build a large-scale knowledge graph.',
  investors: [
    'z2j0xs',
    'm8rgyb',
    'ta5llm',
    'q8nh5s',
    '2zbjm7',
    'dstkk5',
    'hxmvxz',
    'lfbmt3',
    'k4kgrp',
    'd752i2',
    'pj4b1s',
    '3wlhk2',
    'zrv0uy',
    'ik81jg',
    'z1jqg1',
    'mej3v6',
  ],
  duneQueries: null,
  blog: 'https://epikprotocol.medium.com/',
  github: 'https://github.com/EpiK-Protocol',
  telegram: 'https://t.me/EpikProtocol',
  twitter: 'https://twitter.com/EpikProtocol',
} satisfies AdapterProject
