import { AdapterProject } from '../types'

export default {
  name: 'FilSwan',
  ninja: null,
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'v3ycrj',
  description: 'FilSwan: web3 infrastructure for dApp development.',
  discord: '867879887871672331',
  investors: [
    'st9kcn',
    'mrgeec',
    '0msybz',
    'dsl20s',
    'lfbmt3',
    'drdidh',
    'jzrat5',
    'qqc9zd',
    'ti312b',
    'wu15kr',
    'ret0us',
    'rewcp7',
    'o7xcsr',
  ],
  linkedin: 'https://www.linkedin.com/company/swancloud',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@swanchain',
  github: 'https://github.com/filswan',
  telegram: 'https://t.me/swan_chain/1',
  twitter: 'https://twitter.com/swan_chain',
  url: 'https://www.filswan.com/homepage',
  verified: false,
  fundraisesUrls: [
    'https://www.prweb.com/releases/filswan-raises-3m-usd-to-revolutionize-amp-simplify-building-dapps-899321300.html',
  ],
} satisfies AdapterProject
