import { AdapterProject } from '../types'

export default {
  name: 'DePoW',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: 'tgt1jj',
  description: 'DePoW is a PRN-DePIN network on Ton.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/depow_fam',
  twitter: 'https://x.com/depow_io',
  url: 'https://www.depow.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
