import { AdapterProject } from '../types'

export default {
  name: 'Blackbird',
  subcategories: null,
  chain: 'POLYGON',
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: 'vhqz3k',
  description: 'Blackbird is a loyalty and membership platform for restaurants.',
  discord: 'https://discord.com/invite/ysHrDPrJYr',
  investors: [
    'g1jnat',
    '26x5nn',
    'd9o1gj',
    '68yk0j',
    'h9k79h',
    'etvd3c',
    'ifm0v5',
    'jxugz9',
    '2g0699',
    'z5dfl9',
    'cjmn2h',
    'w0qehc',
    'vuz4in',
    'ubuz3j',
  ],
  linkedin: 'https://www.linkedin.com/company/blackbirdvc',
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/blackbirdvc',
  url: 'https://www.blackbird.xyz/',
} satisfies AdapterProject
