import { AdapterProject } from '../types'

export default {
  name: 'Blackbird',
  ninja: null,
  subcategories: null,
  chain: 'POLYGON',
  category: 'SERVICES',
  token: null,
  coinGeckoID: null,
  id: 'vhqz3k',
  description: 'Blackbird is a loyalty and membership platform for restaurants.',
  discord: '1090286137790169161',
  investors: [
    'd40or5',
    'inrvx2',
    'g1mc9m',
    '68yk0j',
    'ifm0v5',
    '2g0699',
    'z5dfl9',
    'o2p1vz',
    '1g7zar',
    'cjmn2h',
    'uoxmpx',
    'vuz4in',
    'ubuz3j',
  ],
  linkedin: 'https://www.linkedin.com/company/blackbirdvc',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/blackbirdvc',
  url: 'https://www.blackbird.xyz/',
  verified: false,
  fundraisesUrls: [
    'https://www.theblock.co/post/175214/resy-co-founder-ben-leventhal-raises-11-million-for-new-Web3 Capital-hospitality-platform?utm_source=twitter&utm_medium=social',
    'https://www.prnewswire.com/news-releases/blackbird-labs-raises-24-million-series-a-round-from-a16z-amex-ventures-and-more-to-help-transform-the-way-restaurants-approach-diner-loyalty-301946664.html',
  ],
} satisfies AdapterProject
