import { AdapterProject } from '../types'

export default {
  name: 'Supermeta',
  ninja: null,
  subcategories: 'Gaming',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '41xvbt',
  description: 'We create phenomenal NFT experiences with exceptional creators and brands.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/supermetafi',
  twitter: 'https://twitter.com/supermetafi',
  url: 'https://www.supermetaplus.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
