import { AdapterProject } from '../types'

export default {
  name: 'Firethree',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'gdo61v',
  description: 'Products and solutions for every stage of your app development journey!',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/_firethree',
  url: 'https://www.firethree.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
