import { AdapterProject } from '../types'

export default {
  name: 'Canto',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'e20ukn',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/CantoPublic',
  url: 'https://canto.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
