import { AdapterProject } from '../types'

export default {
  name: 'Boring',
  ninja: 'wholovesburrito.eth',
  subcategories: 'VPN',
  chain: 'SOLANA',
  category: 'WIRELESS',
  token: 'BOP',
  coinGeckoID: 'boring-protocol',
  id: 'whkmqt',
  description: 'Boring is a decentralized VPN and peer-to-peer bandwidth market.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/boringprotocol/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/boringprotocol/',
  telegram: null,
  twitter: 'https://twitter.com/BoringProtocol',
  url: 'https://boringprotocol.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
