import { AdapterProject } from '../types'

export default {
  name: 'Clique',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'redik6',
  description:
    'Clique is building a compute coordination layer, streamlining the process by which both smart contracts and general applications access and utilize computing resources.',
  discord: '918592135178125443',
  investors: [
    '7ygqh2',
    '896jil',
    'wvitwb',
    'isx1ik',
    'ho4zrz',
    'qreqzv',
    '6ln74n',
    'aeoxcb',
    'tfkff0',
    'yirgyu',
    '870le2',
    'thxgaw',
    '8rcqvw',
    '55qf14',
    'tqh3bl',
    'drbv40',
    'eyy236',
    '9e1gk4',
    '4pw1n0',
    'ksae6d',
    'xph9q9',
    'pu3yyr',
    'm5cayq',
    'k5cgj5',
    'pt9rpd',
    'wu15kr',
    'lzpnns',
    '3mnnrf',
    'cy0ynk',
    'tm95um',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Clique2046',
  url: 'https://www.clique.tech/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://twitter.com/Clique2046/status/1582191761526775808',
    },
    {
      roundType: 'Series A',
      url: 'https://twitter.com/Clique2046/status/1768277734113907127',
    },
  ],
  isApp: true,
} satisfies AdapterProject
