import { AdapterProject } from '../types'

export default {
  name: 'Terathium',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'tm58se',
  description: 'Terathium is building a lithium-ion battery recycling plant.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
