import { AdapterProject } from '../types'

export default {
  name: 'Wingbits',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: 'dxk2mc',
  description: 'Wingbits is a decentralized flight tracking network.',
  discord: '1082294632689455154',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/wingits',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@wingbits',
  github: 'https://github.com/wingbit',
  telegram: null,
  twitter: 'https://twitter.com/wingbits',
  url: 'https://wingbits.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
