import { AdapterProject } from '../types'

export default {
  name: 'BrinxAI',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '48tjwk',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/BrinxAI_Labs',
  url: 'https://brinxai.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
