import { AdapterProject } from '../types'

export default {
  name: 'Drop',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Data',
  chain: 'IOTEX',
  category: 'WIRELESS',
  token: 'DWIN',
  coinGeckoID: null,
  id: 'qnfsx5',
  description: 'Drop Wireless is a decentralized wireless network for IoT use cases.',
  discord: null,
  investors: [],
  linkedin: 'https://ca.linkedin.com/company/joindrop',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/timogiles/wireless-dead-drop',
  telegram: 'https://t.me/dropwireless',
  twitter: 'https://mobile.twitter.com/dropwireless',
  url: 'https://dropwireless.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
