import { AdapterProject } from '../types'

export default {
  name: 'Autonomous Forest',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'b5m10o',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/forest_ev',
  url: 'https://autonomousforest.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
