import { AdapterProject } from '../types'

export default {
  name: 'Bacalhau',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'jtoxcg',
  description: 'Bacalhau: Fast, efficient, secure computation platform.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/showcase/bacalhau-project/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/bacalhau-project',
  telegram: null,
  twitter: 'https://x.com/BacalhauProject',
  url: 'https://www.bacalhau.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
