import { AdapterProject } from '../types'

export default {
  name: 'Bacalhau',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'jtoxcg',
  description: 'Bacalhau: Fast, efficient, secure computation platform.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/showcase/bacalhau-project/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/bacalhau-project',
  telegram: null,
  twitter: 'https://mobile.twitter.com/BacalhauProject/status/1581290104936484864',
  url: 'https://www.bacalhau.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
