import { AdapterProject } from '../types'

export default {
  name: 'Altered State',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Agents',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'ASTO',
  coinGeckoID: 'altered-state-token',
  id: '9limss',
  description:
    'Altered State Machine is a decentralized protocol for the creation and training of AI Agents, owned and traded using NFTs.',
  discord: '864685888830963742',
  investors: [
    'k93k29',
    'hol96b',
    'y8my2p',
    'buime9',
    '9uxyqp',
    'gjt0lb',
    '3j4n9l',
    'd88md4',
    'k8v3go',
    'ln7o85',
    'b2ybqs',
    'hq4myf',
    '73opsz',
    'pjahyf',
    '3yr1j5',
    'j4xyuk',
    '67mqz0',
    's0sfkv',
    'dnu31w',
    '8akn04',
    'c7vsth',
    'czduss',
    'k1qvmn',
    '7zvtvf',
    'h9k79h',
    'jp97kv',
    '6ln74n',
    '1b7u42',
    'mar9ip',
    'dzx3xa',
    'aomyrx',
    'thxgaw',
    'd0dwes',
    'zqwobt',
    'eqqdvr',
    'zegk6g',
    'vt618a',
    'vjpj24',
    '8agdnp',
    'foos12',
    '624loe',
    'z15ywj',
    'nr57n8',
    'lhs5s8',
    'dgjdgm',
    'ztwm8h',
    'zzc3cd',
    'zim0bv',
    'nwl5v7',
    'ehzj0z',
    'v6xlk7',
    'uwd92p',
  ],
  linkedin: 'https://www.linkedin.com/company/altered-state-machine/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/altstatemachine',
  url: 'https://www.alteredstatemachine.xyz/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://medium.com/@alteredstatemachine/altered-state-machine-welcomes-new-crypto-technology-entertainment-and-investment-partners-in-b09344b5d3d8',
    },
    {
      roundType: 'Seed',
      url: 'https://medium.com/@alteredstatemachine/altered-state-machine-welcomes-new-crypto-technology-entertainment-and-investment-partners-in-b09344b5d3d8',
    },
  ],
  isApp: true,
} satisfies AdapterProject
