import { AdapterProject } from '../types'

export default {
  name: 'deBridge',
  ninja: null,
  subcategories: 'Bridges',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'rhpzul',
  description: 'deBridge: blockchain interoperability and liquidity transfer protocol.',
  discord: '875308315700264970',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/debridge-finance/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://debridge.finance/blog/',
  github: 'https://github.com/debridge-finance/',
  telegram: 'https://t.me/deBridge_finance',
  twitter: 'https://twitter.com/deBridgeFinance',
  url: 'https://debridge.finance/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
