import { AdapterProject } from '../types'

export default {
  name: 'deBridge',
  ninja: null,
  subcategories: 'Bridges',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'rhpzul',
  description: 'deBridge: blockchain interoperability and liquidity transfer protocol.',
  discord: 'https://discord.com/invite/debridge',
  investors: [
    'gjt0lb',
    'csfyvy',
    'xmw0ev',
    'ajbv45',
    '2tgqti',
    'hspqs1',
    '2bl1fj',
    'ubwov4',
    '798xl8',
    '3yr1j5',
    '6n1shm',
    'n0g582',
    'n5z0zx',
    'aeoxcb',
    'v81ftp',
    't7xkdd',
    'i1x9du',
    'qu9as2',
    'kjm7ph',
    '91q6ri',
    'yczy5v',
    'su1iz5',
    '6f2cxt',
    'ciz6c6',
    '5o347p',
    'cvjbhg',
    '52fjgj',
    'e2dh7y',
    '7r9603',
    'e0wtte',
  ],
  linkedin: 'https://www.linkedin.com/company/debridge-finance/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://debridge.finance/blog/',
  github: 'https://github.com/debridge-finance/',
  telegram: 'https://t.me/deBridge_finance',
  twitter: 'https://twitter.com/deBridgeFinance',
  url: 'https://debridge.finance/',
} satisfies AdapterProject
