import { AdapterProject } from '../types'

export default {
  name: 'Entheos',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: '0if1hs',
  description: 'Entheos Network: energy solutions & batteries for businesses globally.',
  discord: null,
  investors: ['wb49st', 'abvcou', '566vlr'],
  linkedin: 'http://www.linkedin.com/company/entheos-network',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://entheosnetwork.medium.com/entheos-network-b3e43242a5ae',
  github: null,
  telegram: null,
  twitter: 'https://x.com/entheosnetwork',
  url: 'https://www.entheos.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
