import { AdapterProject } from '../types'

export default {
  name: 'Verida',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'hjruy9',
  description: 'Verida is a decentralized data storage, messaging, and single sign-on solution.',
  investors: [
    'wv0c6u',
    'puuj5e',
    'wqn9ms',
    'qqtb99',
    'knw63n',
    'lm317i',
    'i1vs03',
    'rlo5x9',
    'yoijyl',
    '88qc33',
    'j74kap',
    'dd123i',
    'b6vnn8',
    'a6bd06',
    'g72mqv',
    'e0510f',
  ],
  duneQueries: null,
} satisfies AdapterProject
