import { AdapterProject } from '../types'

export default {
  name: 'Verida',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'hjruy9',
  description: 'Verida is a decentralized data storage, messaging, and single sign-on solution.',
  discord: '664594912460668960',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/verida-technology/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://news.verida.io/',
  github: null,
  telegram: 'https://t.me/verida_community',
  twitter: 'https://twitter.com/verida_io',
  url: 'https://verida.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
