import { AdapterProject } from '../types'

export default {
  name: 'READYgg',
  ninja: 'ZZ',
  subcategories: 'Gaming',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'wjko90',
  description: 'READYgg is a Layer3 gaming infrastructure for the Web3 creator economy.',
  discord: '449614151262928897',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/ready-makers-inc/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/readygamesofficial',
  twitter: 'https://twitter.com/TheReadyGames',
  url: 'https://ready.gg/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
