import { AdapterProject } from '../types'

export default {
  name: 'Inference Labs',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'qi9eg6',
  description:
    'Inference Labs develops infrastructure and products for AI on web3, specializing in zero-knowledge proofs for transparent and secure AI operations in a decentralized ecosystem.',
  discord: null,
  investors: [
    '4l8mmr',
    '2tgqti',
    'lkgkfl',
    '67mqz0',
    'dnu31w',
    'ry12po',
    '2imimj',
    'ulvyo3',
    'bah2fw',
    '90syk8',
    'pnypo2',
    'c6texe',
    '9e1gk4',
    'ksae6d',
    'kzy7cw',
    '2ge04u',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/inference_labs',
  url: 'https://inferencelabs.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://chainwire.org/2024/04/15/inference-labs-raises-2-3-million-in-pre-seed-funding-to-revolutionize-ai-with-proof-of-inference-starting-with-liquid-staking/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
