import { AdapterProject } from '../types'

export default {
  name: 'UKISS',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: 'KISS',
  coinGeckoID: null,
  id: '4uhpxf',
  description: 'UKISS Technology is dedicated in building the next-gen digital security Ecosystem.',
  discord: '1143746313738010685',
  investors: [
    'is950u',
    '606zzb',
    'gpswp8',
    'zmuz4i',
    'ki7fc2',
    '76c6i8',
    '87tpbd',
    'tgtgbr',
    'nr57n8',
    'u8r7ah',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.ukiss.io/',
  verified: false,
} satisfies AdapterProject
