import { AdapterProject } from '../types'

export default {
  name: 'Handshake',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: 'HNS',
  coinGeckoID: 'handshake',
  id: 'm9gkfk',
  description:
    'Handshake is a decentralized, permissionless naming protocol where every peer is validating and in charge of managing the root DNS naming zone.',
  discord: '822591034202521641',
  investors: [
    'd40or5',
    'd33d7a',
    '2qhnja',
    '8m8hfx',
    'jtci9b',
    'gzipi5',
    '9btyj8',
    '5dsvsj',
    '419x6r',
    'ja2261',
    'z3ngzr',
    'tqh3bl',
    'vf0qg4',
    'wu15kr',
    '7xqu4s',
    'xt0vj3',
    'fuws95',
    'v6xlk7',
    'dl3888',
  ],
  linkedin: 'https://www.linkedin.com/company/hns-handshake/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/handshake-org/hsd',
  telegram: 'https://t.me/handshake_hns',
  twitter: 'https://twitter.com/hns',
  url: 'https://handshake.org/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://twitter.com/HNS/status/1744237732992593976',
    },
  ],
  isApp: true,
} satisfies AdapterProject
