import { AdapterProject } from '../types'

export default {
  name: 'Handshake',
  chain: null,
  category: 'NOT_DEPIN',
  token: 'HNS',
  coingeckoId: 'handshake',
  id: 'm9gkfk',
  description:
    'Handshake is a decentralized, permissionless naming protocol where every peer is validating and in charge of managing the root DNS naming zone with the goal of creating an alternative to existing Certificate Authorities and naming systems. By participating in Handshake, users contribute to a decentralized open platform for domain management using a utility coin system.',
  investors: [
    'r1a7zj',
    'd33d7a',
    '2qhnja',
    '26x5nn',
    '8m8hfx',
    'jtci9b',
    'gzipi5',
    '9btyj8',
    '5dsvsj',
    '419x6r',
    'ja2261',
    'z3ngzr',
    'tqh3bl',
    'vf0qg4',
    'wu15kr',
    '7xqu4s',
    'xt0vj3',
    'fuws95',
    'v6xlk7',
    'dl3888',
  ],
  duneQueries: null,
  blog: null,
  github: 'https://github.com/handshake-org/hsd',
  telegram: 'https://t.me/handshake_hns',
  twitter: 'https://twitter.com/hns',
  url: 'https://handshake.org/',
} satisfies AdapterProject
