import { AdapterProject } from '../types'

export default {
  name: 'Stratlab',
  ninja: '0x35aD39E4bB8D4B405721A540303E54f33143910B',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'ytahiz',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://stratlab.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
