import { AdapterProject } from '../types'

export default {
  name: 'Cheeze',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '9tcuea',
  description:
    'Cheeze is a decentralized creator economy platform that enables brand activation for imagery on-chain.',
  discord: null,
  investors: [
    '2mccdz',
    'rjcwff',
    'eogul3',
    'lb3dac',
    'p7qu8t',
    '9id98s',
    'ipknt7',
    'tivoxv',
    'cacqhz',
    'rz9az7',
    'bb8u86',
    'z5gcrq',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://cheeze.com/',
  verified: false,
} satisfies AdapterProject
