import { AdapterProject } from '../types'

export default {
  name: 'HashMix',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '5v5xcz',
  description:
    'HashMix proposes a tokenization scheme suitable for arbitrary hash power, implements a set of universal decentralized cloud hash power trading, lending, and swapping protocols.',
  discord: '1036550293455917096',
  investors: [
    '1zgufc',
    's16t1q',
    'h2tvqq',
    '2ckrz9',
    'lfbmt3',
    'mywjsu',
    'rlo5x9',
    'nxzb7m',
    'micofj',
    'kvp438',
    'po8xe3',
    'k9u90q',
    'z6hza6',
    '9yykrx',
    'mx8grh',
    'pu3yyr',
    'brmebh',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://hashmix.medium.com/',
  github: 'https://github.com/HashMixProject',
  telegram: 'https://t.me/HashMixChannel',
  twitter: 'https://twitter.com/HashMixOfficial',
  url: 'https://www.hashmix.org/en/#intro',
  verified: false,
} satisfies AdapterProject
