import { AdapterProject } from '../types'

export default {
  name: 'ScyNet',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '5kz9p0',
  description: 'ScyNet is a Decentralized network for creating and training autonomous AI agents.',
  discord: '484370483739885608',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/comrade-coop/scynet',
  telegram: null,
  twitter: 'https://twitter.com/ScynetAI',
  url: 'https://scynet.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
