import { AdapterProject } from '../types'

export default {
  name: 'Endcoin',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'cj88v2',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/pulseonclimate',
  url: 'https://pulseonclimate.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
