import { AdapterProject } from '../types'

export default {
  name: 'Volmex',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '7055ri',
  description:
    'Volmex Finance is a protocol for volatility indices and non-custodial trading built on Ethereum.',
  discord: 'https://discord.com/invite/volmex',
  investors: [
    'b8gebp',
    'ovfuq8',
    'y7olrs',
    'lfyin7',
    'q4ztc2',
    'fjt6b4',
    '3yr1j5',
    'i98114',
    '1b7u42',
    'i1x9du',
    'k778fp',
    '243kcn',
    '7unh2b',
    'eyy236',
    '3rqujt',
    'uu233m',
    'lq00qd',
    'rwh53e',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://volmex.finance/',
  verified: false,
} satisfies AdapterProject
