import { AdapterProject } from '../types'

export default {
  name: 'DexAuction',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'ok3cyf',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/dexauction',
  url: 'https://www.dex.auction/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
