import { AdapterProject } from '../types'

export default {
  name: 'WaveNodes',
  ninja: '0x6997bcc18dea68ae3cbf243e92ce831e541cd9e4',
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: 'WMT',
  coinGeckoID: null,
  id: '84rrjz',
  description: 'WaveNodes is a World Mobile EarthNode operator.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/wavenodes_io',
  url: 'https://wavenodes.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
