import { AdapterProject } from '../types'

export default {
  name: 'MeMeTalk',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '09v332',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/memetalk_sol',
  twitter: 'https://x.com/memetalk_sol',
  url: 'https://memetalk.net/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
