import { AdapterProject } from '../types'

export default {
  name: 'Ruff',
  ninja: null,
  subcategories: 'IoT',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'RUFF',
  coingeckoId: 'ruff',
  id: 'la5o39',
  description:
    'Ruff is a blockchain-based architecture combining IoT with a public chain and distributed operating system.',
  discord: null,
  investors: [
    'qmoomu',
    'chcjy9',
    's9xpzx',
    'gun7y3',
    '3av5f4',
    'ymnjdr',
    'zyybpp',
    '9205ui',
    '07pxi6',
    '7mo8zq',
    'm1jl0k',
    'yaxu8c',
  ],
  linkedin: 'https://www.linkedin.com/company/ruffllc/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'http://ruffchain.com',
  verified: false,
} satisfies AdapterProject
