import { AdapterProject } from '../types'

export default {
  name: 'Ceramic',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 'ancy5d',
  description: 'Ceramic is a decentralized data network.',
  investors: [
    '5yy6cw',
    'ti312b',
    '2g0699',
    '2tgqti',
    'szfiug',
    'bku3ew',
    'zaf9xh',
    '73opsz',
    'hol96b',
    'vuz4in',
    'gduv1m',
    'urug6u',
    'uwuv2v',
    'nx424z',
    'bmsbeq',
    'j29sm3',
    'w5c605',
    'moo9hj',
    'hamhvv',
    'ja2261',
    'p2tiib',
    '6cp8be',
    '2acydu',
    'c3q4sa',
    'xkn0vq',
    '8ojtlq',
  ],
  duneQueries: null,
  cmcId: null,
} satisfies AdapterProject
