import { AdapterProject } from '../types'

export default {
  name: 'Ceramic',
  ninja: 'ZZ',
  subcategories: 'Data',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'ancy5d',
  description: 'Ceramic is a decentralized data network.',
  discord: '682786569857662976',
  investors: [
    'hol96b',
    'w5c605',
    'g5bi1d',
    '2tgqti',
    'hamhvv',
    '73opsz',
    'szfiug',
    'p7lpx4',
    'ho4zrz',
    'apd14v',
    'uwuv2v',
    'ja2261',
    '2g0699',
    'hne3si',
    '1g74jp',
    'bku3ew',
    'ti312b',
    'bmsbeq',
    '6cp8be',
    '2acydu',
    '0o9uby',
    'gf4mkp',
    'vuz4in',
    'ubuz3j',
    'wnkupi',
    'gduv1m',
    'urug6u',
  ],
  linkedin: 'https://www.linkedin.com/company/ceramic-network',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/ceramic',
  github: 'https://github.com/ceramicnetwork',
  telegram: 'https://t.me/s/shreejiceramic?before=2',
  twitter:
    'https://twitter.com/ceramicnetwork?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://ceramic.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://techcrunch.com/2019/06/26/Web3 Capital-platform-3box-raises-seed-to-bring-back-control-of-user-data/',
    },
    {
      roundType: 'Series A',
      url: 'https://www.coindesk.com/business/2022/02/16/Union Square-multicoin-lead-30m-raise-for-3boxs-ceramic-data-network/',
    },
  ],
} satisfies AdapterProject
