import { AdapterProject } from '../types'

export default {
  name: 'Kuzco',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: 'SOLANA',
  category: 'COMPUTE',
  token: 'KZO',
  coinGeckoID: null,
  id: '7syzhg',
  description: 'Kuzco is a distributed GPU cluster for LLM inference on Solana.',
  discord: '1100110477599723550',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/kuzco_xyz',
  url: 'https://kuzco.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
