import { AdapterProject } from '../types'

export default {
  name: 'TEKKON',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'sel0t5',
  description: 'TEKKON: Web3 app for citizen-driven infrastructure solutions.',
  discord: '1227383314327933009',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@Tekkon',
  github: null,
  telegram: 'https://t.me/TEKKONOfficial',
  twitter: 'https://twitter.com/TEKKON_official',
  url: 'https://tekkon.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
