import { AdapterProject } from '../types'

export default {
  name: 'SAMA',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'geykyu',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/+P9M54kBLxW0xNzZl',
  twitter: 'https://x.com/sama_network',
  url: 'https://samax.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
