import { AdapterProject } from '../types'

export default {
  name: 'AXIS',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'AXIS',
  coinGeckoID: 'axis-token',
  id: '56jkto',
  description: 'AXIS is a blockchain-powered direct freight network.',
  discord: '1224009941933756489',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/laneaxis/axisToken_smart_contact',
  telegram: 'https://t.me/laneaxis',
  twitter: 'https://twitter.com/axis_token',
  url: 'https://axistoken.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
