import { AdapterProject } from '../types'

export default {
  name: 'Intuition',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'kx9y1a',
  description:
    "Operator of a decentralized identity company intended to help users to create attestations about any subject, storing the information in such a way that it's easily navigable, queryable, and leveraged by other applications.",
  investors: [
    'f7094w',
    'zloyr1',
    'e3qzk9',
    '9du4gx',
    'p7lpx4',
    'j4xyuk',
    'blk96m',
    'beum1u',
    '65epfb',
    'hfmbi5',
    'izwxxy',
    '8agdnp',
    'hepzxq',
    'zj4ect',
    '6ob6ls',
    '7iosyo',
    'lhs5s8',
    'w0qehc',
    't9j2qz',
    '6fx6k3',
    'e2dh7y',
    't44ifr',
  ],
  duneQueries: null,
  blog: 'https://medium.com/0xintuition',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/0xintuition',
  url: 'https://intuition.systems/',
} satisfies AdapterProject
