import { AdapterProject } from '../types'

export default {
  name: 'Intuition',
  ninja: null,
  subcategories: 'L1/L2',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'kx9y1a',
  description:
    'Operator of a decentralized identity company intended to help users to create attestations about any subject.',
  discord: '909531430881746974',
  investors: [
    'f7094w',
    'zloyr1',
    'e3qzk9',
    '9du4gx',
    'p7lpx4',
    'j4xyuk',
    'blk96m',
    'beum1u',
    '65epfb',
    'hfmbi5',
    'izwxxy',
    '8agdnp',
    'hepzxq',
    'zj4ect',
    '6ob6ls',
    '7iosyo',
    'lhs5s8',
    'w0qehc',
    't9j2qz',
    '6fx6k3',
    'e2dh7y',
    't44ifr',
  ],
  linkedin: 'https://www.linkedin.com/company/0xintuition/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/0xintuition',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/0xintuition',
  url: 'https://intuition.systems/',
  verified: false,
} satisfies AdapterProject
