import { AdapterProject } from '../types'

export default {
  name: 'AllianceBlock',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ALBT',
  coingeckoId: 'allianceblock',
  id: 'zgvzl4',
  description:
    'AllianceBlock builds gateways between traditional & decentralized industries with blockchain infrastructure.',
  discord: 'https://discord.com/invite/fB4tkF52H5',
  investors: [
    'mrgeec',
    'k1qvmn',
    'ghumon',
    'oyirya',
    'bah2fw',
    'dczz01',
    'xvgf6w',
    'nwl5v7',
    '2wn9ev',
  ],
  linkedin: 'http://www.linkedin.com/company/allianceblock',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/allianceblock/allianceblock-the-next-era-of-allianceblock-eabb78b29ac3',
  github: 'https://github.com/Stichting-AllianceBlock-Foundation/',
  telegram: 'https://t.me/allianceblock',
  twitter: 'https://twitter.com/allianceblock',
  url: 'https://allianceblock.io/',
  verified: false,
} satisfies AdapterProject
