import { AdapterProject } from '../types'

export default {
  name: 'Loom',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'LOOM',
  coingeckoId: 'loom-network-new',
  id: 'el7s07',
  description:
    'Loom Network is a production-ready, multichain interop platform for serious dapp developers.',
  discord: null,
  investors: [
    'vap740',
    '6erxyq',
    'i1x9du',
    'hqpm32',
    'xrz24d',
    '9id9yt',
    'kzsrt6',
    'xqcbrl',
    '97qlqj',
    'afeud9',
    'a1uyxq',
    'ex2fez',
    'pcw959',
  ],
  linkedin: 'https://www.linkedin.com/company/loom-network/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/loom-network',
  github: 'https://github.com/loomnetwork',
  telegram: 'https://t.me/loomnetwork',
  twitter: 'https://twitter.com/loomnetwork',
  url: 'https://loomx.io/',
  verified: false,
} satisfies AdapterProject
