import { AdapterProject } from '../types'

export default {
  name: 'Allora',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'qs7j6q',
  description:
    'Allora is a self-improving decentralized AI network. It enables applications to leverage smarter, more secure AI through a self-improving network of ML models by crowdsourcing mechanisms, federated learning, and zkML.',
  discord: '644591703507861515',
  investors: [
    'tupwbv',
    'tdmlep',
    'te4xtz',
    'q4ztc2',
    'szfiug',
    '21e2s8',
    'r54jbx',
    '67mqz0',
    'sknhsa',
    'yx4w71',
    'f5o3jl',
    'ulvyo3',
    'ivtzio',
    'rz9az7',
    'tqh3bl',
    '6iy81o',
    'wcgf78',
    'ooq1d1',
    '3bchmx',
    'jx87gk',
    'fx71c5',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/AlloraNetwork',
  url: 'https://allora.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.businesswire.com/news/home/20240201941258/en/Introducing-Allora-A-Self-Improving-Decentralized-AI-Network',
    },
    {
      roundType: 'Seed',
      url: 'https://www.businesswire.com/news/home/20210506005124/en/Upshot-Raises-7.5-Million-in-Series-A-Led-by-Framework-Ventures-CoinFund-and-Blockchain-Capital',
    },
    {
      roundType: 'Series A',
      url: 'https://www.businesswire.com/news/home/20220322005518/en/Upshot-Raises-22M-Series-A2-Led-by-Polychain-to-Accelerate-Development-of-Real-Time-NFT-Appraisals',
    },
  ],
} satisfies AdapterProject
