import { AdapterProject } from '../types'

export default {
  name: 'Modal',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'xegpzk',
  description: 'Modal Labs offers Modal, a runtime for data teams.',
  discord: null,
  investors: [
    'd7e7x7',
    'a1wztr',
    'djmofb',
    'f0vgv5',
    '1pi13y',
    'eud3qk',
    'uns0bm',
    'snj7ma',
    '03hx49',
    '6qqzvk',
    '64cas2',
    'k5q5k9',
    'ul6tyf',
    'umdkfq',
    'cs5wgp',
    '2o6wn2',
    'mdb8di',
    'zkz4v0',
    'q7s8dk',
    'krji44',
    'ah0a0s',
    'n9fxs2',
    '9tdi8p',
    'ic9k7i',
    'gdty4y',
    'zhjcle',
    'b2k6ex',
    'v2grtn',
    'h0yuhw',
    '9ltipb',
  ],
  linkedin: 'https://www.linkedin.com/company/modal-labs/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/modal-labs',
  telegram: null,
  twitter: 'https://twitter.com/modal_labs',
  url: 'https://modal.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://techcrunch.com/2023/10/10/modal-labs-lands-16m-to-abstract-away-big-data-workload-infrastructure/',
    },
    {
      roundType: 'Series A',
      url: 'https://techcrunch.com/2023/10/10/modal-labs-lands-16m-to-abstract-away-big-data-workload-infrastructure/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
