import { AdapterProject } from '../types'

export default {
  name: 'BAZED',
  ninja: null,
  subcategories: 'Gaming',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'maga37',
  description: 'Bazed is a PvP gaming platform using web3 technology.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/BAZEDBET',
  url: 'https://bazed.bet/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
