import { AdapterProject } from '../types'

export default {
  name: 'Lumoz',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'x60254',
  description:
    'Lumoz is a Modular Compute Layer and ZK-RaaS platform that utilizes a PoW mining mechanism to provide ZKP arithmetic for ZK-Rollup.',
  discord: null,
  investors: [
    'r07kjn',
    '7oqynx',
    'k0celj',
    'goald7',
    'i1vs03',
    'nxzb7m',
    'f5avgu',
    'yv5v8q',
    'bvyx97',
    'azofz8',
    'smqwtv',
    '9e1gk4',
    '4f9p4d',
    'cdoetr',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/LumozOrg',
  url: 'https://lumoz.org/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.theblock.co/post/286969/lumoz-crypto-funding-token-round-valuation',
    },
    {
      roundType: 'Strategic/Angel',
      url: 'https://x.com/LumozOrg/status/1795824512468160602',
    },
  ],
  isApp: true,
} satisfies AdapterProject
