import { AdapterProject } from '../types'

export default {
  name: 'Growfitter',
  ninja: null,
  subcategories: 'Health & Fitness',
  chain: null,
  category: 'SERVICES',
  token: null,
  coinGeckoID: null,
  id: '8ve4hw',
  description:
    'Growfitter is a gamified digital health reward platform that adds financial benefits to your physical activity.',
  discord: null,
  investors: [
    '4p826x',
    'rgrbi1',
    'son7io',
    'b2ybqs',
    'xk9vnv',
    'l765bu',
    '1ixehb',
    '5vzkab',
    'i8evbl',
    'iy5jcg',
    'zyw1ef',
    '9xr3sv',
    'ww9xnu',
    'edbfmp',
    'ms3jph',
    'tmyvo7',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'http://www.linkedin.com/company/growfitter.com',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/growfitter?lang=en',
  url: 'https://www.growfitter.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://entrackr.com/2017/06/health-startup-growfitter-raises-600k-pre-series-funding-expand-fitness-services/',
    },
    {
      roundType: 'Seed',
      url: 'https://economictimes.indiatimes.com/tech/funding/shark-tank-featured-growfitter-raises-1-million-in-funding-led-by-inflection-point-ventures/articleshow/90257919.cms?from=mdr',
    },
  ],
} satisfies AdapterProject
