import { AdapterProject } from '../types'

export default {
  name: 'Growfitter',
  chain: null,
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: '8ve4hw',
  description:
    'Growfitter is a gamified digital health reward platform that adds financial benefits to your physical activity.',
  discord: null,
  investors: [
    '4p826x',
    'rgrbi1',
    'son7io',
    'b2ybqs',
    '2ossdx',
    'xk9vnv',
    'l765bu',
    '1ixehb',
    '5vzkab',
    'i8evbl',
    'vj7qw8',
    'iy5jcg',
    'zyw1ef',
    '9xr3sv',
    '2o7g8w',
    'edbfmp',
    'ms3jph',
    'tmyvo7',
  ],
  linkedin: null,
  duneQueries: null,
  blog: 'http://www.linkedin.com/company/growfitter.com',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/growfitter?lang=en',
  url: 'https://www.growfitter.com/',
} satisfies AdapterProject
