import { AdapterProject } from '../types'

export default {
  name: 'GitPOAP',
  subcategories: null,
  chain: null,
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: '2fl69i',
  description: 'GitPOAP - recognizing contributions on GitHub with POAP issuance',
  discord: 'https://discord.com/invite/qa3mfPvjWm',
  investors: [
    'cd2nay',
    'abvcou',
    '896jil',
    'e7om6t',
    'sk9qn6',
    'mlsidm',
    '3xs22l',
    'ti312b',
    '3j2gta',
  ],
  linkedin: 'http://www.linkedin.com/company/gitpoap',
  duneQueries: null,
  blog: 'https://medium.com/gitpoap',
  github: 'https://github.com/gitpoap',
  telegram: null,
  twitter: 'https://twitter.com/gitpoap',
  url: 'https://www.gitpoap.io/',
} satisfies AdapterProject
