import { AdapterProject } from '../types'

export default {
  name: 'GitPOAP',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '2fl69i',
  description: 'GitPOAP - recognizing contributions on GitHub with POAP issuance',
  discord: '918207795113885737',
  investors: [
    'cd2nay',
    'abvcou',
    '896jil',
    'e7om6t',
    'sk9qn6',
    'mlsidm',
    '3xs22l',
    'ti312b',
    '3j2gta',
  ],
  linkedin: 'http://www.linkedin.com/company/gitpoap',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/gitpoap',
  github: 'https://github.com/gitpoap',
  telegram: null,
  twitter: 'https://twitter.com/gitpoap',
  url: 'https://www.gitpoap.io/',
  verified: false,
  fundraisesUrls: [
    'https://www.prnewswire.com/news-releases/gitpoap-raises-over-4-2-million-usd-in-seed-funding-to-memorialize-professional-contributions-and-accomplishments-as-blockchain-based-badges-301608123.html',
  ],
} satisfies AdapterProject
