import { AdapterProject } from '../types'

export default {
  name: 'Protomaps',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'qppebc',
  description: 'A free and open source map of the world.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://protomaps.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
