import { AdapterProject } from '../types'

export default {
  name: 'Viper',
  ninja: '0x9Ab59cB71d4657f4c2DB7E0963212A81b6445b4c',
  subcategories: 'RPC/Indexing',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '1sbdg8',
  description: 'Viper is a decentralized RPC for Solana.',
  discord: '1035116329193189396',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/viper/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Nilfiskofficial',
  url: 'https://vipernet.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
