import { AdapterProject } from '../types'

export default {
  name: 'Injective',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'INJ',
  coingeckoId: 'injective-protocol',
  id: 't2mgs2',
  description:
    'Injective is a finance-oriented blockchain for DeFi apps: exchanges, lending, and prediction markets.',
  discord: 'https://discord.com/invite/NK4qdbv',
  investors: [
    'xmw0ev',
    'ajbv45',
    'mrgeec',
    '0xvra5',
    '2tgqti',
    'jbacwh',
    '1vifzd',
    'fe57x9',
    'q2goo9',
    'nk4njt',
    'la4mmt',
    'q4ztc2',
    'voobdr',
    'lrxdc8',
    'knw63n',
    'xeklhm',
    'uwuv2v',
    'lsc0yi',
    'mlhi9g',
    'ja2261',
    'rrtsc3',
    'q7dhth',
    '4ssdn4',
    'ofcma6',
    'qu9as2',
    'pkboiz',
    'dd123i',
    'k9u90q',
    'gnhylz',
    'terqpd',
    'ozeg73',
    '6cd1m3',
    '17wi5y',
    'rnj4da',
    'ret0us',
    '24ormv',
    '0nsbs7',
  ],
  linkedin: 'http://www.linkedin.com/company/injective-labs',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/injective-labs',
  github: 'https://github.com/InjectiveLabs',
  telegram: 'https://t.me/joininjective',
  twitter: 'https://twitter.com/Injective_',
  url: 'https://injective.com/',
  verified: false,
} satisfies AdapterProject
