import { AdapterProject } from '../types'

export default {
  name: 'Sarcophagus',
  chain: 'ETHEREUM',
  category: 'OTHER',
  token: 'SARCO',
  coingeckoId: 'sarcophagus',
  id: 'se7wj7',
  description: "Decentralized dead man's switch",
  discord: 'https://discord.com/invite/5XkvsEmMab',
  investors: [
    'hhudw8',
    'hbpmm3',
    'mqgff4',
    'fxmvug',
    'e7om6t',
    'q9qqsj',
    'qqc9zd',
    'vdyl97',
    'xnftxc',
    'bku3ew',
  ],
  linkedin: 'https://github.com/sarcophagus-org',
  duneQueries: null,
  blog: 'http://www.linkedin.com/company/sarcophagusio',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/sarcophagusio',
  url: 'https://sarcophagus.io/',
} satisfies AdapterProject
