import { AdapterProject } from '../types'

export default {
  name: 'Sarcophagus',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'SARCO',
  coinGeckoID: 'sarcophagus',
  id: 'se7wj7',
  description: "Decentralized dead man's switch",
  discord: '753398645507883099',
  investors: [
    'hhudw8',
    'hbpmm3',
    'mqgff4',
    'fxmvug',
    'e7om6t',
    'q9qqsj',
    'qqc9zd',
    'vdyl97',
    'rgk0ot',
    'bku3ew',
  ],
  linkedin: 'https://github.com/sarcophagus-org',
  duneQueries: null,
  foundingYear: null,
  blog: 'http://www.linkedin.com/company/sarcophagusio',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/sarcophagusio',
  url: 'https://sarcophagus.io/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://decrypt.co/90032/crypto-dead-mans-switch-sarcophagus-raises-5-47m-from-vcs-via-dao',
    },
  ],
} satisfies AdapterProject
