import { AdapterProject } from '../types'

export default {
  name: 'Nym',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'WIRELESS',
  token: 'NYM',
  coinGeckoID: 'nym',
  id: '5gc718',
  description:
    'Nym protects communication patterns, IP addresses and metadata for end-users, enterprise and infrastructure operators',
  discord: '824256813200834580',
  investors: [
    'bspyld',
    'pdp1mt',
    'd40or5',
    'k8v3go',
    'la4mmt',
    'apd14v',
    'jitv3q',
    'mywjsu',
    'uwuv2v',
    'wir0cg',
    'nxzb7m',
    't7xkdd',
    'ujw2s3',
    'kjm7ph',
    'xgzede',
    '07pxi6',
    'tqh3bl',
    'c69vl1',
    'llojfj',
  ],
  linkedin: 'http://www.linkedin.com/company/nymproject',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.nymtech.net/',
  github: 'https://github.com/nymtech',
  telegram: 'https://t.me/nymchan',
  twitter: 'https://twitter.com/nymproject',
  url: 'https://nymtech.net/',
  verified: false,
  fundraisesUrls: [
    'https://www.coindesk.com/business/2019/05/13/nym-technologies-raises-25-million-to-anonymize-crypto-apps/',
    'https://techcrunch.com/2021/11/19/nym-raises-13m-from-a16zs-crypto-fund/',
  ],
} satisfies AdapterProject
