import { AdapterProject } from '../types'

export default {
  name: 'Nym',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'WIRELESS',
  token: 'NYM',
  coingeckoId: 'nym',
  id: '5gc718',
  description:
    'Nym protects communication patterns, IP addresses and metadata for end-users, enterprise and infrastructure operators',
  discord: 'https://discord.gg/nym',
  investors: [
    'bspyld',
    'pdp1mt',
    '26x5nn',
    'k8v3go',
    'mrgeec',
    'la4mmt',
    'v2rrnz',
    'jitv3q',
    'mywjsu',
    'uwuv2v',
    'wir0cg',
    'nxzb7m',
    't7xkdd',
    'ujw2s3',
    'kjm7ph',
    'xgzede',
    '07pxi6',
    'tqh3bl',
    'c69vl1',
    'llojfj',
  ],
  linkedin: 'http://www.linkedin.com/company/nymproject',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.nymtech.net/',
  github: 'https://github.com/nymtech',
  telegram: 'https://t.me/nymchan',
  twitter: 'https://twitter.com/nymproject',
  url: 'https://nymtech.net/',
} satisfies AdapterProject
