import { AdapterProject } from '../types'

export default {
  name: 'Kresko',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'pks4ee',
  description:
    'Making wealth accessible to anyone, anywhere. An open platform for synthetic stocks, commodities, and crypto.',
  discord: 'https://discord.com/invite/FG3AuCaHRz',
  investors: [
    '7065hj',
    'z6cdtc',
    'ajzzhi',
    'vkntey',
    'b04x9g',
    '1p1iry',
    'tqh3bl',
    'nlvx3r',
    'v4za8v',
  ],
  linkedin: 'https://www.linkedin.com/company/kreskolabs/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/kreskofi',
  github: 'https://github.com/kreskohq/',
  telegram: 'https://t.me/kreskofi',
  twitter: 'https://twitter.com/kreskofi',
  url: 'https://www.kresko.fi/',
  verified: false,
} satisfies AdapterProject
