import { AdapterProject } from '../types'

export default {
  name: 'XMTP',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coingeckoId: null,
  id: 'rvdlk1',
  description:
    'The Extensible Message Transport Protocol (XMTP) is a secure messaging protocol that enables communication between blockchain accounts.',
  discord: 'https://discord.com/invite/xmtp',
  investors: [
    'm21s7e',
    'y2y3vv',
    '2uillv',
    'omhdmx',
    'tbwpai',
    '26x5nn',
    'rr0j76',
    'cd2nay',
    'lmepop',
    'k5yniy',
    '9v9ugt',
    '896jil',
    'dbo8tt',
    'eqr6sq',
    '7pgfvz',
    'bks4ew',
    'tr916u',
    'km2if5',
    'phdncr',
    'dbskiw',
    '73opsz',
    '21e2s8',
    'wbr2bp',
    'k2s470',
    'x7118g',
    '84vchg',
    'ub70vu',
    'sknhsa',
    '56m0g5',
    'mgnesp',
    'g7agdk',
    '469hl6',
    '0yezfi',
    'rip35s',
    'xuzons',
    's2rvpp',
    'l7sko2',
    'i3z0du',
    'fk1fe5',
    '68ov85',
    'c8adar',
    'e22hk8',
    'ftggor',
    'qseex0',
    '50jw3f',
    '7qpopw',
    'r21x33',
    'x873w6',
    'hai5f5',
    'vneh4n',
    'peq6op',
    '3251gx',
    'h3klar',
    '0p4k7g',
    'f5o3jl',
    'h32wcl',
    '7c0m37',
    '53hd8j',
    'etvgeg',
    'el1juk',
    '5q4e79',
    't0ydan',
    'ivtzio',
    'ojwcp9',
    'hzpxiq',
    'qplnp8',
    'zz3fnm',
    'gnhylz',
    'xezjxn',
    'co49ki',
    '2nph6s',
    'uj91b9',
    'b53azd',
    '0rh814',
    'dmnm1n',
    'o2577p',
    '820cst',
    'wz0frs',
    'tu6afb',
    'hum3ve',
    '9ox376',
    'zhjcle',
    '6zh0nn',
    '2t3jg5',
    'thv317',
    'sz5x0j',
    'k8lm1b',
    '1ev9k4',
    '6iy81o',
    'ksae6d',
    'telo89',
    '07gk2w',
    '44ad84',
    '8a6o80',
    'z0wsaf',
    '6hxbzz',
    '2abi82',
    'z8j32q',
    'myil2k',
    '3bchmx',
    'vrsed8',
    'jx87gk',
    'h8bix0',
    'gwi3em',
    '35j3pt',
    'gduv1m',
  ],
  linkedin: 'https://www.linkedin.com/company/xmtp-labs/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://xmtp.org/blog',
  github: 'https://github.com/xmtp',
  telegram: null,
  twitter: 'https://twitter.com/xmtp_',
  url: 'https://xmtp.org/',
  verified: false,
} satisfies AdapterProject
