import { AdapterProject } from '../types'

export default {
  name: 'Nebula',
  ninja: '0x0F46456F2D00d6a6F10FB18f6c36C0f03129C979',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'Nebula',
  coinGeckoID: 'nebula-2',
  id: 'dt5m92',
  description: 'NEBULA is an AI-Powered Preconfigured Cloud Computing platform.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@nebulateamsupport',
  github: null,
  telegram: 'https://t.me/NebulasPortal',
  twitter: 'https://x.com/NebulasClouds',
  url: 'https://nebulacloudnetwork.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
