import { AdapterProject } from '../types'

export default {
  name: 'UpRock',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: '1rtzqi',
  description: 'UpRock AI revolutionizes decision-making with personalized, real-time insights.',
  discord: '907363977527431270',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/uprock/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/uprockcom',
  telegram: 'https://t.me/uprockcom',
  twitter: 'https://twitter.com/uprockcom',
  url: 'https://uprock.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
