import { AdapterProject } from '../types'

export default {
  name: 'dPing',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'v7ijqy',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/dping_io',
  url: 'https://dping.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
