import { AdapterProject } from '../types'

export default {
  name: 'Overlay',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '5zte11',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/OverlayProtocol',
  url: 'https://overlay.market/#/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
