import { AdapterProject } from '../types'

export default {
  name: 'Pluralis',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'r80yu7',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/Pluralis__',
  url: 'https://pluralis.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
