import { AdapterProject } from '../types'

export default {
  name: 'Trace',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'TRACE',
  coinGeckoID: 'trace-network-labs',
  id: 'bjvhmg',
  description: 'Trace is a metaverse technology for fashion and lifestyle powered by Web 3.0.',
  discord: '889566942678102016',
  investors: [
    'bf6y5u',
    'n6kqj7',
    'xmw0ev',
    'ia20oh',
    'drq7a8',
    'grev3h',
    'rlo5x9',
    '5dsvsj',
    '3uz422',
    'qqc9zd',
    'fnoivv',
    'tzyxtr',
    'ka4f30',
    '5252r4',
    'n73vnt',
    'dd123i',
    'k9u90q',
    '07pxi6',
    'smqwtv',
    '9e1gk4',
  ],
  linkedin: 'http://www.linkedin.com/company/trace-network-labs',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@tracenetwork',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/trace_network',
  url: 'https://trace.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.newsbtc.com/news/company/trace-network-raises-strategic-investment-of-over-1-6-million-from-leading-blockchain-investors/',
    },
  ],
} satisfies AdapterProject
