import { AdapterProject } from '../types'

export default {
  name: 'Trace',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'TRACE',
  coingeckoId: 'trace-network-labs',
  id: 'bjvhmg',
  description:
    'Trace is a decentralized protocol enabling luxury lifestyle for multichain metaverses with NFTs & digital fashion.',
  discord: 'https://discord.com/invite/SF3xyD7xPb',
  investors: [
    'bf6y5u',
    'n6kqj7',
    'xmw0ev',
    'ia20oh',
    'drq7a8',
    'grev3h',
    'rlo5x9',
    '5dsvsj',
    '3uz422',
    'qqc9zd',
    'fnoivv',
    'tzyxtr',
    'ka4f30',
    '5252r4',
    'n73vnt',
    'dd123i',
    'k9u90q',
    '07pxi6',
    'smqwtv',
    '9e1gk4',
    'pyukl2',
  ],
  linkedin: 'http://www.linkedin.com/company/trace-network-labs',
  duneQueries: null,
  blog: 'https://medium.com/@tracenetwork',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/trace_network',
  url: 'https://trace.network/',
} satisfies AdapterProject
