import { AdapterProject } from '../types'

export default {
  name: 'Spacemesh',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 'ojaphf',
  description: 'Decentralized, energy-efficient blockmesh with unique consensus.',
  discord: 'https://discord.com/invite/yVhQ7rC',
  investors: [
    'bspyld',
    'x2iw8r',
    'csfyvy',
    '3o9fr1',
    '5drrpf',
    'xfqvxi',
    'suthoi',
    '73opsz',
    'zaf9xh',
    'isf2hj',
    '6jj8ov',
    '772xwk',
    'dnu31w',
    '5tj4jx',
    'z6cdtc',
    '3qhfkz',
    'wir0cg',
    'y5m26s',
    'ykd20k',
    'vn2xbi',
    '9p60sa',
    'kjm7ph',
    'vfifi9',
    '07pxi6',
    'tfi9fe',
    'tqh3bl',
    'xl9a26',
    'vf0qg4',
    'ooq1d1',
    'qpv2lq',
    'zmowee',
  ],
  linkedin: 'http://www.linkedin.com/company/spacemesh',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/spacemesh',
  github: 'https://github.com/spacemeshos',
  telegram: null,
  twitter: 'https://twitter.com/teamspacemesh',
  url: 'https://spacemesh.io/',
  verified: false,
} satisfies AdapterProject
