import { AdapterProject } from '../types'

export default {
  name: 'Pickspot',
  ninja: 'wholovesburrito.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '9mrlrq',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/pickspotnetwork',
  url: 'https://pickspot.net/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
