import { AdapterProject } from '../types'

export default {
  name: 'Depi',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'zso4nu',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/DepiXYZ',
  url: 'https://www.depi.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
