import { AdapterProject } from '../types'

export default {
  name: 'Coco Swap',
  ninja: null,
  subcategories: 'Gaming',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '0g5igr',
  description: 'Coco Swap: Faster and easier token swaps with COCO token and BSC blockchain.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://coco-swap.finance/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
