import { AdapterProject } from '../types'

export default {
  name: 'Juno',
  ninja: null,
  subcategories: null,
  chain: 'COSMOS',
  category: 'NOT_DEPIN',
  token: 'JUNO',
  coinGeckoID: 'juno-network',
  id: 'e277dp',
  description: 'Juno is decentralized network for interoperable apps',
  discord: '816256689078403103',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/juno-network',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@JunoNetwork',
  github: 'https://github.com/CosmosContracts',
  telegram: 'https://t.me/JunoNetwork',
  twitter: 'https://twitter.com/JunoNetwork',
  url: 'https://junonetwork.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
