import { AdapterProject } from '../types'

export default {
  name: 'SolSplits',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'nyewp0',
  description: 'SolSplits is a composable standard for splitting on-chain income on Solana.',
  discord: '934693914399633418',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/solsplits/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@solsplits',
  github: 'https://github.com/solsplits',
  telegram: null,
  twitter: 'https://twitter.com/solsplits',
  url: 'https://solsplits.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
