import { AdapterProject } from '../types'

export default {
  name: 'Up Network',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '9divjf',
  description: '',
  discord: '1250726425422594080',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://discord.com/invite/upnetworkhq',
  twitter: 'https://x.com/upnetworkhq',
  url: 'https://www.upnetwork.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
