import { AdapterProject } from '../types'

export default {
  name: 'Up Network',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '9divjf',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/upnetworkhq',
  url: 'https://www.upnetwork.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
