import { AdapterProject } from '../types'

export default {
  name: 'Kandola',
  ninja: null,
  subcategories: 'IoT',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '8y4g79',
  description: 'Kandola is a decentralized Chip-to-Cloud IoT Protocol.',
  discord: '958002050174709761',
  investors: [
    'vstg5d',
    'm8rgyb',
    'kav4di',
    'xent44',
    'bxcu1r',
    'l4gut1',
    'wohqmd',
    'ka3b7r',
    '9e1gk4',
  ],
  linkedin: 'https://www.linkedin.com/company/kandola-network/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@KandolaNetwork',
  github: null,
  telegram: 'https://web.telegram.org/a/',
  twitter: 'https://twitter.com/KandolaNetwork',
  url: 'https://kandola.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://www.businesswireindia.com/blockchain-startup-kandola-raises-usd-450k-in-a-pre-seed-round-funding-led-by-arcanum-capital-alphawave-global-and-polygons-sandeep-nailwal-78135.html',
    },
  ],
  isApp: true,
} satisfies AdapterProject
