import { AdapterProject } from '../types'

export default {
  name: 'Rumi',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'DeFi',
  chain: null,
  category: 'NOT_DEPIN',
  token: 'RUMI',
  coinGeckoID: 'rumi-finance',
  id: '3x8glb',
  description: 'Rumi is a permissionless platform for DeFi asset management.',
  discord: '1030554262670942208',
  investors: [],
  linkedin: 'https://pt.linkedin.com/company/rumi-finance',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/rumilabs',
  url: 'https://www.rumi.finance/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
