import { AdapterProject } from '../types'

export default {
  name: 'NuNet',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'NTX',
  coingeckoId: 'nunet',
  id: '6wpm8m',
  description:
    'NuNet is a computing framework that offers global distributed computing power and storage for decentralized networks.',
  discord: 'https://discord.com/invite/8S7JNRBHJa',
  investors: [
    'o5kpgb',
    'nrotlx',
    'u2w7b1',
    '2bl1fj',
    'xdw0yr',
    '243kcn',
    'n73vnt',
    '65epfb',
    'tktadr',
  ],
  linkedin: 'https://www.linkedin.com/company/nunet-global/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/nunet',
  github: null,
  telegram: 'https://t.me/NuNet_community',
  twitter: 'https://twitter.com/nunet_global',
  url: 'https://www.nunet.io/',
  verified: false,
} satisfies AdapterProject
