import { AdapterProject } from '../types'

export default {
  name: 'VeChain',
  ninja: null,
  subcategories: null,
  chain: 'VECHAIN',
  category: 'NOT_DEPIN',
  token: 'VET',
  coingeckoId: 'vechain',
  id: 'ed5hwr',
  description:
    'VeChain enables businesses to build decentralized apps for data transfer and supply-chain management.',
  discord: 'https://discord.com/invite/vechain',
  investors: [
    '8nclhv',
    '3gin8b',
    'v13ekf',
    'k091ng',
    'b8g963',
    '3vixai',
    'pmco7y',
    'tlw2rt',
    'p296oy',
    'caojlf',
    'xeklhm',
    '4mxvwg',
    'mywjsu',
    'rqlsps',
    'e3qnb5',
    'hofy4x',
    'i1x9du',
    '9p60sa',
    'mt8ttl',
    '2raj2q',
    'afeud9',
    'ql9q87',
    '24ormv',
    '935mux',
  ],
  linkedin: 'http://www.linkedin.com/company/vechain-foundation',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://vechainofficial.medium.com/',
  github: 'https://github.com/vechain',
  telegram: 'https://t.me/s/vechainannouncement',
  twitter: 'https://twitter.com/vechainofficial?lang=en',
  url: 'https://www.vechain.org/',
  verified: false,
} satisfies AdapterProject
