import { AdapterProject } from '../types'

export default {
  name: 'VeChain',
  chain: 'VECHAIN',
  category: 'NOT_DEPIN',
  token: 'VET',
  coingeckoId: 'vechain',
  id: 'ed5hwr',
  description:
    'VeChain enables businesses to build decentralized apps for data transfer and supply-chain management.',
  investors: [
    '8nclhv',
    '3gin8b',
    'v13ekf',
    'k091ng',
    'b8g963',
    '3vixai',
    'pmco7y',
    'tlw2rt',
    'p296oy',
    'caojlf',
    'xeklhm',
    '4mxvwg',
    'mywjsu',
    'rqlsps',
    'e3qnb5',
    'hofy4x',
    'i1x9du',
    '9p60sa',
    'mt8ttl',
    '2raj2q',
    'afeud9',
    'ql9q87',
    '24ormv',
    '935mux',
  ],
  duneQueries: null,
} satisfies AdapterProject
