import { AdapterProject } from '../types'

export default {
  name: 'Hyperspace',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'oevejl',
  description:
    'Hyperspace is a decentralized prompt engine for making AI better, faster, and cheaper at-scale.',
  discord: null,
  investors: [
    't2as8g',
    'a9qi3v',
    'nlqu6w',
    'tptsn3',
    '3x72a9',
    'by4pbo',
    'uzi06y',
    'ojom6m',
    '6rzgq8',
    '18r8ir',
    'pp6ut1',
  ],
  linkedin: 'http://www.linkedin.com/company/hyperspacegl',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/hyperspaceorg',
  url: 'https://hyperspace.foundation/',
  verified: false,
} satisfies AdapterProject
