import { AdapterProject } from '../types'

export default {
  name: 'SONM',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'SNM',
  coingeckoId: 'sonm',
  id: 'qjzgqy',
  description:
    'SONM is a decentralized worldwide fog supercomputer for general purpose computing from site hosting to scientific calculations.',
  discord: '1140549119258140722',
  investors: [
    'k9zddv',
    'fdepqs',
    '59nhq9',
    '44qnji',
    'x3p01b',
    'c94bgn',
    'lagcw0',
    'j5a8b4',
    't1lahd',
    'nopne6',
  ],
  linkedin: 'https://www.linkedin.com/company/sonm/about/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://sonm.medium.com/',
  github: 'https://github.com/sonm-io',
  telegram: 'https://t.me/sonm_eng',
  twitter: 'https://twitter.com/sonmdevelopment',
  url: 'https://sonm.com/',
  verified: false,
} satisfies AdapterProject
