import { AdapterProject } from '../types'

export default {
  name: 'PulseFolio',
  ninja: null,
  subcategories: null,
  chain: 'BINANCE',
  category: 'AI',
  token: 'PULSE',
  coinGeckoID: 'pulsefolio',
  id: 'ry8vac',
  description: 'Decentralized AI protocol for personalized investment strategies.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/PulsefolioPortal',
  twitter: 'https://twitter.com/PulseFolio/',
  url: 'https://pulsefolios.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
