import { AdapterProject } from '../types'

export default {
  name: 'Ark',
  ninja: 'ZZ',
  subcategories: 'L1/L2',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'f918a3',
  description: 'Ark is a layer-2 protocol enabling cheap, anonymous, off-chain Bitcoin payments.',
  discord: null,
  investors: [],
  linkedin: 'https://uk.linkedin.com/company/ark-schools',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://projectark.medium.com/',
  github: 'https://github.com/ArkEcosystem',
  telegram: 'https://t.me/s/ARK_Trading_Desk?before=3180',
  twitter: 'https://twitter.com/survivetheark',
  url: 'https://ark.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
