import { AdapterProject } from '../types'

export default {
  name: 'M^ZERO',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'oane9t',
  description:
    'M^ZERO Labs aims to develop a decentralized network enabling institutional participants to reliably link assets to a decentralized infrastructure.',
  discord: null,
  investors: [
    'y8my2p',
    'wux3o5',
    '5175b7',
    'aeti3d',
    'ozeg73',
    '6f2cxt',
    'oygqys',
    'aq52wc',
    'v35xwk',
  ],
  linkedin: 'https://www.linkedin.com/company/m-zero-labs/?originalSubdomain=de',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.m0.xyz/',
  verified: false,
} satisfies AdapterProject
