import { AdapterProject } from '../types'

export default {
  name: 'Royale',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ROYA',
  coingeckoId: 'royale',
  id: 'csbwex',
  description:
    'Provider of cross-chain decentralized finance services intended to serve the iGaming industry.',
  discord: '837332113677090876',
  investors: [
    'o5kpgb',
    'xmw0ev',
    '8a2od5',
    '798xl8',
    'xeklhm',
    'rh0j4p',
    '4cvh3k',
    'eg5xoc',
    'wpvtch',
    'nwl5v7',
    'p5t7hp',
    '0nsbs7',
  ],
  linkedin: 'https://www.linkedin.com/company/officialroyale/about/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://officialroyale.medium.com/',
  github: null,
  telegram: 'https://t.me/RoyaleFinance',
  twitter: 'https://twitter.com/Royale_Finance',
  url: 'https://www.royale.finance/',
  verified: false,
} satisfies AdapterProject
