import { AdapterProject } from '../types'

export default {
  name: 'Deeper',
  chain: 'ETHEREUM',
  category: 'WIRELESS',
  token: 'DPR',
  coingeckoId: 'deeper-network',
  id: '3s1vpm',
  description: 'Deeper is a decentralized VPN and privacy network.',
  investors: [
    'pu3yyr',
    'wu15kr',
    'ka4f30',
    'okjrd0',
    'pcw959',
    'u2w7b1',
    'hxmvxz',
    'b1hrk6',
    'unykak',
    '5dok1r',
    'z2j0xs',
    'terqpd',
    'jshutd',
    'rk3esc',
    'jdil01',
  ],
  duneQueries: null,
  cmcId: 8894,
} satisfies AdapterProject
