import { AdapterProject } from '../types'

export default {
  name: 'CLAPART',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'g7kfey',
  description: 'CLAPART empowers creators and fans for project funding.',
  discord: '947501488429756456',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/clapartgroup',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/CLAPART_Announcements',
  twitter: 'https://twitter.com/clapartofficial',
  url: 'https://www.clapart.com/?locale=en-US',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
