import { AdapterProject } from '../types'

export default {
  name: 'StationX',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'osv0he',
  description: 'StationX is a protocol for swiftly creating and overseeing DAOs in under a minute.',
  discord: '945568396911738982',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/stationxnetwork',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/StationXnetwork',
  twitter: 'https://twitter.com/stationxnetwork',
  url: 'https://www.stationx.network/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
