import { AdapterProject } from '../types'

export default {
  name: 'Seismic',
  ninja: '0x4003408058d490FCD0A8b76925a412E6F39bc939',
  subcategories: 'TEE',
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 's3ffe5',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/SeismicSys',
  url: 'https://www.seismic.systems/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
