import { AdapterProject } from '../types'

export default {
  name: 'Frodobots',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: 'zsejow',
  description: 'Frodobots is an open real-world racing game with sidewalk robots.',
  discord: '943055769157402624',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.frodobots.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
