import { AdapterProject } from '../types'

export default {
  name: 'VulaCoin',
  ninja: null,
  subcategories: 'Wallet',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: '4xae6i',
  description: 'VulaCoin digitizes prepaid cash with stable coin for mobile wallets.',
  discord: null,
  investors: [],
  linkedin: 'http://www.linkedin.com/company/vulacoin',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@vulacoin',
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://about.vulacoin.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
