import { AdapterProject } from '../types'

export default {
  name: 'Thala',
  ninja: null,
  subcategories: null,
  chain: 'APTOS',
  category: 'NOT_DEPIN',
  token: 'THL',
  coinGeckoID: 'thala',
  id: 'rrvozj',
  description: 'Thala is a DeFi protocol native to the Aptos blockchain.',
  discord: '1031262886863048834',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.thala.fi/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
