import { AdapterProject } from '../types'

export default {
  name: 'Thala',
  ninja: null,
  subcategories: null,
  chain: 'APTOS',
  category: 'NOT_DEPIN',
  token: 'THL',
  coinGeckoID: 'thala',
  id: 'rrvozj',
  description: 'Thala is a DeFi protocol native to the Aptos blockchain.',
  discord: '1031262886863048834',
  investors: [
    '26x5nn',
    'yc3rjf',
    '2ks1dq',
    '4l8mmr',
    'hqx0t6',
    '596ql7',
    'yont93',
    '870le2',
    'ucmbtp',
    'micofj',
    'zzypcf',
    '6f2cxt',
    'dgqzvx',
    'd8vsmb',
    '003re3',
    'lhs5s8',
    'oltsrb',
    'o3c9bd',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.thala.fi/',
  verified: false,
} satisfies AdapterProject
