import { AdapterProject } from '../types'

export default {
  name: 'Thala',
  chain: 'APTOS',
  category: 'NOT_DEPIN',
  token: 'THL',
  coingeckoId: 'thala',
  id: 'rrvozj',
  description: 'Thala is a DeFi protocol native to the Aptos blockchain.',
  investors: [
    '26x5nn',
    'yc3rjf',
    '2ks1dq',
    '4l8mmr',
    'hqx0t6',
    '596ql7',
    'yont93',
    '870le2',
    'ucmbtp',
    'micofj',
    'zzypcf',
    '6f2cxt',
    'dgqzvx',
    'd8vsmb',
    '003re3',
    'lhs5s8',
    'oltsrb',
    'o3c9bd',
  ],
  duneQueries: null,
} satisfies AdapterProject
