import { AdapterProject } from '../types'

export default {
  name: 'Suanbot',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'a4zdzs',
  description: 'Telegram bot for permissionless communications',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 't.me/Suanbot',
  twitter: null,
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
