import { AdapterProject } from '../types'

export default {
  name: 'ZKPass',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'uhupn6',
  description: 'ZKPass is a privacy-preserving protocol for private data verification.',
  discord: '950858460122206228',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/zkpass',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/zkpass',
  github: 'https://github.com/zkPassOfficial',
  telegram: null,
  twitter: 'https://twitter.com/zkPass',
  url: 'https://zkpass.org/home',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
