import { AdapterProject } from '../types'

export default {
  name: 'Elusiv',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '3wkk5f',
  description:
    'Elusiv is building a Web3 universal encryption layer empowering the decentralized world.',
  discord: '963285822327652403',
  investors: [
    'fahk60',
    '4l8mmr',
    'bxcu1r',
    '4ssdn4',
    'po8xe3',
    'qyzsbd',
    'fexzjx',
    'n73vnt',
    '07pxi6',
    'jg2vfb',
    'gmkv01',
    'p3lgat',
  ],
  linkedin: 'https://www.linkedin.com/company/elusiv/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/elusiv-privacy',
  github: 'https://github.com/elusiv-privacy',
  telegram: null,
  twitter: 'https://twitter.com/elusivprivacy',
  url: 'https://www.elusiv.io/',
  verified: false,
} satisfies AdapterProject
