import { AdapterProject } from '../types'

export default {
  name: 'Neutralx',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'RWA',
  token: null,
  coinGeckoID: null,
  id: '1d8dh4',
  description: 'Neutral is an exchange for environmental assets.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.linkedin.com/company/neutral-exchange/about/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/NeutralExchange',
  url: 'https://www.neutralx.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
