import { AdapterProject } from '../types'

export default {
  name: 'Arcium',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'v29y88',
  description:
    'Arcium is a parallelized confidential computing network that provides developers and applications with a trustless, verifiable, and efficient framework to run encrypted computations.',
  discord: '963285822327652403',
  investors: [
    'fahk60',
    'nxop7l',
    'jm2nln',
    '4l8mmr',
    'bxcu1r',
    '73opsz',
    '1b3xfu',
    '2p413m',
    'wir0cg',
    'awafbg',
    '4ssdn4',
    'v28nvp',
    'gha27i',
    'po8xe3',
    'fexzjx',
    'n73vnt',
    '07pxi6',
    'oy5ooz',
    'gmkv01',
    'f4g8b6',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/ArciumHQ',
  url: 'https://arcium.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://twitter.com/ArciumHQ/status/1588235769860194304',
    },
    {
      roundType: 'Strategic/Angel',
      url: 'https://twitter.com/ArciumHQ/status/1788557786537689447',
    },
  ],
  isApp: true,
} satisfies AdapterProject
