import { AdapterProject } from '../types'

export default {
  name: 'Graphlinq',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'GLQ',
  coinGeckoID: 'graphlinq-protocol',
  id: 'ofzalk',
  description: 'GraphLinq is a no-code blockchain ecosystembuilt for on-chain automationand dApps.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/graphlinq-protocol/about/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://graphlinq.medium.com/',
  github: 'https://github.com/GraphLinq',
  telegram: 'https://t.me/graphlinq',
  twitter: 'https://twitter.com/graphlinq_proto',
  url: 'https://graphlinq.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
