import { AdapterProject } from '../types'

export default {
  name: 'Inferix',
  ninja: '0x3D8594a62385EB7B35e1687E7AaB35f8260524a9',
  subcategories: 'GPUs',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'adhfwc',
  description: 'Inferix is a Decentralized GPU network for 3D rendering, AI training & inference.',
  discord: '1139015527939981453',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/inferixgpu',
  url: 'https://inferix.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
