import { AdapterProject } from '../types'

export default {
  name: 'Uncentered Systems',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'xb9cw4',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/UncenteredSys',
  url: 'https://uncentered.systems/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
