import { AdapterProject } from '../types'

export default {
  name: 'AYDO',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: '3g5b35',
  description: 'Aydo is a decentralized network of smart home devices.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/AYDOAI',
  telegram: 'https://t.me/aydoai',
  twitter: 'https://x.com/AYDO_AI',
  url: 'https://www.aydo.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
