import { AdapterProject } from '../types'

export default {
  name: 'Native Planet',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: 'URBIT',
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'tk0z9w',
  description: 'Urbit hosting at home.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.nativeplanet.io/hardware',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
