import { AdapterProject } from '../types'

export default {
  name: 'everVision',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'zr5vzn',
  description:
    'everVision: Blockchain provider for Web3 development, offering everPay, Permaswap, PermaDAO, and Web3Infra.',
  discord: '826354651493564446',
  investors: [
    '1zgufc',
    'hhudw8',
    '4l8mmr',
    'm6mz4i',
    'b1hrk6',
    'zirsty',
    'us9d7q',
    'nxzb7m',
    'b5zicz',
    't7xkdd',
    'thxgaw',
    'jhl62h',
    'smqwtv',
    'pu3yyr',
  ],
  linkedin: 'https://sg.linkedin.com/company/ever-vision',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/everFinance',
  telegram: null,
  twitter: 'https://twitter.com/everVisionHQ',
  url: 'https://ever.vision/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
