import { AdapterProject } from '../types'

export default {
  name: 'Agrotoken',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coingeckoId: null,
  id: 'r2yc3l',
  description:
    'Agrotoken allows you to do more and better business with agrocommodities, creating a simpler, more efficient and technological ecosystem. We are the new dimension of agribusiness',
  discord: null,
  investors: [
    's7b833',
    '7puspk',
    'buo8ql',
    '9cyg5d',
    'azeayu',
    '2buriy',
    'ycz5x9',
    'ershn5',
    'gnqpgc',
    't6992i',
  ],
  linkedin: 'https://www.linkedin.com/company/agrotoken/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/agrotoken',
  url: 'https://agrotoken.com/es/',
} satisfies AdapterProject
