import { AdapterProject } from '../types'

export default {
  name: 'SubQuery',
  chain: 'NATIVE',
  category: 'NOT_DEPIN',
  token: 'SQL',
  coingeckoId: 'subquery-network',
  id: 'kzaj07',
  description:
    'SubQuery is a decentralized data aggregation and querying layer for Layer-1 blockchains and dApps.',
  investors: [
    'pdp1mt',
    '7ygqh2',
    'ii5tnv',
    'csfyvy',
    'giq489',
    '6g8wou',
    'pbunpe',
    'tj2f0a',
    'yva82n',
    'k8v3go',
    '5a1i7n',
    'wxro8b',
    '2tgqti',
    '8nclhv',
    'enemyk',
    '6hezki',
    'm6mz4i',
    '35e9e6',
    'v2rrnz',
    'r2lof0',
    'b1hrk6',
    '8e6e1u',
    '0bht16',
    'knw63n',
    'xx442f',
    'zdzojb',
    '5qx1w8',
    'okjrd0',
    'vpdazm',
    'y5m26s',
    'vkntey',
    '9pp2xp',
    '9xb78i',
    'ixk61j',
    'rrtsc3',
    '97h38q',
    'i3u36b',
    'gi55pp',
    '1kxhn8',
    'snubsq',
    '9p60sa',
    'ka4f30',
    '967a4z',
    'qa36jx',
    'dd123i',
    '07pxi6',
    '3cjty6',
    'pwuofb',
    '0u6vae',
    'hbepme',
    '1z06ce',
    '1pxk2o',
    'ciz6c6',
    'e512t7',
    'pu3yyr',
    '2ge04u',
    '3c4o3d',
    '52fjgj',
    'e2dh7y',
    'bt1i9c',
    'nzxtym',
    's812zr',
    't44ifr',
    'e0wtte',
  ],
  duneQueries: null,
  blog: 'https://medium.com/@subquery',
  github: 'https://github.com/OnFinality-io/subql',
  telegram: 'https://t.me/subquerynetwork',
  twitter: 'https://twitter.com/SubQueryNetwork',
  url: 'https://www.subquery.network/',
} satisfies AdapterProject
