import { AdapterProject } from '../types'

export default {
  name: 'Spexi',
  ninja: 'W. L.',
  subcategories: 'Drones',
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: 'xjyor4',
  description:
    'Spexi is a decentralized network of drone operators using the first fly-to-earn drone imagery platform.',
  discord: '1005154271634931844',
  investors: [
    '9ubit6',
    '7ygqh2',
    'hbpmm3',
    'nfgv6v',
    '2mccdz',
    'vuhvkv',
    'h58ujg',
    'z7e0vq',
    'ti312b',
    'kzp9u0',
    'mfu4x6',
    'natuqc',
  ],
  linkedin: 'https://www.linkedin.com/company/spexigon',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/spexinetwork',
  url: 'https://www.spexi.com//',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://finance.yahoo.com/news/software-firm-spexi-raises-us-085832523.html',
    },
  ],
  isApp: true,
} satisfies AdapterProject
