import { AdapterProject } from '../types'

export default {
  name: 'Switch Electric',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: 'IOTEX',
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: 'nm1uyh',
  description: 'Switch Electric Switch is a stealth project built on IoTeX.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/switchelectric#',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/WhyNotSwitch',
  telegram: null,
  twitter: 'https://twitter.com/whyNotSwitch',
  url: 'https://www.whynotswitch.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
