import { AdapterProject } from '../types'

export default {
  name: 'TRACKPAC',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '6nkbmk',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/Trackpacio',
  url: 'https://trackpac.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
