import { AdapterProject } from '../types'

export default {
  name: 'IYO',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'n20fci',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/iyo_audio',
  url: 'https://iyo.audio/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
