import { AdapterProject } from '../types'

export default {
  name: 'Suptho',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coingeckoId: null,
  id: 'rku44v',
  description: 'Suptho: Geo-based social app merging digital experiences with in-person events.',
  discord: 'https://discord.com/invite/M2xcC2Cex5',
  investors: [
    'auczp7',
    'buo8ql',
    'bxcu1r',
    'drq7a8',
    'b04x9g',
    'izwxxy',
    'lhs5s8',
    'oltsrb',
    'ur9o63',
  ],
  linkedin: 'https://www.linkedin.com/company/suptho/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/introducing-suptho',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/SupthoApp',
  url: 'https://www.suptho.xyz/',
  verified: false,
} satisfies AdapterProject
