import { AdapterProject } from '../types'

export default {
  name: 'PlayART',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '3ry0cb',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/playart_media',
  url: 'https://playart.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
