import { AdapterProject } from '../types'

export default {
  name: 'Weatherflow',
  ninja: null,
  subcategories: null,
  chain: 'IOTEX',
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: '4xa4u6',
  description: 'Weatherflow is a decentralized weather monitoring network.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/weatherflow',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/WeatherFlow',
  telegram: null,
  twitter: 'https://twitter.com/weatherflow',
  url: 'https://weatherflow.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
