import { AdapterProject } from '../types'

export default {
  name: 'Tree News',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'TREE',
  coinGeckoID: null,
  id: 'zrsqma',
  description: 'Tree News is a Decentralized Community-Run News Aggregator.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/treetokeneth',
  url: 'https://www.treeofalpha.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
