import { AdapterProject } from '../types'

export default {
  name: 'BitsCrunch',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'x835xi',
  description: 'BitsCrunch: AI-powered, decentralized NFT data for reliable dApps.',
  discord: 'https://discord.com/invite/bitscrunch-official',
  investors: [
    'gjt0lb',
    'puuj5e',
    'buo8ql',
    'dsl20s',
    '73opsz',
    'oxwb9m',
    'bcnphy',
    'jefoou',
    'ubwov4',
    '6hezki',
    '798xl8',
    'n0g582',
    'i1vs03',
    '5dsvsj',
    'mlhi9g',
    'nxzb7m',
    'xdw0yr',
    '22iktu',
    'ekpeem',
    'fsyot8',
    '9p60sa',
    'zzypcf',
    'tzyxtr',
    'd0dwes',
    'k9u90q',
    'jwrten',
    '8agdnp',
    'lhs5s8',
    'pyukl2',
    'lkk8cu',
    'yviisw',
  ],
  linkedin: 'https://www.linkedin.com/company/bitscrunch/',
  duneQueries: null,
  blog: 'https://blog.bitscrunch.com/',
  github: null,
  telegram: 'https://t.me/bitsCrunch/',
  twitter: 'https://twitter.com/bitscrunch/',
  url: 'https://bitscrunch.com/',
} satisfies AdapterProject
