import { AdapterProject } from '../types'

export default {
  name: 'BitsCrunch',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'x835xi',
  description: 'BitsCrunch: AI-powered, decentralized NFT data for reliable dApps.',
  discord: '860459595025219585',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/bitscrunch/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.bitscrunch.com/',
  github: null,
  telegram: 'https://t.me/bitsCrunch/',
  twitter: 'https://twitter.com/bitscrunch/',
  url: 'https://bitscrunch.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
