import { AdapterProject } from '../types'

export default {
  name: 'Lambda',
  ninja: '0x9Ab59cB71d4657f4c2DB7E0963212A81b6445b4c',
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '129gin',
  description: 'Decentralized Storage 3.0 Evolution - LWS Modular Storage Network',
  discord: '998081240697679924',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://lambda.im/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
