import { AdapterProject } from '../types'

export default {
  name: 'Lambda',
  ninja: 'W. L.',
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '129gin',
  description: 'Decentralized Storage 3.0 Evolution - LWS Modular Storage Network',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://lambda.im/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
