import { AdapterProject } from '../types'

export default {
  name: 'Sleepless',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: 'BINANCE',
  category: 'AI',
  token: 'AI',
  coinGeckoID: 'sleepless-ai',
  id: 'u5x0h7',
  description: 'Sleepless AI is a Web3+AI companion gaming platform.',
  discord: '1184356662774083604',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/SleeplessAI_Lab',
  url: 'https://www.sleeplessai.net/home',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
