import { AdapterProject } from '../types'

export default {
  name: 'Copute.ai',
  ninja: 'meta-light',
  subcategories: null,
  chain: null,
  category: null,
  token: null,
  coinGeckoID: null,
  id: 'la5n2y',
  cmcId: null,
  description: null,
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.copute.ai/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject