import { AdapterProject } from '../types'

export default {
  name: 'Datum',
  ninja: null,
  subcategories: 'Data',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'zyw7wx',
  description: 'Datum: Secure, private, and anonymous data storage and trading on blockchain.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/datumfoundation/about/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/datumnetwork',
  url: 'https://datum.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
