import { AdapterProject } from '../types'

export default {
  name: 'Dippy AI',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '2o0fk5',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/dippy_ai',
  url: 'https://www.dippy.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
