import { AdapterProject } from '../types'

export default {
  name: 'Covalent',
  subcategories: 'RPC/Indexing',
  chain: 'ETHEREUM',
  category: 'OTHER',
  token: 'CQT',
  coingeckoId: 'covalent',
  id: 'cfxf9v',
  description:
    'Covalent is a decentralized data infrastructure that enables users to seamlessly access blockchain data that is otherwise inaccessible. Covalent has indexed entire blockchain histories and has transformed these data in a way that is standardized and truly interoperable. Users can leverage a unified API to query virtually any data on a given blockchain.',
  discord: 'https://discord.com/invite/VHgmzB9973',
  investors: [
    'bspyld',
    'spurmc',
    'xmw0ev',
    'r000x8',
    'mrgeec',
    'puuj5e',
    'eq77bg',
    '8nclhv',
    'zqdy3j',
    'la4mmt',
    '73opsz',
    'uwgwnq',
    '6erxyq',
    '6hezki',
    '35e9e6',
    'rwthif',
    'xeklhm',
    'bu5d49',
    'uwuv2v',
    'ja2261',
    '33rsis',
    'vkntey',
    'zzypcf',
    'ulvyo3',
    'k9u90q',
    'pyukl2',
    '5qyd32',
    '2wn9ev',
    '0nsbs7',
  ],
  linkedin: 'https://www.linkedin.com/company/covalenthq/',
  duneQueries: null,
  blog: 'https://www.covalenthq.com/blog/',
  github: 'https://github.com/covalenthq/',
  telegram: 'https://t.me/CovalentHQ',
  twitter: 'https://twitter.com/Covalent_HQ',
  url: 'https://www.covalenthq.com/',
} satisfies AdapterProject
