import { AdapterProject } from '../types'

export default {
  name: 'Greensparc',
  ninja: null,
  subcategories: 'Environmental',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'j8knk9',
  description: 'Greensparc: Sustainable computing and ESG analytics.',
  discord: null,
  investors: ['pkaqi7', 'a3dnz6'],
  linkedin: 'https://www.linkedin.com/company/greensparc/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.greensparc.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/greensparc',
  url: 'https://www.greensparc.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
