import { AdapterProject } from '../types'

export default {
  name: 'Pontem',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'tusnjs',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/PontemNetwork',
  url: 'https://pontem.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
