import { AdapterProject } from '../types'

export default {
  name: 'Beoble',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'y4wofx',
  description: 'Wallet to wallet messaging app',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/beoble_official',
  url: 'https://www.beoble.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
