import { AdapterProject } from '../types'

export default {
  name: 'Sonr',
  ninja: null,
  subcategories: 'L1/L2',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'admvie',
  description: 'Sonr is an L1 blockchain for self-custody decentralized identity.',
  discord: '843061375160156170',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/sonr-io',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://sonr.io/github',
  telegram: null,
  twitter: 'https://sonr.io/twitter',
  url: 'https://sonr.io/home',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
