import { AdapterProject } from '../types'

export default {
  name: 'Spheron',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: 'ARBITRUM',
  category: 'COMPUTE',
  token: 'SPHN',
  coinGeckoID: 'spheron-network',
  id: 'bpnvkv',
  description: 'Spheron Network is a decentralized GPU marketplace for AI.',
  discord: '745315423783878757',
  investors: [
    '4zcbhk',
    'h6uwpw',
    'uydtk8',
    'knfugm',
    'ui1axd',
    'vh40ts',
    'zpvc7c',
    'yoijyl',
    '2x1lbw',
    'et0tra',
    'ikeqay',
    'fmhhl6',
    'tfi9fe',
    'ti312b',
    '9e1gk4',
    'yviisw',
    'urug6u',
  ],
  linkedin: 'https://www.linkedin.com/company/spheron/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.spheron.network',
  github: 'https://github.com/spheronFdn',
  telegram: null,
  twitter: 'https://twitter.com/SpheronFDN',
  url: 'https://spheron.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.linkedin.com/posts/techprashantmaurya_web3-activity-7122206249290452993-PK8Q?utm_source=share&utm_medium=member_desktop',
    },
  ],
  isApp: true,
} satisfies AdapterProject
