import { AdapterProject } from '../types'

export default {
  name: 'Dynex',
  ninja: null,
  subcategories: null,
  chain: 'NATIVE',
  category: 'AI',
  token: 'DNX',
  coinGeckoID: 'dynex',
  id: '6e2zu2',
  description: 'Dynex is a decentralized neuromorphic computing protocol.',
  discord: '1145567770872922223',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/dynextg',
  twitter: 'https://x.com/dynexcoin',
  url: 'https://dynexcoin.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
