import { AdapterProject } from '../types'

export default {
  name: 'Theoriq',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'oahep1',
  description: 'Theoriq is a modular and composable AI Agent Base Layer.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/theoriqai',
  url: 'https://www.theoriq.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
