import { AdapterProject } from '../types'

export default {
  name: 'Gevulot',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'ZK',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '7bg2pd',
  description: 'Gevulot is an Internet-scale compute network for zero-knowledge proofs.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/gevulot_network',
  url: 'https://gevulot.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
