import { AdapterProject } from '../types'

export default {
  name: 'APhone',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: 'PHONE',
  coinGeckoID: null,
  id: 'p8juld',
  description: 'APhone is a decentralized cloud smartphone, powered by Aethir.',
  discord: '1196486945069596832',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/aphonelabs',
  url: 'https://www.aphone.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
