import { AdapterProject } from '../types'

export default {
  name: 'APhone',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'SENSORS',
  token: 'PHONE',
  coinGeckoID: null,
  id: 'p8juld',
  description: 'APhone is the 1st decentralized cloud smartphone, powered by Aethir.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/aphonelabs',
  url: 'https://www.aphone.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
