import { AdapterProject } from '../types'

export default {
  name: 'ONINO',
  ninja: 'ZZ',
  subcategories: 'L1/L2',
  chain: 'BINANCE',
  category: 'NOT_DEPIN',
  token: 'ONI',
  coinGeckoID: 'oni-token',
  id: 'vybtqu',
  description: 'ONINO enables developers to create identity-based dapps with privacy by default.',
  discord: '969202888565993533',
  investors: [],
  linkedin: 'https://de.linkedin.com/company/onino-io',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@OninoOfficial/5becebdee2fb',
  github: 'https://github.com/ONINO-IO',
  telegram: null,
  twitter: 'https://twitter.com/onino_io?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://www.onino.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
