import { AdapterProject } from '../types'

export default {
  name: 'M3tering',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: 'ae6gb1',
  description: 'M3tering incentivizes solar energy investment for underserved regions.',
  discord: '1128564139472736296',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/whynotswitch',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/whyNotSwitch',
  url: 'https://m3tering.whynotswitch.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
