import { AdapterProject } from '../types'

export default {
  name: 'Hypersign',
  ninja: null,
  subcategories: 'ZK',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'HID',
  coinGeckoID: 'hypersign-identity-token',
  id: 'nir8er',
  description: 'Hypersign is a decentralized identity layer for the internet.',
  discord: '777575858075861033',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/hyperminetech/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://hypersign.id/blogs',
  github: 'https://github.com/hypersign-protocol',
  telegram: 'https://t.me/hypersignchain',
  twitter: 'https://twitter.com/hypersignchain',
  url: 'https://hypersign.id/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
