import { AdapterProject } from '../types'

export default {
  name: 'Apocryph',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '5rs7v8',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/apocryphcloud',
  url: 'https://apocryph.network/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
