import { AdapterProject } from '../types'

export default {
  name: 'Story Protocol',
  ninja: 'EV3 Sal',
  subcategories: 'L1/L2',
  chain: null,
  category: 'INTELLECTUAL_PROPERTY',
  token: null,
  coinGeckoID: null,
  id: '5maai7',
  description: '',
  discord: '1133510822975512708',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.storyprotocol.xyz/media',
  github: 'https://github.com/storyprotocol',
  telegram: null,
  twitter: 'https://x.com/StoryProtocol',
  url: 'https://www.storyprotocol.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
