import { AdapterProject } from '../types'

export default {
  name: 'Story Protocol',
  ninja: 'EV3 Sal',
  subcategories: 'Intellectual Property',
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '5maai7',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/StoryProtocol',
  url: 'https://www.storyprotocol.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
