import { AdapterProject } from '../types'

export default {
  name: 'Galxe',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'GAL',
  coinGeckoID: 'galxe',
  id: 'tlwvl7',
  description: 'Galxe develops a credential infrastructure that all Web3 developers can access.',
  discord: '824767871183355954',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://galxe.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
