import { AdapterProject } from '../types'

export default {
  name: 'CESS',
  ninja: null,
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'qdkzic',
  description:
    'CESS is a decentralized cloud storage network supporting enterprise-level applications.',
  discord: '867067208382152744',
  investors: [
    'z2j0xs',
    'i98114',
    'ncaski',
    'sz5akr',
    'rrtsc3',
    'qixq0l',
    '4eyql6',
    '7ligqu',
    'a4jf5o',
    'g5adzv',
    'nj1v3c',
    'pvr738',
    '6m0hgx',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://cess.cloud/',
  verified: false,
  fundraisesUrls: [
    'https://cointelegraph.com/news/decentralized-storage-platform-cess-raises-8-million-13-vc-funds',
  ],
} satisfies AdapterProject
