import { AdapterProject } from '../types'

export default {
  name: 'Ares Protocol',
  ninja: null,
  subcategories: 'Oracle',
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'ARES',
  coinGeckoID: 'ares-protocol',
  id: 'obq296',
  description:
    'Ares is an on-chain-verified oracle platform that provides secure and reliable data services for the Polkadot DeFi ecosystem',
  discord: '857112014648115221',
  investors: [
    'perhf5',
    'h3elac',
    'ri09e0',
    'ck6wgr',
    'i1vs03',
    '6qjs9a',
    'h7yooe',
    '9xb78i',
    '22iktu',
    'ab1ve5',
    '67igtu',
    '7ligqu',
    'rk3esc',
    '5zxzuu',
    'ret0us',
    'xxi1ub',
    'nwl5v7',
    'o7xcsr',
  ],
  linkedin: 'https://www.linkedin.com/company/aresprotocol/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://aresprotocollab.medium.com/',
  github: 'https://github.com/aresprotocols',
  telegram: 'https://t.me/AresProtocolLab',
  twitter: 'https://twitter.com/AresProtocolLab',
  url: 'https://www.aresprotocol.io/',
  verified: false,
} satisfies AdapterProject
