import { AdapterProject } from '../types'

export default {
  name: 'tomi',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'hxlekf',
  description: '',
  discord: '983854078285201408',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/tomidotcom/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/tomipioneers',
  github: null,
  telegram: null,
  twitter: 'https://x.com/tomipioneers',
  url: 'https://tomi.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
