import { AdapterProject } from '../types'

export default {
  name: 'Unimoon',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'UMOON',
  coinGeckoID: 'unimoon-umoon',
  id: '48jwhp',
  description: 'Unimoon maximizes token rewards using AI on Ethereum.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/unimoonportal',
  twitter: 'https://twitter.com/Unimoonofficial',
  url: 'https://unimoon.ai/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
