import { AdapterProject } from '../types'

export default {
  name: 'Farcaster',
  ninja: null,
  subcategories: 'Social',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'qbrxm3',
  description: 'Farcaster is a sufficiently decentralized protocol for building social apps.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/farcaster/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/farcasterxyz',
  telegram: 'https://t.me/farcasterdevchat',
  twitter: 'https://twitter.com/farcaster_xyz',
  url: 'https://www.farcaster.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
