import { AdapterProject } from '../types'

export default {
  name: 'Farcaster',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'qbrxm3',
  description:
    'Farcaster is a sufficiently decentralized protocol for building social apps. Sufficient decentralization means that two people who want to communicate can always do so. It also means developers have permissionless access to public data on the network.',
  discord: null,
  investors: [
    'mp2gqb',
    '0ga0g3',
    '92ar5l',
    '26x5nn',
    'r2f93a',
    'ze1wdg',
    '896jil',
    'ky4d34',
    '596ql7',
    'gwix1y',
    '73opsz',
    'ul6tyf',
    '8nd6rp',
    'vydmt3',
    'ujjw80',
    'jxugz9',
    '2g0699',
    '0rh814',
    '7vfw5s',
    'tr6y85',
    'b51i7e',
    'telo89',
    'v35xwk',
    'pl6fqf',
    'i9mcxw',
    'gasfop',
  ],
  linkedin: 'https://www.linkedin.com/company/farcaster/',
  duneQueries: null,
  blog: null,
  github: 'https://github.com/farcasterxyz',
  telegram: 'https://t.me/farcasterdevchat',
  twitter: 'https://twitter.com/farcaster_xyz',
  url: 'https://www.farcaster.xyz/',
} satisfies AdapterProject
