import { AdapterProject } from '../types'

export default {
  name: 'Minima',
  ninja: null,
  subcategories: 'Mobile, IoT',
  chain: 'NATIVE',
  category: 'BLOCKCHAIN_INFRA',
  token: 'WMINIMA',
  coinGeckoID: 'wrapped-minima',
  id: 'w75xgw',
  description:
    'Minima is a decentralized Layer 1 DePIN blockchain designed to be accessible to as many people as possible by making it compact enough to run on mobile and IoT devices.',
  discord: '562272317930209280',
  investors: [
    'mzqq7s',
    'ug1ce2',
    '1e5ima',
    '4l8mmr',
    '7oqynx',
    'hbpmm3',
    'bxcu1r',
    'eksjs4',
    'w9rvnt',
    'v81ftp',
    'b04x9g',
    '5rmf8c',
    'tktadr',
    'natuqc',
  ],
  linkedin: 'http://www.linkedin.com/company/minimaglobal',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.minima.global/',
  github: 'https://github.com/minima-global',
  telegram: 'https://t.me/Minima_Global',
  twitter: 'https://twitter.com/Minima_Global',
  url: 'https://www.minima.global/',
  verified: false,
} satisfies AdapterProject
