import { AdapterProject } from '../types'

export default {
  name: 'Ansa',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'i9mqty',
  description: 'Ansa Research is a research firm focused on distributed infrastructure.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://ansaresearch.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
