import { AdapterProject } from '../types'

export default {
  name: 'Jiritsu',
  ninja: 'ZZ',
  subcategories: 'L1/L2',
  chain: null,
  category: 'RWA',
  token: null,
  coinGeckoID: null,
  id: 'j68t8z',
  description:
    'The Jiritsu blockchain is a Layer 1 solution for tokenizing and managing real-world assets using Zero-Knowledge Proofs and Multi-Party Computation, ensuring secure, private verification and regulatory compliance.',
  discord: null,
  investors: [
    'mzqq7s',
    'k0celj',
    'vw2n89',
    'y5m26s',
    '1ojew7',
    'tn0wwd',
    '6q7dh3',
    'hepzxq',
    'unykak',
    '5rmf8c',
    '003re3',
    'lhs5s8',
    'ga1lv7',
    'qpv2lq',
  ],
  linkedin: 'https://www.linkedin.com/company/jiritsunetwork/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Jiritsu_Network',
  url: 'https://www.jiritsu.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.prnewswire.com/news-releases/jiritsu-raises-10-2-million-in-funding-to-revolutionize-verifiable-compute-301934115.html',
    },
  ],
  isApp: true,
} satisfies AdapterProject
