import { AdapterProject } from '../types'

export default {
  name: 'Jiritsu',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'j68t8z',
  description:
    'Jiritsu is a decentralized protocol enabling verifiable compute. Jiritsu allows one to orchestrate and verify any computational workflow, integrating any combination of L1, L2 and Middleware.',
  discord: null,
  investors: [
    'mzqq7s',
    'k0celj',
    'vw2n89',
    'y5m26s',
    '1ojew7',
    'tn0wwd',
    '6q7dh3',
    'hepzxq',
    'unykak',
    '5rmf8c',
    '003re3',
    'lhs5s8',
    'ga1lv7',
    'qpv2lq',
  ],
  linkedin: 'https://www.linkedin.com/company/jiritsunetwork/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.jiritsu.network/',
  verified: false,
} satisfies AdapterProject
