import { AdapterProject } from '../types'

export default {
  name: 'Jiritsu',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'j68t8z',
  description:
    'Jiritsu specializes in decentralized and verifiable computing. Their new asset tokenization platform is built on their Unlimited Verifiable Compute (UVC) and decentralized Zero-Knowledge Multi-Party Compute (ZK-MPC) technologies.',
  discord: null,
  investors: [
    'mzqq7s',
    'k0celj',
    'vw2n89',
    'y5m26s',
    '1ojew7',
    'tn0wwd',
    '6q7dh3',
    'hepzxq',
    'unykak',
    '5rmf8c',
    '003re3',
    'lhs5s8',
    'ga1lv7',
    'qpv2lq',
  ],
  linkedin: 'https://www.linkedin.com/company/jiritsunetwork/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Jiritsu_Network',
  url: 'https://www.jiritsu.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.prnewswire.com/news-releases/jiritsu-raises-10-2-million-in-funding-to-revolutionize-verifiable-compute-301934115.html',
    },
  ],
} satisfies AdapterProject
