import { AdapterProject } from '../types'

export default {
  name: 'Reclaim',
  ninja: null,
  subcategories: 'ZK',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '6kjw4f',
  description: 'User consent & data integrity guaranteed cryptographically.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.reclaimprotocol.org/',
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.reclaimprotocol.org/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
