import { AdapterProject } from '../types'

export default {
  name: 'MyShell',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: 'SHELL',
  coinGeckoID: null,
  id: '1gfb8a',
  description:
    'MyShell is a decentralized and comprehensive platform for discovering, creating, and staking AI-native apps.',
  discord: '1122227993805336617',
  investors: [
    '896jil',
    'wvitwb',
    '2njhsb',
    '67mqz0',
    '5tj4jx',
    'ifb7yv',
    'nxzb7m',
    'cnyjaq',
    's4jf02',
    'zwue16',
    'xgzede',
    'gnhylz',
    'zoshoo',
    'smqwtv',
    '9qbjjp',
    'ksae6d',
    'pu3yyr',
    'qce0sh',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://myshell.ai/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://crypto-fundraising.info/projects/myshell/',
    },
    {
      roundType: 'Seed',
      url: 'https://www.theblock.co/post/285072/web3-ai-platform-myshell-funding',
    },
    {
      roundType: 'Seed',
      url: 'https://www.theblock.co/post/256691/web-ai-platform-myshell-funding',
    },
    {
      roundType: 'Seed',
      url: 'https://www.theblock.co/post/256691/web-ai-platform-myshell-funding',
    },
  ],
} satisfies AdapterProject
