import { AdapterProject } from '../types'

export default {
  name: 'Gstake',
  ninja: '0xF91aBEAa8346673E5567e10a5e028f71ECC48e25',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'n6z698',
  description: 'Gstake is a liquid staking solution for DePIN.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/gstakefinance?t=vROorl7zUTqIzywZDfJaCw&s=09',
  url: 'https://www.gstake.fi/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
