import { AdapterProject } from '../types'

export default {
  name: 'InvArch',
  subcategories: 'L1/L2',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'm2541n',
  description:
    'InvArch allows organizations & individuals to manage assets & execute transactions across any blockchain using a single non-custodial account. Powered by the network’s breakthrough Saturn Multisig protocol, InvArch Network users can deploy self-sovereign accounts which may be controlled either individually, by multiple parties, or as a digitally-native organization.',
  discord: 'https://discord.com/invite/invarch',
  investors: [
    'wsbapa',
    'gvqos9',
    'ii5tnv',
    '1e5ima',
    'cpymss',
    'k8v3go',
    'h2tvqq',
    '35e9e6',
    'i1vs03',
    '2stlpq',
    '6qjs9a',
    't7xkdd',
    'yv5v8q',
    'ardv2y',
    'tnkrzw',
    'jofsd4',
    'o7xcsr',
    '7q5pnm',
  ],
  linkedin: 'https://www.linkedin.com/company/invarch/',
  duneQueries: null,
  blog: 'https://invarch.medium.com/',
  github: null,
  telegram: 'https://t.me/InvArch',
  twitter: 'https://twitter.com/InvArchNetwork',
  url: 'https://www.invarch.network/',
} satisfies AdapterProject
