import { AdapterProject } from '../types'

export default {
  name: 'Fetch.ai',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'FET',
  coingeckoId: 'fetch-ai',
  id: 'mhpovr',
  description:
    'Fetch.ai: Blockchain-based AI and ML platform connecting devices for market creation and data value addition.',
  discord: 'https://discord.com/invite/fetchai',
  investors: [
    'fj88qi',
    'o3xe28',
    'n01vko',
    'i98114',
    '1kptr4',
    'laupoy',
    'dm8n2p',
    '3krjgm',
    '948drp',
    'vjpj24',
    '44u6gg',
    'pyukl2',
  ],
  linkedin: 'http://www.linkedin.com/company/fetch-ai',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/fetch-ai',
  github: 'https://github.com/fetchai?utm_source=Website',
  telegram: 'https://t.me/fetch_ai?utm_source=website',
  twitter: 'https://twitter.com/Fetch_ai',
  url: 'https://fetch.ai/',
} satisfies AdapterProject
