import { AdapterProject } from '../types'

export default {
  name: 'Fetch.ai',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'FET',
  coinGeckoID: 'fetch-ai',
  id: 'mhpovr',
  description:
    'Fetch.ai is a Blockchain-based AI and ML platform connecting devices for market creation and data value addition.',
  discord: '1141305890796994651',
  investors: [
    'fj88qi',
    'o3xe28',
    'n01vko',
    'oy2wzi',
    'i98114',
    '1kptr4',
    'dm8n2p',
    '3krjgm',
    'kjm7ph',
    '948drp',
    'vjpj24',
    '44u6gg',
    'pyukl2',
    'h3j1gl',
  ],
  linkedin: 'http://www.linkedin.com/company/fetch-ai',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/fetch-ai',
  github: 'https://github.com/fetchai?utm_source=Website',
  telegram: 'https://t.me/fetch_ai?utm_source=website',
  twitter: 'https://twitter.com/Fetch_ai',
  url: 'https://fetch.ai/',
  verified: false,
  fundraisesUrls: [
    'https://www.cypherhunter.com/zh-hans/e/fetch-ai-raised-funding-2018-06-11/',
    'https://www.coindesk.com/markets/2021/03/10/fetchai-nabs-5m-in-institutional-investment-fireblocks-to-add-support-for-fet-token/',
    'https://www.coindesk.com/business/2023/03/29/ai-focused-crypto-protocol-fetchai-raises-40m-to-deploy-decentralized-machine-learning/',
    'https://cointelegraph.com/news/bitget-pledges-10m-for-fetch-ai-ecosystem-amid-chatgpt-boom',
  ],
} satisfies AdapterProject
