import { AdapterProject } from '../types'

export default {
  name: 'Ramo',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'unhr0p',
  description: '',
  discord: '965534143930851358',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/filmineio/',
  telegram: null,
  twitter: 'https://x.com/ramo_io',
  url: 'https://www.ramo.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
