import { AdapterProject } from '../types'

export default {
  name: 'SmartPoint',
  ninja: null,
  subcategories: null,
  chain: 'IOTEX',
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: '7su9n8',
  description: 'SmartPoint is a decentralized edge computing network.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/smartpoint',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://github.com/topics/smartpoint-cloud-platform',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/SmartPointIO',
  url: 'https://smartpoint.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
