import { AdapterProject } from '../types'

export default {
  name: 'MANTRA',
  ninja: null,
  subcategories: 'DeFi',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'OM',
  coinGeckoID: 'mantra-dao',
  id: 'jnhaaq',
  description:
    'MANTRA is a first of its kind, vertically-integrated and regulatory compliant blockchain ecosystem. ',
  discord: '821988232538357761',
  investors: [
    'ycxcre',
    'l6myld',
    'phsvfp',
    '8nclhv',
    'mkgpcb',
    '6hezki',
    '35e9e6',
    'xx442f',
    'zdzojb',
    'ka4f30',
    'bah2fw',
    'n7ldex',
    'tt1rmz',
    'tnf5cs',
    'nwl5v7',
    'o7xcsr',
    '935mux',
  ],
  linkedin: 'https://www.linkedin.com/company/mantraomniverse/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://mantraomniverse.medium.com/',
  github: null,
  telegram: 'https://t.me/MANTRA_omniverse',
  twitter: 'https://twitter.com/MANTRAOMniverse',
  url: 'https://www.mantraomniverse.com/',
  verified: false,
} satisfies AdapterProject
