import { AdapterProject } from '../types'

export default {
  name: 'NFT3',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'z1ks7o',
  description:
    'NFT3 Labs is a virtual identity framework, enabling personal monetization and identity-lveraging in Web3 applications.',
  discord: 'https://discord.com/invite/HgHuuS9wzx',
  investors: [
    'gjt0lb',
    'yxetck',
    '9a7u1l',
    'giq489',
    '1e5ima',
    'vcxbpn',
    'q4ztc2',
    'bxcu1r',
    '6uuq9l',
    '798xl8',
    'r2lof0',
    '8e6e1u',
    '18l8yx',
    'knw63n',
    '5dsvsj',
    '8zouxb',
    'qqc9zd',
    '6ewe4i',
    'ka4f30',
    'to40x8',
    'b04x9g',
    'f4awf9',
    'lhs5s8',
    'oltsrb',
    '52fjgj',
    'dvz6gg',
    '8uix7q',
    'onzcv5',
    'nwl5v7',
    'gy5k6a',
  ],
  linkedin: 'http://www.linkedin.com/company/nft3',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/nft3',
  github: 'https://github.com/nft3labs',
  telegram: 'https://t.me/nft3com',
  twitter: 'https://twitter.com/nft3com',
  url: 'https://nft3.com/',
  verified: false,
  fundraisesUrls: [
    'https://www.businesswire.com/news/home/20220131005406/en/NFT3-Raises-US7.5-Million-Led-by-Animoca-Brands-Signaling-Decentralized-Identity-Technology-and-NFTs-as-Gate.ioway-to-the-Metaverse',
  ],
} satisfies AdapterProject
