import { AdapterProject } from '../types'

export default {
  name: 'Shardeum',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'SHM',
  coingeckoId: 'shardeum',
  id: 'g65u6w',
  description: 'Shardeum: EVM-based platform ensuring decentralization and security.',
  discord: 'https://discord.com/invite/shardeum',
  investors: [
    'oixym4',
    'z37132',
    '896jil',
    '4l8mmr',
    '93qwp0',
    'wxcf8r',
    'bxcu1r',
    'uwgwnq',
    '2bl1fj',
    '6uuq9l',
    'enemyk',
    '6hezki',
    'r2lof0',
    'nuuvcg',
    'uktppp',
    'geps91',
    'zart5o',
    'zf8iq9',
    'jcbbxl',
    'l4gut1',
    '90k6bh',
    'ldzkf8',
    'cji8w5',
    '8zouxb',
    'vxrpsy',
    'q84v53',
    'dgr3qv',
    'tzyxtr',
    'jf4tai',
    'b04x9g',
    'l307ry',
    'gii6no',
    'sby0uo',
    'fnlug2',
    'cckw2g',
    'ggh7wv',
    '6cp8be',
    'f5e4m8',
    'pgoyl5',
    'n0wdkb',
    'ot4bu5',
    'nzxtym',
    '7i7ead',
    'monvfg',
    'kh8jxd',
    't9lvtn',
    'phgssx',
    '71p088',
    'e0wtte',
  ],
  linkedin: 'http://www.linkedin.com/company/shardeum',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@Shardeum',
  github: 'https://github.com/shardeum/',
  telegram: 'https://telegram.me/shardeum',
  twitter: 'https://twitter.com/shardeum',
  url: 'https://shardeum.org/',
  verified: false,
} satisfies AdapterProject
