import { AdapterProject } from '../types'

export default {
  name: 'MammothAI',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: 'mammothai',
  id: '4gt6gm',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/Mammoth_AI',
  twitter: 'https://twitter.com/mammothai_',
  url: 'https://www.mammothai.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
