import { AdapterProject } from '../types'

export default {
  name: 'Inferix GPU',
  ninja: null,
  subcategories: 'GPUs',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'r1c4n7',
  description: 'Inferix - Decentralized GPU network for 3D rendering, AI training & inference.',
  discord: '1139015527939981453',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@inferixgpu',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/inferixgpu',
  url: 'https://inferix.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
