import { AdapterProject } from '../types'

export default {
  name: 'Bitenet',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '5ctgya',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/bitenet_io',
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
