import { AdapterProject } from '../types'

export default {
  name: 'Livepeer',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'LPT',
  coinGeckoID: 'livepeer',
  id: '0dpzm4',
  description: 'Livepeer is a decentralized network for video encoders and streamers.',
  discord: '423160867534929930',
  investors: [
    'r1a7zj',
    'bspyld',
    'hol96b',
    'ts7u8r',
    'z0kxfe',
    'lksww3',
    'q8z49k',
    '4l2hcd',
    'eumauw',
    '73opsz',
    'szfiug',
    'zaf9xh',
    'isf2hj',
    'mqgff4',
    'apd14v',
    '8one47',
    'eg9pp3',
    'sk9qn6',
    'dd123i',
    '2g0699',
    'f87dvf',
    'hne3si',
    't105wi',
    'ozeg73',
    '5pzmni',
    'fco3b6',
    'rotj2h',
    'xt0vj3',
    'gduv1m',
  ],
  linkedin: 'http://www.linkedin.com/company/livepeer',
  duneQueries: {
    MINT: '2944847',
    REVENUE: '2944851',
    SUPPLY: '2944838',
  },
  foundingYear: null,
  blog: 'https://medium.com/livepeer-blog',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/livepeerorg',
  url: 'https://livepeer.org/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://techcrunch.com/2019/06/17/decentralized-video-infrastructure-platform-livepeer-raises-8m-series-a/',
    },
    {
      roundType: 'Series B',
      url: 'https://www.coindesk.com/business/2021/07/29/decentralized-video-protocol-livepeer-raises-20m-to-take-on-streaming-giants/',
    },
  ],
} satisfies AdapterProject
