import { AdapterProject } from '../types'

export default {
  name: 'Livepeer',
  chain: 'ARBITRUM',
  category: 'COMPUTE',
  token: 'LPT',
  coingeckoId: 'livepeer',
  id: '0dpzm4',
  description: 'Livepeer is decentralized network of video encoders & streamers.',
  investors: [
    '5yy6cw',
    '2g0699',
    'szfiug',
    'zaf9xh',
    '73opsz',
    '7c9znx',
    'dd123i',
    'ozeg73',
    'xt0vj3',
    'hol96b',
    'bspyld',
    't105wi',
    'rotj2h',
    'gduv1m',
    'cxs3go',
    'mqgff4',
    'sk9qn6',
    'f87dvf',
    'nx424z',
    '4wrbd1',
    'uuh4tw',
    '54kbb7',
    'uauf0n',
    'q8z49k',
    'ayqo8y',
    '3118ba',
    'ybtn6z',
    'alik4i',
  ],
  cmcId: 3640,
} satisfies AdapterProject
