import { AdapterProject } from '../types'

export default {
  name: 'Banksea Finance',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'v5r18r',
  description: 'Banksea NFT is the first AI-Driven NFT Oracle & NFT Liquidity Infrastructure.',
  discord: '856444560371875891',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://banksea.finance/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
