import { AdapterProject } from '../types'

export default {
  name: 'Filecoin',
  ninja: null,
  subcategories: null,
  chain: 'FILECOIN',
  category: 'COMPUTE',
  token: 'FIL',
  coinGeckoID: 'filecoin',
  id: 'r1uv9t',
  description:
    'Filecoin is the largest decentralized data storage marketplace, protocol, & cryptocurrency.',
  discord: '1210612276357500978',
  investors: [
    'd40or5',
    'zloyr1',
    '8m8hfx',
    'h2tvqq',
    'te4xtz',
    'b3o7lp',
    'jo973z',
    '94mx0d',
    'saw27c',
    'ri09e0',
    'vax8ny',
    'tuqdxz',
    '2ckrz9',
    'apd14v',
    '772xwk',
    '18l8yx',
    'vuhvkv',
    '48kg9t',
    'x14dla',
    '7zvtvf',
    'h58ujg',
    '2sc5z5',
    'bb4qnj',
    '5dsvsj',
    'bqmpxo',
    'ckjv3m',
    '08hz7d',
    '9n4okv',
    'ujjw80',
    'e7om6t',
    'i1x9du',
    'ccfk2o',
    'eg9pp3',
    'q9qqsj',
    'ujk97b',
    'bpkrxo',
    'lszufu',
    'po1oia',
    'dd123i',
    'co49ki',
    '7fql0t',
    '07pxi6',
    'wfcztc',
    't105wi',
    'tqh3bl',
    'g72mqv',
    'wskgqw',
    'tcaja1',
    'zp05qw',
    'a7c1uh',
    'vf0qg4',
    '3jk0fl',
    'wu15kr',
    'eud02c',
    'rnj4da',
    'x31uoh',
    'vuz4in',
    'natuqc',
    'o7xcsr',
    '3amt6k',
    'hmrrh1',
    '1r0cdr',
  ],
  linkedin: null,
  duneQueries: {
    KEY_METRIC: '4144157',
    NODE_NUMBER: '4144139',
  },
  foundingYear: null,
  blog: 'https://filecoin.io/blog/',
  github: 'https://github.com/filecoin-project',
  telegram: 'https://t.me/filecoinio',
  twitter: 'https://twitter.com/Filecoin',
  url: 'https://filecoin.io/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.coindesk.com/markets/2017/09/07/257-million-filecoin-breaks-all-time-record-for-ico-funding/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
