import { AdapterProject } from '../types'

export default {
  name: 'Filecoin',
  chain: 'FILECOIN',
  category: 'COMPUTE',
  token: 'FIL',
  coingeckoId: 'filecoin',
  id: 't59kqa',
  description:
    "Filecoin is a decentralized storage network designed to store humanity's most important information.",
  investors: [
    '5yy6cw',
    '07pxi6',
    'te4xtz',
    '5dsvsj',
    'bku3ew',
    'wu15kr',
    'zaf9xh',
    'hbpmm3',
    'q9qqsj',
    'i1x9du',
    'h58ujg',
    '26x5nn',
    'zloyr1',
    '772xwk',
    '9n4okv',
    '7c9znx',
    'dd123i',
    'ozeg73',
    'xt0vj3',
    'vuz4in',
    'tqh3bl',
    '4bc5rd',
    'qngu2a',
    '2ckrz9',
    'lszufu',
    't105wi',
    'g72mqv',
    'nf3ei2',
    '2ngx9z',
    'o7xcsr',
    'h2tvqq',
    'ri09e0',
    'o4le4j',
    'd892rm',
    'n0g582',
    'adhmfx',
    '7zvtvf',
    'e3qnb5',
    'ujjw80',
    'ccfk2o',
    'vf0qg4',
    'eud02c',
    'natuqc',
    'jo973z',
    'baurlm',
    'wdtkj1',
    '8m8hfx',
    'odkc1c',
    'doohkn',
    'nl9ebe',
    'd84ej0',
    '8tsi0b',
    'bqmpxo',
    'ckjv3m',
    'wsb1mz',
    'tshiuo',
    'e7om6t',
    'zuaju5',
    '551q4x',
    'dliu7c',
    'ahajub',
    'vc9dns',
    'pldhin',
    'co49ki',
    'mz1hxn',
    'rrix91',
    'ggmwx8',
    'tcaja1',
    '05ojrg',
    '6sajf0',
    'gkv33p',
    '0ytrxu',
    'v788ua',
    'uq3q5o',
    'naazfy',
    'rnj4da',
    'fp3orn',
    'sbpved',
    'atxt9k',
  ],
  duneQueries: null,
  cmcId: 2280,
} satisfies AdapterProject
