import { AdapterProject } from '../types'

export default {
  name: 'Incognito',
  ninja: 'wholovesburrito.eth',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'PRV',
  coinGeckoID: 'incognito-2',
  id: 'g8ux2k',
  description: 'Incognito is a privacy hub for privately shielded cryptocurrency transactions.',
  discord: '1046631732067184711',
  investors: [],
  linkedin: 'https://linkedin.com/company/incognitochain',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@incognitochain',
  github: 'https://github.com/incognitochain',
  telegram: 'https://t.me/incognitochain',
  twitter: 'https://twitter.com/IncognitoChain',
  url: 'https://incognito.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
