import { AdapterProject } from '../types'

export default {
  name: 'Hotspotty',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: '8hmhev',
  description: 'Hotspotty is a tool for ordering and managing helium hotspots.',
  discord: '874255050929745930',
  investors: ['6c0yfx', '1im0oz'],
  linkedin: 'https://www.linkedin.com/company/hotspotty-official/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/hotspotty',
  github: 'https://github.com/hotspotty',
  telegram: null,
  twitter: 'https://twitter.com/hotspotty',
  url: 'https://hotspotty.net/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
