import { AdapterProject } from '../types'

export default {
  name: 'dFusion',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '5kv026',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/dFusionAI',
  url: 'https://www.dfusion.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
