import { AdapterProject } from '../types'

export default {
  name: 'VPN3',
  ninja: null,
  subcategories: 'VPN',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'tficxt',
  description: 'VPN3 is a provider of a decentralized VPN protocol',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.hotspotvpn.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
