import { AdapterProject } from '../types'

export default {
  name: 'Valid One',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '9piig3',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/ValidOne_',
  url: 'https://valid.one/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
