import { AdapterProject } from '../types'

export default {
  name: 'Prodia',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '51ffds',
  description: 'Prodia is an easy-to-use Stable Diffusion API for AI-powered image generation.',
  discord: '961289090886692964',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/prodia-labs/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/prodialabs',
  url: 'https://prodia.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
