import { AdapterProject } from '../types'

export default {
  name: 'Cortensor',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '0lavfs',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/cortensor',
  url: 'https://www.cortensor.network/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
