import { AdapterProject } from '../types'

export default {
  name: 'Flow',
  chain: null,
  category: 'NOT_DEPIN',
  token: 'FLOW',
  coingeckoId: 'flow',
  id: 'g4borf',
  description:
    'Flow is a permissionless layer 1 blockchain, empowering developers to create limitless Web3 apps for mainstream adoption',
  investors: [
    'spurmc',
    'onvq9f',
    'zloyr1',
    'xmw0ev',
    'cpymss',
    '2f68vj',
    'wqn9ms',
    'xvqjcw',
    'tuqdxz',
    '9oo0xs',
    'i98114',
    'mywjsu',
    'lsc0yi',
    '2g0699',
    'f87dvf',
    'w9yetk',
    'g72mqv',
    'wu15kr',
    'thqjz1',
    'qoijyy',
    'x5h9ow',
    'qf539o',
    '9kybya',
    'gduv1m',
    'pcw959',
  ],
  duneQueries: null,
} satisfies AdapterProject
