import { AdapterProject } from '../types'

export default {
  name: 'Supra',
  ninja: 'ZZ',
  subcategories: 'L1/L2',
  chain: 'NATIVE',
  category: 'BLOCKCHAIN_INFRA',
  token: 'SUPRA',
  coinGeckoID: 'supra',
  id: '2d4mvd',
  description:
    'Supra is a powerful Layer-1 blockchain ecosystem that provides advanced cross-chain interoperability and decentralization through its suite of groundbreaking protocols, including decentralized oracles, bridges, and verifiable random functions.',
  discord: '850682587273625661',
  investors: [
    '7bn5bf',
    'ug1ce2',
    'ydmvp5',
    'gjt0lb',
    'pqaoc9',
    'yva82n',
    '0hfvt9',
    'h97beq',
    'r4uuo1',
    '73opsz',
    'enemyk',
    'hc1ro0',
    '18l8yx',
    'qxuz9y',
    'wrzaj6',
    'rh0j4p',
    'nlqu6w',
    'mlhi9g',
    'ja2261',
    'nxzb7m',
    't7xkdd',
    'z2pfjb',
    'ka4f30',
    'xydyea',
    'bah2fw',
    '07pxi6',
    'zytdn7',
    'agwzs7',
    'pwuofb',
    '4u100f',
    'w19rhh',
    '2bbbj5',
    'cuuxy3',
    'unykak',
    'lhs5s8',
    'oltsrb',
    'tktadr',
    'z8j32q',
    '9wcle7',
    'dvz6gg',
    'bix4ir',
    'qf539o',
    '6mh2rx',
    'ixxo16',
    'e0wtte',
    'dovucn',
  ],
  linkedin: 'https://www.linkedin.com/company/supraoracles/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@SupraOracles',
  github: null,
  telegram: 'https://t.me/SupraOracles',
  twitter: 'https://twitter.com/SUPRA_Labs',
  url: 'https://supra.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Accelerator',
      url: 'https://www.mastercard.com/news/press/2021/july/mastercard-launches-new-start-path-cryptocurrency-and-blockchain-program-for-startups/',
    },
    {
      roundType: 'Series A',
      url: 'https://cointelegraph.com/press-releases/supra-completes-over-24m-in-early-stage-funding-to-date',
    },
  ],
  isApp: true,
} satisfies AdapterProject
