import { AdapterProject } from '../types'

export default {
  name: 'Supra',
  subcategories: 'Oracle',
  chain: null,
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: '2d4mvd',
  description:
    'SupraOracles is a decentralized oracle network that allows smart contracts to access off-chain data in a secure and reliable way.',
  discord: 'https://discord.com/invite/supraoracles',
  investors: [
    '7bn5bf',
    'ug1ce2',
    'ydmvp5',
    'gjt0lb',
    'yva82n',
    '0hfvt9',
    'h97beq',
    'r4uuo1',
    '73opsz',
    'enemyk',
    'hc1ro0',
    'n0g582',
    'qxuz9y',
    'rh0j4p',
    'nlqu6w',
    'jcbbxl',
    'mlhi9g',
    'nxzb7m',
    '90k6bh',
    'z2pfjb',
    'ka4f30',
    'xydyea',
    'bah2fw',
    '07pxi6',
    'zytdn7',
    'wfcztc',
    'pwuofb',
    '4u100f',
    'w19rhh',
    '2bbbj5',
    'cuuxy3',
    'unykak',
    'oltsrb',
    'tktadr',
    'dvz6gg',
    'bix4ir',
    'qf539o',
    '6mh2rx',
    'ixxo16',
    'e0wtte',
    'dovucn',
  ],
  linkedin: 'https://www.linkedin.com/company/supraoracles/',
  duneQueries: null,
  blog: 'https://medium.com/@SupraOracles',
  github: null,
  telegram: 'https://t.me/SupraOracles',
  twitter: 'https://twitter.com/SupraOracles',
  url: 'https://supraoracles.com/',
} satisfies AdapterProject
