import { AdapterProject } from '../types'

export default {
  name: 'Unifique',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'dto1yc',
  description: 'Home internet provider in Brazil.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://unifique.com.br/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
