import { AdapterProject } from '../types'

export default {
  name: 'Griffy',
  ninja: null,
  subcategories: 'Prediction Market',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '4loe4v',
  description: 'Griffy is a poll-based prediction markets protocol.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://griffy.app/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
