import { AdapterProject } from '../types'

export default {
  name: 'SelfKey',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'KEY',
  coinGeckoID: 'selfkey',
  id: 'b12fse',
  description: 'SelfKey is a blockchain-based identity platform.',
  discord: '897002577831526460',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/selfkey',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@SelfKey',
  github: 'https://github.com/SelfKeyFoundation',
  telegram: 'https://t.me/selfkeyfoundation',
  twitter: 'https://twitter.com/selfkey',
  url: 'https://selfkey.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
