import { AdapterProject } from '../types'

export default {
  name: 'Bware Labs',
  ninja: null,
  subcategories: 'RPC/Indexing',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'udxaxs',
  description:
    'Bware Labs: Web 3 solution solving latency issues with geographically distributed nodes.',
  discord: '791275547740995594',
  investors: [
    'bp637k',
    'ue6j4s',
    'ajbv45',
    'uwgwnq',
    'xiwarw',
    'uwuv2v',
    'rlo5x9',
    'vkntey',
    'ixk61j',
    'rrtsc3',
    '9p60sa',
    'k9u90q',
    'f0xcpi',
    '7vmgv2',
    'pgoyl5',
    'qnjxzd',
    'gdar4n',
    '2wn9ev',
  ],
  linkedin: 'https://bware.page.link/linkedin',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://bware.page.link/medium',
  github: 'https://bware.page.link/github',
  telegram: 'https://bware.page.link/telegram',
  twitter: 'https://bware.page.link/twitter',
  url: 'https://bwarelabs.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.accesswire.com/689805/bware-labs-raises-6m-in-series-a-funding-round-to-boost-blockchain-api-infrastructure',
    },
  ],
} satisfies AdapterProject
