import { AdapterProject } from '../types'

export default {
  name: 'Bware Labs',
  chain: null,
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: 'udxaxs',
  description:
    'Bware Labs: Web 3 solution solving latency issues with geographically distributed nodes.',
  investors: [
    'ilq2gw',
    'b2wxdu',
    'bp637k',
    'nfo6xr',
    'ue6j4s',
    'ajbv45',
    'hfbe1e',
    'ltitbn',
    'uwgwnq',
    'xiwarw',
    'nbh8i8',
    '6t1kr0',
    'szewq6',
    'rwthif',
    'qxuz9y',
    'uwuv2v',
    'zf8iq9',
    'rlo5x9',
    'vkntey',
    'ixk61j',
    '870le2',
    '9p60sa',
    '4r9qkn',
    'n73vnt',
    'k9u90q',
    'f0xcpi',
    '7vmgv2',
    'pgoyl5',
    'qnjxzd',
    'gdar4n',
    'nwl5v7',
    'o7xcsr',
    '2wn9ev',
  ],
  duneQueries: null,
} satisfies AdapterProject
