import { AdapterProject } from '../types'

export default {
  name: 'Lotus',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '8lf7at',
  description: 'Decentralized Security and Data Ownership for Edge Devices',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://docsend.com/v/hy9yw/lotus-deck-wo-nda',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
