import { AdapterProject } from '../types'

export default {
  name: 'Botanix',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '97mtzl',
  description: 'The first fully decentralized Layer 2 EVM on Bitcoin.',
  discord: '937915188903018498',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.botanixlabs.xyz/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
