import { AdapterProject } from '../types'

export default {
  name: 'RAAD',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'lnurdi',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/raadlabs',
  url: 'https://raad.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
