import { AdapterProject } from '../types'

export default {
  name: 'GPUtopia',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'lj3v06',
  description: 'GPUtopia is a marketplace for decentralized GPU compute and related AI services.',
  discord: '1157469556768514068',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://gputopia.ai/blog',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/GPUtopia',
  url: 'https://gputopia.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
