import { AdapterProject } from '../types'

export default {
  name: 'Kontos',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'bf586p',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/kontosio',
  url: 'https://kontos.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
