import { AdapterProject } from '../types'

export default {
  name: 'Iagon',
  chain: 'CARDANO',
  category: 'OTHER',
  token: 'IAG',
  coingeckoId: 'iagon',
  id: 'omgud6',
  description:
    'Iagon is a decentralized cloud network built on Cardano, revolutionizing data storage and processing.',
  investors: [
    'o5kpgb',
    'xmw0ev',
    '68y1pb',
    '26u2xo',
    'htjmml',
    '15begf',
    'k1qvmn',
    'rlo5x9',
    '5dsvsj',
    'zyyr5b',
    'ehuolk',
    '864q70',
    '8egclo',
    '4r7042',
    '11dur6',
    'l3imfr',
    'dd10pl',
    'brmebh',
  ],
  duneQueries: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/Iagon_official',
  twitter: 'https://twitter.com/IagonOfficial',
} satisfies AdapterProject
