import { AdapterProject } from '../types'

export default {
  name: 'Iagon',
  ninja: 'ZZ',
  subcategories: 'IoT',
  chain: 'CARDANO',
  category: 'BLOCKCHAIN_INFRA',
  token: 'IAG',
  coinGeckoID: 'iagon',
  id: 'omgud6',
  description:
    'Iagon is a decentralized cloud network built on Cardano, revolutionizing data storage and processing.',
  discord: '837215135999197246',
  investors: [
    'o5kpgb',
    'xmw0ev',
    '68y1pb',
    '26u2xo',
    'htjmml',
    '15begf',
    'k1qvmn',
    'rlo5x9',
    '5dsvsj',
    'zyyr5b',
    'ehuolk',
    '864q70',
    '8egclo',
    '4r7042',
    '11dur6',
    'l3imfr',
    'dd10pl',
    'brmebh',
  ],
  linkedin: 'https://www.linkedin.com/company/iagon/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/Iagon_official',
  twitter: 'https://twitter.com/IagonOfficial',
  url: 'https://iagon.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.investing.com/news/cryptocurrency-news/iagon-raises-34m-funding-to-build-first-data-platform-on-cardano-2545346',
    },
  ],
  isApp: true,
} satisfies AdapterProject
