import { AdapterProject } from '../types'

export default {
  name: 'Massive',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 's4glrh',
  description:
    'Massive is an SDK enabling developers to offer premium content to users by leveraging their unused processing power.',
  investors: [
    'gow2jo',
    'ei0xwd',
    '1vifzd',
    '73opsz',
    'skjtm0',
    'wtmpjt',
    'bl0wyj',
    'nio0gx',
    '6p6ssw',
    'ibmmdz',
    'qd0p5n',
    'xlaqe8',
    'a3lqus',
    'hosat8',
    'mc0vmp',
    'e1gqs2',
    'm1prxp',
    'o2577p',
    'mhujq3',
    'ng63an',
    'on54di',
    'ak8c1a',
    'vxdiqe',
    '6iy81o',
    'c24ctk',
    'myil2k',
    'bm9s6p',
    '78enfd',
  ],
  duneQueries: null,
} satisfies AdapterProject
