import { AdapterProject } from '../types'

export default {
  name: 'Massive',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 's4glrh',
  description:
    'Massive is an SDK enabling developers to offer premium content to users by leveraging their unused processing power.',
  discord: null,
  investors: [
    'gow2jo',
    'ei0xwd',
    '1vifzd',
    '73opsz',
    'skjtm0',
    'wtmpjt',
    'bl0wyj',
    'nio0gx',
    '6p6ssw',
    'ibmmdz',
    'qd0p5n',
    'xlaqe8',
    'a3lqus',
    'hosat8',
    'mc0vmp',
    'e1gqs2',
    'm1prxp',
    'o2577p',
    'mhujq3',
    'ng63an',
    'on54di',
    'ak8c1a',
    'vxdiqe',
    '6iy81o',
    'c24ctk',
    'myil2k',
    'bm9s6p',
    '78enfd',
  ],
  linkedin: 'https://www.linkedin.com/company/massive/about/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/topics/massive',
  telegram: null,
  twitter: null,
  url: 'https://www.joinmassive.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.prnewswire.com/news-releases/massive-raises-11-million-in-seed-funding-from-point72-ventures-to-bring-a-new-business-model-to-the-internet-301434259.html',
    },
  ],
} satisfies AdapterProject
