import { AdapterProject } from '../types'

export default {
  name: 'Gun.Eco',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'RPC/Indexing',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'fk3mfi',
  description: 'Gun.Eco is a decentralized distributed graph database engine for developers.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/gun-io',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/topics/gunjs',
  telegram: null,
  twitter: 'https://twitter.com/databasegun',
  url: 'https://gun.eco/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
