import { AdapterProject } from '../types'

export default {
  name: 'Rangeview',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'u0jkdv',
  description: 'Rangeview is a developer of industrial machinery designed to make aerospace parts.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/rangeview',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://rangeview.co/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
