import { AdapterProject } from '../types'

export default {
  name: 'Rangeview',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'u0jkdv',
  description: 'Rangeview is a developer of industrial machinery designed to make aerospace parts.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/rangeview',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://rangeview.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
