import { AdapterProject } from '../types'

export default {
  name: 'Metablox',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'k5fxwj',
  description:
    'Metablox is a provider of enterprise-grade WiFi roaming solutions, delivering worldwide public access.',
  discord: '916937100744597548',
  investors: [
    'fahk60',
    'zaf9xh',
    'k0celj',
    '4t27eh',
    'xz1vnr',
    'g4z7os',
    'vzqumt',
    'z22qa3',
    'v7aaaw',
    'wu15kr',
    '9jfdo8',
    'xf57bt',
    'gasfop',
    'o5of0s',
  ],
  linkedin: 'https://www.linkedin.com/company/metablox/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://metabloxnetwork.medium.com/metablox-x-cryptolab-ama-recap-highlights-ba556d3ce506',
  github: 'https://github.com/MetaBloxIO',
  telegram: null,
  twitter: 'https://twitter.com/metablox',
  url: 'https://metablox.io/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.venturecapitaljournal.com/metablox-inks-seed-financing/',
    },
    {
      roundType: 'Strategic/Angel',
      url: 'https://twitter.com/DePINBuddy/status/1773164755634487785',
    },
  ],
} satisfies AdapterProject
