import { AdapterProject } from '../types'

export default {
  name: 'Swaye',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: 'Prediction Market',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '58duis',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/swaye_co',
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
