import { AdapterProject } from '../types'

export default {
  name: 'Sorella Labs',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '3mqf4i',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/SorellaLabs',
  telegram: null,
  twitter: 'https://twitter.com/sorellalabs',
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
