import { AdapterProject } from '../types'

export default {
  name: 'SingularityDAO',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'SDAO',
  coingeckoId: 'singularitydao',
  id: 'g7dhjc',
  description:
    'SingularityDAO: Decentralized Portfolio Management Protocol for safe and easy crypto asset management.',
  investors: [
    'z2j0xs',
    'o5kpgb',
    'xmw0ev',
    'u2w7b1',
    '798xl8',
    'i98114',
    'rlo5x9',
    'xdw0yr',
    'e9qwvr',
    '8kqjbk',
    '243kcn',
    'dd123i',
    '65epfb',
    '9ptsrm',
    '17wi5y',
    'tktadr',
    '0nsbs7',
  ],
  duneQueries: null,
  blog: 'https://medium.com/singularitydao',
  github: null,
  telegram: 'https://t.me/SingDAO',
  twitter: 'https://twitter.com/SingularityDao',
  url: 'https://www.singularitydao.ai/',
} satisfies AdapterProject
