import { AdapterProject } from '../types'

export default {
  name: 'commune',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'COMAI',
  coinGeckoID: 'commune-ai',
  id: 'dam39v',
  description: 'commune is a Peer to Peer Incentive-driven Coordination System for AI.',
  discord: '941362322000203776',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/commune-ai',
  telegram: null,
  twitter: 'https://twitter.com/communeaidotorg',
  url: 'https://www.communeai.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
