import { AdapterProject } from '../types'

export default {
  name: 'MedeLeite',
  ninja: null,
  subcategories: 'Software',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'jtrmoh',
  description: 'Full-stack supply chain platform for mlik production',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.medeleite.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
