import { AdapterProject } from '../types'

export default {
  name: 'AirTor',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'WIRELESS',
  token: 'ATOR',
  coinGeckoID: 'airtor-protocol',
  id: 'l9if1e',
  description: 'AirTor: Proof-of-uptime and relay hardware for passive earning and support of Tor.',
  discord: '1083735132470521907',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@ZeroSumTrayder/ator-protocol-the-next-big-thing-6d67a87243e2',
  github: 'https://github.com/ATOR-Development',
  telegram: 'https://t.me/atorcommunityportal',
  twitter: 'https://twitter.com/atorprotocol',
  url: 'https://ator.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
