import { AdapterProject } from '../types'

export default {
  name: 'Nitro League',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'NITRO',
  coingeckoId: 'nitro-league',
  id: '5m6iby',
  description:
    'Nitro League is a decentralized game where players earn tokens racing futuristic cars and completing missions.',
  investors: [
    'ajbv45',
    '4apzxz',
    'n0g582',
    'qxuz9y',
    'og4xif',
    '870le2',
    'qqc9zd',
    'tzyxtr',
    'k9u90q',
    '07pxi6',
    'jk6ype',
    'tdw5kr',
    '2zfr6y',
    '614ya2',
    '2wn9ev',
    'nv73pg',
    '32ha77',
  ],
  duneQueries: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/nitroleaguegame',
  twitter: 'https://twitter.com/nitroleaguegame',
  url: 'https://www.nitroleague.com/',
} satisfies AdapterProject
