import { AdapterProject } from '../types'

export default {
  name: 'RevoFi',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'bdxcwj',
  description: 'RevoFi is a decentralized wireless infrastructure platform.',
  discord: '839162257862295554',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/revofi',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/revofico?lang=en',
  url: 'https://revofi.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
