import { AdapterProject } from '../types'

export default {
  name: 'W3AIRouter',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '29n75r',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/W3AIRouter',
  url: 'https://www.w3airouter.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
