import { AdapterProject } from '../types'

export default {
  name: 'Pyse',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: '44h60y',
  description: 'Pyse enables retail investing in renewable energy assets.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'http://www.linkedin.com/company/pysefin',
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://pyse.in/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
