import { AdapterProject } from '../types'

export default {
  name: 'NEAR Health',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'xmvwz4',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/nearhealth_',
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
