import { AdapterProject } from '../types'

export default {
  name: 'DIMO',
  ninja: null,
  subcategories: 'Mobility',
  chain: 'POLYGON',
  category: 'SENSORS',
  token: 'DIMO',
  coinGeckoID: 'dimo',
  id: '0wr2ea',
  description: 'DIMO is a decentralized ecosystem of connected vehicles.',
  discord: '892438668453740634',
  investors: [
    'eu0hym',
    '6xvdkx',
    'k5yniy',
    'kpxn7o',
    'buo8ql',
    'szfiug',
    'p7lpx4',
    'fwm3hf',
    'ofm89h',
    'ty4xtv',
    'kdz1ka',
    'q9qqsj',
    'ff0uq6',
    'f3ofqn',
    'akhe1r',
    '4x80nx',
    'pdggb7',
    'o2577p',
    'qcisd1',
    'eh4ivf',
    'xiw1r7',
    'ooq1d1',
    '3c4o3d',
    'er8yvb',
    'twnyql',
    'gwi3em',
    'ubuz3j',
    'xk2j4b',
    'fpfcrh',
  ],
  linkedin: 'https://www.linkedin.com/company/dimo-network',
  duneQueries: {
    KEY_METRIC: '3241310',
    NODE_NUMBER: '3448434',
  },
  foundingYear: null,
  blog: 'https://dimo.zone/news',
  github: 'https://github.com/DIMO-Network',
  telegram: null,
  twitter: 'https://twitter.com/DIMO_Network',
  url: 'https://dimo.zone/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.coindesk.com/business/2022/02/15/coinfund-joins-9m-round-for-digital-infrastructure-incs-bid-to-decentralize-vehicle-data/',
    },
    {
      roundType: 'Series A',
      url: 'https://www.theblock.co/post/272456/decentralized-infrastructure-11-5-million-series-a-coinfund',
    },
  ],
} satisfies AdapterProject
