import { AdapterProject } from '../types'

export default {
  name: 'Dimo',
  chain: 'POLYGON',
  category: 'SENSORS',
  token: 'DIMO',
  coingeckoId: 'dimo',
  id: '0wr2ea',
  description: 'Dimo is a decentralized ecosystem of connected vehicles.',
  investors: [
    'ekbjen',
    '3k9ouz',
    'k5yniy',
    '15df7f',
    'szfiug',
    'sew7au',
    'anxufn',
    'pj0uyc',
    '4gxtxe',
    'q9qqsj',
    'exufh8',
    'mjbflx',
    'sd27jl',
    'evpa5e',
    'kh62fk',
    'nejuin',
    '5k429i',
    'gribdd',
    'ooq1d1',
    '3c4o3d',
    'er8yvb',
    'pfvp3a',
    'twqdfw',
    'j29sm3',
    'gaps2j',
    'q6mnc6',
  ],
  duneQueries: null,
} satisfies AdapterProject
