import { AdapterProject } from '../types'

export default {
  name: 'DILL',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '0gi6mz',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/dill_xyz_',
  url: 'https://www.dill.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
