import { AdapterProject } from '../types'

export default {
  name: 'cheqd',
  chain: 'COSMOS',
  category: 'OTHER',
  token: 'CHEQ',
  coingeckoId: 'cheqd-network',
  id: 'o6gk4u',
  description: 'Cheqd offers infrastructure for trusted data markets.',
  investors: [
    'e4xh6i',
    'kans6x',
    'gun7y3',
    'k2hev4',
    'n01vko',
    '91420f',
    'l70dye',
    'ddz0bc',
    'n0g582',
    'xznxug',
    'cn32xf',
    'xx442f',
    '2o1qgx',
    'ivz32u',
    '6oicpo',
    'q6o5fc',
    'c9dgeq',
    '50jszy',
    'vjpj24',
    '5o347p',
    '8n2fw1',
    'oxft8q',
    'kic36s',
  ],
  duneQueries: null,
} satisfies AdapterProject
