import { AdapterProject } from '../types'

export default {
  name: 'cheqd',
  ninja: null,
  subcategories: 'Data',
  chain: 'COSMOS',
  category: 'BLOCKCHAIN_INFRA',
  token: 'CHEQ',
  coinGeckoID: 'cheqd-network',
  id: 'o6gk4u',
  description: 'Cheqd offers infrastructure for trusted data markets.',
  discord: '879754359859216394',
  investors: [
    'e4xh6i',
    'ept6x8',
    'gun7y3',
    'k2hev4',
    'n01vko',
    '91420f',
    'l70dye',
    'ddz0bc',
    '18l8yx',
    'xznxug',
    'cn32xf',
    'xx442f',
    '2o1qgx',
    'ivz32u',
    '6oicpo',
    'q6o5fc',
    'c9dgeq',
    '50jszy',
    'vjpj24',
    '5o347p',
    '8n2fw1',
    'oxft8q',
    'kic36s',
  ],
  linkedin: 'http://www.linkedin.com/company/cheqd-identity',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.cheqd.io/',
  github: 'https://github.com/cheqd',
  telegram: 'https://t.me/cheqd',
  twitter: 'https://twitter.com/cheqd_io',
  url: 'https://cheqd.io/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://cheqd.io/blog/cheqd-raises-2-6-million-to-drive-the-uptake-of-digital-ids/',
    },
  ],
} satisfies AdapterProject
