import { AdapterProject } from '../types'

export default {
  name: 'RoseonApp',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '3stx3v',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/RoseonApp',
  url: 'https://roseon.world/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
