import { AdapterProject } from '../types'

export default {
  name: 'AIT',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'ux0c4s',
  description: 'Intersection of AI & blockchain',
  discord: null,
  investors: [
    'g4q79j',
    'gjt0lb',
    'fj88qi',
    'llgix7',
    '2bl1fj',
    '967a4z',
    'qa36jx',
    '1t2jxf',
    'bah2fw',
    'k9u90q',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://ait.tech/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://finance.yahoo.com/news/ait-protocol-receives-investment-animoca-075000283.html',
    },
    {
      roundType: 'Seed',
      url: 'https://www.binance.com/en/feed/post/2023-12-13-ait-protocol-completes-new-funding-round-with-participation-from-multiple-investors-1317935449953',
    },
    {
      roundType: 'Seed',
      url: 'https://twitter.com/AITProtocol/status/1734558802459152682',
    },
  ],
  isApp: true,
} satisfies AdapterProject
