import { AdapterProject } from '../types'

export default {
  name: 'Ankr',
  chain: 'ETHEREUM',
  category: 'OTHER',
  token: 'ANKR',
  coingeckoId: 'ankr',
  id: 'hqtk8u',
  description:
    'Ankr is a blockchain node infrastructure network enhancing multi-chain tools for Web3, DeFi, and the crypto economy.',
  investors: [
    '07pxi6',
    'te4xtz',
    'tg9num',
    'gj9v6c',
    'gun7y3',
    'zloyr1',
    'ztpy5d',
    '35e9e6',
    '772xwk',
    'tzyxtr',
    'dd123i',
    'ozeg73',
    'wlc0pw',
    '8nclhv',
    'addxil',
    'rwthif',
    'v90s8d',
    'kjm7ph',
    '23uc3k',
    'xvgf6w',
    'bv2lun',
    'mrgeec',
    'ap48og',
    'lrxdc8',
    'gzipi5',
    'z2frfw',
    'r8n4fo',
    'p5udhm',
    '3wlhk2',
    '9205ui',
    '3e0qzv',
    '7r65uq',
    '9ptsrm',
  ],
  cmcSlug: 'ankr',
} satisfies AdapterProject
