import { AdapterProject } from '../types'

export default {
  name: 'RSS3',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'RSS3',
  coingeckoId: 'rss3',
  id: '1tdy5h',
  description: 'RSS3 is a next-gen feed protocol for decentralized applications.',
  investors: [
    'hhudw8',
    '5b00r6',
    'abvcou',
    '896jil',
    '73opsz',
    'skjtm0',
    '2ckrz9',
    '2mccdz',
    '5tj4jx',
    'i98114',
    '4x7qfo',
    '6ln74n',
    'n5z0zx',
    'us9d7q',
    'nxzb7m',
    'zagn6s',
    't7xkdd',
    'w9dy7u',
    'q9nh9n',
    '870le2',
    'eehu3u',
    'aiqhf6',
    'jynpbk',
    'qxfsh5',
    'thxgaw',
    'd85f6i',
    'l73dc6',
    'xph9q9',
    'pu3yyr',
    'm5cayq',
    '6m0hgx',
    'oa0h6s',
    'pcw959',
  ],
  duneQueries: null,
  blog: 'https://medium.com/tag/rss3',
  github: 'https://github.com/NaturalSelectionLabs',
  telegram: 'https://bit.ly/3e6FZoV',
  twitter: 'https://twitter.com/RSS3_',
  url: 'https://rss3.io/',
} satisfies AdapterProject
