import { AdapterProject } from '../types'

export default {
  name: 'RSS3',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'RSS3',
  coinGeckoID: 'rss3',
  id: '1tdy5h',
  description: 'RSS3 is a next-gen feed protocol for decentralized applications.',
  discord: '837332113677090876',
  investors: [
    'hhudw8',
    '5b00r6',
    'abvcou',
    'b9h5l3',
    '896jil',
    '73opsz',
    'skjtm0',
    '2ckrz9',
    '2mccdz',
    '5tj4jx',
    'i98114',
    '4x7qfo',
    '6ln74n',
    'n5z0zx',
    'us9d7q',
    'nxzb7m',
    'zagn6s',
    't7xkdd',
    'w9dy7u',
    'q9nh9n',
    'rrtsc3',
    'eehu3u',
    'aiqhf6',
    'jynpbk',
    'qxfsh5',
    'thxgaw',
    'd85f6i',
    'l73dc6',
    'xph9q9',
    'pu3yyr',
    'm5cayq',
    '6m0hgx',
    'oa0h6s',
    'pcw959',
  ],
  linkedin: 'http://www.linkedin.com/company/rss3',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/tag/rss3',
  github: 'https://github.com/NaturalSelectionLabs',
  telegram: 'https://bit.ly/3e6FZoV',
  twitter: 'https://twitter.com/RSS3_',
  url: 'https://rss3.io/',
  verified: false,
  fundraisesUrls: [
    'https://www.coindesk.com/business/2023/04/11/information-protocol-rss3-raises-10m-via-token-sale-to-dwf-labs/',
  ],
} satisfies AdapterProject
