import { AdapterProject } from '../types'

export default {
  name: 'Magna',
  ninja: '0x4003408058d490FCD0A8b76925a412E6F39bc939',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'zbf95j',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/magna_digital',
  url: 'https://www.magna.so/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
