import { AdapterProject } from '../types'

export default {
  name: 'Magna',
  ninja: 'vkurup.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'zbf95j',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/magna_digital',
  url: 'https://www.magna.so/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
