import { AdapterProject } from '../types'

export default {
  name: 'Peaq',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'PEAQ',
  category: 'BLOCKCHAIN_INFRA',
  token: 'PEAQ',
  coinGeckoID: 'peaq-2',
  id: 'vx7fas',
  description: 'Peaq provides decentralized infrastructure and tools for dapp builders and users.',
  discord: '943486047625572392',
  investors: [
    'eq458r',
    'gjt0lb',
    'buo8ql',
    'xvqjcw',
    'l70dye',
    'bxcu1r',
    '1k9g0d',
    '798xl8',
    '7eqfdf',
    'i98114',
    'n5z0zx',
    'jki94w',
    'mlhi9g',
    'v81ftp',
    'fn2hky',
    '89glxu',
    'ka4f30',
    'n73vnt',
    '4dh0t9',
    '07pxi6',
    'pgoyl5',
    '8dhvoo',
    'nzxtym',
    'o7xcsr',
  ],
  linkedin: 'https://www.linkedin.com/company/peaq-network/',
  duneQueries: {
    REVENUE: '4807708',
  },
  foundingYear: null,
  blog: 'https://medium.com/peaqnetwork',
  github: null,
  telegram: 'https://t.me/s/peaqnetwork?before=165',
  twitter: 'https://twitter.com/peaqnetwork',
  url: 'https://www.peaq.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Private/Public token sale',
      url: 'https://coinlist.co/peaq',
    },
    {
      roundType: 'Seed',
      url: 'https://www.coindesk.com/business/2022/06/28/web3-network-peaq-raises-6m-led-by-fundamental-labs/',
    },
    {
      roundType: 'Series A',
      url: 'https://www.theblock.co/post/285001/depin-layer-1-peaq-raises-15-million-in-pre-launch-funding',
    },
  ],
  isApp: true,
} satisfies AdapterProject
