import { AdapterProject } from '../types'

export default {
  name: 'Source',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '0c3hjd',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/sourcenetwrk',
  url: 'https://source.network/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
