import { AdapterProject } from '../types'

export default {
  name: 'Zaya',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'q8rs1m',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/zayaai_pathdx',
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
