import { AdapterProject } from '../types'

export default {
  name: 'GreenPower',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: '6t7pf0',
  description: 'GreenPower is a decentralized network of global sustainability activists.',
  discord: '978985389857570826',
  investors: [],
  linkedin: 'https://au.linkedin.com/company/greenpower-australia',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@marketing_84129',
  github: 'https://github.com/laurentphilippe/greenpower',
  telegram: null,
  twitter: 'https://twitter.com/Greenpowertrus',
  url: 'https://www.greenpowern.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
