import { AdapterProject } from '../types'

export default {
  name: 'Kino',
  ninja: null,
  subcategories: 'NFTs',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'u1g1gw',
  description: 'KINO aims to make the film/tv industry more equitable for all.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.linkedin.com/company/kinomakesmovies/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/kinomakesmovies',
  url: 'https://www.kino.studio/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
