import { AdapterProject } from '../types'

export default {
  name: '6079',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'v4u52z',
  description: '6079.ai is an open and distributed protocol for AI inference.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/6079ai',
  url: 'https://6079.ai/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
