import { AdapterProject } from '../types'

export default {
  name: 'Sahara',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Agents',
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'a2h6y8',
  description:
    'Sahara is a decentralized AI network enabling everyone to securely deploy and leverage custom AI agents.',
  discord: null,
  investors: [
    '4bc5rd',
    '596ql7',
    'bax7uz',
    'r54jbx',
    '9oo0xs',
    '7zxuth',
    'ikeqay',
    'yodrbc',
    'zoshoo',
    'tqh3bl',
    '1im0oz',
    '9e1gk4',
    'vf0qg4',
    '6fx6k3',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/SaharaLabsAI',
  url: 'https://www.saharalabs.ai/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://chainwire.org/2024/03/05/sahara-raises-6-million-seed-round-to-democratize-global-knowledge-capital-access-through-ai-and-blockchain-technologies-led-by-polychain-capital/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
