import { AdapterProject } from '../types'

export default {
  name: 'Keyring',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '3s01ds',
  description: '',
  discord: '920027753900810281',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/keyring-network/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/KeyringNetwork',
  url: 'https://www.keyring.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
