import { AdapterProject } from '../types'

export default {
  name: 'Keyring',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '3s01ds',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/KeyringNetwork',
  url: 'https://www.keyring.network/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
