import { AdapterProject } from '../types'

export default {
  name: 'OctaSpace',
  ninja: 'W. L.',
  subcategories: 'Storage, VPN',
  chain: 'NATIVE',
  category: 'COMPUTE',
  token: 'OCTA',
  coinGeckoID: 'octaspace',
  id: 'eppbxs',
  description: 'OctaSpace is a decentralized cloud computing network.',
  discord: '973249548245925958',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://octa.space/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
