import { AdapterProject } from '../types'

export default {
  name: 'OctaSpace',
  ninja: '0x9Ab59cB71d4657f4c2DB7E0963212A81b6445b4c',
  subcategories: 'Storage',
  chain: 'NATIVE',
  category: 'COMPUTE',
  token: 'OCTA',
  coinGeckoID: 'octaspace',
  id: 'eppbxs',
  description: 'OctaSpace is a decentralized cloud computing network.',
  discord: '973249548245925958',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://octa.space/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
