import { AdapterProject } from '../types'

export default {
  name: 'Arbitrum',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ARB',
  coinGeckoID: 'arbitrum',
  id: 'v0j5p5',
  description: 'Arbitrum: Fast, scalable and cost-efficient Ethereum scaling solution.',
  discord: '585084330037084172',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/offchainlabs',
  github: null,
  telegram: 'https://t.me/s/arbitrum',
  twitter: 'https://twitter.com/arbitrum',
  url: 'https://arbitrum.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
