import { AdapterProject } from '../types'

export default {
  name: 'Arbitrum',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ARB',
  coingeckoId: 'arbitrum',
  id: 'v0j5p5',
  description: 'Arbitrum: Fast, scalable and cost-efficient Ethereum scaling solution.',
  discord: 'https://discord.com/invite/arbitrum',
  investors: [
    '0ga0g3',
    '7ygqh2',
    '93qwp0',
    'i8ag5m',
    'rqnzcf',
    '73opsz',
    'zaf9xh',
    'mqgff4',
    'tfdh2e',
    'qp5s3g',
    '0y8voh',
    'kk8zod',
    'mywjsu',
    '67nk5m',
    'i1x9du',
    'qivqf5',
    'rwhpsx',
    'pkboiz',
    'ulvyo3',
    'oxjxo0',
    'dd123i',
    'smqwtv',
    '0u6vae',
    'ozeg73',
    '6f2cxt',
    'tqh3bl',
    '19djg3',
    'ofhc4b',
    'zhjcle',
    'b51i7e',
    '1im0oz',
    'wu15kr',
    'pgoyl5',
    'v35xwk',
    'ywa2is',
    'mwx1nm',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/offchainlabs',
  github: null,
  telegram: 'https://t.me/s/arbitrum',
  twitter: 'https://twitter.com/arbitrum',
  url: 'https://arbitrum.io/',
} satisfies AdapterProject
