import { AdapterProject } from '../types'

export default {
  name: 'Royal',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coingeckoId: null,
  id: 't62qym',
  description:
    'Royal is a marketplace built on top of the Polygon blockchain that enables anyone to invest in music and earn royalties alongside artists.',
  discord: 'https://discord.com/invite/royalofficial',
  investors: [
    'opiq98',
    '26x5nn',
    'fyqab6',
    '73opsz',
    'l0ve70',
    '7ny99e',
    'dc26g1',
    'm4su31',
    'qzqxez',
    '9btyj8',
    'qd41qe',
    'cywns1',
    'jspppz',
    '8c25ay',
    'eqqdvr',
    'i5asuo',
    'tfi9fe',
    '7px1kd',
    'x0j6y0',
    '8m2xub',
    '3mv99i',
    'ix94yu',
    '0y7rv5',
    'dn6pok',
  ],
  linkedin: 'https://www.linkedin.com/company/joinroyal/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://support.royal.io/hc/en-us',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/join_royal',
  url: 'https://royal.io/',
} satisfies AdapterProject
