import { AdapterProject } from '../types'

export default {
  name: 'Upshot',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: '2ne1u8',
  description:
    'Upshot is a decentralized AI platform enabling efficient financial markets for anything.',
  discord: '644591703507861515',
  investors: [
    'tupwbv',
    'tdmlep',
    'te4xtz',
    'q4ztc2',
    'szfiug',
    '21e2s8',
    '67mqz0',
    'yx4w71',
    'f5o3jl',
    'ulvyo3',
    'ivtzio',
    'rz9az7',
    'tqh3bl',
    '6iy81o',
    'wcgf78',
    'ooq1d1',
    '3bchmx',
    'jx87gk',
    'fx71c5',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://upshot.xyz/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.businesswire.com/news/home/20220322005518/en/Upshot-Raises-22M-Series-A2-Led-by-Polychain-to-Accelerate-Development-of-Real-Time-NFT-Appraisals',
    },
    {
      roundType: 'Seed',
      url: 'https://www.businesswire.com/news/home/20210506005124/en/Upshot-Raises-7.5-Million-in-Series-A-Led-by-Framework-Ventures-CoinFund-and-Blockchain-Capital',
    },
  ],
} satisfies AdapterProject
