import { AdapterProject } from '../types'

export default {
  name: 'Manta',
  ninja: null,
  subcategories: null,
  chain: 'POLKADOT',
  category: 'NOT_DEPIN',
  token: 'MANTA',
  coinGeckoID: null,
  id: 'm3djiu',
  description:
    'Manta utilises zero-knowledge proofs (ZKPs) to guarantee the secure and private minting of NFTs and SBTs while maintaining the confidentiality of crypto assets.',
  discord: '795390654628102165',
  investors: [
    '7bn5bf',
    'hcx26d',
    'zloyr1',
    'go7fr1',
    'xmw0ev',
    'mrgeec',
    'o1unbe',
    'q4ztc2',
    'szfiug',
    'qp5s3g',
    'r2lof0',
    '0y8voh',
    'rwthif',
    '5dsvsj',
    'vkntey',
    '9xb78i',
    '9p60sa',
    'po8xe3',
    'n73vnt',
    '2g0699',
    'j36zoh',
    '6f2cxt',
    '6cd1m3',
    'tqh3bl',
    'ciz6c6',
    'drbv40',
    'h9g1s5',
    '7rf9rs',
    'm05wan',
    'pu3yyr',
    '5o347p',
    'wu15kr',
    'pgoyl5',
    'lb0lmf',
    'pvr738',
    'urug6u',
  ],
  linkedin: 'https://www.linkedin.com/company/mantanetwork',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://mantanetwork.medium.com/',
  github: 'https://github.com/manta-network',
  telegram: 'https://www.t.me/mantanetworkofficial',
  twitter: 'https://twitter.com/mantanetwork',
  url: 'https://manta.network/',
  verified: false,
  fundraisesUrls: [
    'https://cointelegraph.com/news/manta-aims-to-bring-a-private-decentralized-exchange-to-polkadot-with-1-1m-raise',
    'https://cointelegraph.com/news/polkadot-based-privacy-project-manta-network-raises-5-5m',
    'https://cointelegraph.com/news/manta-network-developer-raises-25m-in-series-a-launches-layer-2-for-zk-apps',
  ],
} satisfies AdapterProject
