import { AdapterProject } from '../types'

export default {
  name: 'Fluxbot',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'ld3i07',
  description: 'Fluxbot Trading is a Solana-based telegram bot.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://fluxbot.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
