import { AdapterProject } from '../types'

export default {
  name: 'Sunrise Layer',
  ninja: 'meta-light',
  subcategories: 'Data',
  chain: null,
  category: 'COMPUTE',
  token: 'RISE',
  coinGeckoID: null,
  id: 'j7kp4i',
  cmcId: null,
  description: null,
  discord: 'sunrise',
  investors: [],
  linkedin: '',
  duneQueries: null,
  foundingYear: '2022',
  blog: 'http://sunriselayer.medium.com',
  github: 'https://github.com/sunriselayer',
  telegram: null,
  twitter: 'https://x.com/SunriseLayer',
  url: 'http://sunriselayer.io',
  verified: false,
  fundraises: [],
} satisfies AdapterProject