import { AdapterProject } from '../types'

export default {
  name: 'Store',
  ninja: null,
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'nb0mpn',
  description:
    'STORE is a new layer zero staking protocol at the intersection of cloud computing and WEB3.',
  discord: null,
  investors: [
    'o5kpgb',
    '9xan1p',
    'p0l4xh',
    'cpymss',
    '6hezki',
    'udnk74',
    'zge5vh',
    'rnxt65',
    'el8e09',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://storecloud.org/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
