import { AdapterProject } from '../types'

export default {
  name: 'LongFi',
  ninja: null,
  subcategories: 'Mining',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'nbam9o',
  description: 'LongFi Solutions: Decentralized Infrastructure for community connectivity',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/longfisolutions/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/topics/longfi',
  telegram: null,
  twitter: 'https://twitter.com/LongFiSolutions',
  url: 'https://www.longfisolutions.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
