import { AdapterProject } from '../types'

export default {
  name: 'Equito',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Bridges',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '02ugap',
  description: 'Equito Finance is a chain-agnostic open-source bridge protocol.',
  discord: '952703700483330049',
  investors: [],
  linkedin: 'https://it.linkedin.com/company/equito-finance',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/EquitoBridge',
  telegram: null,
  twitter: 'https://twitter.com/EquitoFinance',
  url: 'https://equitofinance.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
