import { AdapterProject } from '../types'

export default {
  name: 'Cortex Labs',
  chain: 'NATIVE',
  category: 'AI',
  token: 'CTXC',
  coingeckoId: 'cortex',
  id: 'pd82aa',
  description:
    'Cortex Labs: Decentralized blockchain for AI models in smart contracts for enhanced DApps.',
  investors: [
    'csfyvy',
    '7ntjyp',
    'v8hv28',
    '2f68vj',
    'gun7y3',
    'te4xtz',
    'is950u',
    'addxil',
    '0wramd',
    'l0ve70',
    '2ckrz9',
    '6jj8ov',
    'ymnjdr',
    '772xwk',
    'c94bgn',
    'lfbmt3',
    'n5z0zx',
    'u13una',
    'fc4tet',
    't7xkdd',
    'i1x9du',
    'pm15uy',
    'micofj',
    '9205ui',
    'ecuh5g',
    'kzsrt6',
    'hiwb24',
    'j36zoh',
    'ffz00y',
    'xemx4j',
  ],
  duneQueries: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/CortexOfficialEN',
  twitter: 'https://twitter.com/CTXCBlockchain',
} satisfies AdapterProject
