import { AdapterProject } from '../types'

export default {
  name: 'Firstbatch',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'xjzev4',
  description: 'FirstBatch is building collaboration and user-centric tools for AGI.',
  discord: '1088019643618308200',
  investors: ['hhudw8', 'fzd0ha', 'uktppp', '68e0bl', '10z6rb', 'e29e8f', 'oltsrb'],
  linkedin: 'https://www.linkedin.com/company/firstbatchxyz',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@FirstBatchLabs',
  github: 'https://github.com/firstbatchxyz',
  telegram: null,
  twitter: 'https://twitter.com/firstbatchxyz_',
  url: 'https://www.firstbatch.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
