import { AdapterProject } from '../types'

export default {
  name: 'rhino.fi',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'd3ignz',
  description: 'rhino.fi is the ultimate Layer 2 bridge for effortless multi-chain token movement.',
  discord: '745570257808130058',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://rhino.fi/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
