import { AdapterProject } from '../types'

export default {
  name: 'rhino.fi',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'd3ignz',
  description: 'rhino.fi is the ultimate Layer 2 bridge for effortless multi-chain token movement.',
  discord: '745570257808130058',
  investors: [
    '9ns4s9',
    '3rh50q',
    'qp5s3g',
    '67mqz0',
    'mywjsu',
    '5dsvsj',
    'f91vtn',
    'qcqrf7',
    'rwhpsx',
    'po8xe3',
    '87j7du',
    'smqwtv',
    '6f2cxt',
    'pgoyl5',
    'vrsed8',
    'urug6u',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://rhino.fi/',
  verified: false,
} satisfies AdapterProject
