import { AdapterProject } from '../types'

export default {
  name: 'rhino.fi',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'd3ignz',
  description: 'rhino.fi is the ultimate Layer 2 bridge for effortless multi-chain token movement.',
  investors: [
    '9ns4s9',
    '3rh50q',
    'qp5s3g',
    '67mqz0',
    'mywjsu',
    '5dsvsj',
    'f91vtn',
    'qcqrf7',
    'rwhpsx',
    'po8xe3',
    '87j7du',
    'smqwtv',
    '6f2cxt',
    'pgoyl5',
    'vrsed8',
    'urug6u',
  ],
  duneQueries: null,
} satisfies AdapterProject
