import { AdapterProject } from '../types'

export default {
  name: 'RUNodE',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '8c3y8v',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/RUNodE_ai',
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
