import { AdapterProject } from '../types'

export default {
  name: 'Hapi',
  ninja: null,
  subcategories: 'DeFi',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'HAPI',
  coinGeckoID: 'hapi-one',
  id: 'um75jm',
  description: 'Hapi Protocol: Cross-chain protocol for DeFi security.',
  discord: '854680817661640754',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/hapi-protocol/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/i-am-hapi',
  github: 'https://github.com/HAPIprotocol',
  telegram: 'https://t.me/hapiHF',
  twitter: 'https://twitter.com/i_am_hapi_one',
  url: 'https://hapi.one/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
