import { AdapterProject } from '../types'

export default {
  name: 'Yokai',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'jbyfc1',
  description: 'Yokai Developer: Security network with crowdsourced audit and bug bounty platform.',
  discord: '874678777748279316',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/yokainetwork',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://yokainetwork.medium.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/yokai_network',
  url: 'http://www.yokai.network/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
