import { AdapterProject } from '../types'

export default {
  name: 'Pi',
  ninja: null,
  subcategories: 'Mining, Mobile',
  chain: 'ALGORAND',
  category: 'SENSORS',
  token: 'PI',
  coinGeckoID: 'pi-network-iou',
  id: 'xpggzk',
  description: 'Pi is a decentralized environmental data collection network.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/pi-net/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://pinetwork-official.medium.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/PiCoreTeam',
  url: 'https://minepi.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
