import { AdapterProject } from '../types'

export default {
  name: 'Datagen',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '6rasyf',
  description:
    'Datagen provides an all-purpose generator of synthetic images of human faces and bodies.',
  investors: [
    'nrxmnx',
    'mufjv7',
    '9v9mrd',
    '4qiys7',
    'tpfed4',
    '43gceu',
    'nzep63',
    'qvg9oe',
    '3aevc3',
    'ot2q4f',
    'rkun5v',
    'nh0uiu',
    '1im0oz',
    't6nsde',
    'uigra7',
    'xjrpvv',
    'egfy5d',
    '310vx3',
    '5p9gpb',
    '2cor6o',
    'o7axgq',
    'pfvnry',
    '9ltipb',
  ],
  duneQueries: null,
  blog: 'https://datagen.tech/blog/',
  github: 'https://github.com/DatagenTech',
  telegram: null,
  twitter: 'https://twitter.com/datagentech',
} satisfies AdapterProject
