import { AdapterProject } from '../types'

export default {
  name: 'impactMarket',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'PACT',
  coingeckoId: 'impactmarket',
  id: 'p19y87',
  description:
    'ImpactMarket enables communities to implement financial inclusive mechanisms like Unconditional Basic Income (UBI).',
  discord: '809102018827255868',
  investors: [
    'hpndgr',
    'q8to28',
    '7065hj',
    'ub70vu',
    'i98114',
    'o0rx1i',
    'ajzzhi',
    'eqzxf8',
    'tk2v6b',
    's7rn7t',
  ],
  linkedin: 'https://www.linkedin.com/company/impactmarket',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/impactmarket',
  github: 'https://github.com/impactMarket',
  telegram: 'https://t.me/impactMarketOfficial',
  twitter: 'https://twitter.com/impactmarket',
  url: 'https://www.impactmarket.com/',
  verified: false,
} satisfies AdapterProject
