import { AdapterProject } from '../types'

export default {
  name: 'Thought',
  ninja: null,
  subcategories: 'Agents',
  chain: 'NATIVE',
  category: 'AI',
  token: 'THT',
  coinGeckoID: 'thought',
  id: '0bu4wx',
  description: 'ThoughtAI is an adaptive AI using Self-Aware Intelligent Software Agents.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.thought.live/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
