import { AdapterProject } from '../types'

export default {
  name: 'HOPR',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'WIRELESS',
  token: 'HOPR',
  coinGeckoID: 'hopr',
  id: 'rdr178',
  description: 'HOPR connects unused internet bandwidth for monetization.',
  discord: '679586195529007116',
  investors: [
    'yxetck',
    'zloyr1',
    'xmw0ev',
    '8nclhv',
    'wldl30',
    '8a2od5',
    'lrxdc8',
    'opc76c',
    '23f4q2',
    '9va778',
    '5aftnd',
    'curksv',
    '1rq4ip',
    'z1ww7b',
    'pyukl2',
    'eud02c',
    '1uyl9r',
    'xvgf6w',
    'nwl5v7',
    'xemx4j',
  ],
  linkedin: 'https://www.linkedin.com/company/hoprnet',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/hoprnet',
  github: 'https://github.com/hoprnet',
  telegram: 'https://t.me/hoprnet',
  twitter: 'https://twitter.com/hoprnet',
  url: 'https://hoprnet.org/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://twitter.com/GnosisDAO/status/1783874344013463583',
    },
    {
      roundType: 'Seed',
      url: 'https://www.coindesk.com/business/2020/07/09/binance-labs-leads-1m-seed-round-in-crypto-tor-alternative-hopr/',
    },
  ],
} satisfies AdapterProject
