import { AdapterProject } from '../types'

export default {
  name: 'HOPR',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'WIRELESS',
  token: 'HOPR',
  coingeckoId: 'hopr',
  id: 'rdr178',
  description: 'HOPR connects unused internet bandwidth for monetization.',
  discord: null,
  investors: [
    'yxetck',
    'zloyr1',
    'xmw0ev',
    'mrgeec',
    '8nclhv',
    'wldl30',
    '8a2od5',
    'lrxdc8',
    'opc76c',
    '23f4q2',
    '9va778',
    'curksv',
    '1rq4ip',
    'z1ww7b',
    'pyukl2',
    'eud02c',
    '1uyl9r',
    'xvgf6w',
    'nwl5v7',
    'xemx4j',
  ],
  linkedin: 'https://www.linkedin.com/company/hoprnet',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/hoprnet',
  github: 'https://github.com/hoprnet',
  telegram: 'https://t.me/hoprnet',
  twitter: 'https://twitter.com/hoprnet',
  url: 'https://hoprnet.org/',
  verified: false,
} satisfies AdapterProject
