import { AdapterProject } from '../types'

export default {
  name: 'Loke',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: 'LOKE',
  coinGeckoID: null,
  id: '6b4f0x',
  description: 'Loke is a gamified social layer for action sports.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/getloke',
  url: 'https://getloke.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
