import { AdapterProject } from '../types'

export default {
  name: 'Vaxchain',
  ninja: null,
  subcategories: 'Health & Fitness',
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: 'adc9fo',
  description: "Devpost inspires the world's developers to build great software.",
  discord: '861966823054639134',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/devpost/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://info.devpost.com/blog',
  github: 'https://github.com/kie478/vaxchain',
  telegram: null,
  twitter: 'https://twitter.com/devpost',
  url: 'https://devpost.com/software/vaxchain',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
