import { AdapterProject } from '../types'

export default {
  name: 'Obi',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'HUMAN_CAPITAL',
  token: null,
  coinGeckoID: null,
  id: '0ixv4e',
  description: 'Obi - The cheapest ride, every time.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.rideobi.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
