import { AdapterProject } from '../types'

export default {
  name: 'ioFog',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'g9rym4',
  description: 'Eclipse ioFog: Open-source edge computing platform for ECN.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://iofog.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
