import { AdapterProject } from '../types'

export default {
  name: 'GooseAI',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'in3vdx',
  description: 'GooseAI is a fully managed NLP-as-a-Service, delivered via API.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/gooseai_NLP',
  url: 'https://goose.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
