import { AdapterProject } from '../types'

export default {
  name: 'Blockvolt',
  ninja: 'meta-light',
  subcategories: null,
  chain: null,
  category: null,
  token: null,
  coinGeckoID: null,
  id: 'yznlur',
  cmcId: null,
  description: 'Get Rewarded for Helping the Planet',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/blockvolt-limited/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://blockvolt.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject