import { AdapterProject } from '../types'

export default {
  name: 'Wysdom',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'trnymt',
  description: 'Wysdom is a collaboration platform for web3 development and publishing.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/wysdomxyz/about/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/WysdomXyz',
  url: 'https://wysdom.xyz/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
