import { AdapterProject } from '../types'

export default {
  name: 'RRM Global',
  ninja: '0xF7a705A81b28891c4CF87Faa3DdD9bA9928E4894',
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'syqs10',
  description: 'RRM Global is a decentralized GPU computing resource aggregation network.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/rrm_global',
  url: 'https://www.rrmglobal.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
