import { AdapterProject } from '../types'

export default {
  name: 'Notus',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'L1/L2',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'b4jy5r',
  description: 'Notus Labs is a decentralized blockchain platform for dapp development.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/notus-labs',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@notus-labs',
  github: 'https://github.com/notus-labs',
  telegram: null,
  twitter: 'https://twitter.com/NotusLabs',
  url: 'https://notuslabs.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
