import { AdapterProject } from '../types'

export default {
  name: 'dClimate',
  ninja: null,
  subcategories: 'Environmental, Data',
  chain: null,
  category: 'ENERGY',
  token: null,
  coingeckoId: null,
  id: 'a5w7th',
  description:
    'dClimate: Decentralized climate data network that standardizes and distributes climate data, forecasts, and models.',
  discord: 'https://discord.com/invite/bYWVdNDMpe',
  investors: [
    'oi4yuk',
    '2enw83',
    '4zunln',
    'szfiug',
    '1ojs3d',
    'lr20nt',
    'pkboiz',
    '2g0699',
    '9iw9vx',
    '9rflkn',
    '63huxu',
    'unykak',
    'gkv33p',
    'x52ni8',
    'sbxp1t',
    'eseesx',
  ],
  linkedin: 'https://linkedin.com/company/dclimatenet',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/dClimate',
  telegram: 'http://t.me/dclimatechat-',
  twitter: 'https://twitter.com/dClimateDAO',
  url: 'https://www.dclimate.net/',
  verified: false,
} satisfies AdapterProject
