import { AdapterProject } from '../types'

export default {
  name: 'Cudos',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'CUDOS',
  coinGeckoID: 'cudos',
  id: 'jitkjs',
  description: 'Cudos is a decentralized cloud computing network.',
  discord: '593796681103966208',
  investors: [
    '8nclhv',
    'gtjd6o',
    'zqdy3j',
    'usw204',
    'rvvd5u',
    '6hezki',
    '18l8yx',
    'yi5hs8',
    'xx442f',
    '0y66ov',
    'rlo5x9',
    'n73vnt',
    'dd123i',
    'vjpj24',
    'sjvt2e',
    'knx4ht',
  ],
  linkedin: 'https://uk.linkedin.com/company/cudos1',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/cudos-',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/CUDOS_?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://www.cudos.org/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.cudos.org/blog/cudos-raises-10million-in-funding/',
    },
  ],
} satisfies AdapterProject
