import { AdapterProject } from '../types'

export default {
  name: 'Cudos',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'CUDOS',
  coingeckoId: 'cudos',
  id: 'jitkjs',
  description: 'Cudos is a decentralized cloud computing network.',
  investors: [
    'ycxcre',
    'z7irdg',
    '8nclhv',
    'te4xtz',
    'gtjd6o',
    'buo8ql',
    'zqdy3j',
    'p6imce',
    'd6wjf8',
    'qngu2a',
    'n0g582',
    'yi5hs8',
    'xx442f',
    '0y66ov',
    'rlo5x9',
    'okjrd0',
    'n73vnt',
    'dd123i',
    'vjpj24',
    'nxirg2',
    'zcdny8',
  ],
  duneQueries: null,
} satisfies AdapterProject
