import { AdapterProject } from '../types'

export default {
  name: 'VC Spectra',
  ninja: null,
  subcategories: 'DeFi',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'qbgfxz',
  description: 'Decentralized asset management and trading platform with secure investments.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/spectravcfund',
  url: 'https://vcspectra.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
