import { AdapterProject } from '../types'

export default {
  name: 'MooFi',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'wa70xv',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/moofiapp',
  url: 'https://linktr.ee/moofiapp',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
