import { AdapterProject } from '../types'

export default {
  name: 'Roso',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ROSO',
  coingeckoId: 'roso-elite-gamblers-mansion',
  id: '36f3to',
  description:
    'Roso is a diverse online casino and gaming platform, offering a wide range of gambling experiences.',
  investors: [
    'bspyld',
    'hol96b',
    '92ar5l',
    '896jil',
    'suthoi',
    'zaf9xh',
    '0z5mdu',
    '1l9l10',
    'fzp696',
    'uwuv2v',
    'lx8o88',
    'mar9ip',
    '2zituv',
    'y5m26s',
    'tg9num',
    'qcg7xy',
    'ejxwgz',
    'u3ke67',
    'q9qqsj',
    'w45czo',
    'po8xe3',
    '08avju',
    'y5gvku',
    'evpa5e',
    'id69f9',
    'o92n85',
    '820cst',
    'ti312b',
    'shz3zr',
    'btlofg',
    '6iy81o',
    'emg882',
    'lhs5s8',
    'ooq1d1',
    'w0qehc',
    '3bchmx',
    'lqi9dk',
    'e2dh7y',
    '35dl2w',
    'due5zk',
    't1v2ug',
    '03zdwj',
    'dbr5ig',
    'xt0vj3',
  ],
  duneQueries: null,
} satisfies AdapterProject
