import { AdapterProject } from '../types'

export default {
  name: 'Synesis One',
  ninja: null,
  subcategories: null,
  chain: 'SOLANA',
  category: 'AI',
  token: 'SNS',
  coinGeckoID: 'synesis-one',
  id: 'mhf5jn',
  description:
    'Synesis One is a data crowdsourcing platform where anyone can earn $SNS by completing micro-tasks that train AI.',
  discord: '914802829904982047',
  investors: [
    'k93k29',
    '7jssah',
    'rbndwa',
    'ujq536',
    'xmw0ev',
    'tp01af',
    'ri09e0',
    '04mlyu',
    'm6mz4i',
    'wc20rz',
    '6gkso9',
    'aeoxcb',
    'kottog',
    'mdznvx',
    'vmlzwp',
    'micofj',
    'wqz1py',
    'qqc9zd',
    'd8iuux',
    '243kcn',
    'ka4f30',
    'oxjxo0',
    '07pxi6',
    'tnqlc5',
    'lhs5s8',
    't3b3p0',
    'og1ppi',
    '03zdwj',
    'nv73pg',
  ],
  linkedin: 'http://www.linkedin.com/company/synesisone',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@synesisone',
  github: null,
  telegram: 'https://t.me/Synesis_One',
  twitter: 'https://twitter.com/synesis_one',
  url: 'https://www.synesis.one/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://cointelegraph.com/press-releases/synesis-one-raises-95m-to-gamify-ai-data-collection',
    },
  ],
  isApp: true,
} satisfies AdapterProject
