import { AdapterProject } from '../types'

export default {
  name: 'Apron',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'APN',
  coingeckoId: 'apron',
  id: 'bg8k10',
  description:
    'Apron is a decentralized infrastructure service network for DApp developers, users, and operators on blockchain.',
  discord: 'https://discord.com/invite/Bu6HzJP2YY',
  investors: [
    'xmw0ev',
    'h3elac',
    'q4ztc2',
    'r2lof0',
    'b1hrk6',
    'j4k67v',
    '07pxi6',
    '67igtu',
    'tnkrzw',
    'ciz6c6',
    'unykak',
    'pyukl2',
    '51acus',
    '935mux',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://apron-network.medium.com/',
  github: 'https://github.com/Apron-Network/',
  telegram: null,
  twitter: 'https://twitter.com/apronofficial1',
  url: 'https://apron.network/',
} satisfies AdapterProject
