import { AdapterProject } from '../types'

export default {
  name: 'Alpha',
  ninja: '0x9Ab59cB71d4657f4c2DB7E0963212A81b6445b4c',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'w39fsd',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/0xalphanet',
  url: 'https://alphaos.net/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
