import { AdapterProject } from '../types'

export default {
  name: 'Syntropy',
  ninja: null,
  subcategories: 'Bridges',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'NOIA',
  coingeckoId: 'syntropy',
  id: 'm9yv19',
  description:
    'Syntropy transforms the way blockchain data is accessed through our innovative Data Layer protocol.',
  discord: null,
  investors: [
    'buime9',
    'kmkpmm',
    'nx7p3n',
    'k8v3go',
    '0jqary',
    'xfwkcl',
    '7e0mh4',
    '6uctn4',
    'xgzede',
    'mc0vmp',
    '4rmqk4',
    '5rmf8c',
  ],
  linkedin: 'https://www.linkedin.com/company/syntropynet/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/SyntropyNet',
  telegram: 'https://t.me/SyntropyNet',
  twitter: 'https://twitter.com/Syntropynet',
  url: 'https://www.syntropynet.com/',
  verified: false,
} satisfies AdapterProject
