import { AdapterProject } from '../types'

export default {
  name: 'Zeetta',
  ninja: null,
  subcategories: 'Software',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: '6gz71b',
  description:
    'Zeetta is a network virtualization company specializing in SDN solutions for enterprise and carrier networks.',
  discord: null,
  investors: [
    'e59pqh',
    'v28p9a',
    '8em4a3',
    'phnmc1',
    '0pcodk',
    'gkjom1',
    'ot6qbe',
    '1dngmz',
    'kxmrz5',
    'gmweh7',
  ],
  linkedin: 'https://uk.linkedin.com/company/zeetta',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/zeeta',
  telegram: 'https://t.me/s/ZeetaaProjects?before=209',
  twitter: 'https://twitter.com/zeettas?lang=en',
  url: 'https://zeetta.com/',
  verified: false,
} satisfies AdapterProject
