import { AdapterProject } from '../types'

export default {
  name: 'Kwil',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: '9xue69',
  description: 'Kwil is a permissionless SQL database for the decentralized internet.',
  investors: [
    '5yy6cw',
    '07pxi6',
    '5dsvsj',
    'pu3yyr',
    'hbpmm3',
    'h58ujg',
    'hhudw8',
    'xnftxc',
    'dsl20s',
    'uktppp',
    '6ln74n',
    'pqz4bg',
    'thxgaw',
    '9zlute',
    '4j4oj3',
    '0jqovb',
    'a1wztr',
    'maid89',
    '4nohge',
    'gn3guk',
  ],
  duneQueries: null,
  cmcId: null,
} satisfies AdapterProject
