import { AdapterProject } from '../types'

export default {
  name: 'Kwil',
  ninja: null,
  subcategories: 'Data',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '9xue69',
  description: 'Kwil is a permissionless SQL database for the decentralized internet.',
  discord: '819855804554543114',
  investors: [
    '4j4oj3',
    '0jqovb',
    'a1wztr',
    'hhudw8',
    'hbpmm3',
    'e3ul8g',
    'maid89',
    'apd14v',
    'h58ujg',
    'uktppp',
    '6ln74n',
    '5dsvsj',
    '4nohge',
    'thxgaw',
    '795ufc',
    '07pxi6',
    'rgk0ot',
    'pu3yyr',
    'gn3guk',
  ],
  linkedin: 'http://www.linkedin.com/company/kwilteam',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/kwildb',
  github: 'https://github.com/kwilteam',
  telegram: null,
  twitter: 'https://twitter.com/KwilTeam',
  url: 'https://www.kwil.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.accesswire.com/718966/Decentralized-Database-Platform-Kwil-Raises-89M-Seed-Round',
    },
  ],
} satisfies AdapterProject
