import { AdapterProject } from '../types'

export default {
  name: 'RentSpace',
  ninja: 'wholovesburrito.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'zydynr',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/Rentspaceco',
  url: 'https://rentb.space/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
