import { AdapterProject } from '../types'

export default {
  name: 'KYVE',
  ninja: null,
  subcategories: 'Storage',
  chain: 'COSMOS',
  category: 'COMPUTE',
  token: 'KYVE',
  coinGeckoID: 'kyve-network',
  id: 'u6mo76',
  description: 'KYVE connects nodes to Arweave storage, ensuring trustless uploads.',
  discord: '817113909957361664',
  investors: [
    '4j4oj3',
    '5g3hyv',
    'fahk60',
    'hhudw8',
    'abvcou',
    'ue6j4s',
    '5b7spr',
    '7oqynx',
    '9jairy',
    '3t07jb',
    'q4ztc2',
    '73opsz',
    'jmdud3',
    'maid89',
    '67afgf',
    'm6mz4i',
    'sknhsa',
    '2igv5u',
    'ag8xow',
    'yjw8np',
    'ajzzhi',
    'zf8iq9',
    'yoijyl',
    't7xkdd',
    'vkntey',
    'c9dgeq',
    'i3u36b',
    'i1x9du',
    '0e5as0',
    'cwh18x',
    'dbnrgb',
    'kjm7ph',
    'zwue16',
    'niilon',
    'ulvyo3',
    'd0dwes',
    'b6vnn8',
    'mwijuq',
    'n9t6zl',
    'nym997',
    'v3nhx4',
    '6br51s',
    'ksae6d',
    'xph9q9',
    'tlb60n',
    '91d2gg',
    'bym0hu',
    'gasfop',
    'eo7aux',
    'urug6u',
  ],
  linkedin: 'http://www.linkedin.com/company/kyve',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://kyve.medium.com/',
  github: 'https://github.com/KYVENetwork',
  telegram: 'https://t.me/kyvenet',
  twitter: 'https://twitter.com/KYVENetwork',
  url: 'https://www.kyve.network/',
  verified: false,
  fundraisesUrls: [
    'https://www.coindesk.com/tech/2021/10/26/data-pipeline-protocol-kyve-raises-28m-from-industry-insiders/',
    'https://www.theblock.co/post/154836/kyve-network-hits-100-million-valuation-as-it-raises-9-million',
  ],
} satisfies AdapterProject
