import { AdapterProject } from '../types'

export default {
  name: 'PerpsTech',
  ninja: 'ZZ',
  subcategories: 'DeFi',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'x0ftnx',
  description: 'PerpsTech is a  decentralized Influencer Investment Platform.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/perpstech',
  twitter: 'https://twitter.com/perpstech',
  url: 'https://www.perps.tech/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
