import { AdapterProject } from '../types'

export default {
  name: 'Saga DAO',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'q3ybfy',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/sagamobiledao',
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
