import { AdapterProject } from '../types'

export default {
  name: 'Saga DAO',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'q3ybfy',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/sagamobiledao',
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
