import { AdapterProject } from '../types'

export default {
  name: 'Carv',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '4y6snk',
  description: 'Gaming credentials infrastructure',
  discord: '915445727600205844',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://carv.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
