import { AdapterProject } from '../types'

export default {
  name: 'Archblock',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'rq4805',
  description:
    "Archblock is a decentralized alternatives marketplace built on TrueFi's open, transparent and immutable financial infrastructure.",
  discord: null,
  investors: [
    '2q8xba',
    '7jssah',
    'jn4ice',
    '4bc5rd',
    'oq9fz1',
    'jv1erw',
    '26x5nn',
    'p0l4xh',
    '6s7v1l',
    '3gin8b',
    '1vifzd',
    'ucjx6z',
    '772xwk',
    '1k3sod',
    '9td18r',
    '9btyj8',
    'ckjv3m',
    'a3mqq8',
    'vfc1ky',
    'ccfk2o',
    'psf709',
    '4ssdn4',
    '551q4x',
    'lszufu',
    '8gv3kn',
    'unykak',
    'pdrbjw',
    'rnj4da',
    '4guotr',
    'ex2fez',
    'xt0vj3',
    'ffz00y',
  ],
  linkedin: 'https://www.linkedin.com/company/archblock/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.archblock.com/blog',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/archblock_',
  url: 'https://www.archblock.com/',
  verified: false,
} satisfies AdapterProject
