import { AdapterProject } from '../types'

export default {
  name: 'Impermax',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'IBEX',
  coinGeckoID: 'impermax-2',
  id: 'd869lq',
  description: 'Impermax: Cross-chain lending protocol offers yield for lenders and borrowers.',
  discord: '782387768411815947',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/impermax-finance',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://impermax.medium.com/',
  github: 'https://github.com/Impermax-Finance',
  telegram: null,
  twitter: 'https://twitter.com/ImpermaxFinance',
  url: 'http://www.impermax.finance/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
