import { AdapterProject } from '../types'

export default {
  name: 'DLTEO',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Environmental',
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: 'byzgll',
  description: 'DLTEO is a platform to monetize and process Earth Observation Data & AI models.',
  discord: null,
  investors: ['296d7m'],
  linkedin: 'https://at.linkedin.com/company/dlteo-gmbh',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/dlt_eo',
  url: 'https://www.dlteo.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
