import { AdapterProject } from '../types'

export default {
  name: 'AuditX',
  ninja: '0x25052A4B28a35FfdBf2FaBA7DCCEB350e91b908F',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: 'AUDITX',
  coinGeckoID: null,
  id: 'o7wclz',
  description: 'AuditX is a DePIN-powered and AI-driven audit layer for L2 Rollups.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://auditx.io/',
  url: 'https://auditx.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
