import { AdapterProject } from '../types'

export default {
  name: 'Preprints',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'xvpxoa',
  description: '',
  discord: '871601937148166154',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/haailabs',
  telegram: 'https://t.me/preprintsio',
  twitter: 'https://twitter.com/preprints_io',
  url: 'https://preprints.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
