import { AdapterProject } from '../types'

export default {
  name: 'Vega',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'VEGA',
  coingeckoId: 'vega-protocol',
  id: 'ie91s7',
  description:
    'Vega Protocol is a blockchain-backed network enabling automated trading and execution of financial products.',
  discord: 'https://discord.com/invite/3hQyGgZ',
  investors: [
    '6ueww6',
    'pdp1mt',
    '7ygqh2',
    'csfyvy',
    'eq77bg',
    'vbbb1g',
    'la4mmt',
    'q4ztc2',
    'suthoi',
    '73opsz',
    'f40lhg',
    'li943w',
    'jitv3q',
    'knw63n',
    '2p413m',
    'qxuz9y',
    '9va778',
    'qogp0a',
    '5dsvsj',
    'wir0cg',
    'v81ftp',
    'y5m26s',
    'ja2261',
    'ujw2s3',
    '6iqdv9',
    'xjtllv',
    'j4k67v',
    'k9u90q',
    '07pxi6',
    'ozeg73',
    '6f2cxt',
    '6r6q3d',
    'we3g51',
    'pu3yyr',
    'oltsrb',
    '3bchmx',
    'zngvoi',
    'urug6u',
  ],
  linkedin: 'https://linkedin.com/company/vega-protocol',
  duneQueries: null,
  blog: 'https://medium.com/@Vega_Protocol',
  github: 'https://github.com/vegaprotocol',
  telegram: 'https://t.me/vegacommunity/',
  twitter: 'https://twitter.com/vegaprotocol',
  url: 'https://vega.xyz/',
} satisfies AdapterProject
