import { AdapterProject } from '../types'

export default {
  name: 'Nautilus',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'tm4rcw',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/nautilus_chain',
  url: 'https://nautchain.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
