import { AdapterProject } from '../types'

export default {
  name: 'Nautilus',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'tm4rcw',
  description: '',
  discord: '1076321699924017183',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://nautchain.medium.com/',
  github: null,
  telegram: 'https://t.me/nautchain',
  twitter: 'https://x.com/nautilus_chain',
  url: 'https://nautchain.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
