import { AdapterProject } from '../types'

export default {
  name: 'Orchid',
  chain: 'ETHEREUM',
  category: 'WIRELESS',
  token: 'OXT',
  coingeckoId: 'orchid-protocol',
  id: 'vg1qec',
  description:
    'Orchid is a decentralized onion routing network incentivized through multi-hop VPN clients.',
  investors: [
    '2q8xba',
    'vty6hq',
    '86udzh',
    'b2ru54',
    'hbpmm3',
    'uit0wg',
    'n5a3e9',
    'e34j95',
    '9td18r',
    '0ls3us',
    'pbn252',
    'e3qnb5',
    'vn2xbi',
    '1n8dqw',
    'fajtph',
    'tu6afb',
    'bku3ew',
    'h25e6r',
    'vf0qg4',
    'lhs5s8',
    '01e8f1',
    'gu9yms',
    '0wvjml',
    'ea62bc',
    'dcxpa9',
    '42bud8',
    'iamhka',
  ],
  duneQueries: null,
} satisfies AdapterProject
