import { AdapterProject } from '../types'

export default {
  name: 'Orchid',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'OXT',
  coingeckoId: 'orchid-protocol',
  id: 'vg1qec',
  cmcId: 5026,
  description:
    'Orchid is a decentralized onion routing network incentivized through multi-hop VPN clients.',
  investors: [
    'bku3ew',
    'hbpmm3',
    '9td18r',
    'lhs5s8',
    'pbn252',
    'e3qnb5',
    'vn2xbi',
    'vf0qg4',
    'gu9yms',
    'dcxpa9',
    'iamhka',
    '2q8xba',
    'vty6hq',
    '86udzh',
    'b2ru54',
    'uit0wg',
    'n5a3e9',
    'e34j95',
    '0ls3us',
    '1n8dqw',
    'fajtph',
    'tu6afb',
    'h25e6r',
    '01e8f1',
    '0wvjml',
    'ea62bc',
    '42bud8',
  ],
} satisfies AdapterProject
