import { AdapterProject } from '../types'

export default {
  name: 'AIRO',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Environmental',
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: '8q0l7y',
  description: 'AIRO is a decentralized air quality monitoring network.',
  discord: '1089157531001167958',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/airo-missions',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@airo.network',
  github: 'https://github.com/airo',
  telegram: null,
  twitter: 'https://twitter.com/AIRO_MU',
  url: 'https://www.airo.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
