import { AdapterProject } from '../types'

export default {
  name: 'Echo1',
  ninja: 'EV3 Sal',
  subcategories: 'CDN',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'h69708',
  description: 'Echo is a Decentralized Network for Streaming Content Delivery.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
