import { AdapterProject } from '../types'

export default {
  name: 'Echo1',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: 'CDN',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'h69708',
  description: 'Echo is a Decentralized Network for Streaming Content Delivery.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
