import { AdapterProject } from '../types'

export default {
  name: 'Linea',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'ZK',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'xg7vy5',
  description: 'Linea is an EVM-equivalent zk-rollup for scaling Ethereum dapps.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://linea.build/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
