import { AdapterProject } from '../types'

export default {
  name: 'Dojima',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'aomkd4',
  description: 'Dojima is an omnichain EVM layer enabling cross-chain applications.',
  discord: 'https://discord.com/invite/6fQWukdgbM',
  investors: [
    '62da1y',
    'zloyr1',
    'hhudw8',
    'xmw0ev',
    'q4ztc2',
    '7jqyom',
    '6qjs9a',
    'wohqmd',
    'dpvve5',
    '6iqdv9',
    'l1yhc5',
    '65epfb',
    'dniqw5',
    'oltsrb',
    '8dhvoo',
    'jofsd4',
    '24ormv',
  ],
  linkedin: 'https://www.linkedin.com/company/dojimanetwork',
  duneQueries: null,
  blog: null,
  github: 'https://github.com/dojimanetwork',
  telegram: null,
  twitter: 'https://twitter.com/dojimanetwork',
  url: 'https://www.dojima.network/',
} satisfies AdapterProject
