import { AdapterProject } from '../types'

export default {
  name: 'Dojima',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'aomkd4',
  description: 'Dojima is an omnichain EVM layer enabling cross-chain applications.',
  discord: '864498254958821378',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/dojimanetwork',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/dojimanetwork',
  telegram: null,
  twitter: 'https://twitter.com/dojimanetwork',
  url: 'https://www.dojima.network/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
