import { AdapterProject } from '../types'

export default {
  name: 'Chirp',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'zf4ctb',
  description: 'Chirp Wireless is a decentralized wireless network for IoT, mobile, and broadband.',
  discord: null,
  investors: [],
  linkedin: 'http://www.linkedin.com/company/chirpiot',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://chirpiot.medium.com/',
  github: 'https://github.com/topics/chirp?o=desc&s=forks',
  telegram: null,
  twitter: 'https://twitter.com/ChirpDeWi',
  url: 'https://chirpwireless.io/commercial',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
