import { AdapterProject } from '../types'

export default {
  name: 'Chirp',
  ninja: '0x9Ab59cB71d4657f4c2DB7E0963212A81b6445b4c',
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'zf4ctb',
  description: 'Chirp Wireless is a decentralized wireless network for IoT, mobile, and broadband.',
  discord: null,
  investors: [],
  linkedin: 'http://www.linkedin.com/company/chirpiot',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://chirpiot.medium.com/',
  github: 'https://github.com/topics/chirp?o=desc&s=forks',
  telegram: null,
  twitter: 'https://twitter.com/ChirpDeWi',
  url: 'https://chirpwireless.io/commercial',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
