import { AdapterProject } from '../types'

export default {
  name: 'DStor',
  ninja: null,
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'p5n1y8',
  description: 'DStor is a globally-distributed cloud storage network.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/dstor',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/SitePen/dstore/blob/master/docs/Store.md',
  telegram: null,
  twitter: 'https://twitter.com/dstor',
  url: 'https://dstor.cloud/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
