import { AdapterProject } from '../types'

export default {
  name: 'Astria',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'lgm1f3',
  description: 'Astria Developer: Decentralization platform replacing centralized sequencers.',
  investors: [
    'bspyld',
    'fahk60',
    'i04xvv',
    '0mqnsr',
    'bbcbhk',
    '67mqz0',
    'uwuv2v',
    'kjm7ph',
    '08avju',
    'xgzede',
    'gf09a2',
    'eyy236',
    'q48ben',
  ],
  duneQueries: null,
  blog: null,
  github: 'https://github.com/astriaorg',
  telegram: null,
  twitter: 'https://twitter.com/AstriaOrg',
} satisfies AdapterProject
