import { AdapterProject } from '../types'

export default {
  name: 'Astria',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'lgm1f3',
  description: 'Astria Developer: Decentralization platform replacing centralized sequencers.',
  discord: '1163902555080904715',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/astria-labs',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/astriaorg',
  telegram: null,
  twitter: 'https://twitter.com/AstriaOrg',
  url: 'https://www.astria.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
