import { AdapterProject } from '../types'

export default {
  name: 'Nillion Network',
  ninja: null,
  subcategories: 'L1/L2',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'qb5fdz',
  description:
    'Nillion is a distributed computing platform that expands trustless infrastructure into new use cases and verticals.',
  discord: '248822834317492245',
  investors: [
    'ii5tnv',
    'xmw0ev',
    '6nxw7d',
    '4l8mmr',
    'hamhvv',
    'gwix1y',
    'sknhsa',
    'mar9ip',
    'v81ftp',
    'nxzb7m',
    'mssm5f',
    'q84v53',
    'rd2mzf',
    '07pxi6',
    '9qbjjp',
    '4u100f',
    'aq52wc',
    'otzp4l',
    '8dhvoo',
    'ugp187',
    'e3c7wh',
    'nlvx3r',
    '3qflb4',
  ],
  linkedin: 'https://www.linkedin.com/company/nillionnetwork/?originalSubdomain=ch',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/nillionnetwork',
  twitter: 'https://twitter.com/nillionnetwork',
  url: 'https://www.nillion.com/',
  verified: false,
} satisfies AdapterProject
