import { AdapterProject } from '../types'

export default {
  name: 'Nillion Network',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'qb5fdz',
  description:
    'Nillion is a distributed computing platform that expands trustless infrastructure into new use cases and verticals. It is a decentralized network (but not a layer 1 or blockchain) that utilizes a novel primitive, Nil Message Compute (NMC). NMC innovates on the foundations of Multi-Party Computation (MPC) and Homomorphic Encryption to unlock the secure storage and processing of high value data. The Nillion network invites new decentralized use cases such as machine learning on invisible datasets, quantum secure messaging, smart custody of digital assets, distributed biometric authentication, verifiable dark pools, collaborative block building and composable digital identity – enabling developers to create applications across industries like retail, medical, legal, banking and AI.',
  investors: [
    'ii5tnv',
    'xmw0ev',
    '6nxw7d',
    '4l8mmr',
    'hamhvv',
    'gwix1y',
    'sknhsa',
    'mar9ip',
    'v81ftp',
    'nxzb7m',
    'mssm5f',
    'q84v53',
    'rd2mzf',
    '07pxi6',
    '9qbjjp',
    '4u100f',
    'aq52wc',
    'otzp4l',
    '8dhvoo',
    'ugp187',
    'e3c7wh',
    'nlvx3r',
    '3qflb4',
  ],
  duneQueries: null,
} satisfies AdapterProject
