import { AdapterProject } from '../types'

export default {
  name: 'AIOZ',
  subcategories: 'CDN',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'AIOZ',
  coingeckoId: 'aioz-network',
  id: 'tpqdbi',
  description: 'AIOZ is a decentralized content delivery network.',
  discord: null,
  investors: [
    'i98114',
    'okjrd0',
    'lsc0yi',
    'jw4wz7',
    'snubsq',
    'ka4f30',
    'tqc1qx',
    'nwl5v7',
    '0nsbs7',
  ],
  linkedin: 'https://sg.linkedin.com/company/aioz-ai',
  duneQueries: null,
  blog: 'https://medium.com/aioz-network',
  github: null,
  telegram: 'https://t.me/s/aiozofficial',
  twitter: 'https://twitter.com/aioznetwork?lang=en',
  url: 'https://aioz.network/',
} satisfies AdapterProject
