import { AdapterProject } from '../types'

export default {
  name: 'Akash',
  chain: 'COSMOS',
  category: 'AI',
  token: 'AKT',
  coingeckoId: 'akash-network',
  id: 'qmmyw0',
  description:
    'Akash is an open-source supercloud that enables secure and efficient buying and selling of computing resources.',
  investors: [
    'mzqq7s',
    '1yqm3h',
    'go7fr1',
    'j110q6',
    'ts721o',
    'd6wjf8',
    'la4mmt',
    'd892rm',
    '798xl8',
    'wi3q48',
    'knw63n',
    'rwthif',
    '2hteus',
    '5dsvsj',
    'pbn252',
    'zluhsc',
    'nawuv7',
    'fxmvug',
    '4dc71l',
    'qyzsbd',
    'zkrb16',
    'ptw0vo',
    'y2u2sf',
    'g72mqv',
    '4vrrqt',
    'yibv9g',
    '5plfkq',
    'wu15kr',
    'nzxtym',
    'fa62pa',
    'oblyiu',
  ],
  duneQueries: null,
} satisfies AdapterProject
