import { AdapterProject } from '../types'

export default {
  name: 'Akash',
  ninja: null,
  subcategories: 'GPUs',
  chain: 'COSMOS',
  category: 'COMPUTE',
  token: 'AKT',
  coinGeckoID: 'akash-network',
  id: 'qmmyw0',
  description:
    'Akash is an open-source supercloud that enables secure and efficient buying and selling of computing resources.',
  discord: '747885925232672829',
  investors: [
    'mzqq7s',
    '66xw1k',
    'go7fr1',
    '6998je',
    'pmg1r8',
    'jsmrlo',
    'la4mmt',
    'box926',
    '798xl8',
    'dnu31w',
    'b4hdjb',
    'knw63n',
    'rwthif',
    '5qx1w8',
    'h25qln',
    '5dsvsj',
    'ofjyek',
    'af2ees',
    'i98ktk',
    'fxmvug',
    'xkxso5',
    '3keso5',
    'qyzsbd',
    '50oy3l',
    'yi2vaq',
    'qcvhmz',
    'g72mqv',
    'dx4kss',
    'yibv9g',
    '0yfxp7',
    'wu15kr',
    'emawdh',
    't30rwx',
  ],
  linkedin: 'http://www.linkedin.com/company/akash-network',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@akashnet_',
  github: 'https://github.com/akash-network',
  telegram: null,
  twitter: 'https://twitter.com/akashnet_',
  url: 'https://akash.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://www.wsj.com/articles/funding-snapshot-overclock-labs-raises-1-3-million-seed-round-to-automate-cloud-infrastructure-1511300185',
    },
  ],
} satisfies AdapterProject
