import { AdapterProject } from '../types'

export default {
  name: 'Taxa',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '5zk1x8',
  description:
    'Taxa: blockchain agnostic layer-2 infrastructure ensuring privacy, power, and easy development.',
  investors: [
    '2q8xba',
    'oq9fz1',
    'q4zzkd',
    'xr8iwa',
    'lfbmt3',
    'ht2snh',
    'sqkxbd',
    'i1vs03',
    'u13una',
    'i1x9du',
    '9205ui',
    'dc47oz',
    'kzsrt6',
    'q0cuxs',
    'ocqa20',
    'xemx4j',
  ],
  duneQueries: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/taxanetwork',
  twitter: 'https://twitter.com/taxanetwork',
  url: 'https://taxa.network/',
} satisfies AdapterProject
