import { AdapterProject } from '../types'

export default {
  name: 'GenomeFi',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'x5s3a0',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/GenomeFi',
  url: 'https://genomefi.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
