import { AdapterProject } from '../types'

export default {
  name: 'MXC',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'SENSORS',
  token: 'MXC',
  coinGeckoID: 'mxc',
  id: 'h1l8jh',
  description: 'MXC is a L3 zkEVM built on top of a decentralized network of LPWAN radio nodes.',
  discord: '445679878004801547',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/mxc-foundation',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/mxc',
  github: 'https://github.com/mxc-foundation',
  telegram: 'https://t.me/mxcfoundation',
  twitter: 'https://twitter.com/mxcfoundation',
  url: 'https://www.mxc.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
