import { AdapterProject } from '../types'

export default {
  name: 'LogX',
  ninja: 'sal-gala.eth',
  subcategories: 'Prediction Market',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'c9gt14',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/LogX_trade',
  url: 'https://www.logx.trade/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
