import { AdapterProject } from '../types'

export default {
  name: 'dVIN',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'tabxir',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/dvinlabs',
  url: 'https://www.clubdvin.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
