import { AdapterProject } from '../types'

export default {
  name: 'WELL3',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '2sme5b',
  description: '',
  discord: '930328152117485569',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/well3official',
  url: 'https://well.eco/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
