import { AdapterProject } from '../types'

export default {
  name: 'Pano AI',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Environmental',
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: '111p2s',
  description:
    'Pano AI detects wildfires using deep learning AI & computer vision for real-time event identification & classification.',
  discord: null,
  investors: [
    'uog43p',
    'dbnjzb',
    '4zunln',
    'z29ewp',
    'xz7t5c',
    'ambkkn',
    '74s00h',
    'r6v4in',
    'bcamtz',
    'n1w9x7',
    'q5m1p9',
    '9pb2mx',
    'grut3l',
    'kr9pzv',
    'qmk67p',
    'w19rhh',
    'gdty4y',
    'tcaja1',
    '6d2jcm',
    '3te3nj',
    'o6rvj3',
    'qf539o',
    'hhcvbz',
  ],
  linkedin: 'https://www.linkedin.com/company/pano-ai/about/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Pano_AI',
  url: 'https://www.pano.ai/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://techcrunch.com/2022/09/19/pano-ai/',
    },
    {
      roundType: 'Series A',
      url: 'https://techcrunch.com/2023/07/10/pano-series-a-extension/',
    },
    {
      roundType: 'Series A',
      url: 'https://techcrunch.com/2022/09/19/pano-ai/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
