import { AdapterProject } from '../types'

export default {
  name: 'Ylide',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'zug89a',
  description: 'Ylide Protocol: secure cross-chain wallet communication for Web3 projects.',
  discord: null,
  investors: ['jtzx5o', '6nxw7d', 'bxcu1r', '7vs71r', 'o76txg'],
  linkedin: 'http://www.linkedin.com/company/ylide',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@ylide',
  github: 'https://github.com/ylide-io',
  telegram: 'https://t.me/ylide_chat',
  twitter: 'https://twitter.com/ylide_',
  url: 'http://www.ylide.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
