import { AdapterProject } from '../types'

export default {
  name: 'Dedium',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '5v30ct',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/DediumNetwork',
  url: 'https://dedium.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
