import { AdapterProject } from '../types'

export default {
  name: 'Flock Safety',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'kcetq1',
  description:
    'Developer of camera technology designed to capture images to eliminate crime while protecting privacy.',
  discord: null,
  investors: [
    '26x5nn',
    '7bywo5',
    'xkd8xw',
    'y5tgkc',
    '9btyj8',
    'r6v4in',
    '2vxsqs',
    'z7jgni',
    'u3ke67',
    'ikeqay',
    'erx8op',
    '1bgp2n',
    '80hqah',
    'gj9v6c',
    'ge3scw',
    'k1e97y',
    'rotj2h',
    'wdtkj1',
    'hhcvbz',
  ],
  linkedin: 'https://www.linkedin.com/company/flock-safety/',
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Flock_Safety',
  url: 'https://www.flocksafety.com/',
} satisfies AdapterProject
