import { AdapterProject } from '../types'

export default {
  name: 'SingularityNET',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'AGIX',
  coingeckoId: 'singularitynet',
  id: '48m8lh',
  description:
    'SingularityNET enables easy creation, sharing, and monetization of AI services through its global marketplace.',
  investors: [
    'fdepqs',
    's7b833',
    'buime9',
    'qi3rfl',
    '7itbm5',
    '3b0ihr',
    'oee9lj',
    '8kqjbk',
    'ct9jfu',
    'xc3d4p',
    'ncxg2x',
    'm5j9oz',
    'p6t4kv',
    '9ptsrm',
    'eofkvo',
    '1im0oz',
    'wdtkj1',
    'myul3m',
  ],
  duneQueries: null,
  blog: 'https://medium.com/tag/singularitynet',
  github: 'https://github.com/singnet',
  telegram: 'https://telegram.me/singularitynet',
  twitter: 'https://twitter.com/singularitynet',
} satisfies AdapterProject
