import { AdapterProject } from '../types'

export default {
  name: 'SingularityNET',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'AGIX',
  coinGeckoID: 'singularitynet',
  id: '48m8lh',
  description:
    'SingularityNET enables easy creation, sharing, and monetization of AI services through its global marketplace.',
  discord: '909843832491896832',
  investors: [
    'z2j0xs',
    'fdepqs',
    'buime9',
    'o5kpgb',
    'xmw0ev',
    'qi3rfl',
    'u2w7b1',
    '798xl8',
    '7itbm5',
    '3b0ihr',
    'i98114',
    'rlo5x9',
    'xdw0yr',
    'oee9lj',
    'e9qwvr',
    '8kqjbk',
    '243kcn',
    'ct9jfu',
    'xc3d4p',
    'm5j9oz',
    'p6t4kv',
    'dd123i',
    '65epfb',
    '9ptsrm',
    '17wi5y',
    'eofkvo',
    'tktadr',
    'myul3m',
  ],
  linkedin: 'http://www.linkedin.com/company/singularitynet',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/tag/singularitynet',
  github: 'https://github.com/singnet',
  telegram: 'https://telegram.me/singularitynet',
  twitter: 'https://twitter.com/singularitynet',
  url: 'https://singularitynet.io/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://cryptoslate.com/press-releases/singularitydao-raises-2-7m-in-private-sale-led-by-alphabit-to-usher-ai-driven-defi/',
    },
    {
      roundType: 'Series A',
      url: 'https://www.coindesk.com/business/2022/05/19/singularitynet-singularitydao-receive-25m-to-accelerate-ai-backed-defi/',
    },
  ],
} satisfies AdapterProject
