import { AdapterProject } from '../types'

export default {
  name: 'NATIX',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'MOBILITY',
  token: null,
  coinGeckoID: null,
  id: 'uq4s3v',
  description: 'NATIX is a decentralized real-time mapping & surveillance network.',
  discord: '811964821000028160',
  investors: [
    '4l8mmr',
    '7bjt0y',
    'hbpmm3',
    'buo8ql',
    'bxcu1r',
    'h8sw72',
    'l89xw2',
    '8a0izu',
    '7zvxz8',
    '6c0yfx',
    'ykd20k',
    's4jf02',
    'g4z7os',
    'kaduov',
    'fhd6hx',
    'n73vnt',
    '4dh0t9',
    '56k9fh',
    '0kzxhl',
    'w19rhh',
    '1qqzyc',
    'a1uyxq',
    'llojfj',
    'monvfg',
    'kh8jxd',
    'nlvx3r',
    '5jng4b',
  ],
  linkedin: 'https://www.linkedin.com/company/natixio',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/natix-io',
  github: 'https://github.com/natix-io',
  telegram: null,
  twitter: 'https://twitter.com/NATIXNetwork',
  url: 'https://www.natix.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.thesaasnews.com/news/natix-raises-3-5-million-in-seed-round',
    },
    {
      roundType: 'Strategic/Angel',
      url: 'https://www.theblock.co/post/290927/depin-natix-funding-token-airdrop-solana',
    },
  ],
  isApp: true,
} satisfies AdapterProject
