import { AdapterProject } from '../types'

export default {
  name: 'FSP',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '5tr97t',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.futureofsports.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
