import { AdapterProject } from '../types'

export default {
  name: 'Blockus',
  ninja: 'vkurup.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'wawujf',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/HelloBlockus',
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
