import { AdapterProject } from '../types'

export default {
  name: 'KIZZY',
  ninja: null,
  subcategories: 'Prediction Market',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'tmsb4i',
  description: 'The first content prediction marketplace.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/kizzymobile',
  url: 'https://www.kizzy.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
