import { AdapterProject } from '../types'

export default {
  name: 'OpenServ',
  ninja: 'ZZ',
  subcategories: 'Agents',
  chain: null,
  category: 'AI',
  token: 'OPEN',
  coinGeckoID: null,
  id: '7x2h0s',
  description: 'OpenServ is a Marketplace for Autonomous AI Agents.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/openservai',
  url: 'https://openserv.ai/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
