import { AdapterProject } from '../types'

export default {
  name: 'OpenServ',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Agents',
  chain: null,
  category: 'AI',
  token: 'OPEN',
  coinGeckoID: null,
  id: '7x2h0s',
  description: 'OpenServ is a Marketplace for Autonomous AI Agents.',
  discord: '1176767100350644254',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/openservai',
  url: 'https://openserv.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
