import { AdapterProject } from '../types'

export default {
  name: 'Omo',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'puytcq',
  description: 'Omo is a modular asset management protocol powered by On-Chain Agents.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/omoprotocol',
  url: 'https://www.omoprotocol.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
