import { AdapterProject } from '../types'

export default {
  name: 'Kalp',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'b5okyb',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.kalp.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
