import { AdapterProject } from '../types'

export default {
  name: 'Koii',
  ninja: null,
  subcategories: null,
  chain: 'NATIVE',
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coingeckoId: null,
  id: 'xfjtib',
  description:
    'Koii is a platform enabling passive income by connecting idle devices to transparent apps and audit systems.',
  discord: 'https://discord.com/invite/koii',
  investors: [
    'p69jgl',
    'pbunpe',
    'puuj5e',
    'wqn9ms',
    '6hezki',
    'pmco7y',
    'n0g582',
    'knw63n',
    'mywjsu',
    'xgzede',
    'j4k67v',
    'vjpj24',
    'g72mqv',
    'm05wan',
    'pu3yyr',
    'lzpnns',
    'o7xcsr',
  ],
  linkedin: 'http://www.linkedin.com/company/koii-network',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://koii-network.medium.com/',
  github: 'https://github.com/koii-network/',
  telegram: 'https://t.me/koiinetwork',
  twitter: 'https://twitter.com/KoiiNetwork',
  url: 'https://www.koii.network/',
} satisfies AdapterProject
