import { AdapterProject } from '../types'

export default {
  name: 'Defit',
  ninja: null,
  subcategories: 'Health & Fitness',
  chain: 'POLYGON',
  category: 'SENSORS',
  token: 'DEFIT',
  coinGeckoID: 'defit',
  id: 'jmavqd',
  description: 'Defit is a fitness web3 brand that rewards users with a Move to Earn movement.',
  discord: '932304379694944277',
  investors: [],
  linkedin: 'https://sg.linkedin.com/company/defitfitnessclub',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://defitofficial.medium.com/',
  github: null,
  telegram: 'https://t.me/DEFITofficial',
  twitter: 'https://twitter.com/DEFITofficial',
  url: 'https://app.defit.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
