import { AdapterProject } from '../types'

export default {
  name: 'Chingari',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'teymg6',
  description:
    'Chingari is a fast-growing Web3 Social Media company in India, combining the features of TikTok and OnlyFans.',
  investors: [
    '9cmz24',
    '9h3wro',
    'p4m6wn',
    'z0bwg1',
    'yc3rjf',
    'm174rg',
    '9a7u1l',
    'g738qx',
    'nubjif',
    '7fb6dj',
    'wxcf8r',
    '35lw16',
    'ssztnh',
    'ri09e0',
    'szfiug',
    'r5sj96',
    'u1wx4a',
    '6uuq9l',
    '6hezki',
    'hhylf0',
    'cllmwd',
    'laupoy',
    'h58ujg',
    '44e83n',
    'nlqu6w',
    'dm8n2p',
    'u13una',
    '09zqe3',
    'ckjv3m',
    'oqxxne',
    '7lu5le',
    'l73m6h',
    '2roey0',
    'k4y02w',
    '2x1lbw',
    'd9murm',
    '2gyewh',
    'mgr5kn',
    'i8evbl',
    'ptvey1',
    'qd0p5n',
    'q84v53',
    'azofz8',
    'qqc9zd',
    'hiczng',
    'qw4aok',
    'ka4f30',
    '8or4a9',
    'svzvqn',
    'vfifi9',
    'pu0mg9',
    'pnypo2',
    '07pxi6',
    'j71mmd',
    'zjhj49',
    'pwuofb',
    'hb4mb3',
    'ti312b',
    '6s2s3g',
    'gj7krc',
    'unykak',
    'e8u4l9',
    'virmnk',
    'b1i2hy',
    'lhs5s8',
    'giecp7',
    '2b5dyx',
    '8vbmp2',
    'tlb60n',
    'sbxp1t',
    'wa7xxl',
    'imxksv',
    '5hgqit',
    'cz5kx7',
    'qf539o',
    'jrl9r2',
    'm2vb8u',
    '50neyo',
    '22tft9',
    'dbr5ig',
    'ixxo16',
    '5b8q5j',
    'o3c9bd',
    'qqxhld',
  ],
  duneQueries: null,
  blog: 'https://chingariapp.medium.com/',
  github: 'https://github.com/CodeTheChangeUBC/Chingari/projects/2',
  telegram: null,
  twitter: 'https://twitter.com/Chingari_IN',
  url: 'https://chingari.io/',
} satisfies AdapterProject
