import { AdapterProject } from '../types'

export default {
  name: 'Dmail',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: '84v1j0',
  description:
    'Dmail is an AI-powered decentralized email platform that empowers users with ownership and control of their data.',
  discord: '906006936531660831',
  investors: [
    'oq9fz1',
    'gun7y3',
    'eq77bg',
    'ta5llm',
    'bjj1gw',
    'caojlf',
    '32xkrh',
    'lfbmt3',
    'i1vs03',
    'nxzb7m',
    'nqkr1o',
    'ardv2y',
    'azofz8',
    '4fks6v',
    'n5c5of',
    'pxs0xw',
    'wf1h0f',
    'tnkrzw',
    'hbepme',
    '5u27gc',
    'pyukl2',
    '3y817d',
    'jofsd4',
    'nj1v3c',
    'nlvx3r',
  ],
  linkedin: 'http://www.linkedin.com/company/dmail-idee-utili-e-introvabili',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@dmail_official',
  github: 'https://github.com/dmailofficial/dmail',
  telegram: 'https://t.me/dmailofficial',
  twitter: 'https://twitter.com/dmailofficial',
  url: 'https://dmail.ai/',
  verified: false,
} satisfies AdapterProject
