import { AdapterProject } from '../types'

export default {
  name: 'GlueX',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'vo7y4s',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/GluexProtocol',
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
