import { AdapterProject } from '../types'

export default {
  name: 'Push',
  chain: 'ETHEREUM',
  category: 'WIRELESS',
  token: 'PUSH',
  coingeckoId: 'ethereum-push-notification-service',
  id: 'nhurl1',
  description: 'Push Protocol: web3 cross-chain network for dapps, wallets, and services.',
  discord: 'https://discord.com/invite/pushprotocol',
  investors: [
    '92ar5l',
    'h6uwpw',
    'vstg5d',
    'bonru9',
    'cd2nay',
    'h477gr',
    'xmw0ev',
    'ntqe0t',
    '896jil',
    '2slnxb',
    'mrgeec',
    'puuj5e',
    '2tgqti',
    'gun7y3',
    '8nclhv',
    'oi4yuk',
    '5d2mm5',
    '3yr1j5',
    'y6x2dz',
    '1k4qxq',
    'lkgkfl',
    '35e9e6',
    '8l2m10',
    '1b7u42',
    '9kbvyo',
    'okjrd0',
    'curksv',
    'i1x9du',
    '2x1lbw',
    '4ssdn4',
    '3z06cc',
    'n463s0',
    'dbnrgb',
    'qqc9zd',
    '5kunmp',
    'mlsidm',
    'oxjxo0',
    'vfifi9',
    'bah2fw',
    'n7xol2',
    'dd123i',
    '6f2cxt',
    'd6llvy',
    '8agdnp',
    't0itsl',
    'm8xiuk',
    '06o6kd',
    'z25ee2',
    '9e1gk4',
    'xph9q9',
    'oltsrb',
    'e2dh7y',
    'jtcw6t',
    'rotj2h',
    'hc7wxh',
    'nzxtym',
    'zim0bv',
    's812zr',
    '2wn9ev',
    '935mux',
    '71p088',
    'urug6u',
  ],
  linkedin: 'https://www.linkedin.com/company/push-protocol',
  duneQueries: null,
  blog: 'https://medium.com/push-protocol',
  github: null,
  telegram: null,
  twitter:
    'https://twitter.com/pushprotocol?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://push.org/',
} satisfies AdapterProject
