import { AdapterProject } from '../types'

export default {
  name: 'Qiro',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'RWA',
  token: null,
  coinGeckoID: null,
  id: 'alkph8',
  description: 'Qiro is a unified credit protocol enabling RWA-backed DeFi lending.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/qiro-group/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.qiro.fi/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
