import { AdapterProject } from '../types'

export default {
  name: 'Fission',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coingeckoId: null,
  id: 'dkaff9',
  description:
    'Fission builds open source protocols and managed solutions that empower developers to construct scalable and secure software applications.',
  discord: '478735028319158273',
  investors: [
    'e3qzk9',
    'jo973z',
    'vh40ts',
    'mywjsu',
    'uwuv2v',
    't7xkdd',
    '837q2c',
    '3vlmii',
    'vjpj24',
    'ti312b',
    '1im0oz',
  ],
  linkedin: 'https://ca.linkedin.com/company/fissioncodes',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://fission.codes/blog/',
  github: 'https://github.com/fission-codes/',
  telegram: null,
  twitter: 'https://twitter.com/FISSIONcodes',
  url: 'https://fission.codes/',
  verified: false,
} satisfies AdapterProject
