import { AdapterProject } from '../types'

export default {
  name: 'Herond',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '4609bx',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/HerondLabs',
  url: 'https://herond.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
