import { AdapterProject } from '../types'

export default {
  name: 'Andrena',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'tgalub',
  description:
    'Andrena is a company offering high-speed internet distribution services with a focus on reduced costs.',
  discord: null,
  investors: [
    'zbfwcv',
    'dxtuis',
    'q4gteq',
    'hbpmm3',
    '3hqsew',
    'ucjx6z',
    'tfbeoa',
    'zfcdde',
    '5tj4jx',
    '7zvxz8',
    'h58ujg',
    'wagxxr',
    'jmhi4v',
    'a361c4',
    'i1seo2',
    'u8s1ak',
    'o58u89',
    '11ic7a',
    '795ufc',
    '3nsesl',
    'uulo45',
    'zx1832',
    'puuasi',
    'bjt37s',
  ],
  linkedin: 'https://www.linkedin.com/company/andrenainternet/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/andrena_wifi?lang=en',
  url: 'https://andrena.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.globenewswire.com/news-release/2023/02/27/2616422/0/en/Andrena-Raises-15-Million-in-Series-A-Funding-Advancing-Its-Mission-to-Provide-Next-Gen-Affordable-Internet-for-All.html',
    },
  ],
} satisfies AdapterProject
