import { AdapterProject } from '../types'

export default {
  name: 'Intu',
  ninja: 'vkurup.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'yxypiw',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/IntuOfficial',
  url: 'https://intu.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
