import { AdapterProject } from '../types'

export default {
  name: 'Golem',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'GLM',
  coinGeckoID: 'golem',
  id: 'j4istz',
  description:
    'Golem is a decentralized computing marketplace. It consists of a network of nodes that implement the Golem network protocol.',
  discord: '684703559954333727',
  investors: [
    'bwghh0',
    'wqn9ms',
    '2ckrz9',
    '6c0yfx',
    'hbiw3h',
    'gftio8',
    'ujw2s3',
    'u49yhz',
    'j4k67v',
    'n2k3so',
    'vjpj24',
    'udcrbv',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.golem.network',
  verified: false,
  fundraisesUrls: [
    'https://www.financemagnates.com/cryptocurrency/news/golem-raises-8-6-million-29-minutes-fund-airbnb-computers/',
  ],
} satisfies AdapterProject
