import { AdapterProject } from '../types'

export default {
  name: 'Krang AI',
  ninja: 'W. L',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'u1io58',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/KrangHQ',
  url: 'https://krang.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
