import { AdapterProject } from '../types'

export default {
  name: 'IoTeX',
  ninja: null,
  subcategories: 'IoT',
  chain: 'IOTEX',
  category: 'BLOCKCHAIN_INFRA',
  token: 'IOTX',
  coinGeckoID: 'iotex',
  id: 'oqhdss',
  description:
    'IoTeX is a blockchain-based sensor solution called Pebble, integrating numerous functions in one device.',
  discord: '534888542648664074',
  investors: [
    'd82r3q',
    'saoq66',
    'z37132',
    'buo8ql',
    'ubwov4',
    '772xwk',
    'caojlf',
    '7zvxz8',
    'grev3h',
    'uktppp',
    '6c0yfx',
    'x10a41',
    'wcrsby',
    'nxzb7m',
    'i1x9du',
    '0go35f',
    '07pxi6',
    '1im0oz',
    'wu15kr',
    'ikokx0',
    'o7xcsr',
    't9lvtn',
    's812zr',
    '78enfd',
  ],
  linkedin: 'http://www.linkedin.com/company/iotex',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/fmfw-io/introducing-iotex-3c14699aeecd',
  github: 'https://github.com/iotexproject',
  telegram: 'https://t.me/IoTeXGroup',
  twitter: 'https://twitter.com/iotex_io',
  url: 'https://iotex.io/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.prweb.com/releases/snz-capital-foresight-ventures-futuremoneygroup-borderless-capital-and-others-invest-50m-into-the-iotex-ecosystem-to-accelerate-depin-growth--adoption-302105700.html',
    },
    {
      roundType: 'Series A',
      url: 'https://www.coindesk.com/business/2022/06/07/machinefi-lab-raises-10m-to-incentivize-iot-data-collection-for-web-3/',
    },
  ],
} satisfies AdapterProject
