import { AdapterProject } from '../types'

export default {
  name: 'Fluence',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'FLT',
  coinGeckoID: 'fluence-2',
  id: 'ul9uzl',
  description: 'Fluence - decentralized platform for creating peer-to-peer apps.',
  discord: '483968379833679873',
  investors: [
    'bspyld',
    '2q8xba',
    'b5zojp',
    'hhudw8',
    '9n4okv',
    '2g0699',
    '9qbjjp',
    'hepzxq',
    'ti312b',
    'tki9vm',
    'oltsrb',
    '2acydu',
    'rotj2h',
    'bix4ir',
  ],
  linkedin: 'http://www.linkedin.com/company/fluence-labs',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/fluence-network',
  github: 'https://github.com/fluencelabs',
  telegram: 'https://t.me/fluence_project',
  twitter: 'https://twitter.com/fluence_project',
  url: 'https://fluence.network/',
  verified: false,
} satisfies AdapterProject
