import { AdapterProject } from '../types'

export default {
  name: 'Fluence',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 'ul9uzl',
  description: 'Fluence - decentralized platform for creating peer-to-peer apps.',
  investors: [
    'bspyld',
    '2q8xba',
    'b5zojp',
    'hhudw8',
    '9n4okv',
    '2g0699',
    '9qbjjp',
    'hepzxq',
    'ti312b',
    'tki9vm',
    'oltsrb',
    '2acydu',
    'rotj2h',
    'bix4ir',
  ],
  duneQueries: null,
  blog: 'https://medium.com/fluence-network',
  github: 'https://github.com/fluencelabs',
  telegram: 'https://t.me/fluence_project',
  twitter: 'https://twitter.com/fluence_project',
  url: 'https://fluence.network/',
} satisfies AdapterProject
