import { AdapterProject } from '../types'

export default {
  name: 'FOIL',
  ninja: null,
  subcategories: 'L1/L2',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'wd2g59',
  description: 'Foil: Scalable, secure blockchain for IoT with high-speed transactions.',
  discord: '773843041357135882',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/foil2/about/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/FoilNetwork',
  url: 'https://foil.network/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
