import { AdapterProject } from '../types'

export default {
  name: 'Flock',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'ruqwx5',
  description: 'Decentralized federated learning',
  discord: '977200106531082240',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://flock.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
