import { AdapterProject } from '../types'

export default {
  name: 'Antic',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'hs6fc5',
  description: 'Antic: Decentralized co-ownership integration for businesses.',
  discord: null,
  investors: [],
  linkedin: 'http://www.linkedin.com/company/anticxyz',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/multeez',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Getantic',
  url: 'https://www.getantic.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
