import { AdapterProject } from '../types'

export default {
  name: 'SolRazr',
  ninja: null,
  subcategories: null,
  chain: 'SOLANA',
  category: 'NOT_DEPIN',
  token: 'SOLR',
  coinGeckoID: 'solrazr',
  id: '0fi9q0',
  description: 'SolRazr is a decentralized developer ecosystem for Solana.',
  discord: '886683619958079538',
  investors: [],
  linkedin: 'https://sg.linkedin.com/company/omnistart-network',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@RazrFi/solrazr-2021-in-review-5ba669ed2efc',
  github: 'https://github.com/solrazr-app',
  telegram: 'https://t.me/s/solrazr_app',
  twitter: 'https://mobile.twitter.com/CSolrazr',
  url: 'https://razrfi.ai/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
