import { AdapterProject } from '../types'

export default {
  name: 'Sentimint',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '3tz2mg',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/sentimint_life?s=11',
  url: 'https://sentimint.life/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
