import { AdapterProject } from '../types'

export default {
  name: 'Subconscious',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '5xypv6',
  description: 'Noosphere is a worldwide networked notes graph on IPFS.',
  discord: '1003419732516552724',
  investors: ['eqr6sq', 'jo973z', 'ti312b'],
  linkedin: 'https://www.linkedin.com/company/subconscious-network/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/subconsciousnetwork',
  telegram: null,
  twitter: null,
  url: 'https://subconscious.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
