import { AdapterProject } from '../types'

export default {
  name: 'Overtime',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'ak9wb5',
  description: 'THE WEB3 SPORTS MARKETS REVOLUTION',
  discord: '906484044915687464',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.overtimemarkets.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
