import { AdapterProject } from '../types'

export default {
  name: 'SCDO',
  ninja: '0x25052A4B28a35FfdBf2FaBA7DCCEB350e91b908F',
  subcategories: 'L1/L2',
  chain: 'NATIVE',
  category: 'BLOCKCHAIN_INFRA',
  token: 'SCDO',
  coinGeckoID: null,
  id: 'hxewpy',
  description: 'SCDO is a DePIN public chain based on the ZPoW algorithm. ',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/scdolab',
  url: 'https://scdo.org/#/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
