import { AdapterProject } from '../types'

export default {
  name: 'Create',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'otw9vc',
  description: 'Creator-owned dApp protocol revolutionizing IP creation in the Metaverse space.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/create-protocol/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://create-protocol.medium.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/CreateProtocol',
  url: 'https://www.createprotocol.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
