import { AdapterProject } from '../types'

export default {
  name: 'Project AXS',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '61ziyo',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/3uild-3thos/project_axs',
  telegram: null,
  twitter: 'https://x.com/_axsproject',
  url: 'https://projectaxs.fun/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
