import { AdapterProject } from '../types'

export default {
  name: '0xParc',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'zf9ws4',
  description: '0xPARC supports the next generation of cryptography-enabled applications.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://0xparc.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
