import { AdapterProject } from '../types'

export default {
  name: 'Jim',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'JIM',
  coinGeckoID: 'roasthimjim',
  id: 'b9tawl',
  description: 'Jim is an AI Bot that responds intelligently on social platforms.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/RoastHimJim',
  twitter: 'https://twitter.com/JimAIstudios',
  url: 'https://www.jimaistudios.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
