import { AdapterProject } from '../types'

export default {
  name: 'DRIFE',
  chain: 'BINANCE',
  category: 'LABOR',
  token: 'DRF',
  coingeckoId: 'drife',
  id: 'con8un',
  description: 'DRIFE is a decentralized ride-hailing platform with 30k+ drivers.',
  investors: [
    'xmw0ev',
    'ka4f30',
    'okjrd0',
    '5252r4',
    'bf6y5u',
    'g738qx',
    'gtjd6o',
    '5dok1r',
    'qxuz9y',
    'a0nm72',
    'lfbmt3',
    '2qkv0h',
    '4rfvn9',
    'nbsvit',
    'l4q2pi',
    'z9h8t8',
    'snubsq',
    'ardv2y',
    'qy6xav',
    'tdw5kr',
    '577mxg',
    'imxksv',
    'xxi1ub',
    'xgjf6h',
    'h3vz69',
  ],
  duneQueries: null,
  cmcId: 10889,
} satisfies AdapterProject
