import { AdapterProject } from '../types'

export default {
  name: 'IO.Net',
  ninja: null,
  subcategories: null,
  chain: 'SOLANA',
  category: 'COMPUTE',
  token: 'IO',
  coinGeckoID: 'io-net',
  id: '61zuw7',
  description: 'IO.Net is a decentralized computing platform for ML applications built on Solana.',
  discord: '1080817368646819941',
  investors: [
    'hol96b',
    'nxop7l',
    'gjt0lb',
    'yc3rjf',
    'zloyr1',
    'vulroe',
    '2ckrz9',
    '67mqz0',
    'uktppp',
    'ons3en',
    'po8xe3',
    '80qehd',
    'b04x9g',
    '79518t',
    '2g0699',
    'smqwtv',
    'pu3yyr',
    'tlb60n',
    'z6cfwz',
  ],
  linkedin: 'https://www.linkedin.com/company/ionet-official/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ionet-official',
  telegram: 'https://t.me/ionet_official',
  twitter: 'https://discord.com/invite/kqFzFK7fg2',
  url: 'https://io.net/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.reuters.com/technology/ai-focused-blockchain-startup-io-research-raises-30-mln-series-funding-round-2024-03-05/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
