import { AdapterProject } from '../types'

export default {
  name: 'IO.Net',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '61zuw7',
  description: 'IO.Net is a decentralized computing platform for ML applications built on Solana.',
  discord: '1080817368646819941',
  investors: ['2g0699'],
  linkedin: 'https://linkedin.com/company/antbitio',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ionet-official',
  telegram: 'https://t.me/ionet_official',
  twitter: 'https://discord.com/invite/kqFzFK7fg2',
  url: 'https://io.net/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
