import { AdapterProject } from '../types'

export default {
  name: 'Imbue',
  ninja: null,
  subcategories: 'ML',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'i8a066',
  description: 'Imbue trains foundation models to create practically useful AI agents.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'http://www.linkedin.com/company/imbue-ai',
  github: 'https://imbue.com/blog/',
  telegram: null,
  twitter: 'https://twitter.com/imbue_ai',
  url: 'https://imbue.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
