import { AdapterProject } from '../types'

export default {
  name: 'Imbue',
  ninja: null,
  subcategories: 'ML',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'i8a066',
  description: 'Imbue trains foundation models to create practically useful AI agents.',
  discord: null,
  investors: [
    'h09snm',
    '3jocjo',
    'broyoo',
    'kuceub',
    'o6z0cw',
    'o90q95',
    'sco1gp',
    'lu73ql',
    'ge0bkk',
    's6i5sw',
    'akwngz',
    'snhh59',
    'ordhvp',
    'doumq4',
    '3u3gqf',
    't571yz',
    'lxl0a7',
    'ujck30',
    '8f7soa',
    'fw4cc9',
    'mjt6z5',
    'nr45cw',
    'rwhpsx',
    'xzl1ax',
    'vacncr',
    'm1prxp',
    'pl79fv',
    'y5m1mf',
    'wrrhev',
    '5aepuc',
    't5korm',
    'rgrylg',
    'tau7dj',
    'rwb1o1',
    'j0jsjd',
    '35j3pt',
    '6uczt3',
    'dxbskd',
    'num220',
    'wdtkj1',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'http://www.linkedin.com/company/imbue-ai',
  github: 'https://imbue.com/blog/',
  telegram: null,
  twitter: 'https://twitter.com/imbue_ai',
  url: 'https://imbue.com/',
  verified: false,
} satisfies AdapterProject
