import { AdapterProject } from '../types'

export default {
  name: 'AdHash',
  ninja: null,
  subcategories: 'Advertising',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'p6m3rb',
  description: 'AdHash: direct data exchange between publishers and advertisers, no intermediaries',
  discord: null,
  investors: ['2w7ubz', 'b2ybqs', 'p6iv9v', 'h8sw72', 'qbk051', 'ryj5he'],
  linkedin: 'https://www.linkedin.com/company/adhashprotocol/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/AdHashProtocol',
  telegram: 'https://t.me/adhashprotocol',
  twitter: null,
  url: 'https://adhash.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
