import { AdapterProject } from '../types'

export default {
  name: 'Zeitgeist',
  subcategories: 'Prediction Market',
  chain: 'POLKADOT',
  category: 'NOT_DEPIN',
  token: 'ZTG',
  coingeckoId: 'zeitgeist',
  id: 'yfqm09',
  description:
    'Zeitgeist is a provider of decentralized prediction markets software built on Polkadot.',
  discord: 'https://discord.com/invite/xv8HuA4s8v',
  investors: [
    '4j4oj3',
    '7jssah',
    'x3k5av',
    'xmw0ev',
    'zqdy3j',
    'm6mz4i',
    'r2lof0',
    'b1hrk6',
    '1afbvj',
    '5dsvsj',
    '9pp2xp',
    '9xb78i',
    'ujw2s3',
    '7ligqu',
    'h25e6r',
  ],
  linkedin: 'https://uk.linkedin.com/company/the-zeitgeist-agency-ltd',
  duneQueries: null,
  blog: 'https://medium.com/@zeitgeist.pro',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/zeitgeist_xyz?lang=en',
  url: 'https://zeitgeist.pm/',
} satisfies AdapterProject
