import { AdapterProject } from '../types'

export default {
  name: 'Lava',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'RPC/Indexing',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'jq8mvz',
  description: 'Lava is a modular data access (RPC & indexing) layer for rollups and blockchains.',
  discord: '963778337904427018',
  investors: [
    '7ygqh2',
    'wpzjqq',
    'fahk60',
    '70b3g7',
    'jsmrlo',
    'la4mmt',
    'qh9y6v',
    '9oo0xs',
    '074afi',
    'cznutg',
    'nxzb7m',
    '4ssdn4',
    'i89h0e',
    '7dehxu',
    'b04x9g',
    '3cjty6',
    'f87dvf',
    'ti312b',
    'gdty4y',
    'vrsed8',
    'due5zk',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.lavanet.xyz/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://twitter.com/lavanetxyz/status/1758162588381405563',
    },
  ],
  isApp: true,
} satisfies AdapterProject
