import { AdapterProject } from '../types'

export default {
  name: 'Lava',
  ninja: 'ZZ',
  subcategories: 'RPC/Indexing',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'jq8mvz',
  description: 'Lava is a modular data access (RPC & indexing) layer for rollups and blockchains.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.lavanet.xyz/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
