import { AdapterProject } from '../types'

export default {
  name: 'Axal',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'xex8ed',
  description: 'Axal is an intent coordination network powering autonomous web3 systems.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/getaxal',
  url: 'https://www.ax.al/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
