import { AdapterProject } from '../types'

export default {
  name: 'Braintrust',
  ninja: null,
  subcategories: 'Labor',
  chain: 'ETHEREUM',
  category: 'SERVICES',
  token: 'BTRST',
  coinGeckoID: 'braintrust',
  id: '8mk3xj',
  description:
    'The Braintrust is a decentralized Web3 talent network linking tech freelancers with top brands worldwide.',
  discord: null,
  investors: [
    'gow2jo',
    'qd2sf6',
    '8m8hfx',
    'hbpmm3',
    'r8brcg',
    'f7ccbr',
    'q2gdyi',
    '73opsz',
    'supj15',
    'sn3smj',
    't8bx9f',
    'gizch2',
    '84ay2m',
    '1labbf',
    '44e83n',
    'nlqu6w',
    'a3mqq8',
    'nxzb7m',
    '5s605e',
    'tgyjdv',
    'l7sko2',
    '9b0n2b',
    '0y9ptr',
    'hzmyi0',
    '551q4x',
    'ybmlzh',
    '0vsoya',
    '2g0699',
    'wp41fs',
    '3yvrn0',
    'ozeg73',
    'tcaja1',
    'gkv33p',
    'b1i2hy',
    '07gk2w',
    'uq7z9h',
    '7h08iv',
    'rotj2h',
    'mudfcv',
    'zim0bv',
    'a4zmhw',
    '2prylf',
    'ubuz3j',
    'ii6p9q',
  ],
  linkedin: 'https://www.linkedin.com/company/usebraintrust/',
  duneQueries: {
    BURN: '3151399',
    LOCKED_BALANCE: '3168279',
    MINT: '3168277',
    PRICE: '3151429',
  },
  foundingYear: null,
  blog: 'https://medium.com/tag/braintrust',
  github: null,
  telegram: null,
  twitter: 'https://t.me/braintrustofficial',
  url: 'https://www.usebraintrust.com/',
  verified: false,
  fundraisesUrls: [
    'https://www.coindesk.com/business/2020/10/01/braintrust-raises-18m-to-bring-defi-thinking-to-the-gig-economy/',
    'https://www.reuters.com/markets/funds/coatue-tiger-global-buy-100m-talent-network-braintrusts-tokens-2021-12-09/',
  ],
} satisfies AdapterProject
