import { AdapterProject } from '../types'

export default {
  name: 'Ties.DB',
  ninja: null,
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '4p06pz',
  description: 'Ties.DB: Secure decentralized database for projects.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/tiesdb/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/tiesnetwork',
  telegram: 'https://t.me/tiesdb',
  twitter: 'https://twitter.com/tiesnetwork-',
  url: 'https://tiesdb.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
