import { AdapterProject } from '../types'

export default {
  name: 'MindAI',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: 'MDAI',
  coinGeckoID: null,
  id: '0980mk',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/MindAIProject',
  twitter: 'https://x.com/MindAIProject',
  url: 'https://mindaiproject.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
