import { AdapterProject } from '../types'

export default {
  name: 'MindAI',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: 'MDAI',
  coinGeckoID: null,
  id: '0980mk',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/MindAIProject',
  url: 'https://mindaiproject.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
