import { AdapterProject } from '../types'

export default {
  name: 'Srcful',
  ninja: 'ZZ',
  subcategories: 'VPPs',
  chain: 'SOLANA',
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: 'k7ie81',
  description: 'Srcful is a Blockchain-powered Virtual Power Plant in the Helium ecosystem. ',
  discord: '1050323986271182849',
  investors: [],
  linkedin: 'https://linkedin.com/company/srcful',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.srcful.io/',
  github: 'https://github.com/srcfl',
  telegram: null,
  twitter: 'https://x.com/srcful/',
  url: 'https://srcful.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
