import { AdapterProject } from '../types'

export default {
  name: 'EdgeMatrix',
  ninja: '0x9Ab59cB71d4657f4c2DB7E0963212A81b6445b4c',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'iespkr',
  description: 'EMC Hub is a AI+Web3 computing power and model marketplace.',
  discord: '1101359709547679848',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@EMCProtocol',
  github: 'https://github.com/EMCProtocol-dev',
  telegram: 'https://t.me/emc_network',
  twitter: 'https://twitter.com/EMCprotocol',
  url: 'https://edgematrix.pro/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
