import { AdapterProject } from '../types'

export default {
  name: 'Combinder',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: 'PEAQ',
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: 'hot18z',
  description: 'Combinder is an energy DePIN, built on Peaq network.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/combinderio',
  url: 'https://www.combinder.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
