import { AdapterProject } from '../types'

export default {
  name: 'Influx',
  ninja: '0x4003408058d490FCD0A8b76925a412E6F39bc939',
  subcategories: 'DeFi',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'kemox7',
  description: 'Influx is a next-generation AMM perpetual futures protocol.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://influx.exchange/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
