import { AdapterProject } from '../types'

export default {
  name: 'Cedalio',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'w0adea',
  description: 'Cedalio: Auditable apps with real data ownership and GraphQL databases.',
  discord: '989948949823651862',
  investors: ['8krsge', 'eofkvo', 'g0e1qt', '1r0cdr'],
  linkedin: 'http://www.linkedin.com/company/cedalio',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@cedalio',
  github: 'https://github.com/cedalio',
  telegram: null,
  twitter: 'https://twitter.com/CedalioTech',
  url: 'https://cedalio.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
