import { AdapterProject } from '../types'

export default {
  name: 'MetafourAI',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'wko5kg',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
