import { AdapterProject } from '../types'

export default {
  name: 'DeFli',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: '14khqv',
  description: 'DeFli builds global infrastructure for the unmanned aviation industry.',
  discord: '1085688022001004676',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@team_483',
  github: 'https://github.com/DeFliTeam',
  telegram: null,
  twitter: 'https://twitter.com/Defli_Xyz',
  url: 'https://www.defli.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
