import { AdapterProject } from '../types'

export default {
  name: 'Trustpad',
  subcategories: null,
  chain: 'BINANCE',
  category: 'NOT_DEPIN',
  token: 'TPAD',
  coingeckoId: 'trustpad',
  id: 'rj7rcg',
  description:
    'TrustPad is a decentralized multi-chain fundraising platform enabling projects to raise capital and promise safety to early stage participants.',
  discord: 'https://discord.com/invite/4AG5B8Y8gW',
  investors: [
    '4j4oj3',
    'g738qx',
    '8nclhv',
    'bpwaff',
    'xgnbev',
    'okjrd0',
    'rrtsc3',
    '9wxc8s',
    'mlarvo',
    'n4yi8o',
    'wrr7ix',
    'h3wbqh',
    '3qflb4',
  ],
  linkedin: 'https://www.linkedin.com/company/trustpad/',
  duneQueries: null,
  blog: 'https://trustpad.medium.com/',
  github: null,
  telegram: 'https://t.me/TrustPad',
  twitter: 'https://twitter.com/TrustPad',
  url: 'https://trustpad.io/',
} satisfies AdapterProject
