import { AdapterProject } from '../types'

export default {
  name: 'epPlex',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'ccemio',
  description: 'Empowering a new frontier of Solana NFT use-cases with ephemeral epNFTs',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.epplex.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
