import { AdapterProject } from '../types'

export default {
  name: 'Catapulta',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '1pqp11',
  description: 'Catapulta is a plug-n-play, multi-chain smart contracts platform for Web3 teams.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/catapulta_sh',
  url: 'https://catapulta.sh/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
