import { AdapterProject } from '../types'

export default {
  name: 'OBJECTS',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '2wq780',
  description: 'OBJECTS is creating a personalized ecosystem for making any object, anywhere. ',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
