import { AdapterProject } from '../types'

export default {
  name: 'Selfie.Live',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'ygcyqn',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/Selfiedotlive',
  url: 'https://www.selfie.live/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
