import { AdapterProject } from '../types'

export default {
  name: 'Everyname',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '2i6tkv',
  description:
    'Everyname is a provider of an advanced protocol for retrieving info from any blockchain name registry.',
  discord: null,
  investors: [
    '1wfwc9',
    'x3ijol',
    'fyqab6',
    '1b31w8',
    '3a4l8c',
    'x7ggmz',
    '7i9j5w',
    '0ktyar',
    'enjekr',
    '7ovkfo',
    'mebhr4',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.everyname.xyz/',
} satisfies AdapterProject
