import { AdapterProject } from '../types'

export default {
  name: 'QRL',
  ninja: null,
  subcategories: null,
  chain: 'NATIVE',
  category: 'NOT_DEPIN',
  token: 'QRL',
  coinGeckoID: 'quantum-resistant-ledger',
  id: 'qc35tq',
  description: 'QRL: Post-quantum secure value store and decentralized communication.',
  discord: '357604137204056065',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/qrl/about/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@QRL',
  github: 'https://github.com/topics/qrl',
  telegram: null,
  twitter: 'https://twitter.com/QRLedger',
  url: 'https://www.theqrl.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
