import { AdapterProject } from '../types'

export default {
  name: 'Eclipse',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'dgqlyo',
  description:
    "Eclipse is Ethereum's fastest L2, powered by the Solana Virtual Machine. Eclipse makes it possible to build applications that can coordinate masses of people and scale with any developer’s needs.",
  investors: [
    'idlbd7',
    'nxop7l',
    '4l8mmr',
    'hqx0t6',
    'wldl30',
    'bxcu1r',
    'bfs2r3',
    'n0g582',
    'cznutg',
    '870le2',
    'b04x9g',
    'tqh3bl',
    '8agdnp',
    '7vs71r',
    'rgrylg',
    'kr30sy',
    'n0wdkb',
    'oc50nt',
    'due5zk',
    'qr2jg3',
  ],
  duneQueries: null,
} satisfies AdapterProject
