import { AdapterProject } from '../types'

export default {
  name: 'Fitcentive',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'jvwxi0',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/xnscloud',
  url: null,
  verified: false,
  fundraises: [],
} satisfies AdapterProject
