import { AdapterProject } from '../types'

export default {
  name: 'Lmao',
  ninja: 'vkurup.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '4sx681',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/lmaohq',
  url: 'https://lmao.fun/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
