import { AdapterProject } from '../types'

export default {
  name: 'Open Systems',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '4bsgjw',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/Opnsystm',
  url: 'https://opensystems.dev/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
