import { AdapterProject } from '../types'

export default {
  name: 'Audius',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'AUDIO',
  coingeckoId: 'audius',
  id: '4xwmst',
  description:
    'Audius is a decentralized, community-owned and artist-controlled music-sharing protocol. Audius provides a blockchain-based alternative to existing streaming platforms to help artists publish and monetize their work and distribute it directly to fans. It allows users to upload, share & listen while earning $AUDIO Token Rewards.',
  discord: 'https://discord.com/invite/audius',
  investors: [
    'buime9',
    'weiz7n',
    'mrgeec',
    'hbpmm3',
    'wqn9ms',
    'j8cr7e',
    '73opsz',
    'zaf9xh',
    'm4su31',
    'hm8wrp',
    'a3mqq8',
    'j7hgx5',
    '5h9mpc',
    'safmd6',
    'u3ke67',
    '3krjgm',
    'rwhpsx',
    '7tpa9b',
    'vameup',
    'onlub6',
    'v2y03d',
    'z723wt',
    'n580br',
    'dd123i',
    '2g0699',
    'eqqdvr',
    'ozeg73',
    'vcdl43',
    'uw2lru',
    'z8j32q',
    'v35xwk',
    'nbdtow',
    '0y7rv5',
    'dcqdyn',
    'ixxo16',
  ],
  linkedin: 'https://www.linkedin.com/company/audius-project/',
  duneQueries: null,
  blog: 'https://blog.audius.co/',
  github: null,
  telegram: 'https://t.me/audius',
  twitter: 'https://twitter.com/audius',
  url: 'https://audius.co/',
} satisfies AdapterProject
