import { AdapterProject } from '../types'

export default {
  name: 'Corcel',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: '1azjuz',
  description: 'AI chat powered by Bittensor',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://app.corcel.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
