import { AdapterProject } from '../types'

export default {
  name: 'Corcel',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: '1azjuz',
  description: 'AI chat powered by Bittensor',
  discord: '1176162686833270885',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://app.corcel.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
