import { AdapterProject } from '../types'

export default {
  name: 'Blockless',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: 'BLS',
  coinGeckoID: 'blockless',
  id: '4tmf6y',
  description: 'Blockless is a customizable execution layer for decentralized serverless apps.',
  discord: '929539044742938634',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/blockless',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/blocklessnetwork',
  telegram: 'https://t.me/blocklessofficial',
  twitter: 'https://x.com/theblockless',
  url: 'https://blockless.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
