import { AdapterProject } from '../types'

export default {
  name: 'Blockless',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: 'BLS',
  coingeckoId: 'blockless',
  id: '4tmf6y',
  description: 'Blockless is a customizable execution layer for decentralized serverless apps.',
  discord: null,
  investors: [
    'ympohv',
    'bxcu1r',
    '89glxu',
    '07pxi6',
    'agwzs7',
    'vjpj24',
    'pxvz0k',
    '8dhvoo',
    'rewcp7',
  ],
  linkedin: 'http://www.linkedin.com/company/blockless',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/blocklessnetwork',
  telegram: 'https://t.me/blocklessofficial',
  twitter: 'https://x.com/theblockless',
  url: 'https://blockless.network/',
  verified: false,
} satisfies AdapterProject
