import { AdapterProject } from '../types'

export default {
  name: 'Rumbo',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'rdjrke',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/RumboLabs',
  url: 'https://www.rumbo.so/en',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
