import { AdapterProject } from '../types'

export default {
  name: 'SoulAI',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '8qfgmf',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@SoulAiOfficial',
  github: null,
  telegram: null,
  twitter: 'https://x.com/soulailabs',
  url: 'https://soulai.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
