import { AdapterProject } from '../types'

export default {
  name: 'Myna',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coingeckoId: null,
  id: 'wqoxyk',
  description:
    'Myna is a platform built by collectors, for collectors, that empowers goods to be traded beyond their physical form.',
  discord: null,
  investors: [
    '47vy1z',
    'dczq0j',
    'ltitbn',
    'ksmmyi',
    'cnjnvc',
    'cd6uvj',
    '6vs8gm',
    '3x72a9',
    'vlqjau',
    'mxcxrg',
    'y0xi06',
    '8agdnp',
    '97i1ol',
    'pgoyl5',
    'v6xlk7',
  ],
  linkedin: 'https://www.linkedin.com/company/mynaswap/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/mynaswap',
  url: 'https://www.myna.co/',
  verified: false,
} satisfies AdapterProject
