import { AdapterProject } from '../types'

export default {
  name: 'Aleo',
  ninja: 'ZZ',
  subcategories: 'L1/L2',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'y5j1bu',
  description: "Aleo is a privacy-first Layer-1 blockchain that's zero-knowledge by design.",
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/AleoHQ',
  url: 'https://aleo.org/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
