import { AdapterProject } from '../types'

export default {
  name: 'NGRAVE',
  ninja: null,
  subcategories: 'Wallet',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '4tlww3',
  description: 'NGRAVE is a blockchain company. Ngrave Zero is their air-gapped hardware wallet.',
  discord: '918179581201096765',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/ngrave/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ngraveio',
  telegram: null,
  twitter: 'https://twitter.com/ngrave_official',
  url: 'https://www.ngrave.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
