import { AdapterProject } from '../types'

export default {
  name: 'NGRAVE',
  ninja: null,
  subcategories: 'Wallet',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '4tlww3',
  description: 'NGRAVE is a blockchain company. Ngrave Zero is their air-gapped hardware wallet.',
  discord: '918179581201096765',
  investors: [
    'pbunpe',
    'mrgeec',
    'zr4o5l',
    'r2lof0',
    'lhpass',
    'tzyxtr',
    'n73vnt',
    'k9u90q',
    'xnftxc',
    'pyukl2',
    '2wn9ev',
  ],
  linkedin: 'https://www.linkedin.com/company/ngrave/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ngraveio',
  telegram: null,
  twitter: 'https://twitter.com/ngrave_official',
  url: 'https://www.ngrave.io/',
  verified: false,
} satisfies AdapterProject
