import { AdapterProject } from '../types'

export default {
  name: 'GoQii',
  chain: null,
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: 'tkkrfm',
  description:
    'GOQii is headquartered in California with offices in Mumbai and Shenzhen. It is dedicated to enabling a permanent shift to a healthier lifestyle with the combination of advanced wearable technology, the world’s leading experts, coaches and karma. GOQii focuses on sustained engagement & goal reinforcement and offers a complete ecosystem as a single integrated solution, which is a powerful combination of technology and human connection. GOQii is a collaboration of some of the world’s leading experts and an amazing management team who are driven by a passion for healthy sustainable living, and who believe that all of us contain boundless potential. GOQii’s goal is to enable millions of people across the world to “be the force” by helping them unleash their untapped potential.',
  investors: [
    'jt1491',
    'xxlxhb',
    'h0wvko',
    'xv7xuz',
    '5vpxbp',
    'gjt0lb',
    'bz2cg2',
    'pnenck',
    'egkgd5',
    'lpvwf1',
    '8xisag',
    'm745wj',
    'fjd1uy',
    '46w9xn',
    'd5yu3p',
    'fygzvo',
    'dfcg6x',
    'e7wtgl',
    '44e83n',
    'nlqu6w',
    'i88831',
    '1ehkky',
    'bqhtyc',
    'd8l3f0',
    'ycxt5s',
    'lcnm5k',
    'ia1dup',
    'glao82',
    '3gph14',
    'mrwi8z',
    '1qkrxo',
    '5w0u65',
    'pw9k7i',
    '2z0nw5',
    'g5egk8',
    'uj1qaf',
    'mzct2x',
    'in8thm',
    'n2ixy9',
    'i25bf7',
    'bros3l',
    'y7zual',
    '38t6wi',
    'aiiiye',
    'l8m9rh',
    'g2uuo0',
    'qmb9za',
    'r7ef2i',
    'tmyvo7',
    'r3tuby',
    'yzkp63',
  ],
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/GOQii',
  url: 'https://goqii.com/in-en',
} satisfies AdapterProject
