import { AdapterProject } from '../types'

export default {
  name: 'Mapmetrics',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: 'SOLANA',
  category: 'MOBILITY',
  token: 'MMAPS',
  coinGeckoID: 'mapmetrics',
  id: 'lp6ty8',
  description: 'Mapmetrics is a web3 navigation app that rewards users with tokens and NFTs.',
  discord: '900389466781401098',
  investors: [],
  linkedin: 'https://nl.linkedin.com/company/mapmetrics',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/MobileRoboticsSkoltech/map-metrics',
  telegram: null,
  twitter: 'https://twitter.com/MapMetrics',
  url: 'https://mapmetrics.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
