import { AdapterProject } from '../types'

export default {
  name: 'DA AGE',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'sz3x59',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/DA_AGE_EN',
  url: 'https://www.da-age.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
