import { AdapterProject } from '../types'

export default {
  name: 'Leap',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: null,
  coingeckoId: null,
  id: '3w2wtc',
  description:
    'Leap is the leading global platform for generating new value from grid-connected resources and devices through integration with energy markets.',
  discord: null,
  investors: [
    'kn9vw9',
    '4zunln',
    'z29ewp',
    'spcuji',
    'p296oy',
    'z7brmm',
    'qtus0d',
    'ky6ou4',
    'hm6c6t',
    'bgl0oz',
    'hpcwz5',
    '8kjayp',
    's0jfmj',
    'jskx0k',
    '7px1kd',
    'gkv33p',
    'endttv',
    'uyrjui',
    'bfsmqk',
    'vuz4in',
    'tt96oi',
  ],
  linkedin: 'https://www.linkedin.com/company/18116834/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.leap.energy/blog',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/leapdex',
  url: 'https://www.leap.energy/',
} satisfies AdapterProject
