import { AdapterProject } from '../types'

export default {
  name: 'Hal',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '686w74',
  description: 'Hal is a chatbot built on BitTensor.',
  discord: '1110297556606533744',
  investors: [],
  linkedin: 'https://linkedin.com/company/vercel',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://chatwithhal.vercel.app/platforms/telegram',
  twitter: 'https://x.com/chatwithhal',
  url: 'https://chatwithhal.vercel.app/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
