import { AdapterProject } from '../types'

export default {
  name: 'CroPo',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'khpbec',
  description: 'CroPo collects global data, offers value to participants.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/cropo_data',
  url: 'https://www.cropo.network/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
