import { AdapterProject } from '../types'

export default {
  name: 'RedStone',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Oracle',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: 'REDSTONE',
  coinGeckoID: 'redstone',
  id: 'ap3amn',
  description:
    'RedStone Finance is a decentralized Oracle solution that aims to provide reliable and up-to-date data feeds for dApps and smart contracts across various Layer 1 and Layer 2 blockchains.',
  discord: null,
  investors: [
    'bspyld',
    '4j4oj3',
    'cyv0j9',
    'hhudw8',
    '5b7spr',
    'te4xtz',
    '73opsz',
    'fadhn8',
    'kaftnr',
    'maid89',
    'sknhsa',
    'ia3tqb',
    'ifb7yv',
    'zk01ag',
    'rp0ik4',
    'ujw2s3',
    'q9qqsj',
    'kjm7ph',
    'gfrejr',
    'xgzede',
    'vt618a',
    'yo6dj6',
    'nym997',
    'wo10nx',
    '9e1gk4',
    'pu3yyr',
    '3bchmx',
    'ffngjj',
  ],
  linkedin: 'https://www.linkedin.com/company/redstone-finance/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/redstone-finance',
  telegram: 'https://t.me/redstonefinance/',
  twitter: 'https://twitter.com/redstone_defi',
  url: 'https://redstone.finance/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://www.prnewswire.com/news-releases/redstone-raises-525k-in-first-round-of-funding-to-expand-its-market-leading-next-generation-decentralized-oracle-platform-301332129.html',
    },
    {
      roundType: 'Seed',
      url: 'https://www.coindesk.com/business/2022/08/29/defi-platform-redstone-raises-nearly-7m-to-improve-connectivity-between-blockchains-real-world-data/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
