import { AdapterProject } from '../types'

export default {
  name: 'RedStone',
  chain: null,
  category: 'OTHER',
  token: 'REDSTONE',
  coingeckoId: 'redstone',
  id: 'ap3amn',
  description:
    'RedStone is an Oracle that delivers frequently updated, reliable, and diverse data feeds for your dApp and smart contracts on multiple L1s & L2s.',
  investors: [
    'bspyld',
    '4j4oj3',
    'cyv0j9',
    'hhudw8',
    '5b7spr',
    'te4xtz',
    '73opsz',
    'fadhn8',
    'kaftnr',
    'maid89',
    'sknhsa',
    'ia3tqb',
    'ifb7yv',
    'zk01ag',
    'rp0ik4',
    'ujw2s3',
    'q9qqsj',
    'kjm7ph',
    'gfrejr',
    'xgzede',
    'vt618a',
    'yo6dj6',
    'nym997',
    'wo10nx',
    '0nje2l',
    'pu3yyr',
    '3bchmx',
    'ffngjj',
    'nzxtym',
  ],
  duneQueries: null,
  blog: null,
  github: 'https://github.com/redstone-finance',
  telegram: 'https://t.me/redstonefinance/',
  twitter: 'https://twitter.com/redstone_defi',
} satisfies AdapterProject
