import { AdapterProject } from '../types'

export default {
  name: 'FluxBeam',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 't5hmj6',
  description: 'FluxBeam is a Next Generation Solana DEX.',
  discord: '1175135061755056159',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/solanalabs',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://solana.com/news',
  github: 'https://solana.com/github',
  telegram: 'https://solana.com/telegram',
  twitter: 'https://solana.com/discord',
  url: 'https://fluxbeam.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
