import { AdapterProject } from '../types'

export default {
  name: 'Multiverse',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'AI',
  coinGeckoID: 'multiverse',
  id: 'wsmj41',
  description: 'Multiverse.ai is a distributed marketplace for making immersive AI.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/multiverse_labs',
  url: 'https://www.multiverse.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
