import { AdapterProject } from '../types'

export default {
  name: 'MEVFree',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'MEVFREE',
  coinGeckoID: 'mevfree',
  id: '8sxorc',
  description: 'MEVFree: Platform for crypto traders with tools and services to maximize profits.',
  discord: '1011294496123789322',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/mevfree',
  telegram: 'https://t.me/MevFree',
  twitter: 'https://twitter.com/mevfree',
  url: 'https://mevfree.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
