import { AdapterProject } from '../types'

export default {
  name: 'BitVPN',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'VPN',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'rjoblf',
  description: 'BitVPN is a decentralized VPN service on TOP Network.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Bitvpn1',
  url: 'https://www.bitvpn.net/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
