import { AdapterProject } from '../types'

export default {
  name: 'Go!',
  ninja: null,
  subcategories: 'Health',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '4h5jhz',
  description: 'Go! is a blockchain powering universal basic services.',
  discord: '875930739194093618',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/gobyhealthhero',
  twitter: 'https://twitter.com/GoHealthHero',
  url: 'https://t.co/QiGg27OEIj',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
