import { AdapterProject } from '../types'

export default {
  name: 'AhoyDAO',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'cqpqpq',
  description: 'AhoyDAO is a peer-to-peer ecosystem for the marine industry ownership economy.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/ahoy-/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ahoy-cli/ahoy',
  telegram: null,
  twitter: 'https://twitter.com/ahoy_dao',
  url: 'https://www.ahoy.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
