import { AdapterProject } from '../types'

export default {
  name: 'Aurora',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'AURORA',
  coingeckoId: 'aurora-near',
  id: 'tfu536',
  description:
    'Aurora is a performant, scalable, and carbon neutral solution that executes Ethereum contracts on the NEAR blockchain.',
  discord: 'https://discord.com/invite/dEFJBz8HQV',
  investors: [
    'b8gebp',
    '1zgufc',
    '4bc5rd',
    'h97beq',
    'ubwov4',
    '5tj4jx',
    'lrxdc8',
    'z6cdtc',
    '4x7qfo',
    'lsc0yi',
    'bvyx97',
    'kjm7ph',
    'smqwtv',
    'ozeg73',
    '19djg3',
    'haytnw',
    'pu3yyr',
    '44u6gg',
  ],
  linkedin: 'http://www.linkedin.com/company/aurora-is-near',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/aurora-platform',
  github: 'https://github.com/aurora-is-near',
  telegram: 'https://t.me/auroraisnear',
  twitter: 'https://twitter.com/auroraisnear',
  url: 'https://aurora.dev/',
} satisfies AdapterProject
