import { AdapterProject } from '../types'

export default {
  name: 'Ethstorage',
  ninja: null,
  subcategories: 'L1/L2',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '2kn4hu',
  description: 'Ethstorage is a cost-effective Layer 2 storage rollup solution on Ethereum.',
  discord: '1040111910802182186',
  investors: [
    '0bp83l',
    '4huuqd',
    'r54jbx',
    'bnzukt',
    'uktppp',
    '6c0yfx',
    'geps91',
    'i1vs03',
    '7zxuth',
    '7xtp3e',
    'pu3yyr',
    'm5cayq',
    'r57gpz',
    'mo34ru',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://ethstorage.medium.com/',
  github: 'https://github.com/ethstorage/',
  telegram: 'https://t.me/ethstorage',
  twitter: 'https://twitter.com/EthStorage',
  url: 'https://eth-store.w3eth.io/',
  verified: false,
} satisfies AdapterProject
