import { AdapterProject } from '../types'

export default {
  name: 'stateless',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '92w9o1',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/deep-state',
  github: 'https://github.com/stateless-solutions',
  telegram: null,
  twitter: 'https://x.com/statelessapi',
  url: 'https://www.stateless.solutions/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
