import { AdapterProject } from '../types'

export default {
  name: 'Centrifuge',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'CFG',
  coingeckoId: 'centrifuge',
  id: 'cosgc8',
  description: 'Decentralized OS for global financial supply chain, enabling data ownership.',
  investors: [
    '6pb6ea',
    '1ifr28',
    'ywekdu',
    'xmw0ev',
    '8nclhv',
    'ykzwbk',
    '7oqynx',
    '1vifzd',
    'jo973z',
    'vzue8e',
    'bxcu1r',
    '73opsz',
    'cm381r',
    'rwthif',
    'wweijf',
    '4x7qfo',
    'mywjsu',
    'e338ka',
    'ah5qcu',
    '1b7u42',
    '44e83n',
    'yoijyl',
    '5vzkab',
    'i1x9du',
    'hmfg3c',
    'kswqei',
    'dd123i',
    'juagep',
    'lgw9c6',
    '6tv4o8',
    'sz5x0j',
    'eyy236',
    '6r6q3d',
    'tnixm0',
    'h25e6r',
    'z0wsaf',
    'd0q6hi',
    'uita3x',
    'p3lgat',
    'gduv1m',
  ],
  duneQueries: null,
  blog: 'https://medium.com/centrifuge',
  github: 'https://github.com/centrifuge/',
  telegram: 'https://t.me/centrifuge_chat',
  twitter: 'https://twitter.com/centrifuge',
} satisfies AdapterProject
