import { AdapterProject } from '../types'

export default {
  name: 'Centrifuge',
  ninja: null,
  subcategories: 'DeFi',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'CFG',
  coinGeckoID: 'centrifuge',
  id: 'cosgc8',
  description: 'Decentralized OS for global financial supply chain, enabling data ownership.',
  discord: '805795848432779315',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/centrifugehq',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/centrifuge',
  github: 'https://github.com/centrifuge/',
  telegram: 'https://t.me/centrifuge_chat',
  twitter: 'https://twitter.com/centrifuge',
  url: 'https://centrifuge.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
