import { AdapterProject } from '../types'

export default {
  name: 'SALT',
  ninja: 'vkurup.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'p2f3eh',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
