import { AdapterProject } from '../types'

export default {
  name: 'Shadow',
  ninja: 'ZZ',
  subcategories: 'Storage',
  chain: 'SOLANA',
  category: 'COMPUTE',
  token: 'SHDW',
  coinGeckoID: 'genesysgo-shadow',
  id: 'p01o2s',
  description: 'GenesysGo is a decentralized object storage platform for Web3 builders.',
  discord: '830127596355190804',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/GenesysGo/',
  telegram: null,
  twitter: 'https://twitter.com/genesysgo',
  url: 'https://www.shdwdrive.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
