import { AdapterProject } from '../types'

export default {
  name: 'OXIO',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'q56fbx',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/oxio_com',
  url: 'https://oxio.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
