import { AdapterProject } from '../types'

export default {
  name: 'CIRUS',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'CIRUS',
  coinGeckoID: 'cirus',
  id: 'he3mau',
  description: 'CIRUS: Control data, monetize through blockchain.',
  discord: '858103637023391746',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/cirus-foundation',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/the-cirus-foundation',
  github: null,
  telegram: 'https://en.telghub.com/content?id=16359',
  twitter: 'http://www.twitter.com/Cirusfoundation',
  url: 'https://www.cirus.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
