import { AdapterProject } from '../types'

export default {
  name: 'CIRUS',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'CIRUS',
  coingeckoId: 'cirus',
  id: 'he3mau',
  description: 'CIRUS: Control data, monetize through blockchain.',
  investors: [
    'xmw0ev',
    'oaw1ui',
    'xx442f',
    'qxuz9y',
    '5qx1w8',
    '97h38q',
    'e9qwvr',
    '1kxhn8',
    '9p60sa',
    'uksen6',
    'e97n10',
    'tdw5kr',
    'bt1i9c',
  ],
  duneQueries: null,
  blog: 'https://medium.com/the-cirus-foundation',
  github: null,
  telegram: 'https://en.telghub.com/content?id=16359',
  twitter: 'http://www.twitter.com/Cirusfoundation',
  url: 'https://www.cirusfoundation.com/',
} satisfies AdapterProject
