import { AdapterProject } from '../types'

export default {
  name: 'CIRUS',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'CIRUS',
  coinGeckoID: 'cirus',
  id: 'he3mau',
  description: 'CIRUS: Control data, monetize through blockchain.',
  discord: null,
  investors: [
    'xmw0ev',
    'oaw1ui',
    'xx442f',
    'qxuz9y',
    '5qx1w8',
    '97h38q',
    'e9qwvr',
    '1kxhn8',
    '9p60sa',
    'uksen6',
    'e97n10',
    'tdw5kr',
    'bt1i9c',
  ],
  linkedin: 'http://www.linkedin.com/company/cirus-foundation',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/the-cirus-foundation',
  github: null,
  telegram: 'https://en.telghub.com/content?id=16359',
  twitter: 'http://www.twitter.com/Cirusfoundation',
  url: 'https://www.cirusfoundation.com/',
  verified: false,
} satisfies AdapterProject
