import { AdapterProject } from '../types'

export default {
  name: 'StepN',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'GMT',
  coingeckoId: 'stepn',
  id: '9ptjw7',
  description:
    'STEPN is a Web3 lifestyle app with inbuilt Game-Fi and Social-Fi elements. Players can make handsome tokens earnt though walking, jogging or running. In the game a player can burn game tokens to level up their sneakers, make more sneakers, upgrade in-game gems, pay for repairs, and pay for online marathon participation. At max level, players can earn governance tokens, which enables the player to determine the distribution of the game’s profit.',
  discord: 'https://discord.com/invite/stepn',
  investors: [
    'hol96b',
    '7ygqh2',
    'go7fr1',
    'r000x8',
    'mrgeec',
    'ylo81y',
    't76awu',
    'ifb7yv',
    '2pp0xp',
    'kjm7ph',
    '80qehd',
    'd85f6i',
    'k9u90q',
    'n47r11',
    '7u9ixq',
    'igv2a1',
    'ksae6d',
    'emg882',
    'tlb60n',
    'xvfwxn',
    'pyukl2',
    'qoijyy',
    'nwl5v7',
    'ixxo16',
    'xhnczo',
    'urug6u',
  ],
  linkedin: 'https://www.linkedin.com/company/stepn-by-find-satoshi-lab/',
  duneQueries: null,
  blog: 'https://stepnofficial.medium.com/',
  github: null,
  telegram: 'https://t.me/STEPNofficial',
  twitter: 'https://twitter.com/Stepnofficial',
  url: 'https://www.stepn.com/',
} satisfies AdapterProject
