import { AdapterProject } from '../types'

export default {
  name: 'Cryptomate',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'h2kze5',
  description: 'Cryptomate is a decentralized ecosystem of interactive crypto APIs.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/crypto-mate/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@CryptoMateLATAM',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/CryptoMateLatam',
  url: 'https://cryptomate.me/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
