import { AdapterProject } from '../types'

export default {
  name: 'Cryptomate',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'h2kze5',
  description: 'Cryptomate is a decentralized ecosystem of interactive crypto APIs.',
  discord: null,
  investors: [
    'h09snm',
    '92vkcn',
    'ajzzhi',
    'dc1d3b',
    'wln03g',
    'nxzb7m',
    'b1i2hy',
    '6od4bx',
    'g0a0pq',
  ],
  linkedin: 'https://www.linkedin.com/company/crypto-mate/',
  duneQueries: null,
  blog: 'https://medium.com/@CryptoMateLATAM',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/CryptoMateLatam',
  url: 'https://cryptomate.me/',
} satisfies AdapterProject
