import { AdapterProject } from '../types'

export default {
  name: 'Helium',
  ninja: null,
  subcategories: 'Mobile',
  chain: 'SOLANA',
  category: 'WIRELESS',
  token: 'HNT',
  coinGeckoID: 'helium',
  id: '5bm99m',
  description:
    'Helium is a decentralized network of networks with Mobile, IoT, & other subnetworks.',
  discord: '404106811252408320',
  investors: [
    'd40or5',
    '4bc5rd',
    '2ybws5',
    'xmw0ev',
    'm7a80m',
    'fyqab6',
    'wqn9ms',
    'suthoi',
    'r5sj96',
    'ylo81y',
    'jefoou',
    'ud4lcv',
    '7dddth',
    '19pz0d',
    '9oo0xs',
    '7zvtvf',
    'biweh7',
    'aoxz1k',
    'ihumfm',
    'q062d6',
    'yont93',
    'a3mqq8',
    '9n4okv',
    '16a7gt',
    'nc413e',
    's5s0ze',
    'hmfg3c',
    '80vsaw',
    'r4ood6',
    '3egzcf',
    '6gj1wa',
    '6ojf3f',
    '2g0699',
    'c9zewt',
    'msil0t',
    'wfcztc',
    'ozeg73',
    'tdywri',
    'b51i7e',
    'pixi8p',
    '80hqah',
    'xat35q',
    'ooq1d1',
    'k1e97y',
    'etf466',
    'vub62z',
    'rotj2h',
    '6dsjxk',
    'gbf0q8',
    'vff111',
    'vuz4in',
    'eseesx',
  ],
  linkedin: 'http://www.linkedin.com/company/heliumnetwork',
  duneQueries: {
    MINT: '2573591',
    REVENUE: '3410571',
    NET_REVENUE: '4628381',
    SUPPLY: '3043582',
    TIME_SERIES: '2944860',
    KEY_METRIC: '3223298',
    NODE_NUMBER: '3476664',
  },
  foundingYear: null,
  blog: 'https://blog.helium.com/',
  github: 'https://github.com/helium',
  telegram: null,
  twitter: 'https://x.com/helium',
  url: 'https://www.helium.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://techcrunch.com/2014/12/09/helium/',
    },
    {
      roundType: 'Series B',
      url: 'https://www.businesswire.com/news/home/20160425005330/en/Helium-Raises-20-Million-Series-B-Funding-Round-to-Accelerate-Smart-Sensing-Solutions',
    },
    {
      roundType: 'Series C',
      url: 'https://www.finsmes.com/2019/06/helium-raises-15m-in-series-c-funding.html',
    },
    {
      roundType: 'Series D',
      url: 'https://www.coindesk.com/business/2022/02/18/crypto-powered-wireless-network-helium-raises-200m-at-12b-valuation-report/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
