import { AdapterProject } from '../types'

export default {
  name: 'Astar',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ASTR',
  coingeckoId: 'astar',
  id: 'j764ic',
  description: 'Astar Network is a decentralized blockchain platform for Web3 innovations.',
  discord: null,
  investors: [
    'opiq98',
    'xmw0ev',
    'mrgeec',
    'xvqjcw',
    '73opsz',
    'ubwov4',
    'r2lof0',
    'tsm1o4',
    'xeklhm',
    'mywjsu',
    'v81ftp',
    'y5m26s',
    'nxzb7m',
    'vkntey',
    '4nrz2n',
    'i1x9du',
    'ujw2s3',
    'po8xe3',
    'tzyxtr',
    'j4k67v',
    'cwfc5j',
    'smqwtv',
    'tnkrzw',
    'tqh3bl',
    'h25e6r',
    'mu4hcu',
    'tdy2c2',
    'gduv1m',
    'pmwiko',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://astar.network/',
  verified: false,
} satisfies AdapterProject
