import { AdapterProject } from '../types'

export default {
  name: 'Astar',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'ASTR',
  coingeckoId: 'astar',
  id: 'j764ic',
  description:
    'Astar Network is a decentralized blockchain platform for Web3 innovations. It supports both EVM and WebAssembly environments, allowing for interoperability between them. Developers can earn incentives through the Build2Earn program by building decentralized apps. Astar aims to create a scalable network that powers a global vision for Web3. It runs in conjunction with Ethereum, Polkadot, and Cosmos, enabling the free flow of assets and communications between different ecosystems.',
  discord: null,
  investors: [
    'opiq98',
    'xmw0ev',
    'mrgeec',
    'xvqjcw',
    '73opsz',
    'ubwov4',
    'r2lof0',
    'tsm1o4',
    'xeklhm',
    'mywjsu',
    'v81ftp',
    'y5m26s',
    'nxzb7m',
    'vkntey',
    '4nrz2n',
    'i1x9du',
    'ujw2s3',
    'po8xe3',
    'tzyxtr',
    'j4k67v',
    'cwfc5j',
    'smqwtv',
    'tnkrzw',
    'tqh3bl',
    'h25e6r',
    'mu4hcu',
    'tdy2c2',
    'gduv1m',
    'pmwiko',
  ],
  linkedin: null,
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://astar.network/',
} satisfies AdapterProject
