import { AdapterProject } from '../types'

export default {
  name: 'Astar',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ASTR',
  coinGeckoID: 'astar',
  id: 'j764ic',
  description: 'Astar Network is a decentralized blockchain platform for Web3 innovations.',
  discord: '644182966574252073',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://astar.network/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
