import { AdapterProject } from '../types'

export default {
  name: 'Arweave',
  chain: 'NATIVE',
  category: 'COMPUTE',
  token: 'AR',
  coingeckoId: 'arweave',
  id: '0vks67',
  description: 'Arweave is a permanent and decentralized web inside an open ledger.',
  investors: [
    '07pxi6',
    '2g0699',
    'te4xtz',
    '5dsvsj',
    'bku3ew',
    'pu3yyr',
    'zaf9xh',
    'q9qqsj',
    'gun7y3',
    '73opsz',
    '26x5nn',
    '7c9znx',
    'vuz4in',
    '4l8mmr',
    'bspyld',
    'oi4yuk',
    'laupoy',
    'fnoivv',
    'xgzede',
    't105wi',
    '2ngx9z',
    'a1uyxq',
    'omaddb',
    '3krjgm',
    'oltsrb',
    'dcxpa9',
    '7jssah',
    'csfyvy',
    '5b7spr',
    '4j0lf4',
    'xr8iwa',
    '7os6rh',
    '1euupa',
    '4y5j9o',
    'pmco7y',
    'kk8zod',
    'wir0cg',
    '1oplf7',
    '97h38q',
    'iysh45',
    'o51tze',
    'ulvyo3',
    'oxjxo0',
    '4eyql6',
    '9kybya',
    'myul3m',
  ],
  duneQueries: null,
  cmcId: 5632,
} satisfies AdapterProject
