import { AdapterProject } from '../types'

export default {
  name: 'Arweave',
  ninja: null,
  subcategories: 'Storage',
  chain: 'NATIVE',
  category: 'COMPUTE',
  token: 'AR',
  coinGeckoID: 'arweave',
  id: '0vks67',
  description: 'Arweave is a permanent and decentralized web inside an open ledger.',
  discord: '829732720505520150',
  investors: [
    'bspyld',
    'd40or5',
    '7jssah',
    'csfyvy',
    '5b7spr',
    '4l8mmr',
    'gun7y3',
    '719svc',
    'te4xtz',
    'buo8ql',
    'oi4yuk',
    'xr8iwa',
    'iutpl6',
    'l70dye',
    '73opsz',
    'zaf9xh',
    'bd260g',
    'pmco7y',
    '7c9h68',
    'kk8zod',
    'laupoy',
    '5dsvsj',
    'wir0cg',
    'q6o5fc',
    '97h38q',
    'i1x9du',
    'eg9pp3',
    '3krjgm',
    'sn094y',
    'lwwz2r',
    'q9qqsj',
    'fnoivv',
    'xgzede',
    'ulvyo3',
    'oxjxo0',
    '2g0699',
    '07pxi6',
    't105wi',
    '4eyql6',
    'bku3ew',
    'pu3yyr',
    'oltsrb',
    '5p7vwo',
    'a1uyxq',
    'dcxpa9',
    'vuz4in',
    '9kybya',
    'myul3m',
  ],
  linkedin: 'http://www.linkedin.com/company/arweave',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://arweave.medium.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/ArweaveTeam',
  url: 'https://www.arweave.org/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.axios.com/2020/03/06/arweave-funding-permanent-data-storage-coronavirus',
    },
  ],
} satisfies AdapterProject
