import { AdapterProject } from '../types'

export default {
  name: 'Element',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: 'HYP',
  coinGeckoID: 'hyperstake',
  id: 'hz4cbu',
  description: 'Element is a Matrix-based end-to-end encrypted messenger and collaboration app.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/element-hq/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://element.io/blog/',
  github: 'https://github.com/vector-im',
  telegram: null,
  twitter: 'https://twitter.com/element_hq',
  url: 'https://element.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
