import { AdapterProject } from '../types'

export default {
  name: 'INT',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: 'NATIVE',
  category: 'BLOCKCHAIN_INFRA',
  token: 'INT',
  coinGeckoID: 'internet-node-token',
  id: 'c77cyh',
  description: 'INT is an IoT blockchain infrastructure, focusing on DePIN, IoT and RWA.',
  discord: '819034774252552262',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/int-chain',
  github: 'https://github.com/intfoundation',
  telegram: 'https://t.me/INTchain_officialtelegram',
  twitter: 'https://twitter.com/INTCHAIN',
  url: 'https://intchain.io/#/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
