import { AdapterProject } from '../types'

export default {
  name: 'Space & Time',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 'heeyow',
  description:
    'Space & Time is a decentralized replacement for blockchain indexing, database, data warehouse, and API servers.',
  discord: 'https://discord.com/invite/spaceandtimeDB',
  investors: [
    'opiq98',
    '7ygqh2',
    'yxetck',
    'dczq0j',
    '2tgqti',
    'ltitbn',
    '9jmx43',
    'e3ul8g',
    '5d2mm5',
    'v2rrnz',
    '9oo0xs',
    'vw2n89',
    '1lob3h',
    '074afi',
    'uktppp',
    'yx4w71',
    'yoijyl',
    'nxzb7m',
    'i1x9du',
    '0k831w',
    'q3nv50',
    '07pxi6',
    'xnftxc',
    '8agdnp',
    '1im0oz',
    'pu3yyr',
    '2abi82',
    'wu15kr',
    '3c4o3d',
  ],
  linkedin: 'https://www.linkedin.com/company/space-and-time-media/',
  duneQueries: null,
  blog: 'https://medium.com/@SpaceandTimeDB',
  github: 'https://github.com/spaceandtimelabs',
  telegram: 'https://t.me/spaceandtimedb',
  twitter: 'https://twitter.com/SpaceTimeMedia/',
  url: 'https://www.spaceandtime.io/',
} satisfies AdapterProject
