import { AdapterProject } from '../types'

export default {
  name: 'Space & Time',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 'heeyow',
  description:
    'Space & Time is a decentralized replacement for blockchain indexing, database, data warehouse, and API servers.',
  investors: [
    'opiq98',
    '7ygqh2',
    'yxetck',
    'dczq0j',
    '2tgqti',
    '9jmx43',
    'dsl20s',
    '5d2mm5',
    '5yy6cw',
    '9oo0xs',
    'vw2n89',
    '074afi',
    'uktppp',
    'yx4w71',
    'jqz0zw',
    'nxzb7m',
    'i1x9du',
    '0k831w',
    'q3nv50',
    '07pxi6',
    'xnftxc',
    '8agdnp',
    '1im0oz',
    'pu3yyr',
    '3c4o3d',
  ],
  duneQueries: null,
} satisfies AdapterProject
