import { AdapterProject } from '../types'

export default {
  name: 'Gateway Network',
  ninja: null,
  subcategories: 'Data',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'wwio88',
  description:
    'Gateway is a decentralized protocol for creating, consuming, and displaying verifiable credentials to serve as a basis for an interconnected web and portable reputation.',
  discord: 'https://discord.com/invite/tgt3KjcHGs',
  investors: [
    'hol96b',
    'ah8pl4',
    'm9q98s',
    'v3r6q3',
    'qvgc2n',
    'uwuv2v',
    'exjncl',
    'bmsbeq',
    '6cp8be',
    'btlofg',
    '6iy81o',
    '9e1gk4',
    'pgoyl5',
    'oj41s7',
    'xt0vj3',
  ],
  linkedin: 'https://www.linkedin.com/company/mygateway/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/Gateway-DAO',
  telegram: null,
  twitter: 'https://twitter.com/gateway_xyz',
  url: 'https://www.mygateway.xyz/',
  verified: false,
} satisfies AdapterProject
