import { AdapterProject } from '../types'

export default {
  name: 'AnchorZero',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 's3dnz2',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/anchorzero',
  url: 'https://www.anchorzero.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
