import { AdapterProject } from '../types'

export default {
  name: 'Vuzec',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'oogh3l',
  description: 'Vuzec is a decentralized Record Label.',
  discord: null,
  investors: [],
  linkedin: 'http://www.linkedin.com/company/vuzec',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://vuzecmx.medium.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/vuzecmx',
  url: 'https://www.vuzec.com/work',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
