import { AdapterProject } from '../types'

export default {
  name: 'Nina',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'gbaodd',
  description: 'Nina is a self-publishing protocol for musicians.',
  discord: '829052641408450571',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.ninaprotocol.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
