import { AdapterProject } from '../types'

export default {
  name: 'IX Swap',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'RWA',
  token: 'IXS',
  coinGeckoID: 'ix-swap',
  id: 'lgggcx',
  description: 'IX Swap is a Real World Asset (RWA) Tokenization Launchpad and DEX',
  discord: '899582968463495218',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.ixswap.io',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
