import { AdapterProject } from '../types'

export default {
  name: 'IX Swap',
  ninja: 'EV3 Sal',
  subcategories: 'RWA',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'lgggcx',
  description: 'RWA launchpad & DEX',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.ixswap.io',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
