import { AdapterProject } from '../types'

export default {
  name: 'Dione',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'ETHEREUM',
  category: 'ENERGY',
  token: 'DIONE',
  coinGeckoID: 'dione',
  id: 'ew04hq',
  description: 'Dione is a blockchain company developing renewable energy trading technology.',
  discord: '1193411758870761592',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/dione',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://github.com/DioneProtocol/Dione',
  github: null,
  telegram: 'https://t.me/DioneProtocol',
  twitter: 'https://twitter.com/firstone_DIONE',
  url: 'https://www.dioneprotocol.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
