import { AdapterProject } from '../types'

export default {
  name: 'TEA Project',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'xmaehz',
  description: 'TEA Project: decentralized cloud computing for serverless apps.',
  discord: '1042161438732603513',
  investors: [
    'h2tvqq',
    'y7zqs7',
    'caojlf',
    'nxzb7m',
    'vzqumt',
    'pwuofb',
    'ids90f',
    'slezx6',
    'xi1pkj',
    '7xtp3e',
    '640hn1',
    'o7xcsr',
    '3qflb4',
    'pcw959',
  ],
  linkedin: 'https://www.linkedin.com/company/tea-project/about/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://teaproject.medium.com/',
  github: null,
  telegram: 'https://t.me/teaprojectorg',
  twitter: 'https://twitter.com/teaprojectorg',
  url: 'https://teaproject.org/',
  verified: false,
  fundraisesUrls: [
    'https://teaproject.medium.com/the-tea-project-secures-second-funding-round-to-build-Web3 Capital-decentralized-computing-a2f2e1ea6476',
  ],
} satisfies AdapterProject
