import { AdapterProject } from '../types'

export default {
  name: 'Arctail',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'z931sb',
  description: 'Arctail is builduing a new infrastructure for on-chain finance.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.arctail.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
