import { AdapterProject } from '../types'

export default {
  name: 'Castora',
  ninja: '0x25052A4B28a35FfdBf2FaBA7DCCEB350e91b908F',
  subcategories: 'Prediction Market',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'khtlp3',
  description: 'Castora is a decentralized P2P prediction market built on Monad.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/castora_xyz?s=11',
  url: 'https://castora.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
