import { AdapterProject } from '../types'

export default {
  name: 'Neptune Mutual',
  ninja: null,
  subcategories: 'DeFi',
  chain: null,
  category: 'NOT_DEPIN',
  token: 'NPM',
  coinGeckoID: 'neptune-mutual',
  id: 'r4h43s',
  description: 'Neptune Mutual is the first parametric insurance protocol created for Ethereum.',
  discord: '846975061163900938',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/neptune-mutual',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://neptunemutual.com/blog/',
  github: 'https://github.com/neptune-mutual-blue',
  telegram: 'https://t.me/neptunemutual',
  twitter: 'https://twitter.com/neptunemutual',
  url: 'https://neptunemutual.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
