import { AdapterProject } from '../types'

export default {
  name: 'Neptune Mutual',
  ninja: null,
  subcategories: 'DeFi',
  chain: null,
  category: 'NOT_DEPIN',
  token: 'NPM',
  coingeckoId: 'neptune-mutual',
  id: 'r4h43s',
  description: 'Neptune Mutual is the first parametric insurance protocol created for Ethereum.',
  discord: 'https://discord.com/invite/2qMGTtJtnW',
  investors: [
    'o5kpgb',
    'gjt0lb',
    'g738qx',
    'bmaozl',
    'perhf5',
    'yyrgnc',
    'ypypyu',
    '73opsz',
    '4su8hb',
    'gpswp8',
    'yi5hs8',
    'qreqzv',
    'i98114',
    'mywjsu',
    'n5z0zx',
    'i1vs03',
    'rlo5x9',
    'mlhi9g',
    'v81ftp',
    'et88de',
    't7xkdd',
    'qqc9zd',
    '9tdi8p',
    'tzyxtr',
    'b04x9g',
    '7pnnyt',
    'smqwtv',
    '7ez4vw',
    'rk3esc',
    '6ob6ls',
    '7rf9rs',
    '5o347p',
    'tktadr',
    'y7hamj',
    'knhtue',
    'gy5k6a',
  ],
  linkedin: 'https://www.linkedin.com/company/neptune-mutual',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://neptunemutual.com/blog/',
  github: 'https://github.com/neptune-mutual-blue',
  telegram: 'https://t.me/neptunemutual',
  twitter: 'https://twitter.com/neptunemutual',
  url: 'https://neptunemutual.com/',
  verified: false,
} satisfies AdapterProject
