import { AdapterProject } from '../types'

export default {
  name: '3TV',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'jcp53v',
  description: '3TV.chat is a live-streaming app for creators and communities.',
  discord: '963065410050220052',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/3tv_chat',
  url: 'https://3tv.chat/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
