import { AdapterProject } from '../types'

export default {
  name: 'Aethir',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: 'ATH',
  coinGeckoID: 'aethir',
  id: 'oo2cn2',
  description: 'Aethir is a Scalable Decentralised Cloud Infrastructure (DCI) for Gaming and AI.',
  discord: '993758224438284291',
  investors: [
    'gjt0lb',
    '4l8mmr',
    'hqx0t6',
    'cnjnvc',
    'yx4w71',
    'nxzb7m',
    'rrtsc3',
    'rd2mzf',
    '5j0nni',
    '8rcqvw',
    'bah2fw',
    'm05wan',
    '9jfdo8',
    'lzpnns',
    'pcw959',
  ],
  linkedin: 'https://www.linkedin.com/company/aethir-limited',
  duneQueries: {
    NODE_NUMBER: '3541928',
  },
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/AethirCloud',
  url: 'https://www.aethir.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.prnewswire.com/news-releases/aethir-closes-150-million-valuation-pre-a-funding-round-to-scale-its-decentralized-cloud-infrastructure-301886287.html',
    },
  ],
  isApp: true,
} satisfies AdapterProject
