import { AdapterProject } from '../types'

export default {
  name: 'Aethir',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 'oo2cn2',
  description: 'Aethir enables real-time rendering in the Metaverse.',
  discord: null,
  investors: [
    'gjt0lb',
    '4l8mmr',
    'hqx0t6',
    'cnjnvc',
    'yx4w71',
    'nxzb7m',
    '870le2',
    'rd2mzf',
    '5j0nni',
    '8rcqvw',
    'bah2fw',
    'm05wan',
    '9jfdo8',
    'lzpnns',
    'pcw959',
  ],
  linkedin: 'https://www.linkedin.com/company/aethir-limited',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Aethir_',
  url: 'https://www.aethir.com/',
  verified: false,
} satisfies AdapterProject
