import { AdapterProject } from '../types'

export default {
  name: 'ChainML',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'ae73hb',
  description: 'ChainML is a decentralized compute network for AI and numerical applications.',
  discord: '1119245135620878388',
  investors: [
    '7ygqh2',
    '4bc5rd',
    '3t6j16',
    '2tgqti',
    'dsl20s',
    '5bnlru',
    'uwuv2v',
    'uktppp',
    'a3mqq8',
    'yoijyl',
    'nxzb7m',
    'sz5akr',
    'vkntey',
    's4jf02',
    'i1x9du',
    'tc6q3y',
    'po8xe3',
    '65epfb',
    'rgk0ot',
    'wu15kr',
    'p663q8',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/chainml_',
  url: 'https://www.chainml.net/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://twitter.com/theoriqai/status/1790090952637337852',
    },
    {
      roundType: 'Seed',
      url: 'https://www.theblock.co/post/173081/decentralized-machine-learning-protocol-chainml-raises-4m-led-by-iosg-ventures',
    },
  ],
  isApp: true,
} satisfies AdapterProject
