import { AdapterProject } from '../types'

export default {
  name: 'Render',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'RNDR',
  coingeckoId: 'render-token',
  id: 'drs2bu',
  description: 'Render is a decentralized rendering platform for next-gen media production.',
  investors: [
    '4vtk91',
    'buo8ql',
    'gb35ty',
    'b8m83j',
    '3e2yxp',
    'h58ujg',
    '7fua48',
    '2r6k0a',
    'p9j5in',
    '6aygdq',
    '2g0699',
    '07pxi6',
    'iz5sev',
    'emg882',
    'qg1fkp',
    'fjrjju',
    'p3lgat',
    '80bzm6',
  ],
  duneQueries: null,
} satisfies AdapterProject
