import { AdapterProject } from '../types'

export default {
  name: 'Render',
  ninja: null,
  subcategories: 'GPUs',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'RNDR',
  coinGeckoID: 'render-token',
  id: 'drs2bu',
  description: 'Render is a decentralized rendering platform for next-gen media production.',
  discord: '976195870825529354',
  investors: [
    'b5zojp',
    'wc0r1f',
    'zo7roo',
    'buo8ql',
    'r2lof0',
    'xqdbmz',
    'vkfbt5',
    'winl2g',
    'h58ujg',
    'ja06z4',
    'etiakl',
    '7c2xqy',
    '80vsaw',
    '2g0699',
    '07pxi6',
    'h7bj9w',
    'emg882',
    'tlb60n',
    '4e1ldf',
    'vrprdr',
    '6dsjxk',
    'natuqc',
    '58oane',
  ],
  linkedin: 'http://www.linkedin.com/company/render-network-foundation',
  duneQueries: {
    REVENUE: '3348331',
  },
  foundingYear: null,
  blog: 'https://medium.com/@rendernetwork',
  github: 'https://github.com/rendernetwork/',
  telegram: 'https://t.me/rendernetwork',
  twitter: 'https://twitter.com/rendernetwork',
  url: 'http://renderfoundation.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series D',
      url: 'https://www.prnewswire.com/news-releases/cloud-graphics-pioneer-otoy-announces-series-d-round-led-by-yuri-milner-245185301.html',
    },
    {
      roundType: 'Series F',
      url: 'https://www.theblock.co/post/128266/metaverse-infrastructure-startup-render-network-raises-30-million-in-token-round',
    },
  ],
} satisfies AdapterProject
