import { AdapterProject } from '../types'

export default {
  name: 'D3',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: '6y7ind',
  description:
    'D3 is a next-generation domains company building interoperable web2<>web3 domain names.',
  discord: null,
  investors: [
    '7job29',
    'h97beq',
    '9oo0xs',
    'fxmvug',
    '3wmu8j',
    'tf8yn4',
    'asmbxg',
    'huo2cs',
    'aowm9c',
    'lhs5s8',
    'wzua9l',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'http://www.linkedin.com/company/d3inc',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/d3corp',
  url: 'https://d3.inc/',
  verified: false,
} satisfies AdapterProject
