import { AdapterProject } from '../types'

export default {
  name: 'Crust',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'CRU',
  coingeckoId: 'crust-network',
  id: 'x2nise',
  iconUrl: null,
  description:
    'Crust Network is a decentralized cloud storage provider supporting multiple underlying storage protocols.',
  investors: [
    '07pxi6',
    '2tgqti',
    'jqz0zw',
    'pu3yyr',
    'wu15kr',
    'i1x9du',
    'ujw2s3',
    'xmw0ev',
    'tzyxtr',
    'gb35ty',
    'fnoivv',
    '52fjgj',
    'o7xcsr',
    '6ueww6',
    'h2tvqq',
    '0msybz',
    'ri09e0',
    'hxmvxz',
    'ebviw5',
    'n24ti7',
    'akokzi',
    'oplluy',
    'mtuezh',
    'j36zoh',
    '6cd1m3',
    'wsadn5',
    'nlvx3r',
    '4yr483',
    '935mux',
  ],
  cmcId: null,
} satisfies AdapterProject
