import { AdapterProject } from '../types'

export default {
  name: 'Fileverse',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'gtzdge',
  description:
    'On-chain people and communities deserve on-chain tools for private communication and collaboration.',
  discord: null,
  investors: [
    'hhudw8',
    '896jil',
    'ynh9fg',
    'd8ocj0',
    'b9dhtc',
    'rmj9ht',
    '6ln74n',
    '7hwz6f',
    'geps91',
    '5aftnd',
    'wohqmd',
    'thxgaw',
    'nkdgv1',
    'o7xcsr',
    'xtbe5p',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/fileverse',
  telegram: null,
  twitter: 'https://x.com/fileverse',
  url: 'https://fileverse.io/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.coindesk.com/business/2023/10/17/Web3 Capital-powered-file-management-app-raises-15m-to-offer-alternative-to-google/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
