import { AdapterProject } from '../types'

export default {
  name: 'Blackhat',
  ninja: null,
  subcategories: 'ML',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'BLKC',
  coinGeckoID: 'blackhat-coin',
  id: '3jgdnl',
  description: 'Blackhat cyber game: Players as DeFi protocos v AI hackerChatGPT.',
  discord: '822505689385533440',
  investors: [],
  linkedin: 'https://www.linkedin.com/groups/37658/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/BlackHatEvents',
  url: 'https://blackhatco.in/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
