import { AdapterProject } from '../types'

export default {
  name: 'Collar Protocol',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'qg080i',
  description: 'Collar Protocol is aliquidation-free borrowing solution.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.collarprotocol.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
