import { AdapterProject } from '../types'

export default {
  name: 'MODA',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'MODA',
  coingeckoId: 'moda-dao',
  id: 'qwsoln',
  description: 'MODA DAO empowers music industry with NFTs, licensing, and DeFi.',
  discord: 'https://discord.com/invite/gbm2ZNjGPK',
  investors: [
    'ycxcre',
    '8nclhv',
    'xgnbev',
    'mkgpcb',
    '6hezki',
    'pltz40',
    'j2izfv',
    'n0g582',
    'knw63n',
    '8akn04',
    'wrehju',
    'n4yi8o',
    'dd123i',
    'n7ldex',
    'rgk0ot',
    'vjpj24',
    'zejbn5',
    'thqjz1',
    'xolbff',
    'bt1i9c',
    'o7xcsr',
  ],
  linkedin: 'https://www.linkedin.com/company/moda-foundation/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/modadao',
  twitter: 'https://twitter.com/moda_dao',
  url: 'https://www.moda.audio/',
  verified: false,
} satisfies AdapterProject
