import { AdapterProject } from '../types'

export default {
  name: 'MODA',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'MODA',
  coinGeckoID: 'moda-dao',
  id: 'qwsoln',
  description: 'MODA DAO empowers music industry with NFTs, licensing, and DeFi.',
  discord: '808463591102873601',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/moda-foundation/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/modadao',
  twitter: 'https://twitter.com/moda_dao',
  url: 'https://www.moda.audio/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
