import { AdapterProject } from '../types'

export default {
  name: 'Indicio',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'm5wcp4',
  description:
    "Indicio.tech is a professional services firm specializing in decentralized identity architecture, engineering, and consultancy. They are also the creators of the Indicio Network & CardeaProject. The Indicio Network is the world's only globally available, professionally-managed, enterprise-grade network for decentralized identity. Cardea is a complete opensource ecosystem for the exchange of privacy-preserving digital credentials, a project in Linux Foundation Public Health (LFPH).",
  investors: [
    'uu9js5',
    'k9vfgv',
    'by8fus',
    'jhauap',
    'rin9a4',
    '71vhzo',
    'aeuug7',
    'ji05td',
    'omlxhk',
    '9n4okv',
    '4xreo2',
    'g2i6wt',
    '3gguux',
    'r5ofys',
    'lvg7zu',
    'l7vbx6',
    'jwwrd3',
  ],
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/indicioid?lang=en',
  url: 'https://indicio.tech/',
} satisfies AdapterProject
