import { AdapterProject } from '../types'

export default {
  name: 'Indicio',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'm5wcp4',
  description:
    'Indicio.tech is a professional services firm specializing in decentralized identity architecture, engineering, and consultancy.',
  discord: null,
  investors: [
    'uu9js5',
    'k9vfgv',
    'by8fus',
    'jhauap',
    'rin9a4',
    '71vhzo',
    'aeuug7',
    'ji05td',
    'omlxhk',
    '9n4okv',
    '4xreo2',
    'g2i6wt',
    '3gguux',
    'r5ofys',
    'lvg7zu',
    'l7vbx6',
    'jwwrd3',
  ],
  linkedin: 'https://www.linkedin.com/company/indiciotech/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/indicioid?lang=en',
  url: 'https://indicio.tech/',
  verified: false,
} satisfies AdapterProject
