import { AdapterProject } from '../types'

export default {
  name: 'dotmoovs',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'MOOV',
  coingeckoId: 'dotmoovs',
  id: 'lipfwr',
  description: 'Dotmoovs uses AI scoring & monetization through $MOOVs investment.',
  discord: null,
  investors: [
    'bp637k',
    'xmw0ev',
    'nmr0ay',
    'qxuz9y',
    'rlo5x9',
    'nqkr1o',
    'p21tot',
    'n73vnt',
    'k9u90q',
    'h9g1s5',
    'pyukl2',
  ],
  linkedin: 'http://www.linkedin.com/company/dotmoovs',
  duneQueries: null,
  blog: 'https://dotmoovs.medium.com/',
  github: 'https://github.com/dotmoovs',
  telegram: 'https://t.me/s/dotmoovs_announcements?before=1038',
  twitter: 'https://twitter.com/dotmoovs',
  url: 'https://dotmoovs.com/',
} satisfies AdapterProject
