import { AdapterProject } from '../types'

export default {
  name: 'Mobilian',
  ninja: null,
  subcategories: 'Auto',
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'diyark',
  description: 'Mobilian is a blockchain network empowering secure autonomous vehicles.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/mobiliancoin/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/mobiliancoin',
  twitter: 'https://twitter.com/MobilianCoin',
  url: 'https://mobiliancoin.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
