import { AdapterProject } from '../types'

export default {
  name: 'Metafi',
  ninja: null,
  subcategories: 'Gaming',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'cu6hqb',
  description:
    'Metafi enables embeded wallets, broadcast transactions, indexing on-chain events, and more for web3 game developers.',
  discord: null,
  investors: [
    'fue5t7',
    'rvqbxw',
    '18l8yx',
    '4jm919',
    '9wxc8s',
    '243kcn',
    '967a4z',
    'qa36jx',
    '84hmi4',
    'ljeztv',
    'smqwtv',
    'tdw5kr',
    'yv799p',
    'brmebh',
  ],
  linkedin: 'https://uk.linkedin.com/company/meta-fi',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/easify-network/a-brief-about-metafi-cf3f1736e930',
  github: 'https://github.com/metafiofficial',
  telegram: null,
  twitter: 'https://twitter.com/MetaFi_Official',
  url: 'https://www.metafi.org/',
  verified: false,
} satisfies AdapterProject
