import { AdapterProject } from '../types'

export default {
  name: 'Gelato',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'GEL',
  coinGeckoID: 'gelato',
  id: 'lvwe8x',
  description:
    'Gelato is a Rollup-as-a-Service platform that enables the deployment of enterprise-grade modular L2 and L3 chains integrated with Web3 services, automating smart contracts and gasless transactions while ensuring Ethereum-grade security.',
  discord: null,
  investors: [
    'hol96b',
    'ykzwbk',
    'wxcf8r',
    '04dk8s',
    'm6mz4i',
    '5tj4jx',
    '44e83n',
    '5aftnd',
    'a3mqq8',
    'l7sko2',
    'i1x9du',
    'oxjxo0',
    '5z7w9l',
    'gnhylz',
    '6f2cxt',
    'gmkv01',
    '3bchmx',
    'e2dh7y',
    'mwx1nm',
  ],
  linkedin: 'https://no.linkedin.com/company/gelato',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@gelatonetwork',
  github: 'https://github.com/gelatodigital',
  telegram: 'https://t.me/gelatonetwork',
  twitter: 'https://twitter.com/gelatonetwork',
  url: 'https://www.gelato.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://finance.yahoo.com/news/gelato-network-raises-1-2-140117420.html',
    },
    {
      roundType: 'Series A',
      url: 'https://www.coindesk.com/business/2021/09/30/gelato-raises-11m-as-smart-contract-automation-market-heats-up/',
    },
  ],
} satisfies AdapterProject
