import { AdapterProject } from '../types'

export default {
  name: 'Gelato',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'GEL',
  coingeckoId: 'gelato',
  id: 'lvwe8x',
  description: 'Gelato Network automates smart contract executions across EVM-based blockchains.',
  investors: [
    'hol96b',
    'ykzwbk',
    'wxcf8r',
    '04dk8s',
    'm6mz4i',
    '5tj4jx',
    '44e83n',
    '5aftnd',
    'a3mqq8',
    'l7sko2',
    'i1x9du',
    'oxjxo0',
    '5z7w9l',
    'gnhylz',
    '6f2cxt',
    'gmkv01',
    '3bchmx',
    'e2dh7y',
    'mwx1nm',
  ],
  duneQueries: null,
  blog: 'https://medium.com/@gelatonetwork',
  github: 'https://github.com/gelatodigital',
  telegram: 'https://t.me/gelatonetwork',
  twitter:
    'https://twitter.com/gelatonetwork?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://ops.gelato.network/',
} satisfies AdapterProject
