import { AdapterProject } from '../types'

export default {
  name: 'Telnyx',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '9a244u',
  description: 'Telnyx helps enterprise manages connectivity need from a single platform.',
  discord: null,
  investors: [
    'gmmhsu',
    'gg6rnf',
    'idrlmo',
    'jm7s76',
    '9btyj8',
    '1h28wi',
    'd2so5g',
    'u81z15',
    'n682xx',
    'a1uyxq',
  ],
  linkedin: 'https://www.linkedin.com/company/telnyx',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/telnyx',
  url: 'https://telnyx.com/',
  verified: false,
} satisfies AdapterProject
