import { AdapterProject } from '../types'

export default {
  name: 'Telnyx',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '9a244u',
  description: 'Telnyx helps enterprise manages connectivity need from a single platform.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/telnyx',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/telnyx',
  url: 'https://telnyx.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
