import { AdapterProject } from '../types'

export default {
  name: 'UBIQnet',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '7lu677',
  description: 'UBIQnet - decentralized computing with blockchain tech.',
  discord: '1079671303801425942',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/ubiqnet',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ubiqnet',
  telegram: null,
  twitter: 'https://twitter.com/UBIQ_net',
  url: 'https://ubiqnet.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
