import { AdapterProject } from '../types'

export default {
  name: 'OpenGradient',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'rf20bh',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/OpenGradient',
  url: 'https://opengradient.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
