import { AdapterProject } from '../types'

export default {
  name: 'Oz',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '79wj8l',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/OzProtocol',
  url: 'https://ozprotocol.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
