import { AdapterProject } from '../types'

export default {
  name: 'Everyworld',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'EVERY',
  coinGeckoID: 'everyworld',
  id: 'si0rd5',
  description:
    'Everyworld is a global content network that rewards users for their time and attention, transforming digital activity into rewards. Users can earn points through engagement, participate in drawings for payouts, and support environmental charities.',
  discord: null,
  investors: [
    '26x5nn',
    'gjt0lb',
    'q2goo9',
    '73opsz',
    '5tj4jx',
    'uktppp',
    'nlqu6w',
    'wvda7j',
    'ja2261',
    's4jf02',
    'i1x9du',
    'f0g01v',
    'rwhpsx',
    'lhs7r5',
    '07pxi6',
    'iedbk8',
    'emg882',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/JoinEveryworld',
  url: 'https://www.everyworld.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://twitter.com/JoinEveryworld/status/1771252264985915682',
    },
  ],
} satisfies AdapterProject
