import { AdapterProject } from '../types'

export default {
  name: 'Digital Gaia',
  ninja: 'ZZ',
  subcategories: 'Environmental, Data, Rewards',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'hq0zgu',
  description: 'Digital Gaia is a shared data and AI platform for planetary decision intelligence.',
  discord: null,
  investors: ['xcxzqk', '9jairy'],
  linkedin: 'http://www.linkedin.com/company/digital-gaia',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/_digitalgaia',
  url: 'https://www.digitalgaia.earth/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
