import { AdapterProject } from '../types'

export default {
  name: '4everland',
  ninja: 'ZZ',
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '0tmpgv',
  description:
    '4everland is a decentralized cloud provider integrating storage, computing, and networking resources.',
  discord: '852482727164117022',
  investors: [
    'hhudw8',
    'ympohv',
    'gun7y3',
    'sgvqqt',
    'lfbmt3',
    'mywjsu',
    '7hwz6f',
    'ldgrye',
    'e0v4rn',
    'po1oia',
    '8agdnp',
    'ti312b',
    '7ku2jz',
    'o7xcsr',
    'pvr738',
  ],
  linkedin: 'https://au.linkedin.com/company/4everlandorg',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/4everland_org',
  url: 'https://www.4everland.org/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://medium.com/4everland/4everland-has-raised-1-5-million-dollars-in-a-seed-round-435648b411ef',
    },
    {
      roundType: 'Seed',
      url: 'https://www.coinlive.com/news-flash/405451',
    },
  ],
  isApp: true,
} satisfies AdapterProject
