import { AdapterProject } from '../types'

export default {
  name: 'Banger',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '0c6a3p',
  description: 'Marketplace for buying and selling tweets.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/rawlodawgins',
  twitter: null,
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
