import { AdapterProject } from '../types'

export default {
  name: 'Network3',
  ninja: null,
  subcategories: 'VPN',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'a246lv',
  description: 'Network3 enhances network security and privacy through distributed nodes.',
  discord: '1073393648739307590',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@network3',
  github: null,
  telegram: 'https://t.me/network3official',
  twitter: 'https://twitter.com/network3_com',
  url: 'https://network3.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
