import { AdapterProject } from '../types'

export default {
  name: 'powdr labs',
  ninja: '0x4003408058d490FCD0A8b76925a412E6F39bc939',
  subcategories: 'ZK',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '2r5kuo',
  description: 'powdr is a modular compiler stack to build zkVMs.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/powdr_labs',
  url: 'https://www.powdr.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
