import { AdapterProject } from '../types'

export default {
  name: 'enqAI',
  ninja: 'Mahesh | Escape Velocity',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'vwcy0j',
  description: 'Decentralized & Uncensored AI',
  discord: '1079425803441426562',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.enqai.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
