import { AdapterProject } from '../types'

export default {
  name: '369 AI',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: '369',
  coinGeckoID: null,
  id: 'lkgvvp',
  description: '369 AI is a high-performance blockchain for AI applications.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/Three69AI',
  twitter: 'https://x.com/Three69AI',
  url: 'https://three69ai.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
