import { AdapterProject } from '../types'

export default {
  name: '369 AI',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: '369',
  coinGeckoID: null,
  id: 'lkgvvp',
  description: '369 AI is a high-performance blockchain for AI applications.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/Three69AI',
  twitter: 'https://twitter.com/Three69AI',
  url: 'https://three69.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
