import { AdapterProject } from '../types'

export default {
  name: 'All Stream AI',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'lvt033',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/AllStream_AI',
  url: 'https://www.allstream.ai/#/home',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
