import { AdapterProject } from '../types'

export default {
  name: 'ColdStack',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'CLS',
  coingeckoId: 'coldstack',
  id: 'dka3hq',
  description:
    'ColdStack: A unified API and billing solution for Filecoin, SIA, Arweave, and Storj.',
  investors: [
    'xnheko',
    'yxetck',
    'xmw0ev',
    'iqk4zz',
    'v9u6c9',
    'r2lof0',
    'lrxdc8',
    'rlo5x9',
    '5dsvsj',
    'o2fphw',
    'z2pfjb',
    'micofj',
    'k9u90q',
    'smqwtv',
    'r4wukp',
    'i2jpqr',
    '8z2gqj',
    'kw5h0p',
    'pyukl2',
    'yzjb8p',
    'eud02c',
    '52fjgj',
    'nwl5v7',
    'brmebh',
  ],
  duneQueries: null,
  blog: 'https://medium.com/coldstack',
  github: 'https://github.com/ColdStack-Network/',
  telegram: 'https://t.me/coldstackio',
  twitter: 'https://twitter.com/coldstack_io',
  url: 'https://coldstack.io/',
} satisfies AdapterProject
