import { AdapterProject } from '../types'

export default {
  name: 'Souq',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'hprfe1',
  description:
    'Souq is a blockchain company developing an NFT AMM aiming to revolutionize the trading dynamics of NFTs.',
  discord: 'https://discord.com/invite/clubsouq',
  investors: [
    'hw3u73',
    '7dhoqw',
    't76oo4',
    '54sc23',
    'qfad67',
    't5b3g5',
    'vnz62k',
    'aua9tf',
    '870le2',
    'hnd2e9',
    'pxyqjr',
    '9a34j1',
    'z3p06w',
    '7pu5nr',
    'molo3g',
    'rfnurr',
  ],
  linkedin: null,
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.souq.finance/',
} satisfies AdapterProject
