import { AdapterProject } from '../types'

export default {
  name: 'IOTY',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'zm7sou',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/Ioty_protocol',
  url: 'https://www.iotyprotocol.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
