import { AdapterProject } from '../types'

export default {
  name: 'Phaver',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'oumqih',
  description: 'Phaver: decentralized social app rewarding users with tokens for sharing content.',
  discord: 'https://discord.com/invite/phaver',
  investors: [
    'ujq536',
    '6nxw7d',
    'xent44',
    '779ffb',
    'xvqjcw',
    'r54jbx',
    '07ofjt',
    'uktppp',
    'zoshoo',
    '8agdnp',
    'ft3dw6',
    's3as6l',
    'otzp4l',
    'uzi60w',
  ],
  linkedin: 'https://fi.linkedin.com/company/phaver',
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/phaverapp?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://www.phaver.com/',
} satisfies AdapterProject
