import { AdapterProject } from '../types'

export default {
  name: 'Phaver',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'oumqih',
  description: 'Phaver: decentralized social app rewarding users with tokens for sharing content.',
  discord: '930833706460004402',
  investors: [],
  linkedin: 'https://fi.linkedin.com/company/phaver',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/phaverapp?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://www.phaver.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
