import { AdapterProject } from '../types'

export default {
  name: 'Energy Web',
  ninja: null,
  subcategories: null,
  chain: 'GNOSIS',
  category: 'ENERGY',
  token: 'EWT',
  coingeckoId: 'energy-web',
  id: 'tjcjjf',
  description:
    'The Energy Web Foundation fosters value creation in the energy sector by building and promoting an open, decentralized software infrastructure built around blockchain technology.',
  discord: null,
  investors: [
    'd3piby',
    '5bmg9o',
    'te4xtz',
    'lepbce',
    'mkgpcb',
    '91clzc',
    'u31dfa',
    'yont93',
    '0127i5',
    '76or7t',
    '63huxu',
    'iwjz17',
    'mm4b9e',
    '0fyly9',
    's9wgrj',
    'p3lgat',
    'd0s5nk',
    'id32lg',
    'puhefe',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.energyweb.org/',
} satisfies AdapterProject
