import { AdapterProject } from '../types'

export default {
  name: 'GTURBO',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '9stp66',
  description: 'GTURBO is a cloud computing infrastructure platform',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/gturbo_depin',
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
