import { AdapterProject } from '../types'

export default {
  name: 'Klever',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'xarvqb',
  description: 'A peer-to-peer network for everyone.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://klever.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
