import { AdapterProject } from '../types'

export default {
  name: 'Klever',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'xarvqb',
  description: 'A peer-to-peer network for everyone.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://klever.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
