import { AdapterProject } from '../types'

export default {
  name: 'Autonomy',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'jow0l5',
  description: 'Autonomy is a decentralized automation protocol designed for Web3 builders.',
  discord: '1012829124395532328',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/autonomynetwork/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.autonomynetwork.io/',
  github: 'https://github.com/Autonomy-Network',
  telegram: null,
  twitter: 'https://twitter.com/AutonomyNetwork',
  url: 'https://www.autonomynetwork.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
