import { AdapterProject } from '../types'

export default {
  name: 'Autonomy',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'jow0l5',
  description:
    'Autonomy is a decentralized automation protocol designed for Web3 builders. It allows DApps to add features like stop losses and limit orders for DEXes, levels the playing field between centralized and decentralized exchanges, and brings a powerful suite of tools to NFT creators and communities—all through on-chain, conditional execution.',
  investors: [
    'onvq9f',
    '3rh50q',
    'new0uo',
    'h8sw72',
    'zc36dj',
    'vh40ts',
    'pf49q9',
    's0sfkv',
    'lo28h3',
    'zbwc1y',
    'ysou15',
    '9wj3kh',
    'b6vnn8',
    'ko3khg',
    '07pxi6',
    '8agdnp',
    'ti312b',
    'najniu',
    '0rtomp',
  ],
  duneQueries: null,
  blog: 'https://blog.autonomynetwork.io/',
  github: 'https://github.com/Autonomy-Network',
  telegram: null,
  twitter: 'https://twitter.com/AutonomyNetwork',
} satisfies AdapterProject
