import { AdapterProject } from '../types'

export default {
  name: 'RootData',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'mz1912',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://rootdatalabs.medium.com/',
  github: null,
  telegram: 'https://t.me/RootDataEN',
  twitter: 'https://twitter.com/RootDataLabs',
  url: 'https://www.rootdata.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
