import { AdapterProject } from '../types'

export default {
  name: 'Switchboard',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coingeckoId: null,
  id: 'iik6nb',
  description:
    'Switchboard is a generalized, community-curated oracle network designed to incentivize bringing the long tail of data on-chain.',
  discord: null,
  investors: [
    'b5zojp',
    'bp637k',
    'ybj995',
    'q4ztc2',
    'zaf9xh',
    '0y8voh',
    '17h240',
    'kjm7ph',
    '91q6ri',
    'eg6rtr',
    '2vy35v',
    'u9taet',
    'qi0ovz',
    '7qvbir',
  ],
  linkedin: 'https://www.linkedin.com/company/switchboardxyz/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://switchboardxyz.medium.com/',
  github: 'https://github.com/switchboard-xyz',
  telegram: 'https://t.me/switchboardxyz',
  twitter: 'https://twitter.com/switchboardxyz',
  url: 'https://switchboard.xyz/',
  verified: false,
} satisfies AdapterProject
