import { AdapterProject } from '../types'

export default {
  name: 'Switchboard',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Oracle',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'iik6nb',
  description:
    'Switchboard is a permissionless Oracle network that allows developers to seamlessly connect dApps to real-world data.',
  discord: '841525135311634443',
  investors: [
    'b5zojp',
    'bp637k',
    'ybj995',
    'q4ztc2',
    'zaf9xh',
    '0y8voh',
    '17h240',
    'kjm7ph',
    '91q6ri',
    'eg6rtr',
    '2vy35v',
    'u9taet',
    'qi0ovz',
    '7qvbir',
  ],
  linkedin: 'https://www.linkedin.com/company/switchboardxyz/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://switchboardxyz.medium.com/',
  github: 'https://github.com/switchboard-xyz',
  telegram: 'https://t.me/switchboardxyz',
  twitter: 'https://twitter.com/switchboardxyz',
  url: 'https://switchboard.xyz/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://switchboardxyz.medium.com/switchboard-raises-3-5mm-seed-and-announces-solana-mainnet-beta-5dc21eefece',
    },
  ],
  isApp: true,
} satisfies AdapterProject
