import { AdapterProject } from '../types'

export default {
  name: 'Somos',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coingeckoId: null,
  id: 'ads6qy',
  description: 'Somos Internet provides prepaid high-speed internet services in Latin America.',
  investors: [
    'fxvy7i',
    'ynh9fg',
    '9ectn9',
    '4q2ow9',
    '0pxgvj',
    'nvi3i0',
    '0tzlng',
    'ay6zw8',
    'x59m34',
    'ed6r4e',
    'wdtkj1',
  ],
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.somosinternet.co/',
} satisfies AdapterProject
