import { AdapterProject } from '../types'

export default {
  name: 'tDrive',
  ninja: 'ZZ',
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '63c0w9',
  description: 'tDrive is a decentralized storage platform built on the Telos Blockchain.',
  discord: null,
  investors: [],
  linkedin: 'https://ca.linkedin.com/company/t-drive',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@VeganLover/how-does-google-drive-work-2cda31c58ce8',
  github: 'https://github.com/linagora/TDrive',
  telegram: null,
  twitter: 'https://twitter.com/mytdrive_id?lang=en',
  url: 'https://tdrive.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
