import { AdapterProject } from '../types'

export default {
  name: 'Pitch',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'utndo1',
  description: 'Pitch is the collaborative presentation software for modern teams.',
  investors: [
    '2046fz',
    'ca0yhb',
    'jo973z',
    'n2imyr',
    '2g0hhd',
    'llvibw',
    'ck41hn',
    'nqicih',
    'xw0zu2',
    'q2tl8d',
    'vutw8k',
    'lg0fzf',
    'hum3ve',
    'm0xdp3',
    'r75doi',
    'fbtzpi',
    'rotj2h',
    'pl6fqf',
    'h8bix0',
  ],
  duneQueries: null,
} satisfies AdapterProject
