import { AdapterProject } from '../types'

export default {
  name: 'Pitch',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'utndo1',
  description: 'Pitch is the collaborative presentation software for modern teams.',
  discord: null,
  investors: [],
  linkedin: 'https://github.com/pitch-io',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.linkedin.com/company/pitchhq',
  github: 'https://pitch.com/blog',
  telegram: null,
  twitter: 'https://www.twitter.com/pitch',
  url: 'https://pitch.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
