import { AdapterProject } from '../types'

export default {
  name: 'Meterbox',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: 'smjywm',
  description: 'The Meter Box is used to accurately measure your power usage in live time.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.themeterbox.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
