import { AdapterProject } from '../types'

export default {
  name: 'Truffles',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'tcai80',
  description: 'The most comprehensive suite of tools for smart contract development',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/trufflesuite',
  url: 'https://trufflesuite.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
