import { AdapterProject } from '../types'

export default {
  name: '60ghz',
  ninja: '0x9Ab59cB71d4657f4c2DB7E0963212A81b6445b4c',
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'zbvzq8',
  description: '60ghz is building a decentralized gigabit speed, public mesh WiFi Network.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/60ghz147659',
  url: 'https://60ghz.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
