import { AdapterProject } from '../types'

export default {
  name: 'Polkamarket',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'POLK',
  coinGeckoID: 'polkamarkets',
  id: 'qybaeu',
  description: 'Polkamarket is an Autonomous Prediction Market Protocol.',
  discord: '829288369943085066',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/polkamarkets/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/polkamarkets',
  github: 'https://github.com/Polkamarkets',
  telegram: 'https://t.me/polkamarkets_announcements',
  twitter: 'https://twitter.com/polkamarkets',
  url: 'https://www.polkamarkets.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
