import { AdapterProject } from '../types'

export default {
  name: 'CodeX',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'NATIVE',
  category: 'BLOCKCHAIN_INFRA',
  token: 'CDX',
  coinGeckoID: 'codexchain',
  id: 'xkpeqx',
  description: 'CodeX is an all-in-one no-code AI-powered ecosystem for WEB3 mass adoption.',
  discord: '1149392185725309078',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/codexchain',
  url: 'https://codexchain.xyz/home',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
