import { AdapterProject } from '../types'

export default {
  name: 'Laika',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'i2hs36',
  description: '',
  discord: '1135794443757301830',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/Laikaaiofficial',
  twitter: 'https://twitter.com/laika_ai',
  url: 'https://www.laika-ai.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
