import { AdapterProject } from '../types'

export default {
  name: 'Utilink',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'pp6yep',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/utilinkAI',
  url: 'https://utilink.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
