import { AdapterProject } from '../types'

export default {
  name: 'DeepFakeAI',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'FAKEAI',
  coinGeckoID: 'deepfakeai',
  id: '1cdn19',
  description: 'DeepFakeAI is a deepfake creation program using a Telegram Bot and Web App.',
  discord: '1120405708186337411',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@FakeAI',
  github: null,
  telegram: 'https://t.me/FakeAI',
  twitter: 'https://twitter.com/DeepFakeAI_',
  url: 'https://fakeai.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
