import { AdapterProject } from '../types'

export default {
  name: 'Tau',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'AGRS',
  coinGeckoID: 'agoras-currency-of-tau',
  id: 'ms4h4c',
  description: 'Tau is an AI software generation tool with AI safety features.',
  discord: '695210246557138965',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/tau-network/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://tau.net/blog/',
  github: null,
  telegram: 'https://t.me/tauchain',
  twitter: 'https://twitter.com/TauLogicAI',
  url: 'https://tau.net/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
