import { AdapterProject } from '../types'

export default {
  "name": "Oasis AI",
  "ninja": "W. L.",
  "subcategories": null,
  "chain": null,
  "category": "PENDING",
  "token": null,
  "coinGeckoID": null,
  "id": "nqaqpd",
  "description": "",
  "discord": null,
  "investors": [],
  "linkedin": null,
  "duneQueries": null,
  "foundingYear": null,
  "blog": null,
  "github": null,
  "telegram": null,
  "twitter": "https://x.com/oasisAI",
  "url": "https://oasis.ai/",
  "verified": false,
  "fundraises": []
} satisfies AdapterProjectn": null,
  "duneQueries": null,
  "foundingYear": null,
  "blog": null,
  "github": null,
  "telegram": null,
  "twitter": "https://twitter.com/OasisAI",
  "url": "https://www.oasis.ai/",
  "verified": false,
  "fundraises": []
} satisfies AdapterProject