import { AdapterProject } from '../types'

export default {
  name: 'Picogrid',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'ay3ajm',
  description: 'Picogrid builds a common platform to connect defense and autonomous systems.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/in/zanemountcastle/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@zanemountcastle',
  github: 'https://github.com/zanemountcastle',
  telegram: null,
  twitter: 'https://twitter.com/zanemountcastle',
  url: 'https://picogrid.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
