import { AdapterProject } from '../types'

export default {
  name: 'Secret',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'rwnruc',
  description: '',
  discord: '360051864110235648',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/SecretNetwork',
  url: 'https://scrt.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
