import { AdapterProject } from '../types'

export default {
  name: 'ether.fi',
  ninja: null,
  subcategories: 'Rewards',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '1agi71',
  description:
    'Ether.fi is a non-custodial decentralized ETH staking method that rewards node operators for participating in staking.',
  discord: null,
  investors: [
    'csfyvy',
    '7job29',
    'bdpmv2',
    'gwix1y',
    'rd2mzf',
    '3cjty6',
    'f87dvf',
    '3mzqtp',
    '9kybya',
    'tm95um',
  ],
  linkedin: 'http://www.linkedin.com/company/etherfi',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/etherfi',
  github: null,
  telegram: 'https://t.me/+C3fpSjmPqzA5NTVh',
  twitter: 'https://twitter.com/ether_fi',
  url: 'https://ether.fi/',
  verified: false,
} satisfies AdapterProject
