import { AdapterProject } from '../types'

export default {
  name: 'Sinso',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: 'SINSO',
  coingeckoId: null,
  id: 'tde0ef',
  description:
    'Sinso is a Web3.0 Infrastructure Simplifying Decentralized HotData Cache and Data Governance.',
  discord: null,
  investors: [
    'ovna62',
    's8v8am',
    'x07tqh',
    '1e5ima',
    'wpebfi',
    '03ew5g',
    'gpswp8',
    'v25i1p',
    'y1thi4',
    '4khk4w',
    'hqbyqg',
    'po8xe3',
    'asmbxg',
    'pwuofb',
    'z845oa',
    'x5h9ow',
    'nj1v3c',
    'ka28kz',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.sinso.io/',
  verified: false,
} satisfies AdapterProject
