import { AdapterProject } from '../types'

export default {
  name: 'Siglo',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: '7gjqft',
  description: 'Siglo is a wireless internet service provider.',
  discord: null,
  investors: [
    'ibk8eu',
    'l6myld',
    'tzp7ne',
    'dhr2z2',
    'yqrwim',
    'ud2iej',
    'x10a41',
    'zmmaj6',
    '3j9dp1',
    'p4hs0l',
    'hyymt5',
    '0gxopv',
    'm8wx40',
    'rgrylg',
  ],
  linkedin: 'http://www.linkedin.com/company/siglointernet',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/hashtag/siglobar',
  url: 'https://siglo.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
