import { AdapterProject } from '../types'

export default {
  name: 'Siglo',
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coingeckoId: null,
  id: '7gjqft',
  description: 'Siglo is a wireless internet service provider.',
  discord: null,
  investors: [
    'ibk8eu',
    'l6myld',
    'tzp7ne',
    'dhr2z2',
    'yqrwim',
    'ud2iej',
    'x10a41',
    'zmmaj6',
    '3j9dp1',
    'umz5z8',
    'hyymt5',
    '0gxopv',
    'm8wx40',
    'rgrylg',
    'wdtkj1',
  ],
  linkedin: 'http://www.linkedin.com/company/siglointernet',
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/hashtag/siglobar',
  url: 'https://siglo.com/',
} satisfies AdapterProject
