import { AdapterProject } from '../types'

export default {
  name: 'Swash',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'SWASH',
  coingeckoId: 'swash',
  id: '8mycy6',
  description:
    'Swash enables internet users, developers, and businesses to cultivate new realities of data ownership and value creation through new incentivisation streams.',
  discord: null,
  investors: [
    '7ng8h1',
    'oaw1ui',
    'g738qx',
    'mfisup',
    '8nclhv',
    '7brshu',
    '1jn5wy',
    'mkgpcb',
    'u2w7b1',
    '6hezki',
    'r2lof0',
    'cnvaxn',
    'i1vs03',
    'z3ngzr',
    'g4z7os',
    '8zouxb',
    'ardv2y',
    'azofz8',
    'l6s6c9',
    '6ewe4i',
    '9kyndm',
    '994c2q',
    'w9yetk',
    'vjpj24',
    'uwyyzt',
    'er8yvb',
    't44ifr',
    'gy5k6a',
  ],
  linkedin: 'https://www.linkedin.com/company/swashapp/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/swashapp',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/swashapp',
  url: 'https://swashapp.io/',
  verified: false,
} satisfies AdapterProject
