import { AdapterProject } from '../types'

export default {
  name: 'Kilt',
  chain: null,
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: 'bcanxl',
  description:
    'KILT is a blockchain-based identity platform offering decentralized, secure, and scalable solutions.',
  investors: [
    'gvqos9',
    'pbunpe',
    'y7olrs',
    'wxcf8r',
    'bd260g',
    'enemyk',
    '798xl8',
    '5qx1w8',
    '39iz1e',
    'xdw0yr',
    'rrtsc3',
    '89glxu',
    '5252r4',
    '65epfb',
    '6cd1m3',
    'ciz6c6',
    'wsuffu',
    'h25e6r',
    'm2z4hv',
    'xvgf6w',
  ],
  duneQueries: null,
  blog: 'https://kilt-protocol.medium.com/',
  github: 'https://github.com/KILTprotocol',
  telegram: null,
  twitter: 'https://twitter.com/Kiltprotocol',
} satisfies AdapterProject
