import { AdapterProject } from '../types'

export default {
  name: 'Beluga',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'c9xfts',
  description:
    'Beluga is a trusted crypto platform that onboards and guides new users through their crypto journey.',
  discord: null,
  investors: [
    'wb49st',
    's212gm',
    '08dtnk',
    'fahk60',
    'yc3rjf',
    '4lalb8',
    'buo8ql',
    '190658',
    'o26rsd',
    'bhbw5b',
    '9oo0xs',
    'supj15',
    'u2u1mx',
    'gleu8u',
    'dpvve5',
    'y2kqt7',
    't76v6n',
    'f0q8ea',
    'k1hi6c',
    'iwnv3f',
    '4gwkce',
    'a4ifju',
    '5lxjr4',
  ],
  linkedin: 'http://www.linkedin.com/company/heybeluga',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/getbeluga',
  url: 'https://heybeluga.com/',
  verified: false,
} satisfies AdapterProject
