import { AdapterProject } from '../types'

export default {
  name: 'Alethea',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'ALI',
  coingeckoId: 'alethea-artificial-liquid-intelligence-token',
  id: 'hp9an1',
  description:
    'Alethea AI provides Artificial Liquid Intelligence solutions, enabling decentralized ownership in the AI economy.',
  discord: 'https://discord.com/invite/aiprotocol',
  investors: [
    'hol96b',
    'b5zojp',
    'mrgeec',
    'y69z86',
    '2tgqti',
    'buo8ql',
    'gwix1y',
    'q4ztc2',
    'ltf0q4',
    'ubwov4',
    'qp5s3g',
    'yu0vkh',
    '1labbf',
    'nlqu6w',
    'c047hh',
    'jcbbxl',
    'wvda7j',
    '5s605e',
    'c9dgeq',
    'i1x9du',
    'oh018j',
    'pkboiz',
    '2g0699',
    'gnhylz',
    '07pxi6',
    '6cp8be',
    'z29qp7',
    '3leyzj',
    'gkv33p',
    'emg882',
    'gduv1m',
    'o3c9bd',
  ],
  linkedin: null,
  duneQueries: null,
  blog: null,
  github: 'https://github.com/AletheaAI',
  telegram: null,
  twitter: null,
  url: 'https://aiprotocol.info/',
} satisfies AdapterProject
