import { AdapterProject } from '../types'

export default {
  name: 'Alethea',
  ninja: null,
  subcategories: 'NFTs',
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'ALI',
  coinGeckoID: 'artificial-liquid-intelligence',
  id: 'zzxlj6',
  description:
    'Alethea AI is a research and development studio building at the intersection of two of the most transformative technologies of our time: Generative AI and Blockchain.',
  discord: 'https://discord.com/invite/aiprotocol',
  investors: [
    'b5zojp',
    'tupwbv',
    'y69z86',
    '2tgqti',
    'buo8ql',
    'q4ztc2',
    '2mccdz',
    'ib18pd',
    'lkgkfl',
    'qp5s3g',
    'aeoxcb',
    'nlqu6w',
    'c047hh',
    '4j98hb',
    '5xvyy9',
    '5s605e',
    'l7sko2',
    'i1x9du',
    'vvn12f',
    'qqc9zd',
    'pkboiz',
    'ivtzio',
    '43zijk',
    '2g0699',
    'gnhylz',
    'm8xiuk',
    '9e1gk4',
    'emg882',
    'zkwprh',
    'o3c9bd',
  ],
  linkedin: 'https://www.linkedin.com/company/realalethea/',
  duneQueries: null,
  foundingYear: '2019',
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/real_alethea',
  url: 'https://alethea.ai/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.theblock.co/linked/115574/alethea-ai-raises-16-million-venture-funding',
    },
  ],
} satisfies AdapterProject
