import { AdapterProject } from '../types'

export default {
  name: 'Pi Squared',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'emx2rm',
  description: '',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/pi-squared-inc/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/Pi-Squared-Inc',
  telegram: null,
  twitter: 'https://x.com/Pi_Squared_Pi2',
  url: 'https://pi2.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
