import { AdapterProject } from '../types'

export default {
  name: 'Particle',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'mcgnta',
  description: 'The Intent-Centric Modular Access Layer of Web3',
  discord: '973055032368967711',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://particle.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
