import { AdapterProject } from '../types'

export default {
  name: 'Superlocal',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: '3czn02',
  description:
    'Superlocal is a social network and game that rewards you with points for checking in at various places.',
  discord: '820756104169652254',
  investors: [
    'zmy4gp',
    'jtci9b',
    'rymjbe',
    'hm8wrp',
    '80qehd',
    'j0d5hc',
    '3coq1f',
    'ooq1d1',
    'k1e97y',
    '03zdwj',
  ],
  linkedin: 'https://www.linkedin.com/company/superlocalapp/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@superlocalapp',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/joinsuperlocal',
  url: 'https://www.superlocal.com/',
  verified: false,
  fundraisesUrls: ['https://dot.la/superlocal-2650547082.html'],
} satisfies AdapterProject
