import { AdapterProject } from '../types'

export default {
  name: 'Manta Network',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '2e3sf1',
  description:
    'Manta Network is the multi-modular ecosystem for zero-knowledge (ZK) applications. Manta Atlantic, the fastest ZK L1 chain, brings programmable identities and credentials to web3 through zkSBTs. Manta Pacific, the unique L2 ecosystem for EVM-native ZK applications, provides a scalable and inexpensive gas-fee environment for ZK applications to deploy simply using Solidity. Together, Manta Atlantic and Manta Pacific deliver an unparalleled experience for the next generation of web3 application development and adoption with the applied usage of zero-knowledge cryptography.',
  investors: [
    'b8gebp',
    '7bn5bf',
    'hcx26d',
    'zloyr1',
    'go7fr1',
    'xmw0ev',
    'mrgeec',
    'ezu6pa',
    'q4ztc2',
    'szfiug',
    'qp5s3g',
    'r2lof0',
    '0y8voh',
    'rwthif',
    '5dsvsj',
    'vkntey',
    '9xb78i',
    '9p60sa',
    'po8xe3',
    'n73vnt',
    '2g0699',
    'j36zoh',
    '6f2cxt',
    '6cd1m3',
    'tqh3bl',
    'ciz6c6',
    'drbv40',
    'h9g1s5',
    '7rf9rs',
    'm05wan',
    'pu3yyr',
    '5o347p',
    'wu15kr',
    'pgoyl5',
    'pvr738',
    'urug6u',
  ],
  duneQueries: null,
  blog: 'https://mantanetwork.medium.com/',
  github: 'https://github.com/manta-network',
  telegram: 'https://www.t.me/mantanetworkofficial',
  twitter: 'https://twitter.com/mantanetwork',
  url: 'https://manta.network/',
} satisfies AdapterProject
