import { AdapterProject } from '../types'

export default {
  name: 'Decent land',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'le0b94',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/decentlandlabs',
  url: 'https://www.decent.land/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
