import { AdapterProject } from '../types'

export default {
  name: 'P00LS',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: '0',
  coinGeckoID: 'zer0zer0',
  id: '6bqyjx',
  description: 'P00LS is the premier platform for Web3 community-building.',
  discord: '1175849217617559643',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/p00ls/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@P00LS',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/p00ls_',
  url: 'https://www.p00ls.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
