import { AdapterProject } from '../types'

export default {
  name: 'Pool',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: 'POOL',
  coinGeckoID: null,
  id: 'ueuvax',
  description:
    'Pool provides a platform and associated services to support Data Unions to develop, scale and monetize.',
  discord: null,
  investors: [
    '0ha7xp',
    'rbelby',
    'r2lof0',
    'mlhi9g',
    '8zouxb',
    'zzypcf',
    'n73vnt',
    '994c2q',
    'vjpj24',
    'zj4ect',
  ],
  linkedin: 'https://www.linkedin.com/company/pool-data/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.pooldata.io/blog',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/pooldata',
  url: 'https://www.pooldata.io/',
  verified: false,
} satisfies AdapterProject
