import { AdapterProject } from '../types'

export default {
  name: 'Vicharak',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'sbclxl',
  description: 'Reconfigurable edge computing',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://vicharak.in/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
