import { AdapterProject } from '../types'

export default {
  name: 'WeatherXM',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Environmental',
  chain: 'POLYGON',
  category: 'SENSORS',
  token: 'WXM',
  coinGeckoID: 'weatherxm',
  id: 'ff9s3p',
  description: 'WeatherXM is a decentralized weather data collection network.',
  discord: '813503633278631946',
  investors: [
    '4bc5rd',
    'jme2re',
    'buo8ql',
    'vh40ts',
    'b9dhtc',
    '6bvve4',
    'zbmcb4',
    'rwhpsx',
    'lszufu',
    'bku3ew',
    'ti312b',
    '6cp8be',
  ],
  linkedin: 'https://gr.linkedin.com/company/weatherxm',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.weatherxm.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/weatherxm',
  url: 'https://weatherxm.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.theblock.co/post/154820/web3-network-weatherxm-raises-5-million-in-seed-fundinghttps://www.theblock.co/post/154820/web3-network-weatherxm-raises-5-million-in-seed-funding',
    },
    {
      roundType: 'Series A',
      url: 'https://x.com/TheBlock__/status/1793265598991831507',
    },
  ],
  isApp: true,
} satisfies AdapterProject
