import { AdapterProject } from '../types'

export default {
  name: 'WeatherXM',
  ninja: null,
  subcategories: 'Environmental',
  chain: 'POLYGON',
  category: 'SENSORS',
  token: 'WXM',
  coinGeckoID: 'weatherxm',
  id: 'ff9s3p',
  description: 'WeatherXM is a decentralized weather data collection network.',
  discord: '813503633278631946',
  investors: [],
  linkedin: 'https://gr.linkedin.com/company/weatherxm',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.weatherxm.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/weatherxm?lang=en',
  url: 'https://weatherxm.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
