import { AdapterProject } from '../types'

export default {
  name: 'Metis',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'METIS',
  coinGeckoID: 'metis-token',
  id: '0mfb31',
  description: 'Metis: Scalable platform for Ethereum & infrastructure development',
  discord: '859838997874475008',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/metis-io',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://metisdao.medium.com/',
  github: 'https://github.com/MetisProtocol',
  telegram: 'https://t.me/MetisDAO',
  twitter: 'https://twitter.com/MetisDAO',
  url: 'https://www.metis.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
