import { AdapterProject } from '../types'

export default {
  name: 'Metis',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'METIS',
  coingeckoId: 'metis-token',
  id: '0mfb31',
  description: 'Metis: Scalable platform for Ethereum & infrastructure development',
  discord: 'https://discord.com/invite/RqfEJZXnxd',
  investors: [
    'z2j0xs',
    '1qu55f',
    'm8rgyb',
    'xmw0ev',
    '6g8wou',
    'iqk4zz',
    'k97mn4',
    'gtjd6o',
    'ta5llm',
    'kcao98',
    'xvqjcw',
    'xml0tr',
    '0msybz',
    '8a2od5',
    'hxmvxz',
    'ltf0q4',
    'itt1l4',
    'r2lof0',
    'i1vs03',
    'okjrd0',
    '5dsvsj',
    'ig0so4',
    '37htak',
    'pj4b1s',
    'yv5v8q',
    'hqbyqg',
    'fnoivv',
    'l1yhc5',
    'ka4f30',
    '56lnc2',
    'bah2fw',
    'terqpd',
    '67igtu',
    'b8exwz',
    '9oht0n',
    'uwyyzt',
    've60r2',
    '577mxg',
    'ukf76g',
    'xxi1ub',
    'n24ti7',
    '7xqu4s',
    'o7xcsr',
    '24ormv',
    '935mux',
    '0nsbs7',
  ],
  linkedin: 'http://www.linkedin.com/company/metis-io',
  duneQueries: null,
  blog: 'https://metisdao.medium.com/',
  github: 'https://github.com/MetisProtocol',
  telegram: 'https://t.me/MetisDAO',
  twitter: 'https://twitter.com/MetisDAO',
  url: 'https://www.metis.io/',
} satisfies AdapterProject
