import { AdapterProject } from '../types'

export default {
  name: 'Albedo',
  ninja: null,
  subcategories: 'Satellites',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'iqd05g',
  description:
    "Albedo's low-flying satellites capture visible and thermal imagery at the highest resolution commercially available.",
  discord: null,
  investors: [
    't5ccvg',
    'dnl49s',
    'wdijri',
    'oghpy2',
    'mzwabg',
    'bu2mhb',
    'iygktq',
    'jn6ek2',
    '636uvg',
    '9f6273',
    'nbvzm3',
    'xuzons',
    'gcq9cr',
    '3j9dp1',
    'r6v4in',
    '2zrpz0',
    '3q8qbn',
    'd4l9mo',
    '9pb2mx',
    'dc47oz',
    'dliu7c',
    '3szsa2',
    'erx8op',
    '6tdtou',
    '2fed3b',
    'eofkvo',
    'mo7acl',
    'unykak',
    '6u5jw2',
    'q8gx6g',
    'hkf560',
    'pzw5oi',
    'k3sz1r',
    'rgrylg',
    '8pdw6e',
    'sbxp1t',
    '0vlaoo',
    '3spzgv',
    'qznpam',
    'mjcdun',
    'rsenx1',
    '2zjum0',
    'wdtkj1',
  ],
  linkedin: 'https://www.linkedin.com/company/albedo-space/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/vaxchain',
  url: 'https://albedo.com/',
  verified: false,
} satisfies AdapterProject
