import { AdapterProject } from '../types'

export default {
  name: 'WiCrypt',
  chain: 'POLYGON',
  category: 'WIRELESS',
  token: 'WNT',
  coingeckoId: 'wicrypt',
  id: 'ynsj12',
  description: 'WiCrypt is a decentralized WiFi sharing network.',
  investors: [
    'xmw0ev',
    'w6kzqu',
    'nrotlx',
    '0msybz',
    'r8y2om',
    'r7fxid',
    '3uz422',
    'pj4b1s',
    'zgc59u',
    'tzyxtr',
    '049yft',
    'yga1fh',
    'gqk1el',
    'vjpj24',
    '9e1gk4',
    '331hng',
  ],
  duneQueries: null,
} satisfies AdapterProject
