import { AdapterProject } from '../types'

export default {
  name: 'WiCrypt',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'POLYGON',
  category: 'WIRELESS',
  token: 'WNT',
  coinGeckoID: 'wicrypt',
  id: 'ynsj12',
  description: 'WiCrypt is a decentralized WiFi sharing network.',
  discord: '892017585711886366',
  investors: [
    'xmw0ev',
    '0msybz',
    '3uz422',
    'z6hza6',
    'ucdc3l',
    'h3awvl',
    'vjpj24',
    'upyuaz',
    't9hlod',
    '9e1gk4',
  ],
  linkedin: 'https://ng.linkedin.com/company/wicrypt',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/wicrypt',
  github: 'https://github.com/AmyXandra/wicrypt-new',
  telegram: 'https://t.me/s/wicryptann?before=486',
  twitter: 'https://twitter.com/wicrypt?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://wicrypt.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://disruptafrica.com/2021/11/08/nigerian-wi-fi-sharing-startup-wicrypt-raises-1-5m-funding/',
    },
  ],
} satisfies AdapterProject
