import { AdapterProject } from '../types'

export default {
  name: 'Convo Space',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '6w9zdx',
  description: 'Decentralized conversation layer powering Web3.',
  discord: '857633502011195462',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/theconvospace',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/anudit/convo',
  telegram: null,
  twitter: 'https://twitter.com/0xConvo',
  url: 'https://theconvo.space/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
