import { AdapterProject } from '../types'

export default {
  name: 'SecondLive',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coingeckoId: null,
  id: '6qvjpf',
  description: 'SecondLive: a metaverse for avatars, virtual spaces, art exhibitions, and gaming.',
  discord: '864036969851650048',
  investors: [
    'zloyr1',
    'mrgeec',
    '2f68vj',
    '9jmx43',
    'xml0tr',
    '6hezki',
    '798xl8',
    'rlo5x9',
    'xdw0yr',
    'lkbsw0',
    'qu6tvr',
    '65epfb',
    'ukwp87',
    '40gzi4',
    'karrrt',
    'oa0h6s',
    'q6mxh8',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@SecondLiveReal',
  github: 'https://github.com/SecondLive23',
  telegram: 'https://t.me/SecondLiveCommunity',
  twitter: 'https://twitter.com/SecondLiveReal',
  url: 'https://secondlive.world/',
  verified: false,
} satisfies AdapterProject
