import { AdapterProject } from '../types'

export default {
  name: 'Quant',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'QNT',
  coingeckoId: 'quant-network',
  id: '7u7rag',
  description:
    'Quant is a blockchain project aiming to improve global information communication efficiency.',
  discord: null,
  investors: [
    '7jssah',
    'c0fb4z',
    'buime9',
    'bxcu1r',
    '35e9e6',
    'ka4f30',
    'xrz24d',
    'oxft8q',
    's2idi6',
    'lmuq6h',
  ],
  linkedin: 'https://www.linkedin.com/company/quantnetwork/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/quant_network',
  url: 'https://quant.network/',
} satisfies AdapterProject
