import { AdapterProject } from '../types'

export default {
  name: 'OxAI',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'OXAI',
  coinGeckoID: 'oxai-com',
  id: 'x3l1h6',
  description: 'OxAI: Decentralized AI & blockchain for accessible secure computation.',
  discord: '1067787661076594698',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/oxai/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/oxai',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/oxfordai',
  url: 'https://oxai.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
