import { AdapterProject } from '../types'

export default {
  name: 'Hubble Protocol',
  chain: 'SOLANA',
  category: 'OTHER',
  token: 'USDH',
  coingeckoId: 'usdh',
  id: 'ztuwxq',
  description:
    'Hubble Protocol is exploring the universe of DeFi on Solana. Hubble begins this by minting USDH through zero-interest borrowing. Hubble empowers its community by rewarding behaviors that ensure the protocol works as designed, by distributing rewards to users that lock HBB, provide liquidity on exchanges or USDH funds to cover liquidations, or by opening up platform governance. Building on top of the borrowing protocol, Hubble will offer more use cases for USDH to create an ecosystem of complementary products, including structured products in terms of trading strategies and tailored USDH undercollateralized lending.',
  investors: [
    'b8gebp',
    '7bn5bf',
    'p2rf1n',
    '7ygqh2',
    'onvq9f',
    'q4ztc2',
    'ubwov4',
    '3b0ihr',
    'qp5s3g',
    '67mqz0',
    'v2rrnz',
    '8e6e1u',
    'e338ka',
    'nxzb7m',
    '4ssdn4',
    'po8xe3',
    '967a4z',
    'ulvyo3',
    'bah2fw',
    '2g0699',
    '6f2cxt',
    'unykak',
    'yibv9g',
    '5rmf8c',
    'tlb60n',
    'pgoyl5',
    '8uix7q',
    'ixxo16',
    'pcw959',
  ],
  duneQueries: null,
  blog: 'https://blog.hubbleprotocol.io/',
  github: 'https://github.com/hubbleprotocol',
  telegram: 'https://t.me/hubbleprotocol',
  twitter: 'https://twitter.com/hubbleprotocol',
} satisfies AdapterProject
