import { AdapterProject } from '../types'

export default {
  name: 'DePINs',
  ninja: '0x25052A4B28a35FfdBf2FaBA7DCCEB350e91b908F',
  subcategories: 'Meme',
  chain: 'IOTEX',
  category: 'INTELLECTUAL_PROPERTY',
  token: 'DEPINS',
  coinGeckoID: 'depins',
  id: 'ob91k4',
  description: 'DePINs is a meme token on the IOTEX blockchain.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/depinsapp',
  url: 'https://depins.app/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
