import { AdapterProject } from '../types'

export default {
  name: 'Swarm',
  ninja: 'ZZ',
  subcategories: 'Storage',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'BZZ',
  coinGeckoID: 'swarm-bzz',
  id: '8s783v',
  description: 'Swarm is a decentralised data storage and distribution technology.',
  discord: '799027393297514537',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/ethereum-swarm',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ethersphere',
  telegram: null,
  twitter: 'https://twitter.com/ethswarm',
  url: 'https://www.ethswarm.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
