import { AdapterProject } from '../types'

export default {
  name: 'Solchan',
  ninja: 'EV3 Sal',
  subcategories: 'Social',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'x2oelc',
  description: 'Solchan is a 4chan-inspired free speech board on Solana.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/solchan_org',
  url: 'https://solchan.org/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
