import { AdapterProject } from '../types'

export default {
  name: 'Cryptosat',
  ninja: null,
  subcategories: 'Satellites',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coingeckoId: null,
  id: '9agce6',
  description:
    'Cryptosat is a satellite company that offers cost-efficient, space-based cryptographic trust infrastructure for Web3.',
  discord: null,
  investors: [
    'h4v7bw',
    'wxro8b',
    '5wgx9l',
    '5qx1w8',
    '7klad7',
    '22saty',
    'e7om6t',
    '2rpeeh',
    'tnkrzw',
    'ti312b',
  ],
  linkedin: 'https://www.linkedin.com/company/cryptosat',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/topics/wave?l=html',
  telegram: 'https://medium.com/cryptosatellite',
  twitter: 'https://twitter.com/cryptosat?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://www.cryptosat.io/',
} satisfies AdapterProject
