import { AdapterProject } from '../types'

export default {
  name: 'AWARE',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'rkfiyk',
  description: 'AWARE traces cotton with tracer particles to ensure sustainable textiles.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/aware-inc.',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/awareframework',
  telegram: null,
  twitter: 'https://twitter.com/Aware?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
  url: 'https://wearaware.co/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
