import { AdapterProject } from '../types'

export default {
  name: 'Radicle',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'n2u1ny',
  description:
    'Radicle is a decentralized, peer-to-peer code collaboration platform built on Git, where repositories are replicated across peers in a decentralized manner, empowering users with full control over their data and workflows.',
  discord: null,
  investors: [
    '896jil',
    'jo973z',
    'wldl30',
    '67fqhy',
    '73opsz',
    'szfiug',
    '7k7kbw',
    'kk8zod',
    'z6cdtc',
    'mywjsu',
    '67nk5m',
    '44e83n',
    '1ojs3d',
    'nxzb7m',
    'e7om6t',
    'ivtzio',
    'co49ki',
    '2vjau8',
    't105wi',
    '6f2cxt',
    'bku3ew',
    'gduv1m',
  ],
  linkedin: 'https://www.linkedin.com/company/radicleproject/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/radicle',
  url: 'https://radicle.xyz/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://www.theblock.co/linked/95295/open-source-radicle-12-million-galaxy',
    },
  ],
  isApp: true,
} satisfies AdapterProject
