import { AdapterProject } from '../types'

export default {
  name: 'Radicle',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'SERVICES',
  token: null,
  coingeckoId: null,
  id: 'n2u1ny',
  description:
    'Radicle is a peer-to-peer stack for building software together. Radicle functions as a peer-to-peer protocol where each user on the network runs identical software, known as the Radicle Stack.',
  discord: null,
  investors: [
    '896jil',
    'jo973z',
    'wldl30',
    '67fqhy',
    '73opsz',
    'szfiug',
    '7k7kbw',
    'kk8zod',
    'z6cdtc',
    'mywjsu',
    '67nk5m',
    '44e83n',
    '1ojs3d',
    'nxzb7m',
    'e7om6t',
    'ivtzio',
    'co49ki',
    '2vjau8',
    't105wi',
    '6f2cxt',
    'bku3ew',
    'gduv1m',
  ],
  linkedin: 'https://www.linkedin.com/company/radicleproject/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/radicle',
  url: 'https://radicle.xyz/',
} satisfies AdapterProject
