import { AdapterProject } from '../types'

export default {
  name: 'Lumino',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: '3ttk4l',
  description: 'Decentralized GPU network built on Filecoin',
  discord: null,
  investors: ['7zvxz8', 'tm95um'],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.luminolabs.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
