import { AdapterProject } from '../types'

export default {
  name: 'Cloaked Wireless',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'o26yla',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/cloakedwireless',
  url: 'https://cloakedwireless.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
