import { AdapterProject } from '../types'

export default {
  name: 'Photon',
  ninja: null,
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: '0k8gq4',
  description:
    'Photon is a decentralized storage protocol for the metaverse, Web3, and cloud storage.',
  discord: null,
  investors: [
    '1zgufc',
    'h2tvqq',
    'wldl30',
    'd2hp6f',
    'yv5v8q',
    '07pxi6',
    'oltsrb',
    '3dhuwv',
    'bix4ir',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@photon.storage',
  github: 'https://github.com/photon-storage',
  telegram: 'https://t.me/photonstorage',
  twitter: 'https://twitter.com/photon_storage',
  url: 'https://www.photon.storage/',
  verified: false,
} satisfies AdapterProject
