import { AdapterProject } from '../types'

export default {
  name: 'Stamp',
  ninja: null,
  subcategories: 'Agents',
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'cc337l',
  description: 'Stamp Network is an L2 blockchain focusing on supporting digital entities.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/stampDOTnetwork',
  url: 'https://www.stamp.network/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
