import { AdapterProject } from '../types'

export default {
  name: 'Atlantis',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'vv9k2c',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/AtlantisDao1',
  url: 'https://www.atlantians.world/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
