import { AdapterProject } from '../types'

export default {
  name: 'EYWA',
  chain: null,
  category: 'OTHER',
  token: 'EYWA',
  coingeckoId: null,
  id: 'tbwx5g',
  description:
    'EYWA is a genuinely decentralized medium for transferring data between blockchains and creating aggregated cross-chain assets.',
  investors: [
    's7b833',
    'tvu1r6',
    '4l8mmr',
    'pd9gca',
    'oi4yuk',
    '4sf6wm',
    '6uuq9l',
    'tpcj7y',
    'mlynhb',
    'mar9ip',
    'curksv',
    't6uue7',
    'gw5y68',
    'jzrat5',
    'tzyxtr',
    'vu9glf',
    '4dh0t9',
    'b6vnn8',
    '8agdnp',
    'wvcovb',
    'u8r7ah',
    'onzcv5',
    'nj1v3c',
    'ms8eng',
  ],
  duneQueries: null,
} satisfies AdapterProject
