import { AdapterProject } from '../types'

export default {
  name: 'EYWA',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: 'EYWA',
  coinGeckoID: null,
  id: 'tbwx5g',
  description:
    'EYWA is a genuinely decentralized medium for transferring data between blockchains and creating aggregated cross-chain assets.',
  discord: '880102933298049054',
  investors: [
    's7b833',
    'tvu1r6',
    '4l8mmr',
    'pd9gca',
    'oi4yuk',
    '4sf6wm',
    '6uuq9l',
    'tpcj7y',
    'mlynhb',
    'mar9ip',
    'curksv',
    't6uue7',
    'gw5y68',
    'jzrat5',
    'tzyxtr',
    'vu9glf',
    '4dh0t9',
    'b6vnn8',
    '8agdnp',
    'wvcovb',
    'u8r7ah',
    'onzcv5',
    'nj1v3c',
    'ms8eng',
  ],
  linkedin: 'https://www.linkedin.com/company/eywa-protocol/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@eywaprotocol',
  github: 'https://github.com/eywa-protocol',
  telegram: 'https://t.me/eywa_en',
  twitter: 'https://twitter.com/eywaprotocol',
  url: 'https://eywa.fi/',
  verified: false,
} satisfies AdapterProject
