import { AdapterProject } from '../types'

export default {
  name: 'Jasmine',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: null,
  coinGeckoID: null,
  id: 'bwhoon',
  description:
    'Jasmine Energy is a decentralized market for claiming, trading, and redeeming renewable energy certificates.',
  discord: '1012757430779789403',
  investors: [
    '9jairy',
    '4zunln',
    'zaf9xh',
    'rmj9ht',
    '4ufrbu',
    'v81ftp',
    '6otq8c',
    'q0cuxs',
    '1f9kgy',
  ],
  linkedin: 'https://www.linkedin.com/company/jasmine-energy',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/jasmine-energy?source=topics_v2-8-84022bb4b1_df6b_4af1_8461_679c57abc67d-17',
  github: 'https://github.com/jasmine',
  telegram: null,
  twitter: 'https://twitter.com/Jasmine_Energy',
  url: 'https://www.jasmine.energy/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
