import { AdapterProject } from '../types'

export default {
  name: 'GoldenCrypto',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'qg6lwg',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/GoldenDoge11',
  url: 'https://goldencrypto.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
