import { AdapterProject } from '../types'

export default {
  name: 'gm.ai',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'txqs5b',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/gm_dot_ai',
  url: 'https://gm.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
