import { AdapterProject } from '../types'

export default {
  name: 'GooseFX',
  ninja: '0xc38dECebD857Ec55989155D1cF00348a878b6A07',
  subcategories: null,
  chain: 'SOLANA',
  category: 'NOT_DEPIN',
  token: 'GOFX',
  coinGeckoID: 'goosefx',
  id: '1qhz26',
  description: 'Solana DeFi',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.goosefx.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
