import { AdapterProject } from '../types'

export default {
  name: 'Root Protocol',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'ISME',
  coinGeckoID: 'root-protocol',
  id: 'z1ks7o',
  description:
    'Root Protocol is building a Web3 operating system that will serve as a digital identity aggregator to make accessing different Web3 platforms a more seamless process.',
  discord: '968326172528222268',
  investors: [
    'gjt0lb',
    'yxetck',
    '9a7u1l',
    'giq489',
    '1e5ima',
    'vcxbpn',
    'q4ztc2',
    'bxcu1r',
    '6uuq9l',
    '798xl8',
    'r2lof0',
    '8e6e1u',
    '18l8yx',
    'knw63n',
    '5dsvsj',
    '8zouxb',
    'qqc9zd',
    '6ewe4i',
    'ka4f30',
    'to40x8',
    'b04x9g',
    'f4awf9',
    'lhs5s8',
    'oltsrb',
    '52fjgj',
    'dvz6gg',
    '8uix7q',
    'onzcv5',
    'nwl5v7',
    'gy5k6a',
  ],
  linkedin: 'http://www.linkedin.com/company/nft3',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://root-labs.medium.com/',
  github: 'https://github.com/nft3labs',
  telegram: 'https://t.me/rootlabs',
  twitter: 'https://twitter.com/0xRootLabs',
  url: 'https://root.xyz/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.businesswire.com/news/home/20220131005406/en/NFT3-Raises-US7.5-Million-Led-by-Animoca-Brands-Signaling-Decentralized-Identity-Technology-and-NFTs-as-Gate.ioway-to-the-Metaverse',
    },
  ],
} satisfies AdapterProject
