import { AdapterProject } from '../types'

export default {
  name: 'CheersLand',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '9g1vlq',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/cheers_land',
  url: 'https://cheersland.org/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
