import { AdapterProject } from '../types'

export default {
  name: 'StackOS',
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'SFX',
  coingeckoId: 'stackos',
  id: 'kd6pyc',
  description:
    'StackOS is a cross-chain open infrastructure protocol enabling decentralized cloud services.',
  investors: [
    '7jssah',
    'o5kpgb',
    'ydmvp5',
    'xmw0ev',
    'e3it8b',
    'g9rb5v',
    '5qx1w8',
    'mlhi9g',
    'pcdwc6',
    '6ewe4i',
    '243kcn',
    'ka4f30',
    'to40x8',
    'dd123i',
    '07pxi6',
    '0nl0fg',
    'qzj08j',
    '02tq6x',
    'h9g1s5',
    'pyukl2',
    'thqjz1',
    'brmebh',
    'dovucn',
  ],
  duneQueries: null,
  blog: 'https://medium.com/stackos',
  github: 'https://github.com/stackosofficial',
  telegram: 'https://t.me/DeployOnStackOS',
  twitter: 'https://twitter.com/DeployOnStackOS',
} satisfies AdapterProject
