import { AdapterProject } from '../types'

export default {
  name: 'Blocksurvey',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'w1c0r2',
  description:
    'BlockSurvey offers Tokengated surveys, enabling users to engage in blockchain-based survey participation.',
  discord: '669101220937596953',
  investors: [
    '7bn5bf',
    '1aatyr',
    '8uu9kr',
    '1yjwza',
    'jkb7hq',
    'rlo5x9',
    'dc1d3b',
    '9r6aaf',
    '6od4bx',
    'nr6cj9',
    'wa3eqd',
  ],
  linkedin: 'https://www.linkedin.com/company/blocksurvey/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/BlockSurvey',
  telegram: null,
  twitter: 'https://twitter.com/blocksurvey',
  url: 'https://blocksurvey.io/',
  verified: false,
} satisfies AdapterProject
