import { AdapterProject } from '../types'

export default {
  name: 'Piphi',
  ninja: '0x9Ab59cB71d4657f4c2DB7E0963212A81b6445b4c',
  subcategories: 'Environmental',
  chain: 'ALGORAND',
  category: 'SENSORS',
  token: 'PIPHIN',
  coinGeckoID: null,
  id: 'ksvenu',
  description: 'Piphi is a decentralized environmental data collection network.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://piphi.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
