import { AdapterProject } from '../types'

export default {
  name: 'Paradex',
  ninja: null,
  subcategories: 'Prediction Market',
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'h4uvxu',
  description: 'Stamp Network is an L2 blockchain focusing on supporting digital entities.',
  discord: '1107916848193863740',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.paradex.trade/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
