import { AdapterProject } from '../types'

export default {
  name: 'Glitter Protocol',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'hvnixv',
  description:
    'A blockchain-based data platform to help applications store, manage and elevate data in Web3 way.',
  discord: null,
  investors: [
    'z5oj4n',
    '2ckrz9',
    '8ygsak',
    'us9d7q',
    'n7xol2',
    'rgk0ot',
    'v3sg2g',
    'vjpj24',
    'zj4ect',
    'ti312b',
    'pcw959',
    'urug6u',
  ],
  linkedin: 'https://www.linkedin.com/company/glitterprotocol/about/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/GlitterProtocol',
  url: 'https://glitterprotocol.io/',
} satisfies AdapterProject
