import { AdapterProject } from '../types'

export default {
  name: 'Mysterium',
  ninja: 'wholovesburrito.eth',
  subcategories: null,
  chain: 'NATIVE',
  category: 'WIRELESS',
  token: 'MYST',
  coinGeckoID: 'mysterium',
  id: '8ci5ud',
  description: 'Mysterium is a decentralized wireless network.',
  discord: '614079733663006750',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/mysteriumnet',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/mysterium-network',
  github: 'https://github.com/MysteriumNetwork',
  telegram: 'https://t.me/mysterium_network',
  twitter: 'https://twitter.com/MysteriumNet',
  url: 'https://www.mysterium.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
