import { AdapterProject } from '../types'

export default {
  name: 'RDDL',
  ninja: null,
  subcategories: 'IoT',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'wbocde',
  description: 'RDDL Network is a secure Refi and Defi protocol with trust anchors.',
  discord: '1044693472390697011',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/rddl/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/rddl-network',
  telegram: null,
  twitter: 'http://twitter.com/RDDLNetwork',
  url: 'https://www.rddl.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
