import { AdapterProject } from '../types'

export default {
  name: 'EnviroBLOQ',
  ninja: null,
  subcategories: null,
  chain: 'IOTEX',
  category: 'SENSORS',
  token: null,
  coinGeckoID: null,
  id: 'czooh2',
  description: 'EnviroBLOQ is a decentralized network of connected smart home devices.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/envirobloq',
  url: 'https://envirobloq.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
