import { AdapterProject } from '../types'

export default {
  name: 'ArDrive',
  ninja: 'wholovesburrito.eth',
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'e9qw0z',
  description:
    'ar.io is a network of decentralized gateways and permanent domains for the Arweave ecosystem.',
  discord: '908759493943394334',
  investors: [
    'bspyld',
    'zloyr1',
    'hhudw8',
    'te4xtz',
    'ri09e0',
    'maid89',
    'm6mz4i',
    'b1hrk6',
    'qxxzbk',
    'uktppp',
    'wir0cg',
    'vkntey',
    'i1x9du',
    'po8xe3',
    'thxgaw',
    'bah2fw',
    'aly00l',
    'ukwp87',
    '06o6kd',
    'cgmkn8',
    'pu3yyr',
    'apkkjz',
  ],
  linkedin: 'https://www.linkedin.com/showcase/ar-io/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ar-io',
  telegram: null,
  twitter: 'https://twitter.com/ar_io_network',
  url: 'https://ar.io/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.coindesk.com/business/2021/05/19/arweave-based-permanent-dropbox-raises-16m-seed-round/',
    },
    {
      roundType: 'Series A',
      url: 'https://www.coindesk.com/business/2022/03/03/ardrive-raises-17m-to-make-arweaves-data-storage-blockchain-more-usable/',
    },
  ],
  isApp: true,
} satisfies AdapterProject
