import { AdapterProject } from '../types'

export default {
  name: 'ArDrive',
  ninja: 'W. L.',
  subcategories: 'Storage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 'e9qw0z',
  description:
    'ar.io is a network of decentralized gateways and permanent domains for the Arweave ecosystem.',
  discord: '908759493943394334',
  investors: [
    'bspyld',
    'zloyr1',
    'hhudw8',
    'te4xtz',
    'ri09e0',
    'maid89',
    'm6mz4i',
    'b1hrk6',
    'qxxzbk',
    'uktppp',
    'wir0cg',
    'vkntey',
    'i1x9du',
    'po8xe3',
    'thxgaw',
    'bah2fw',
    'aly00l',
    'ukwp87',
    '06o6kd',
    'cgmkn8',
    'pu3yyr',
  ],
  linkedin: 'https://www.linkedin.com/showcase/ar-io/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/ar-io',
  telegram: null,
  twitter: 'https://twitter.com/ar_io_network',
  url: 'https://ar.io/',
  verified: false,
} satisfies AdapterProject
