import { AdapterProject } from '../types'

export default {
  name: 'Entangle',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'NGL',
  coinGeckoID: 'entangle',
  id: 'upuriv',
  description:
    'Entangle is a customizable messaging Infrastructure designed to unify web3 and optimize ecosystem liquidity. It provides builders & dApps authenticated, customizable, and interoperable data secured on the blockchain with full security configurability.',
  discord: '938906933732212846',
  investors: [
    '56gubq',
    'eq458r',
    '4l8mmr',
    'xilrw4',
    'bxcu1r',
    'p7lpx4',
    '2bl1fj',
    'tuxed4',
    'k1qvmn',
    'wtzat2',
    'qzpg6s',
    '89glxu',
    'b04x9g',
    'rgk0ot',
    'o84ukt',
    'jn38nx',
    '5fmqrb',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Entanglefi',
  url: 'https://entangle.fi/',
  verified: false,
  fundraises: [
    {
      roundType: 'Private/Public token sale',
      url: 'https://cryptorank.io/ico/entangle',
    },
    {
      roundType: 'Seed',
      url: 'https://twitter.com/entanglefi/status/1744751372455784817',
    },
    {
      roundType: 'Strategic/Angel',
      url: 'https://cryptorank.io/ico/entangle',
    },
  ],
  isApp: true,
} satisfies AdapterProject
