import { AdapterProject } from '../types'

export default {
  name: 'Bistroo',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'HUMAN_CAPITAL',
  token: 'BIST',
  coinGeckoID: 'bistroo',
  id: 'qpkhj7',
  description: 'Bistroo is a decentralized marketplace for food & beverage delivery.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/bistroo-nl/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://bistroo.medium.com/',
  github: 'https://github.com/bistroo',
  telegram: null,
  twitter: 'https://twitter.com/BistrooIO',
  url: 'https://www.bistroo.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
