import { AdapterProject } from '../types'

export default {
  name: 'MetaGravity',
  ninja: null,
  subcategories: 'Gaming',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'jvfvyy',
  description:
    'MetaGravity is a company building distributed compute infrastructure for metaverse gaming and virtual world simulations.',
  discord: '885910230007951460',
  investors: [
    'v5aw83',
    'bxcu1r',
    '8v67z1',
    'bqmpxo',
    '3x72a9',
    'q8aum6',
    'n16trk',
    '4dh0t9',
    'pr3bit',
    'y6oua0',
    '5mg8ss',
    '06o6kd',
    'pgoyl5',
  ],
  linkedin: 'https://www.linkedin.com/company/metagravityltd',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://metagravity.medium.com/',
  github: null,
  telegram: 'https://t.me/Felikxz',
  twitter: 'https://twitter.com/MetaGravity_',
  url: 'https://www.metagravity.com/',
  verified: false,
  fundraisesUrls: ['https://tech.eu/2023/04/21/metagravity-do-something-amazing/'],
} satisfies AdapterProject
