import { AdapterProject } from '../types'

export default {
  name: 'Together.ai',
  ninja: null,
  subcategories: 'GPUs',
  chain: null,
  category: 'AI',
  token: null,
  coingeckoId: null,
  id: 'rr8fxt',
  description:
    'Together.ai is a decentralised cloud platform that empowers developers to train and deploy generative AI models.',
  discord: '1082503318624022589',
  investors: [
    '0zuwkc',
    '1crmhb',
    'nk4njt',
    'hbf50y',
    'kox5i6',
    'osmf1q',
    'gvjegy',
    '64cas2',
    'wloi1k',
    '8nd6rp',
    'hnvfm3',
    'zkz4v0',
    't50iac',
    'rnhq72',
    'stdr1v',
    '9tdi8p',
    '08avju',
    '38n337',
    'eyy236',
    'h2kgqh',
    '1nuvtk',
    'tqxo96',
    'ksh3he',
    'tifbbe',
    'k1e97y',
    'qr2jg3',
    '3mawmt',
    '9yjtz6',
  ],
  linkedin: 'http://www.linkedin.com/company/togethercomputer',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'http://twitter.com/togethercompute',
  url: 'https://together.ai/',
  verified: false,
} satisfies AdapterProject
