import { AdapterProject } from '../types'

export default {
  name: 'Together.ai',
  ninja: 'ZZ',
  subcategories: 'GPUs',
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'rr8fxt',
  description:
    'Together.ai is a decentralised cloud platform that empowers developers to train and deploy generative AI models.',
  discord: '1082503318624022589',
  investors: [
    '0zuwkc',
    '1crmhb',
    'nk4njt',
    'hbf50y',
    'kox5i6',
    'osmf1q',
    'gvjegy',
    '64cas2',
    '31tqgm',
    'wloi1k',
    '8nd6rp',
    'hnvfm3',
    'zkz4v0',
    't50iac',
    'u3ke67',
    'rnhq72',
    'stdr1v',
    '9tdi8p',
    '08avju',
    '38n337',
    'm1prxp',
    'eyy236',
    'h2kgqh',
    '1nuvtk',
    'tqxo96',
    'ksh3he',
    'tifbbe',
    'k1e97y',
    'by636n',
    '3mawmt',
    '9yjtz6',
  ],
  linkedin: 'http://www.linkedin.com/company/togethercomputer',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'http://twitter.com/togethercompute',
  url: 'https://together.ai/',
  verified: false,
  fundraises: [
    {
      roundType: 'Series A',
      url: 'https://techcrunch.com/2023/05/15/together-raises-20m-to-build-open-source-generative-ai-models/',
    },
    {
      roundType: 'Series B',
      url: 'https://techcrunch.com/2023/11/29/together-lands-102-5m-investment-to-grow-its-cloud-for-training-generative-ai/',
    },
  ],
} satisfies AdapterProject
