import { AdapterProject } from '../types'

export default {
  name: 'PADS',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: 'dqmv0o',
  description: 'Pads Financial is a Montreal based Fintech startup serving Canadian homeowners.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.padsfinancial.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
