import { AdapterProject } from '../types'

export default {
  name: 'Double Protocol',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '59ty5q',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/DoubleProtocol',
  url: 'https://double.one/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
