import { AdapterProject } from '../types'

export default {
  name: 'Cherry',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'CHER',
  coinGeckoID: 'cherry-network',
  id: 'j6bezo',
  description: 'Cherry: DAO building optimized blockchain for decentralized apps.',
  discord: '787076370952880138',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/cherrynetwork',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://cherryproject.medium.com/',
  github: 'https://github.com/CherryNetwork',
  telegram: 'https://t.me/cherrynetwork',
  twitter: 'https://twitter.com/Cherry_Network',
  url: 'https://www.cherry.network/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
