import { AdapterProject } from '../types'

export default {
  name: 'Cherry',
  ninja: null,
  subcategories: 'L1/L2',
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'CHER',
  coingeckoId: 'cherry-network',
  id: 'j6bezo',
  description: 'Cherry: DAO building optimized blockchain for decentralized apps.',
  discord: 'https://discord.com/invite/KAwC9aafWa',
  investors: [
    'kyzttp',
    '1e5ima',
    '98n1o3',
    'u3ry57',
    'tv2wj1',
    '0hcymb',
    '2bl1fj',
    '410ofn',
    '1k4qxq',
    'v25i1p',
    'chxmjc',
    'uwuv2v',
    'i1vs03',
    't46hjx',
    '1kxhn8',
    'bb8l1y',
    '11dur6',
    '7ligqu',
    'hgmxdl',
    'lhs5s8',
    'ww95ua',
    'x5h9ow',
    '6mh2rx',
    'nj1v3c',
  ],
  linkedin: 'http://www.linkedin.com/company/cherrynetwork',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://cherryproject.medium.com/',
  github: 'https://github.com/CherryNetwork',
  telegram: 'https://t.me/cherrynetwork',
  twitter: 'https://twitter.com/Cherry_Network',
  url: 'https://www.cherry.network/',
  verified: false,
} satisfies AdapterProject
