import { AdapterProject } from '../types'

export default {
  name: 'Teleport',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'MOBILITY',
  token: null,
  coinGeckoID: null,
  id: 'aehc1q',
  description:
    'Teleport connects companies, drivers, and riders, promoting local economies and reducing costs.',
  discord: null,
  investors: [
    'dnl49s',
    'hol96b',
    '7zg71v',
    'osmf1q',
    'k2s470',
    '9td18r',
    '1u0fcq',
    'rgk0ot',
    'oygqys',
    'd14rf6',
    'w3oxcr',
    'jyihc4',
  ],
  linkedin: 'http://www.linkedin.com/company/teleportxyz',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/teleportxyz',
  url: 'https://www.teleport.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
