import { AdapterProject } from '../types'

export default {
  name: 'Teleport',
  subcategories: 'Ridesharing',
  chain: null,
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: 'aehc1q',
  description:
    'Teleport connects companies, drivers, and riders, promoting local economies and reducing costs.',
  discord: 'https://discord.com/invite/teleport',
  investors: [
    'dnl49s',
    'hol96b',
    '7zg71v',
    'osmf1q',
    'k2s470',
    '9td18r',
    '1u0fcq',
    'xnftxc',
    'oygqys',
    'd14rf6',
    'w3oxcr',
    'jyihc4',
  ],
  linkedin: 'http://www.linkedin.com/company/teleportxyz',
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/teleportxyz',
  url: 'https://www.teleport.xyz/',
} satisfies AdapterProject
