import { AdapterProject } from '../types'

export default {
  name: 'Qubic',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: '8hzipe',
  description: 'Qubic Network is a smart contract platform for AI applications.',
  discord: '768887649540243497',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/qubic-li',
  telegram: null,
  twitter: 'https://twitter.com/qubic_network',
  url: 'https://web.qubic.li/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
