import { AdapterProject } from '../types'

export default {
  name: 'AgriDex',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'SOLANA',
  category: 'RWA',
  token: 'AgriDex',
  coinGeckoID: null,
  id: 't42uy8',
  description: 'Agridex is an RWA Marketplace focused on tokenizing agricultural commodities.',
  discord: '940826514717569025',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/AgriDexPlatform',
  url: 'https://agridex.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
