import { AdapterProject } from '../types'

export default {
  name: 'Raiinmaker',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'BINANCE',
  category: 'AI',
  token: 'COIIN',
  coinGeckoID: null,
  id: 'bw9zs2',
  description:
    'Raiinmaker is a Web3 and AI tech company that offers the Raiinmaker AI Super App and Network Protocol, leveraging decentralized AI and Web3 to reward users for contributing to AI content creation, AI model training, and DePIN Node operation.',
  discord: '925938679397105684',
  investors: [
    'z2j0xs',
    'buime9',
    'o5kpgb',
    'ydmvp5',
    'm8rgyb',
    'ajbv45',
    'vcxbpn',
    '798xl8',
    'chxmjc',
    'i1vs03',
    'dm8n2p',
    '4ssdn4',
    'gi55pp',
    'qu9as2',
    'ehuolk',
    'd0dwes',
    '65epfb',
    'rgk0ot',
    'nr57n8',
    'chjkg7',
    '5nt3w6',
    'xxi1ub',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Raiinmakerapp',
  url: 'https://www.raiinmaker.com/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://www.theblock.co/post/285900/jump-capital-7-5-million-seed-round-web3-ai-firm-raiinmaker',
    },
  ],
} satisfies AdapterProject
