import { AdapterProject } from '../types'

export default {
  name: 'NEAR',
  chain: 'NATIVE',
  category: 'NOT_DEPIN',
  token: 'NEAR',
  coingeckoId: 'near',
  id: 'dnmt6p',
  description:
    'NEAR is a layer one, sharded, proof-of-stake blockchain built with usability in mind. It allows developers to create and distribute decentralized apps on any blockchain',
  discord: 'https://discord.com/invite/zfhfRpaM4m',
  investors: [
    'r1a7zj',
    'cvqnc5',
    '92ar5l',
    '6x081t',
    'a1wztr',
    '26x5nn',
    'f7094w',
    'ydmvp5',
    'xqq90r',
    '896jil',
    'r000x8',
    '4l8mmr',
    'h2tvqq',
    '2f68vj',
    '8nclhv',
    'ln7o85',
    '93qwp0',
    'hbpmm3',
    'b3o7lp',
    's4nry9',
    '2q9s6q',
    'r4uuo1',
    'xvqjcw',
    'la4mmt',
    'tuqdxz',
    '73opsz',
    'szfiug',
    '2i86sw',
    '2ckrz9',
    'fjt6b4',
    'ylo81y',
    'jefoou',
    'zyxvem',
    'v2rrnz',
    'r2lof0',
    '5tj4jx',
    'cm4vap',
    'g40hwu',
    'z6cdtc',
    'n9fb33',
    '2td0q3',
    'gzipi5',
    'uwuv2v',
    '0y66ov',
    'lsc0yi',
    '0a3jap',
    '5z78zh',
    'a3mqq8',
    'yoijyl',
    'ja2261',
    'tgyjdv',
    '9pp2xp',
    'l7sko2',
    'q9nh9n',
    'i1x9du',
    '4ssdn4',
    'gi55pp',
    'krji44',
    '3krjgm',
    '9p60sa',
    'hmfg3c',
    'il7ua1',
    '1a31l7',
    '7tpa9b',
    'fh8wrd',
    'dd123i',
    '2g0699',
    'co49ki',
    '65epfb',
    'fz3u0v',
    'lgw9c6',
    '1p1iry',
    '9ptsrm',
    'ozeg73',
    '6f2cxt',
    'eg5xoc',
    'g72mqv',
    'hxrlvs',
    'tdywri',
    'unykak',
    'ly85pz',
    '218prz',
    'kjy2i5',
    'pixi8p',
    'telo89',
    '003re3',
    'pu3yyr',
    'c4veok',
    'wgrsin',
    '4y2xx0',
    'rotj2h',
    'ugp187',
    'vo9rwo',
    'v6xlk7',
    '24ormv',
    'e0510f',
    '935mux',
    '0nsbs7',
  ],
  linkedin: 'https://www.linkedin.com/company/near-protocol-project/',
  duneQueries: null,
  blog: 'https://near.org/blog',
  github: 'https://github.com/near/dx',
  telegram: 'https://t.me/cryptonear',
  twitter: 'https://twitter.com/nearprotocol',
  url: 'https://near.org/',
} satisfies AdapterProject
