import { AdapterProject } from '../types'

export default {
  name: 'cPen',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'BINANCE',
  category: 'BLOCKCHAIN_INFRA',
  token: 'PEN',
  coinGeckoID: null,
  id: 'p64cip',
  description: 'cPen is a digital currency that users can mine on their phones.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/cPenCoreTeam',
  url: 'https://www.cpen.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
