import { AdapterProject } from '../types'

export default {
  name: 'Sallar',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'gh0uy7',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/sallar_io',
  url: 'https://sallar.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
