import { AdapterProject } from '../types'

export default {
  name: 'Mycelium',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'vi4exr',
  description: 'Mycelium is an enterprise DePIN deployer and operator of the Mycelium Testbed.',
  discord: '787027688548073522',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/myceliumnetworks',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@MyceliumX',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/myceliumx',
  url: 'https://www.myceliumnetworks.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
