import { AdapterProject } from '../types'

export default {
  name: 'Elixir',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ELXR',
  coingeckoId: 'elixir-finance',
  id: 'wrifq0',
  description: 'Elixir: Decentralized protocol for secure market-making.',
  discord: '1059691738349977674',
  investors: [
    '7job29',
    'dczq0j',
    'qzrkdy',
    'ykzwbk',
    'gwix1y',
    '5x9ujp',
    'jefoou',
    'mhnbyi',
    'a3mqq8',
    'lg8vhc',
    'azofz8',
    'zzypcf',
    '4giokv',
    'b04x9g',
    '07pxi6',
    '9qbjjp',
    '1dii55',
    'n6jtgl',
    'nlvx3r',
  ],
  linkedin: 'http://www.linkedin.com/company/elixir-protocol',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/elixirprotocol',
  twitter: 'https://twitter.com/ElixirProtocol',
  url: 'http://www.elixir.finance/',
  verified: false,
} satisfies AdapterProject
