import { AdapterProject } from '../types'

export default {
  name: 'Elixir',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'ELXR',
  coinGeckoID: 'elixir-finance',
  id: 'wrifq0',
  description: 'Elixir: Decentralized protocol for secure market-making.',
  discord: '1059691738349977674',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/elixir-protocol',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/elixirprotocol',
  twitter: 'https://twitter.com/ElixirProtocol',
  url: 'http://www.elixir.finance/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
