import { AdapterProject } from '../types'

export default {
  name: 'Internxt',
  ninja: 'ZZ',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'INXT',
  coinGeckoID: 'internxt',
  id: 'fsemso',
  description: 'Internxt is a provider of decentralized, privacy-focused cloud storage services.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://internxt.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
