import { AdapterProject } from '../types'

export default {
  name: 'SolLinked',
  ninja: null,
  subcategories: 'FHE',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'mdhiew',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/Sollinked_com',
  url: 'https://sollinked.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
