import { AdapterProject } from '../types'

export default {
  name: 'FWB',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'FWB',
  coinGeckoID: 'friends-with-benefits-pro',
  id: 'kcidbl',
  description:
    'Friends With Benefits is a new kind of social network made up of creatives and builders who believe in the promise of a better internet.',
  discord: '749418486874243212',
  investors: [
    '26x5nn',
    '73opsz',
    'zaf9xh',
    '0y8voh',
    'x10a41',
    'ybmlzh',
    'stdr1v',
    'gnhylz',
    'gj9v6c',
    '4e1ldf',
    'v35xwk',
    'ubuz3j',
  ],
  linkedin: 'https://www.linkedin.com/company/fwb-pro/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/fwbtweets',
  url: 'https://www.fwb.help/',
  verified: false,
} satisfies AdapterProject
