import { AdapterProject } from '../types'

export default {
  name: 'SolanaStock',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'kdsx3u',
  description: 'SolanaStock: Decentralized stock photo marketplace monetizes photos with AI.',
  discord: '428295358100013066',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/solanalabs',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://solana.com/news',
  github: 'https://solana.com/github',
  telegram: 'https://solana.com/telegram',
  twitter: 'https://solana.com/twitter',
  url: null,
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
