import { AdapterProject } from '../types'

export default {
  name: 'Cookbook.dev',
  ninja: 'vkurup.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'n7o4s9',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/cookbook_dev',
  url: 'https://www.cookbook.dev/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
