import { AdapterProject } from '../types'

export default {
  name: 'Fronesis',
  ninja: 'W. L.',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'nriggd',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/Fronesis_ai',
  url: 'https://fronesis.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
