import { AdapterProject } from '../types'

export default {
  name: 'ReGen',
  ninja: null,
  subcategories: 'Environmental',
  chain: 'COSMOS',
  category: 'NOT_DEPIN',
  token: 'REGEN',
  coinGeckoID: 'regen',
  id: 'sbgvjh',
  description: 'ReGen focuses on Hydrogen, Ammonia, and Methanol trading for the New Fuel Economy.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/regen-sw/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/regen_pk',
  url: 'https://www.regen.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
