import { AdapterProject } from '../types'

export default {
  name: 'Kryptview',
  ninja: null,
  subcategories: null,
  chain: 'NATIVE',
  category: 'BLOCKCHAIN_INFRA',
  token: 'KVT',
  coinGeckoID: 'kryptview',
  id: '3zopno',
  description: 'Kryptview rewards users for analyzing cryptos using P2P and Blockchain mechanisms.',
  discord: '925090445187506217',
  investors: [
    'mrgeec',
    '6jvbqx',
    '0f1owq',
    'o4gps9',
    'v81ftp',
    'azofz8',
    'rfjybl',
    '003re3',
    'jr9bwv',
    '2xfkvg',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://kryptview.medium.com/',
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/thekryptview?lang=en',
  url: 'https://kryptview.com/',
  verified: false,
  fundraisesUrls: ['https://www.finsmes.com/2023/04/kryptview-raises-1-5m-pre-seed-funding.html'],
} satisfies AdapterProject
