import { AdapterProject } from '../types'

export default {
  name: 'AristotleAI',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'gtqv1n',
  description: 'AristotleAI provides personalized learning experiences and insights.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/0xAristotleAI',
  url: 'https://www.aristotle-ai.com/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
