import { AdapterProject } from '../types'

export default {
  name: 'RONA',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'rvmlc7',
  description: '',
  discord: '1169527596841697311',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@rona.game',
  github: null,
  telegram: 'https://t.me/RonaGame_group',
  twitter: 'https://x.com/rona_gamejp',
  url: 'https://www.rona.game/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
