import { AdapterProject } from '../types'

export default {
  name: 'RONA',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'rvmlc7',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/rona_gamejp',
  url: 'https://www.rona.game/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
