import { AdapterProject } from '../types'

export default {
  name: 'enq',
  ninja: '0x0F46456F2D00d6a6F10FB18f6c36C0f03129C979',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'AI',
  token: 'ENQAI',
  coinGeckoID: null,
  id: 'i5b54g',
  description: 'enqAI is developing a Network for Decentralized Uncensored AI Models',
  discord: '1079425803441426562',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/noisegpt',
  twitter: 'https://twitter.com/enq_AI',
  url: 'https://enqai.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
