import { AdapterProject } from '../types'

export default {
  name: 'Peerz',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '4tfb4m',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/peerz_ai',
  url: 'https://peerz.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
