import { AdapterProject } from '../types'

export default {
  name: 'Aimedis',
  ninja: null,
  subcategories: 'Health & Fitness',
  chain: 'POLYGON',
  category: 'AI',
  token: 'AIMX',
  coinGeckoID: 'aimedis-new',
  id: 'p864om',
  description: 'Aimedis is a Blockchain-based eHealth with medical apps and an NFT marketplace.',
  discord: '1227808395617107998',
  investors: ['jkryns', 'imxksv'],
  linkedin: 'https://www.linkedin.com/company/aimedis/?originalSubdomain=nl',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/AimedisOfficialEnglish',
  twitter: 'https://twitter.com/AimedisGlobal',
  url: 'https://aimedis.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
