import { AdapterProject } from '../types'

export default {
  name: 'DTravel',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'SERVICES',
  token: 'TRVL',
  coingeckoId: 'dtravel',
  id: '37xksc',
  description:
    'DTravel is a decentralized platform for home-sharing economy, ensuring easy and secure short and long-term stays.',
  discord: '894038050999517184',
  investors: [
    'xmw0ev',
    '772xwk',
    'i98114',
    'qxuz9y',
    '1labbf',
    'rlo5x9',
    'jcbbxl',
    'micofj',
    'qqc9zd',
    'bah2fw',
    '07pxi6',
    'wfcztc',
    'ukwp87',
    'w19rhh',
    'hazkhs',
    'lhs5s8',
    'u2j4by',
  ],
  linkedin: 'https://www.linkedin.com/company/dtraveldao/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/dtravel-community',
  github: 'https://github.com/dTravel',
  telegram: 'https://t.me/dtravelcommunity',
  twitter: 'https://twitter.com/DtravelDAO',
  url: 'https://www.dtravel.com/',
  verified: false,
} satisfies AdapterProject
