import { AdapterProject } from '../types'

export default {
  name: 'Defog',
  ninja: null,
  subcategories: 'ML',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'u43dxj',
  description: 'Defog.ai helps enterprises deploy fine-tuned LLMs for enterprise analytics.',
  discord: null,
  investors: [],
  linkedin: 'https://github.com/defog-ai',
  duneQueries: null,
  foundingYear: null,
  blog: 'http://www.linkedin.com/company/defog-ai',
  github: 'https://defog.ai/blog/',
  telegram: null,
  twitter: 'https://twitter.com/defogdata',
  url: 'https://defog.ai/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
