import { AdapterProject } from '../types'

export default {
  name: 'NexGen Cloud',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'gw1fz5',
  description: 'NexGen Cloud: Affordable, sustainable cloud solutions for Web2 & Web3 ecosystems.',
  discord: null,
  investors: ['kv8oq2'],
  linkedin: 'https://www.linkedin.com/company/nexgen-cloud',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/CloudNexgen',
  url: 'https://www.nexgencloud.com/',
  verified: false,
  fundraisesUrls: ['https://www.finsmes.com/2022/03/nexgen-cloud-raises-14m-in-funding.html'],
} satisfies AdapterProject
