import { AdapterProject } from '../types'

export default {
  name: 'Ancient8',
  chain: 'ETHEREUM',
  category: 'OTHER',
  token: 'A8',
  coingeckoId: null,
  id: 'xjogkp',
  description:
    'Ancient8 is building a DAO that develops a community and software platform to enable everyone to play and build the Metaverse while earning rewards. Ancient8’s vision is to democratize social and financial access in the Metaverse, and is on a mission to reach, educate, and empower the next 100 million Metaverse citizens through the blockchain.',
  investors: [
    'pt62tc',
    'hol96b',
    'b5zojp',
    'gjt0lb',
    'h97beq',
    'wgnv1v',
    'voobdr',
    '73opsz',
    'enemyk',
    '5tj4jx',
    'qxuz9y',
    'ifb7yv',
    'gokqn0',
    'ja2261',
    'lox6un',
    'ixk61j',
    'i1x9du',
    'gi55pp',
    '4cvh3k',
    '6iqdv9',
    'a4hdnk',
    'f8xkmh',
    '9kyndm',
    '8rcqvw',
    'k9u90q',
    '2qk2oi',
    'l3imfr',
    'ozeg73',
    'v0jbet',
    'hlwtnm',
    'mx8grh',
    'yibv9g',
    'm05wan',
    'ksae6d',
    'lhs5s8',
    'ofi3r7',
    'm5cayq',
    '5o347p',
    'pt9rpd',
    '4n29wi',
    '4pj3dm',
  ],
  duneQueries: null,
  blog: 'https://blog.ancient8.gg/',
  github: null,
  telegram: 'https://t.me/ancient8_gg',
  twitter: 'https://twitter.com/Ancient8_gg',
} satisfies AdapterProject
