import { AdapterProject } from '../types'

export default {
  name: 'Ancient8',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'A8',
  coingeckoId: null,
  id: 'xjogkp',
  description:
    'Ancient8 is building a DAO that develops a community and software platform to enable everyone to play and build the Metaverse while earning rewards.',
  discord: '882274636342116372',
  investors: [
    'pt62tc',
    'hol96b',
    'b5zojp',
    'gjt0lb',
    'h97beq',
    'wgnv1v',
    'voobdr',
    '73opsz',
    'enemyk',
    '5tj4jx',
    'qxuz9y',
    'ifb7yv',
    'gokqn0',
    'ja2261',
    'lox6un',
    'ixk61j',
    'i1x9du',
    'gi55pp',
    '4cvh3k',
    '6iqdv9',
    'a4hdnk',
    'f8xkmh',
    '9kyndm',
    '8rcqvw',
    'k9u90q',
    '2qk2oi',
    'l3imfr',
    'ozeg73',
    'v0jbet',
    'hlwtnm',
    'mx8grh',
    'yibv9g',
    'm05wan',
    'ksae6d',
    'lhs5s8',
    'ofi3r7',
    'm5cayq',
    '5o347p',
    'pt9rpd',
    '4n29wi',
    '4pj3dm',
  ],
  linkedin: 'https://www.linkedin.com/company/ancient8/about/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.ancient8.gg/',
  github: null,
  telegram: 'https://t.me/ancient8_gg',
  twitter: 'https://twitter.com/Ancient8_gg',
  url: 'https://www.ancient8.gg/',
  verified: false,
} satisfies AdapterProject
