import { AdapterProject } from '../types'

export default {
  name: 'myMessage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: '1rcuf0',
  description:
    'myMessage is a decentralized data storage protocol enabling secure, low-cost storage and transfer.',
  discord: 'https://discord.com/invite/BCKyD3HxRh',
  investors: [
    'xmw0ev',
    'oaw1ui',
    'vcxbpn',
    '2h4i1m',
    'nu9e33',
    '35e9e6',
    'tel396',
    'xx442f',
    'wrehju',
    '870le2',
    'fdzd99',
    '243kcn',
    'ofj0rs',
    '41gpqf',
    '5zxzuu',
    'yibv9g',
    'z1ww7b',
    'xvgf6w',
    'nj1v3c',
    'brmebh',
    '0nsbs7',
  ],
  linkedin: 'https://linkedin.com/company/mymessageofficial',
  duneQueries: null,
  blog: 'https://medium.com/@myMessage',
  github: 'https://github.com/myMessageio',
  telegram: 'https://t.me/mymessageEN',
  twitter: 'https://twitter.com/myMessageOS',
  url: 'https://www.mymessage.io/',
} satisfies AdapterProject
