import { AdapterProject } from '../types'

export default {
  name: 'myMessage',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: '1rcuf0',
  description:
    'myMessage is a decentralized data storage protocol enabling secure, low-cost storage and transfer.',
  investors: [
    'xmw0ev',
    'oaw1ui',
    'vcxbpn',
    '2h4i1m',
    'nu9e33',
    '35e9e6',
    'tel396',
    'xx442f',
    'wrehju',
    '870le2',
    'fdzd99',
    '243kcn',
    'ofj0rs',
    '41gpqf',
    '5zxzuu',
    'yibv9g',
    'z1ww7b',
    'xvgf6w',
    'nj1v3c',
    'brmebh',
    '0nsbs7',
  ],
  duneQueries: null,
} satisfies AdapterProject
