import { AdapterProject } from '../types'

export default {
  name: 'idOS',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'oe1vcp',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/idOS_network',
  url: 'https://idos.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
