import { AdapterProject } from '../types'

export default {
  name: 'nodeweb.ai',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'u69474',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/nodewebai',
  url: 'https://www.nodeweb.ai/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
