import { AdapterProject } from '../types'

export default {
  name: 'delta.theta',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'DLTA',
  coinGeckoID: 'delta-theta',
  id: '88l6l8',
  description: 'delta.theta is a Peer-to-peer asset options trading platform.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://deltatheta.tech/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
