import { AdapterProject } from '../types'

export default {
  name: 'Zeppelin',
  ninja: null,
  subcategories: 'Mining',
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'cvzsdf',
  description: 'Zeppelin aims to be the global leader in decentralized wireless infrastructure.',
  discord: null,
  investors: ['hol96b', '7zvxz8', 'rmj9ht', 'v81ftp'],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.zeppelinwireless.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
