import { AdapterProject } from '../types'

export default {
  name: 'TAL',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: '7et9go',
  description: 'TAL: Decentralized AI verification on Solana.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/tal_2/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@thevaizman',
  github: 'https://github.com/topics/tal',
  telegram: null,
  twitter: 'https://twitter.com/talwilkenfeld',
  url: 'https://buildontal.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
