import { AdapterProject } from '../types'

export default {
  name: 'Media',
  ninja: 'W. L.',
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'COMPUTE',
  token: 'MEDIA',
  coinGeckoID: 'media-network',
  id: 'iqnvgc',
  description: 'Media Network is a decentralized hub for web services.',
  discord: '832942573642973194',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/media-network-inc./about/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://mediafoundation.medium.com/',
  github: 'https://github.com/mediafoundation',
  telegram: 'https://t.me/Media_FDN',
  twitter: 'https://twitter.com/Media_FDN',
  url: 'https://www.media.network/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
