import { AdapterProject } from '../types'

export default {
  name: 'Orchai',
  ninja: null,
  subcategories: 'DeFi',
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'h6vfie',
  description: 'Orchai: AI-powered DeFi platform optimizing asset flow.',
  discord: '1001025635302522960',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/orchai/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/orchaiofficial',
  twitter: 'https://twitter.com/orchai_protocol',
  url: 'https://orchai.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
