import { AdapterProject } from '../types'

export default {
  name: 'RPGDepin',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '0fr6gy',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/DepinRpg',
  url: 'https://www.rpgs.work/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
