import { AdapterProject } from '../types'

export default {
  name: 'DeMe',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'oqb51e',
  description: 'DeMe: a user privacy-focused social media with rewards.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/demesocial/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/DecentralisedMe',
  url: 'https://deme.social/#',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
