import { AdapterProject } from '../types'

export default {
  name: 'Lifechain',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'nihfn5',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.lifechainfoundation.com/chain',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
