import { AdapterProject } from '../types'

export default {
  name: 'Integritee',
  ninja: null,
  subcategories: 'TEE',
  chain: 'POLKADOT',
  category: 'BLOCKCHAIN_INFRA',
  token: 'TEER',
  coinGeckoID: 'integritee',
  id: '6hlk6x',
  description: 'Integritee is a TEE-based secure computation platform.',
  discord: '877203191396192316',
  investors: [
    'gvqos9',
    'xmw0ev',
    'jbacwh',
    '0hfvt9',
    'zu1950',
    'lzrigs',
    'r2lof0',
    'lfbmt3',
    'i1vs03',
    'lsc0yi',
    'h7yooe',
    'gi55pp',
    '89glxu',
    'qqc9zd',
    '9kyndm',
    '07pxi6',
    'smqwtv',
    'pu3yyr',
  ],
  linkedin: 'http://www.linkedin.com/company/integritee',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://www.integritee.network/blog',
  github: null,
  telegram: 'https://t.me/Integritee_Official',
  twitter: 'https://twitter.com/integri_t_e_e',
  url: 'https://www.integritee.network/',
  verified: false,
} satisfies AdapterProject
