import { AdapterProject } from '../types'

export default {
  name: 'WatchX',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'pa7uyl',
  description: 'watchX is a Do it Yourself easy to program Smartwatch Kit for STEM Education.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/officialwatchx',
  url: 'https://www.watchx.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
