import { AdapterProject } from '../types'

export default {
  name: 'Linera',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'avq9ep',
  description:
    'Linera is a Blockchain Infrastructure for Highly Scalable Web3 Applications that give users their own blockspace with microchains.',
  discord: 'https://discord.com/invite/linera',
  investors: [
    '26x5nn',
    'zloyr1',
    'lpvwf1',
    'buo8ql',
    'nk4njt',
    'nbuvjs',
    'ee27i4',
    'vw2n89',
    '9d13la',
    'v81ftp',
    '8zouxb',
    'egtjkt',
    '1hc0e8',
    'fhd6hx',
    'beum1u',
    'b04x9g',
    '65epfb',
    'hfmbi5',
    'due5zk',
  ],
  linkedin: 'https://www.linkedin.com/company/linera-io/',
  duneQueries: null,
  blog: 'https://medium.com/@linera',
  github: null,
  telegram: 'https://t.me/linera_official',
  twitter: 'https://twitter.com/linera_io',
  url: 'https://linera.io/',
} satisfies AdapterProject
