import { AdapterProject } from '../types'

export default {
  name: 'ScPrime',
  ninja: null,
  subcategories: 'Storage',
  chain: 'NATIVE',
  category: 'COMPUTE',
  token: 'D2X',
  coinGeckoID: 'd2',
  id: 'ui2nbm',
  description: 'ScPrime is a decentralized network of enterprise-grade cloud storage providers.',
  discord: '500467593375645706',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/scp-corp',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://scpri.me/articles/',
  github: 'https://gitlab.com/scpcorp/',
  telegram: null,
  twitter: 'https://twitter.com/ScPrimeCloud',
  url: 'https://scpri.me/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
