import { AdapterProject } from '../types'

export default {
  name: 'ScPrime',
  ninja: '0x7Ef3169903033C30FF3Da674BD793B236F21B026',
  subcategories: 'Storage',
  chain: 'SOLANA',
  category: 'COMPUTE',
  token: 'SCP',
  coinGeckoID: 'siaprime-coin',
  id: 'ui2nbm',
  description: 'ScPrime is a decentralized network of enterprise-grade cloud storage providers.',
  discord: '500467593375645706',
  investors: [],
  linkedin: 'https://www.linkedin.com/company/scp-corp',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://scpri.me/articles/',
  github: 'https://gitlab.com/scpcorp/',
  telegram: null,
  twitter: 'https://twitter.com/ScPrimeCloud',
  url: 'https://scpri.me/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
