import { AdapterProject } from '../types'

export default {
  name: 'Nodle',
  chain: 'POLKADOT',
  category: 'WIRELESS',
  token: 'NODL',
  coingeckoId: 'nodle-network',
  id: 'znawjs',
  description:
    'Nodle is a smartphone-powered decentralized data network and payment infrastructure for IoT.',
  investors: [
    'ycxcre',
    'gvqos9',
    'vcxbpn',
    '3rh50q',
    'czdr0x',
    '4gopjr',
    'oi4yuk',
    'uk7nly',
    '1u17l7',
    'aeow3c',
    '798xl8',
    'drq7a8',
    'fjwux2',
    'pzek1v',
    'okjrd0',
    '9n4okv',
    'vpd5fe',
    'a1ncs7',
    'q82gy5',
    '1kxhn8',
    'z99lv0',
    'tzyxtr',
    'x8rbk6',
    '5252r4',
    '3cjty6',
    'rw36w8',
    '11dur6',
    '0nl0fg',
    'eg5xoc',
    '5jp8tr',
    'ojmjsk',
    'tnf5cs',
    'nf3ei2',
    'tktadr',
    'ba852j',
    'n24ti7',
    'il9nc7',
    'fqpd8v',
    'p5t7hp',
    'u1jo7t',
    'bnhsos',
  ],
  duneQueries: null,
} satisfies AdapterProject
