import { AdapterProject } from '../types'

export default {
  name: 'Hivemapper',
  chain: 'SOLANA',
  category: 'SENSORS',
  token: 'HONEY',
  coingeckoId: 'hivemapper',
  id: 'o1qnxa',
  description: 'Hivemapper is a decentralized network forstreet-level imaging & mapping.',
  investors: [
    '2g0699',
    'gj9v6c',
    '3k9ouz',
    'ac7ofh',
    'ujjw80',
    'shz3zr',
    'qcsvko',
    'zwbf5f',
    'd5rl72',
    'nxop7l',
    'bfuras',
    'w20x2z',
    'hx50gm',
    'uuzdmh',
    'k9knce',
    'hxuiac',
    'tgyjdv',
    'yxary3',
    'sp9c89',
    '7cf8ay',
    'quqh7m',
    '9e3q0l',
    '7o7kkl',
    'cjmn2h',
    'tlb60n',
    'x9qw9x',
  ],
  cmcId: 22850,
} satisfies AdapterProject
