import { AdapterProject } from '../types'

export default {
  name: 'Hivemapper',
  ninja: null,
  subcategories: 'Positioning',
  chain: 'SOLANA',
  category: 'SENSORS',
  token: 'HONEY',
  coinGeckoID: 'hivemapper',
  id: 'o1qnxa',
  description: 'Hivemapper is a decentralized network for street-level imaging and mapping.',
  discord: '715439007764316191',
  investors: [
    '8vyzyl',
    'i6sgg1',
    'mpsbnn',
    'yont93',
    'dfsp8g',
    'tgyjdv',
    '2g0699',
    'cjmn2h',
    'tlb60n',
    'gj9v6c',
  ],
  linkedin: 'https://www.linkedin.com/company/hivemapper/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@hivemapper',
  github: 'https://github.com/hivemapper',
  telegram: null,
  twitter: 'https://twitter.com/Hivemapper',
  url: 'https://hivemapper.com/explorer',
  verified: false,
  fundraisesUrls: [
    'https://www.businesswire.com/news/home/20220405005894/en/Hivemapper-Raises-18M-From-Multicoin-Capital-to-Create-the-World%E2%80%99s-First-Decentralized-Mapping-Network',
  ],
} satisfies AdapterProject
