import { AdapterProject } from '../types'

export default {
  name: 'Mindsync',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'gpjz8o',
  description: 'Mindsync connects AI enthusiasts, miners, and businesses for AI solutions.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/mindsync/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/mindsync-ai',
  github: 'https://github.com/mindsync-ai',
  telegram: 'https://t.me/mindsyncai',
  twitter: 'https://twitter.com/mind_sync',
  url: 'https://mindsync.ai/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
