import { AdapterProject } from '../types'

export default {
  name: 'Rainfall',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'jtmdi1',
  description: 'Empower billions of people via self-sovereign Personal AI.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://rainfall.one/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
