import { AdapterProject } from '../types'

export default {
  name: 'Peri',
  ninja: '0x49eb81cc817cD5a1E8Df590F43D5A0A0F432251A',
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'gbhi78',
  description: 'Peri Labs is a deep research lab developing an optimization layer for Edge AI.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/peri_labs',
  url: 'https://www.perilabs.net/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
