import { AdapterProject } from '../types'

export default {
  name: 'Luma Protocol',
  ninja: '0x25052A4B28a35FfdBf2FaBA7DCCEB350e91b908F',
  subcategories: 'DeSci',
  chain: 'SOLANA',
  category: 'BLOCKCHAIN_INFRA',
  token: 'LUMA',
  coinGeckoID: null,
  id: '1gblon',
  description: 'Luma Protocol is a DePIN-focused Dex on Solana.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/luma_protocol',
  url: 'https://www.lumaprotocol.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
