import { AdapterProject } from '../types'

export default {
  name: 'Subsquid',
  chain: null,
  category: 'OTHER',
  token: null,
  coingeckoId: null,
  id: 'cp4cw6',
  description:
    'Subsquid: Open-source framework to extract & present blockchain data as GraphQL APIs for Web3 builders.',
  discord: 'https://discord.com/invite/subsquid',
  investors: [
    'k93k29',
    'ii5tnv',
    '6uuq9l',
    'm6mz4i',
    '92bx7w',
    'r2lof0',
    'k1qvmn',
    'hxk2ck',
    'vkntey',
    '9xb78i',
    '8zouxb',
    'uqfti3',
    'q9qqsj',
    'qyzsbd',
    'bah2fw',
    '65epfb',
    '44u6gg',
    'oltsrb',
    'oy5ooz',
    'l1cbmz',
    'gy5k6a',
    'urug6u',
    'lll7yl',
  ],
  linkedin: 'https://ch.linkedin.com/company/subsquid',
  duneQueries: null,
  blog: 'https://subsquid.medium.com/',
  github: 'https://github.com/subsquid',
  telegram: 'https://t.me/subsquid',
  twitter: 'https://twitter.com/subsquid',
  url: 'https://www.subsquid.io/',
} satisfies AdapterProject
