import { AdapterProject } from '../types'

export default {
  name: 'Theta Fuel',
  chain: 'NATIVE',
  category: 'COMPUTE',
  token: 'TFUEL',
  coingeckoId: 'theta-fuel',
  id: 'bsun3b',
  description: 'Theta Fuel is a decentralized video delivery network.',
  investors: [
    '2gx4h3',
    '8si3f3',
    'buime9',
    'muazsx',
    'q4zzkd',
    '03yfei',
    'eecm9d',
    'dm8c6w',
    'jtci9b',
    '772xwk',
    'c94bgn',
    '1qi0o8',
    'qriiq5',
    'sqo7f5',
    '6lkk39',
    '4vsf2b',
    'y5m26s',
    'ugqddc',
    'gftio8',
    'bzh3wn',
    'fxmvug',
    'lp0gdl',
    'i1x9du',
    'safmd6',
    '89glxu',
    'kzsrt6',
    'owrgxe',
    'xl9a26',
    'yibv9g',
    '1im0oz',
    '83uzvl',
    'jsixr8',
    'two8m9',
    'htcsi1',
    'p663q8',
    'yb6ohe',
    '6jmeak',
    'xemx4j',
  ],
  duneQueries: null,
} satisfies AdapterProject
