import { AdapterProject } from '../types'

export default {
  name: 'Theta Fuel',
  ninja: null,
  subcategories: null,
  chain: 'NATIVE',
  category: 'COMPUTE',
  token: 'TFUEL',
  coinGeckoID: 'theta-fuel',
  id: 'bsun3b',
  description: 'Theta Fuel is a decentralized video delivery network.',
  discord: '808417775978676265',
  investors: [
    '2gx4h3',
    '8si3f3',
    'buime9',
    'muazsx',
    'q4zzkd',
    '03yfei',
    'eecm9d',
    'dm8c6w',
    'jtci9b',
    '772xwk',
    'c94bgn',
    '1qi0o8',
    'qriiq5',
    'sqo7f5',
    '6lkk39',
    '4vsf2b',
    'y5m26s',
    'ugqddc',
    'gftio8',
    'bzh3wn',
    'fxmvug',
    'lp0gdl',
    'i1x9du',
    'safmd6',
    '89glxu',
    'kzsrt6',
    'owrgxe',
    'xl9a26',
    'yibv9g',
    '1im0oz',
    '83uzvl',
    'jsixr8',
    'two8m9',
    'htcsi1',
    'p663q8',
    'yb6ohe',
    '6jmeak',
    'xemx4j',
  ],
  linkedin: 'http://www.linkedin.com/company/theta-labs-inc',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/theta-network',
  github: 'https://github.com/thetatoken',
  telegram: 'https://t.me/s/thetanetwork_announcements?before=516',
  twitter: 'https://twitter.com/Theta_Network',
  url: 'https://thetatoken.org/',
  verified: false,
  fundraisesUrls: [
    'https://coinchapter.com/institutional-investors-stake-over-100-million-in-theta-network/',
  ],
} satisfies AdapterProject
