import { AdapterProject } from '../types'

export default {
  name: 'Theta Fuel',
  chain: 'NATIVE',
  category: 'COMPUTE',
  token: 'TFUEL',
  coingeckoId: 'theta-fuel',
  id: 'bsun3b',
  description: 'Theta Fuel is a decentralized video delivery network.',
  investors: [
    '2gx4h3',
    'buime9',
    'muazsx',
    'te4xtz',
    '03yfei',
    'eecm9d',
    '6qckmm',
    'jtci9b',
    '772xwk',
    'c94bgn',
    '1qi0o8',
    'qriiq5',
    'sqo7f5',
    '6lkk39',
    '4vsf2b',
    'y5m26s',
    'ugqddc',
    'gftio8',
    'bzh3wn',
    'fxmvug',
    'lp0gdl',
    'i1x9du',
    'safmd6',
    '1u19m7',
    '948drp',
    'kzsrt6',
    'owrgxe',
    '3cjty6',
    'yibv9g',
    '1im0oz',
    'gx8ia4',
    'jsixr8',
    '5i0u5y',
    'htcsi1',
    'p663q8',
    'tuqiv1',
    '6jmeak',
    'xemx4j',
  ],
  duneQueries: null,
} satisfies AdapterProject
