import { AdapterProject } from '../types'

export default {
  name: 'Valist',
  ninja: null,
  subcategories: 'Gaming',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'g2jtmx',
  description: 'Valist: Decentralized platform for game deployment on Web2 and Web3.',
  discord: '785535462311591976',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/valist-inc',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/valist-io',
  telegram: null,
  twitter: 'https://twitter.com/valist_io',
  url: 'https://www.valist.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
