import { AdapterProject } from '../types'

export default {
  name: 'Stackr',
  ninja: null,
  subcategories: 'Software',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'l3144f',
  description:
    'Stackr SDK is a framework to build app-specific micro-rollups in web2 programming languages.',
  discord: '1018902999982161990',
  investors: [
    '26x5nn',
    'f7094w',
    'xh3wwp',
    'ze1wdg',
    'nn6lp1',
    's10ggg',
    '5qcfza',
    'kjm7ph',
    'd7vmfz',
    'h2yy1z',
    'k6tpgr',
    'telo89',
    'pgoyl5',
    'kr30sy',
    't9j2qz',
    'vrvfoj',
  ],
  linkedin: 'https://www.linkedin.com/company/stackr-labs/about/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/0xStackr',
  url: 'http://www.stackrlabs.xyz/',
  verified: false,
} satisfies AdapterProject
