import { AdapterProject } from '../types'

export default {
  name: 'IOEN',
  ninja: 'wholovesburrito.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: 'xzwxgd',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/IOEN_tech',
  url: 'https://www.ioen.tech/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
