import { AdapterProject } from '../types'

export default {
  name: 'Ingonyama',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'cv434n',
  description:
    'A next-generation semiconductor company that focus on finding and solving computational bottlenecks in ZKP. ICICLE is an open-source library for ZK acceleration using CUDA-enabled GPUs.',
  discord: null,
  investors: [
    'l18dl4',
    'jo973z',
    'saw27c',
    'm5pwht',
    'n231lw',
    'ejxwgz',
    '4mvdzs',
    '8agdnp',
    'ti312b',
    '1im0oz',
    'f1wn0g',
    'vrsed8',
    'jzvvbx',
    'z86cg4',
  ],
  linkedin: 'https://www.linkedin.com/company/ingonyama/',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@ingonyama',
  github: 'https://github.com/ingonyama-zk',
  telegram: null,
  twitter: 'https://twitter.com/Ingo_zk',
  url: 'https://www.ingonyama.com/',
  verified: false,
} satisfies AdapterProject
