import { AdapterProject } from '../types'

export default {
  name: 'Mawari',
  ninja: null,
  subcategories: 'CDN',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'ygaj99',
  description: 'Mawari: Decentralized 3D content delivery platform for mobile XR devices.',
  discord: null,
  investors: [
    'muqrv1',
    'qzewsg',
    'bh4wd4',
    'igwwfx',
    'hbpmm3',
    'rbelby',
    'vjpj24',
    'zj4ect',
    '4219d0',
    '6x8jib',
  ],
  linkedin: 'https://www.linkedin.com/company/mawari/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/mawarijp',
  url: 'https://www.mawari.io/',
  verified: false,
} satisfies AdapterProject
