import { AdapterProject } from '../types'

export default {
  name: 'Zoth',
  ninja: null,
  subcategories: 'RWA',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: '4l25dn',
  description: 'Zoth is an on-chain marketplace for Real World Assets (RWAs).',
  discord: null,
  investors: [
    'oixym4',
    'wv0c6u',
    '17gwc8',
    'z7nhe9',
    'b88od5',
    '8bpixq',
    't4yd43',
    '1d0vnd',
    '1tnc8x',
    'h6gukx',
    'fvpynw',
    'sv52so',
    'l4ot1d',
    '8cibwi',
    'hesk1z',
    'p65ot4',
    'v450ah',
  ],
  linkedin: 'https://github.com/0xZothio',
  duneQueries: null,
  foundingYear: null,
  blog: 'http://www.linkedin.com/company/zoth-io',
  github: null,
  telegram: 'https://telegram.me/+nFUrC_I1hA1iNWU9',
  twitter: 'https://twitter.com/i/flow/login?redirect_after_login=%2Fzothdotio',
  url: 'https://zoth.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
