import { AdapterProject } from '../types'

export default {
  name: 'Owl',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'ENERGY',
  token: 'OWL',
  coinGeckoID: null,
  id: 'ok01cq',
  description: 'Owl is a decentralized network of phone charging stations.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://owlnetwork.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
