import { AdapterProject } from '../types'

export default {
  name: 'q-ctrl',
  ninja: null,
  subcategories: 'Quantum',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: '69yd7k',
  description:
    'Q-ctrl uniquely addresses the problem of hardware error and instability in quantum computing, entirely through software.',
  discord: null,
  investors: [
    'rz0q81',
    '4bc5rd',
    '5rzcio',
    'stvmbz',
    '3xr5rh',
    '4vwk0l',
    'vghgy8',
    'ydmc3p',
    'ilwy9t',
    'd3ronc',
  ],
  linkedin: 'https://www.linkedin.com/company/q-ctrl/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/qctrl',
  telegram: null,
  twitter: 'https://twitter.com/qctrlHQ',
  url: 'https://q-ctrl.com/',
  verified: false,
} satisfies AdapterProject
