import { AdapterProject } from '../types'

export default {
  name: 'Blockride',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'RWA',
  token: null,
  coinGeckoID: null,
  id: '84nnyv',
  description: 'Blockride: democratizing vehicle financing in Africa through crypto assets.',
  discord: '994991249071288430',
  investors: [],
  linkedin: 'http://www.linkedin.com/company/blockride',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/@info.blockride/hello-world-7d0e75386221',
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.blockride.xyz/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
