import { AdapterProject } from '../types'

export default {
  name: 'LM Studio',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'vh0qps',
  description: 'LM Studio allows users to run local/open LLMs on their computers.',
  discord: '1110598183144399058',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: 'https://github.com/lmstudio-ai',
  telegram: null,
  twitter: 'https://twitter.com/LMStudioAI',
  url: 'https://lmstudio.ai/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
