import { AdapterProject } from '../types'

export default {
  name: 'Meson',
  ninja: null,
  subcategories: 'CDN',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'wop23m',
  description: 'Meson is building a decentralized CDN and Bandwidth Exchange.',
  discord: '784251111678148608',
  investors: [
    'oplwzc',
    'suthoi',
    'apd14v',
    '772xwk',
    'us9d7q',
    'nxzb7m',
    'vn2xbi',
    'xq7npm',
    'sk9qn6',
    'thxgaw',
    'ikeqay',
    'ivtzio',
    'smqwtv',
    'nym997',
    '6j16uu',
    'h9g1s5',
    'uqojef',
    'm05wan',
    'pu3yyr',
    'l24zdj',
    'pcw959',
    '1m3pt6',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.meson.network/',
  verified: false,
  fundraises: [
    {
      roundType: 'Private/Public token sale',
      url: 'https://twitter.com/NetworkMeson/status/1755662941511356581',
    },
    {
      roundType: 'Seed',
      url: 'https://finance.yahoo.com/news/meson-network-raises-3-5m-131500338.html',
    },
    {
      roundType: 'Strategic/Angel',
      url: 'https://crypto-fundraising.info/projects/meson-network/',
    },
    {
      roundType: 'Strategic/Angel',
      url: 'https://twitter.com/NetworkMeson/status/1768445122914775217',
    },
  ],
} satisfies AdapterProject
