import { AdapterProject } from '../types'

export default {
  name: 'Meson',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coingeckoId: null,
  id: 'q3ku4k',
  description: 'Meson is building the world’s first decentralized Bandwidth Exchange.',
  investors: [
    '5yy6cw',
    '2tgqti',
    'jqz0zw',
    'pu3yyr',
    'gun7y3',
    'suthoi',
    '772xwk',
    '9td18r',
    'lhs5s8',
    'hhudw8',
    'nxzb7m',
    'pcw959',
    'aeow3c',
    'b1hrk6',
    'q9nh9n',
    'vn2xbi',
    'sk9qn6',
    'h9g1s5',
    'oltsrb',
    'g738qx',
    '6ln74n',
    'thxgaw',
    'ilml5k',
    'ifb7yv',
    'tnhwwr',
    'cwh18x',
    'yv5v8q',
    'ivtzio',
    'm2otz0',
    'nym997',
    'm05wan',
    'lg91ns',
    'ezr70r',
    'hkzxu8',
    'fikwo5',
  ],
  cmcId: 27026,
} satisfies AdapterProject
