import { AdapterProject } from '../types'

export default {
  name: 'OpenAgents',
  ninja: 'ZZ',
  subcategories: 'Agents',
  chain: null,
  category: 'AI',
  token: null,
  coinGeckoID: null,
  id: 'zh7o1l',
  description: 'OpenAgents is a platform for building, selling and using AI agents.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/OpenAgentsInc',
  url: 'https://openagents.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
