import { AdapterProject } from '../types'

export default {
  name: 'Exabits',
  ninja: null,
  subcategories: 'GPUs',
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'ks1fra',
  description:
    'exaBITS is a decentralized infrastructure for AI and computationally intensive applications.',
  discord: '1105999312393076877',
  investors: [
    '4l8mmr',
    '94d9pz',
    'aju8zg',
    'g4z7os',
    '89glxu',
    'yh3lfl',
    'vjpj24',
    't3kcho',
    'loynnk',
    'ti312b',
    '5nt3w6',
    '9cx2zp',
  ],
  linkedin: 'http://www.linkedin.com/company/exabits',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/decentralizedcomputing',
  github: null,
  telegram: 'https://t.me/+D0CulDl9udZjMWIx',
  twitter: 'https://twitter.com/exa_bits',
  url: 'https://www.exabits.ai/',
  verified: false,
  fundraises: [
    {
      roundType: 'Preseed',
      url: 'https://twitter.com/exa_bits/status/1753121707806826800',
    },
  ],
  isApp: true,
} satisfies AdapterProject
