import { AdapterProject } from '../types'

export default {
  name: 'RobotEra',
  ninja: null,
  subcategories: 'Gaming',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 't7b6bu',
  description: 'RobotEra: play-to-earn gaming with NFTs and metaverse world-building.',
  discord: null,
  investors: [],
  linkedin: 'https://www.linkedin.com/company/robot-era/',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: 'https://t.me/+_wOHpPocsxE3NjBh',
  twitter: 'https://twitter.com/robotera_io',
  url: 'https://robotera.io/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
