import { AdapterProject } from '../types'

export default {
  name: 'Project Internet Capacity',
  ninja: 'sal-gala.eth',
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '6t4nx8',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/threefold_io',
  url: 'https://projectinternetcapacity.com/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
