import { AdapterProject } from '../types'

export default {
  name: 'Questbook',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coingeckoId: null,
  id: 'c5xom1',
  description: 'Grants program management software.',
  investors: [
    'y04p2x',
    'kli6og',
    '5fy5l2',
    'j2n1wh',
    'cz996v',
    '896jil',
    'ca0yhb',
    'suthoi',
    '73opsz',
    '5tj4jx',
    'lygwx0',
    'lfk2td',
    'ajzzhi',
    '8fv3lj',
    'ckjv3m',
    'ja2261',
    'knxp8u',
    'u5jibe',
    'ptvey1',
    'q84v53',
    'kjm7ph',
    'ru6grc',
    '8rcqvw',
    '2mtu07',
    'occbmd',
    '8agdnp',
    'uqn8uq',
    'shz3zr',
    'pgoyl5',
    'bd6os6',
    'v2sslg',
    'due5zk',
    'pu9sq2',
    'a1da8k',
    'wdtkj1',
  ],
  duneQueries: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://questbook.app/',
} satisfies AdapterProject
