import { AdapterProject } from '../types'

export default {
  name: 'Questbook',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'c5xom1',
  description: 'Grants program management software.',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://questbook.app/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
