import { AdapterProject } from '../types'

export default {
  name: 'Brume',
  ninja: 'EV3 Sal',
  subcategories: null,
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'nr3e02',
  description: 'The private Ethereum wallet with built-in Tor',
  discord: '1101132502963322880',
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://bento.me/brume',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
