import { AdapterProject } from '../types'

export default {
  name: 'Verasity',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'BLOCKCHAIN_INFRA',
  token: 'VRA',
  coinGeckoID: 'verasity',
  id: '20y2yy',
  description: 'Verasity is a decentralized ecosystem of digital advertisers and merchants.',
  discord: '850659368953577492',
  investors: [],
  linkedin: 'https://vg.linkedin.com/company/verasity',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://medium.com/verasity',
  github: 'https://github.com/veracity',
  telegram: 'https://t.me/verasity',
  twitter: 'https://twitter.com/verasitytech',
  url: 'https://verasity.io/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
