import { AdapterProject } from '../types'

export default {
  name: 'Boson',
  ninja: null,
  subcategories: null,
  chain: 'ETHEREUM',
  category: 'NOT_DEPIN',
  token: 'BOSON',
  coinGeckoID: 'boson-protocol',
  id: 'nzimvj',
  description:
    "Boson Protocol's Web3 Commerce Layer enables the tokenization, transfer and trade of any physical thing as a redeemable NFT.",
  discord: '811155042714779678',
  investors: [
    'ycxcre',
    'cvqnc5',
    'spurmc',
    'gjt0lb',
    '8nclhv',
    'oi4yuk',
    'zqdy3j',
    'e1im3l',
    'bd260g',
    '6hezki',
    '35e9e6',
    'yi5hs8',
    'rwthif',
    'lfbmt3',
    'mar9ip',
    'i1vs03',
    'okjrd0',
    'fnoivv',
    'qckvg6',
    'ka4f30',
    'bah2fw',
    'dd123i',
    'vjpj24',
    '11dur6',
    '5giv9q',
    'h9g1s5',
    'bnge9y',
    'zzmhe1',
    'nwl5v7',
    'e0510f',
    't44ifr',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.bosonprotocol.io/',
  verified: false,
} satisfies AdapterProject
