import { AdapterProject } from '../types'

export default {
  name: 'Smlxl',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'COMPUTE',
  token: null,
  coinGeckoID: null,
  id: 'x6phis',
  description:
    'At smlXL, we spend much time diving into solc - our latest blog series (3 parts) will cover areas of solc that lack documentation yet are essential (and interesting).',
  discord: null,
  investors: [
    'd40or5',
    'rny435',
    'lmdm54',
    'ul6tyf',
    'jwgb9c',
    '419x6r',
    'izhh27',
    'co49ki',
    '3cjty6',
    'uulo45',
    'ta1eea',
    'sz5x0j',
    'k8lm1b',
  ],
  linkedin: 'https://www.linkedin.com/company/smlxl-tech',
  duneQueries: null,
  foundingYear: null,
  blog: 'https://blog.smlxl.io/',
  github: 'https://github.com/smlxl',
  telegram: null,
  twitter: 'https://twitter.com/smlxldotio',
  url: 'https://smlxl.io/',
  verified: false,
  fundraisesUrls: [
    'https://fortune.com/crypto/2023/10/24/smlxl-a16z-dor-levi-lyft-blockchains-funding-round/',
  ],
} satisfies AdapterProject
