import { AdapterProject } from '../types'

export default {
  name: 'Passage',
  ninja: null,
  subcategories: 'Gaming',
  chain: 'NATIVE',
  category: 'NOT_DEPIN',
  token: 'PASG',
  coinGeckoID: 'passage',
  id: 'aqaszb',
  description: 'Passage connects virtual and physical experiences through creator-built games.',
  discord: '932715756423086090',
  investors: [],
  linkedin: 'https://linkedin.com/company/passageio',
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://twitter.com/passageio',
  url: 'https://www.passage.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
