import { AdapterProject } from '../types'

export default {
  name: 'Sphere',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '76qa11',
  description: 'Sphere is building a permissionless payment infrastructure for web3 on Solana. ',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://spherepay.co/',
  verified: false,
  fundraisesUrls: [],
} satisfies AdapterProject
