import { AdapterProject } from '../types'

export default {
  name: 'Sphere',
  ninja: 'ZZ',
  subcategories: null,
  chain: null,
  category: 'BLOCKCHAIN_INFRA',
  token: null,
  coinGeckoID: null,
  id: '76qa11',
  description: 'Sphere is building a permissionless payment infrastructure for web3 on Solana. ',
  discord: null,
  investors: [
    'nxop7l',
    '4l8mmr',
    'bxcu1r',
    'lg8vhc',
    'n6kv8g',
    'shz3zr',
    'unykak',
    'tlb60n',
    '762hpi',
    '5powje',
    'ztwm8h',
  ],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://spherepay.co/',
  verified: false,
  fundraises: [
    {
      roundType: 'Seed',
      url: 'https://twitter.com/sphere_labs/status/1762541489467613656',
    },
  ],
} satisfies AdapterProject
