import { AdapterProject } from '../types'

export default {
  name: 'Receipts',
  ninja: 'sal-gala.eth',
  subcategories: 'ZK',
  chain: null,
  category: 'NOT_DEPIN',
  token: null,
  coinGeckoID: null,
  id: 'zowtah',
  description: 'zk verified credentials minting',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://receipts.xyz/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
