import { AdapterProject } from '../types'

export default {
  name: 'Moflix',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'WIRELESS',
  token: null,
  coinGeckoID: null,
  id: 'u35fhl',
  description: 'Moflix enables telco operators to become the backbone of Web3.',
  discord: null,
  investors: ['jy83oo'],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: null,
  url: 'https://www.moflixgroup.com/',
  verified: false,
  fundraises: [],
} satisfies AdapterProject
