import { AdapterProject } from '../types'

export default {
  name: 'TACEO',
  ninja: null,
  subcategories: null,
  chain: null,
  category: 'PENDING',
  token: null,
  coinGeckoID: null,
  id: '7c6zgs',
  description: '',
  discord: null,
  investors: [],
  linkedin: null,
  duneQueries: null,
  foundingYear: null,
  blog: null,
  github: null,
  telegram: null,
  twitter: 'https://x.com/TACEO_IO',
  url: 'https://taceo.io/',
  verified: false,
  fundraises: [],
  isApp: true,
} satisfies AdapterProject
